# Copyright © 2020 Inoni Limited Liability Company
# Creator: Corey Post
# License: BSL 1.1
"""Subsystem Registry — Domain Data Part B (domains 14–26)

Owner: Platform Engineering

Contains :class:`SubsystemDomain` definitions for domains 14–26:
Self-Healing/Resilience, Onboarding/Setup, Knowledge/Research,
Swarm/Multi-Agent, Integration Framework, Control/Gate, HITL,
Librarian/OrgCompiler, MFGC/Chatbot, Board/ProjectManagement,
Testing/QA, Learning Engine, Protocols/Standards.

Imported by :mod:`subsystem_registry`.
"""
from __future__ import annotations

from typing import List

from ._registry_types import SubsystemDomain, SubsystemEntry, _e  # noqa: F401

_DOMAINS_B: List[SubsystemDomain] = [
    # =========================================================================
    # 14. SELF-HEALING / RESILIENCE
    # =========================================================================
    SubsystemDomain(
        name="Self-Healing/Resilience",
        space_alias="murphy-self-healing",
        hivemind_bot="OptimizationBot",
        entries=[
            _e("self_fix_loop", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Continuous self-fix loop.",
               cmds=["fix", "self-fix"]),
            _e("self_healing_coordinator", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Coordinates self-healing actions.",
               cmds=["heal"]),
            _e("autonomous_repair_system", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Autonomous repair system.", cmds=["repair"]),
            _e("chaos_resilience_loop", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Chaos engineering resilience loop.",
               cmds=["chaos"]),
            _e("blackstart_controller", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Blackstart (cold start) recovery controller.",
               cmds=["blackstart"]),
            _e("self_improvement_engine", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Self-improvement via feedback loops.",
               cmds=["improve"]),
            _e("self_optimisation_engine", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Continuous self-optimisation.",
               cmds=["optimize", "optimise"]),
            _e("self_learning_toggle", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Toggle for online self-learning."),
            _e("murphy_wingman_evolution", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Evolutionary improvement of Murphy agents.",
               cmds=["wingman evolve"]),
            _e("self_automation_orchestrator", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Self-automation orchestrator.",
               cmds=["automation self", "automation orchestrate"]),
            _e("code_repair_engine", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Automated code repair engine.",
               cmds=["repair"]),
            _e("murphy_code_healer", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Murphy code healing subsystem.",
               cmds=["heal code"]),
            _e("murphy_shadow_trainer", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Shadow training of Murphy models.",
               cmds=["shadow train"]),
            _e("recursive_stability_controller", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Recursive stability control sub-package.", pkg=True,
               cmds=["runtime stability"]),
            _e("repair_api_endpoints", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "REST endpoints for repair operations.",
               cmds=["repair"]),
            _e("cost_optimization_advisor", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Cost optimisation recommendations.",
               cmds=["costs", "cost"]),
        ],
    ),
    # =========================================================================
    # 15. ONBOARDING / SETUP
    # =========================================================================
    SubsystemDomain(
        name="Onboarding/Setup",
        space_alias="murphy-onboarding",
        hivemind_bot="TriageBot",
        entries=[
            _e("setup_wizard", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Interactive setup wizard.", cmds=["setup", "wizard"]),
            _e("onboarding_flow", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "User onboarding flow.", cmds=["onboard"]),
            _e("agentic_onboarding_engine", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "AI-driven onboarding engine.",
               cmds=["onboard start", "onboard status"]),
            _e("onboarding_automation_engine", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Automates onboarding steps.",
               cmds=["onboard automate"]),
            _e("environment_setup_agent", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Environment setup agent.", cmds=["env-setup"]),
            _e("hardware_visual_onboarding", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Hardware visual onboarding guide."),
            _e("onboarding_team_pipeline", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Team onboarding pipeline.",
               cmds=["onboard team"]),
            _e("highlight_overlay", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "UI highlight overlay for guided tours."),
            _e("inoni_org_bootstrap", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Inoni organisation bootstrap."),
            _e("setup_retry_amplifier", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Retries failed setup steps with amplification."),
            _e("env_manager", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "Environment variable management.", cmds=["env"]),
            _e("config", "murphy-general", "murphy-general",
               "TriageBot", "System configuration.", cmds=["config"]),
        ],
    ),
    # =========================================================================
    # 16. KNOWLEDGE / RESEARCH
    # =========================================================================
    SubsystemDomain(
        name="Knowledge/Research",
        space_alias="murphy-knowledge",
        hivemind_bot="LibrarianBot",
        entries=[
            _e("knowledge_base_manager", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Knowledge base CRUD and querying.",
               cmds=["knowledge", "kb"]),
            _e("knowledge_gap_system", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Identifies and fills knowledge gaps.",
               cmds=["gaps"]),
            _e("knowledge_graph_builder", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Builds and maintains knowledge graphs.",
               cmds=["graph"]),
            _e("generative_knowledge_builder", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "AI-powered knowledge generation.",
               cmds=["librarian generate", "kg generate"]),
            _e("concept_graph_engine", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Concept graph engine.",
               cmds=["kg concepts"]),
            _e("research_engine", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Core research engine.",
               cmds=["research"]),
            _e("advanced_research", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Advanced multi-step research.",
               cmds=["research advanced"]),
            _e("multi_source_research", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Multi-source research aggregation.",
               cmds=["research multi"]),
            _e("inquisitory_engine", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Inquisitory question-generation engine.",
               cmds=["inquire"]),
            _e("domain_expert_system", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Domain expert system.", cmds=["expert"]),
            _e("domain_expert_integration", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Integrates domain expert knowledge.",
               cmds=["eng expert-integrate"]),
            _e("question_manager", "murphy-research", "murphy-knowledge",
               "LibrarianBot", "Question lifecycle manager.", cmds=["question"]),
        ],
    ),
    # =========================================================================
    # 17. SWARM / MULTI-AGENT
    # =========================================================================
    SubsystemDomain(
        name="Swarm/Multi-Agent",
        space_alias="murphy-swarm",
        hivemind_bot="RubixCubeBot",
        entries=[
            _e("advanced_swarm_system", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Advanced multi-agent swarm system.",
               cmds=["swarm"]),
            _e("true_swarm_system", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "True swarm intelligence system."),
            _e("domain_swarms", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Domain-specific swarm agents.",
               cmds=["swarm domain"]),
            _e("durable_swarm_orchestrator", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Durable swarm orchestrator with persistence.",
               cmds=["swarm orchestrate", "swarm durable"]),
            _e("murphy_crew_system", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Murphy crew / team orchestration.",
               cmds=["crew"]),
            _e("swarm_proposal_generator", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Generates swarm task proposals.",
               cmds=["swarm propose"]),
            _e("agent_persona_library", "murphy-agent-activity", "murphy-swarm",
               "RubixCubeBot", "Agent persona library.", pkg=True,
               cmds=["agents personas", "agents list"]),
            _e("agent_run_recorder", "murphy-agent-activity", "murphy-swarm",
               "RubixCubeBot", "Records agent run history.",
               cmds=["agents runs", "agents history"]),
            _e("agent_monitor_dashboard", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Agent monitoring dashboard.", cmds=["agents"]),
            _e("declarative_fleet_manager", "murphy-agent-activity", "murphy-swarm",
               "RubixCubeBot", "Declarative agent fleet management.",
               cmds=["fleet"]),
            _e("llm_swarm_integration", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "LLM integration for swarm agents.",
               cmds=["llm swarm"]),
            _e("rubix_evidence_adapter", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Rubix cube evidence adapter.",
               cmds=["rubix"]),
            _e("shadow_agent_integration", "murphy-agent-activity", "murphy-swarm",
               "RubixCubeBot", "Shadow agent integration layer."),
            _e("murphy_osmosis_engine", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Murphy osmosis knowledge propagation engine.",
               cmds=["osmosis run"]),
            _e("murphy_trace", "murphy-agent-activity", "murphy-swarm",
               "MonitoringBot", "Murphy execution tracer.", cmds=["trace"]),
            _e("murphy_action_engine", "murphy-swarm-coordinator", "murphy-swarm",
               "TriageBot", "Murphy action execution engine.",
               cmds=["action"]),
        ],
    ),
    # =========================================================================
    # 18. INTEGRATION FRAMEWORK
    # =========================================================================
    SubsystemDomain(
        name="Integration Framework",
        space_alias="murphy-communication",
        hivemind_bot="FeedbackBot",
        entries=[
            _e("integration_engine", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Integration engine sub-package.", pkg=True,
               cmds=["integrations list", "integrations status", "integrations add"]),
            _e("integrations", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Third-party integrations sub-package.", pkg=True,
               cmds=["integrations all"]),
            _e("integration_bus", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Integration event bus.",
               cmds=["integration", "bus"]),
            _e("enterprise_integrations", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Enterprise system integrations.",
               cmds=["enterprise"]),
            _e("platform_connector_framework", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "50+ platform connector framework.",
               cmds=["connectors", "connect"]),
            _e("automation_integration_hub", "murphy-task-status", "murphy-triage",
               "TriageBot", "Automation integration hub.",
               cmds=["automation hub", "automation integrations"]),
            _e("remote_access_connector", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Remote access connector.",
               cmds=["remote connect"]),
            _e("universal_integration_adapter", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Universal integration adapter.",
               cmds=["integrate"]),
            _e("bridge_layer", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Bridge layer sub-package.", pkg=True,
               cmds=["bridge status"]),
            _e("adapter_framework", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Adapter framework sub-package.", pkg=True),
            _e("api_gateway_adapter", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "API gateway adapter.", cmds=["api"]),
            _e("api_collection_agent", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Collects and catalogues external APIs."),
            _e("agentic_api_provisioner", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Agentic API provisioning.",
               cmds=["provision"]),
            _e("graphql_api_layer", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "GraphQL API layer.", cmds=["graphql"]),
            _e("eq", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "EQ sub-package.", pkg=True,
               cmds=["eq status"]),
        ],
    ),
    # =========================================================================
    # 19. CONTROL / GATE SYSTEM
    # =========================================================================
    SubsystemDomain(
        name="Control/Gate",
        space_alias="murphy-triage",
        hivemind_bot="TriageBot",
        entries=[
            _e("gate_builder", "murphy-task-status", "murphy-triage",
               "TriageBot", "Builds gate evaluation pipelines.",
               cmds=["gate", "gates"]),
            _e("gate_bypass_controller", "murphy-task-status", "murphy-triage",
               "TriageBot", "Controls gate bypass for authorised overrides.",
               cmds=["gates bypass"]),
            _e("gate_execution_wiring", "murphy-task-status", "murphy-triage",
               "TriageBot", "Wires gates into execution flows."),
            _e("gate_synthesis", "murphy-task-status", "murphy-triage",
               "TriageBot", "Gate synthesis sub-package.", pkg=True,
               cmds=["compliance gates", "gates status", "gates arm", "gates disarm"]),
            _e("authority_gate", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Authority gate.", cmds=["authority"]),
            _e("cost_explosion_gate", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Prevents cost explosions.",
               cmds=["finance cost-gate"]),
            _e("inference_gate_engine", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Inference-level gate evaluation.",
               cmds=["llm gate"]),
            _e("niche_viability_gate", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Niche viability gate evaluation.",
               cmds=["biz viability"]),
            _e("domain_gate_generator", "murphy-task-status", "murphy-triage",
               "TriageBot", "Domain-specific gate generation.",
               cmds=["eng gate-gen"]),
            _e("confidence_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Confidence scoring sub-package.", pkg=True,
               cmds=["confidence"]),
            _e("control_plane", "murphy-task-status", "murphy-triage",
               "TriageBot", "Control plane sub-package.", pkg=True,
               cmds=["control status", "control plane"]),
            _e("control_plane_separation", "murphy-task-status", "murphy-triage",
               "TriageBot", "Separates control and data planes."),
            _e("compute_plane", "murphy-task-status", "murphy-triage",
               "TriageBot", "Compute plane sub-package.", pkg=True,
               cmds=["compute status", "compute resources"]),
            _e("deterministic_compute", "murphy-task-status", "murphy-triage",
               "TriageBot", "Deterministic compute layer."),
            _e("deterministic_compute_plane", "murphy-task-status", "murphy-triage",
               "TriageBot", "Deterministic compute plane sub-package.", pkg=True,
               cmds=["compute deterministic"]),
            _e("deterministic_routing_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Deterministic routing engine."),
            _e("control_theory", "murphy-task-status", "murphy-triage",
               "TriageBot", "Control theory sub-package.", pkg=True,
               cmds=["control theory"]),
            _e("observation_model", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "System observation model."),
            _e("unified_control_protocol", "murphy-task-status", "murphy-triage",
               "TriageBot", "Unified control protocol.",
               cmds=["control"]),
            _e("semantics_boundary_controller", "murphy-task-status", "murphy-triage",
               "TriageBot", "Semantics boundary enforcement."),
            _e("constraint_system", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Constraint management system."),
        ],
    ),
    # =========================================================================
    # 20. HITL (HUMAN-IN-THE-LOOP)
    # =========================================================================
    SubsystemDomain(
        name="HITL",
        space_alias="murphy-triage",
        hivemind_bot="TriageBot",
        entries=[
            _e("hitl_autonomy_controller", "murphy-task-status", "murphy-triage",
               "TriageBot", "HITL autonomy level controller.",
               cmds=["hitl", "autonomy"]),
            _e("hitl_graduation_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Graduates tasks from HITL to autonomous mode.",
               cmds=["hitl graduate", "hitl level"]),
            _e("murphy_shadow_trainer", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Shadow training from HITL decisions.",
               cmds=["shadow train"]),
            _e("trading_hitl_gateway", "murphy-trading-alerts", "murphy-trading",
               "ScalingBot", "Trading-specific HITL gateway.",
               cmds=["trading approve"]),
            _e("closure_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Task closure and sign-off engine.",
               cmds=["close", "closure"]),
            _e("freelancer_validator", "murphy-task-status", "murphy-triage",
               "TriageBot", "Freelancer work validation sub-package.", pkg=True,
               cmds=["validate"]),
            _e("resolution_scoring", "murphy-task-status", "murphy-triage",
               "TriageBot", "Scores resolution quality."),
            _e("murphy_shadow_trainer", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Shadow trainer for Murphy agents.",
               cmds=["shadow train"]),
        ],
    ),
    # =========================================================================
    # 21. LIBRARIAN / ORG COMPILER
    # =========================================================================
    SubsystemDomain(
        name="Librarian/OrgCompiler",
        space_alias="murphy-knowledge",
        hivemind_bot="LibrarianBot",
        entries=[
            _e("librarian", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Librarian sub-package.", pkg=True,
               cmds=["library", "librarian"]),
            _e("librarian_adapter", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Librarian adapter."),
            _e("librarian_integration", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Librarian system integration."),
            _e("system_librarian", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "System-level librarian.",
               cmds=["library"]),
            _e("bot_inventory_library", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Bot capability inventory library.",
               cmds=["bots inventory"]),
            _e("capability_map", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Murphy capability mapping.",
               cmds=["capabilities"]),
            _e("org_compiler", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Organisation compiler sub-package.", pkg=True,
               cmds=["org compile", "org chart"]),
            _e("module_compiler", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Module compiler sub-package.", pkg=True,
               cmds=["compile"]),
            _e("module_compiler_adapter", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Module compiler adapter.",
               cmds=["compile adapt"]),
            _e("module_manager", "murphy-general", "murphy-general",
               "TriageBot", "Module lifecycle management.",
               cmds=["module", "modules"]),
            _e("module_registry", "murphy-general", "murphy-general",
               "TriageBot", "Module discovery registry.",
               cmds=["registry"]),
            _e("dynamic_expert_generator", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Generates domain expert agents dynamically.",
               cmds=["eng expert-gen"]),
            _e("architecture_evolution", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Architecture evolution tracking."),
        ],
    ),
    # =========================================================================
    # 22. MFGC / CHATBOT
    # =========================================================================
    SubsystemDomain(
        name="MFGC/Chatbot",
        space_alias="murphy-ai",
        hivemind_bot="AnalysisBot",
        entries=[
            _e("mfgc_adapter", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "MFGC (Modular Fuzzy Gate Chatbot) adapter.",
               cmds=["mfgc adapt"]),
            _e("mfgc_core", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "MFGC core implementation.",
               cmds=["mfgc status"]),
            _e("mfgc_metrics", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "MFGC performance metrics.",
               cmds=["mfgc metrics"]),
            _e("mfgc_v1_1", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "MFGC v1.1 implementation."),
            _e("unified_mfgc", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Unified MFGC layer.", cmds=["mfgc"]),
            _e("enhanced_chatbot_mfgc", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Enhanced chatbot MFGC.",
               cmds=["chat", "chatbot"]),
            _e("chatbot_v1_1_fixed", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Legacy chatbot v1.1."),
        ],
    ),
    # =========================================================================
    # 23. BOARD / PROJECT MANAGEMENT (Monday.com parity)
    # =========================================================================
    SubsystemDomain(
        name="Board/ProjectManagement",
        space_alias="murphy-triage",
        hivemind_bot="TriageBot",
        entries=[
            _e("board_system", "murphy-task-status", "murphy-triage",
               "TriageBot", "Board system sub-package.", pkg=True,
               cmds=["board", "boards"]),
            _e("portfolio", "murphy-task-status", "murphy-triage",
               "TriageBot", "Portfolio management sub-package.", pkg=True,
               cmds=["portfolio"]),
            _e("workdocs", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "WorkDocs collaborative documents sub-package.",
               pkg=True, cmds=["docs", "workdocs"]),
            _e("time_tracking", "murphy-task-status", "murphy-triage",
               "TriageBot", "Time tracking sub-package.", pkg=True,
               cmds=["time", "timetrack"]),
            _e("collaboration", "murphy-general", "murphy-general",
               "TriageBot", "Collaboration sub-package.", pkg=True,
               cmds=["collaborate"]),
            _e("dev_module", "murphy-ci-cd", "murphy-deployment",
               "KeyManagerBot", "Dev module (sprints, bugs, Git) sub-package.",
               pkg=True, cmds=["dev", "sprint"]),
            _e("service_module", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Service module (catalog, SLA, tickets) sub-package.",
               pkg=True, cmds=["service"]),
            _e("guest_collab", "murphy-general", "murphy-general",
               "TriageBot", "Guest collaboration sub-package.", pkg=True,
               cmds=["guest"]),
            _e("scheduler", "murphy-task-status", "murphy-triage",
               "SchedulerBot", "Task scheduler.", cmds=["schedule"]),
            _e("knostalgia_engine", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Knostalgia knowledge engine.",
               cmds=["knostalgia run"]),
            _e("knostalgia_category_engine", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Knostalgia category classification.",
               cmds=["knostalgia categories"]),
            _e("shadow_knostalgia_bridge", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Shadow-Knostalgia integration bridge."),
            _e("kfactor_calculator", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "K-factor growth calculator."),
            _e("dynamic_assist_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Dynamic task assistance engine."),
            _e("executive_planning_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Executive-level planning engine.",
               cmds=["plan"]),
        ],
    ),
    # =========================================================================
    # 24. TESTING / QA
    # =========================================================================
    SubsystemDomain(
        name="Testing/QA",
        space_alias="murphy-monitoring",
        hivemind_bot="MonitoringBot",
        entries=[
            _e("ab_testing_framework", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "A/B testing framework.", cmds=["ab-test"]),
            _e("ui_testing_framework", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "UI automated testing framework.",
               cmds=["ui-test"]),
            _e("ui_test_completeness", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "UI test coverage completeness."),
            _e("test_mode_controller", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Controls test mode activation."),
            _e("playwright_task_definitions", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Playwright E2E task definitions.",
               cmds=["playwright run"]),
            _e("ui_data_service", "murphy-general", "murphy-general",
               "TriageBot", "UI data service layer."),
            _e("response_composer", "murphy-llm-responses", "murphy-ai",
               "AnalysisBot", "Composes structured responses."),
            _e("response_formatter", "murphy-llm-responses", "murphy-ai",
               "AnalysisBot", "Formats responses for output channels."),
            _e("feedback_integrator", "murphy-feedback", "murphy-feedback",
               "FeedbackBot", "Integrates feedback into improvement loops.",
               cmds=["feedback"]),
            _e("auar", "murphy-security-audit", "murphy-security",
               "SecurityBot", "AUAR (Adaptive Unified Agent Router) sub-package.",
               pkg=True, cmds=["auar"]),
            _e("auar_api", "murphy-security-audit", "murphy-security",
               "SecurityBot", "AUAR REST API.",
               deps=["auar"], cmds=["auar"]),
        ],
    ),
    # =========================================================================
    # 25. LEARNING ENGINE
    # =========================================================================
    SubsystemDomain(
        name="Learning Engine",
        space_alias="murphy-self-healing",
        hivemind_bot="OptimizationBot",
        entries=[
            _e("learning_engine", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Core learning engine sub-package.", pkg=True,
               cmds=["learn"]),
            _e("learning_system", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Learning system integration.",
               cmds=["learn"]),
            _e("federated_learning_coordinator", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Federated learning coordinator.",
               cmds=["federated"]),
            _e("murphy_wingman_evolution", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Evolutionary wingman protocol.",
               cmds=["wingman evolve"]),
            _e("wingman_protocol", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Wingman collaboration protocol."),
            _e("domain_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Domain engine for specialised routing.",
               cmds=["eng domain"]),
        ],
    ),
    # =========================================================================
    # 26. PROTOCOLS / STANDARDS
    # =========================================================================
    SubsystemDomain(
        name="Protocols/Standards",
        space_alias="murphy-general",
        hivemind_bot="TriageBot",
        entries=[
            _e("protocols", "murphy-general", "murphy-general",
               "TriageBot", "Protocols sub-package.", pkg=True,
               cmds=["protocols list"]),
            _e("legacy_compatibility_matrix", "murphy-general", "murphy-general",
               "TriageBot", "Legacy compatibility mapping.",
               cmds=["bridge compat"]),
            _e("thread_safe_operations", "murphy-general", "murphy-general",
               "TriageBot", "Thread-safe utility operations.",
               cmds=["runtime thread-safe"]),
            _e("golden_path_engine", "murphy-general", "murphy-general",
               "TriageBot", "Golden path workflow engine."),
            _e("golden_path_bridge", "murphy-general", "murphy-general",
               "TriageBot", "Golden path bridge."),
            _e("cli_art", "murphy-general", "murphy-general",
               "TriageBot", "CLI ASCII art utilities."),
            _e("murphy_template_hub", "murphy-general", "murphy-general",
               "TriageBot", "Template hub for Murphy artifacts.",
               cmds=["templates"]),
            _e("shim_compiler", "murphy-general", "murphy-general",
               "TriageBot", "Shim compiler sub-package.", pkg=True,
               cmds=["compile shim"]),
            _e("bug_pattern_detector", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Detects recurring bug patterns."),
            _e("runtime_profile_compiler", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Compiles runtime performance profiles."),
            _e("system_builder", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "System build orchestrator.", cmds=["build"]),
            _e("system_integrator", "murphy-general", "murphy-general",
               "TriageBot", "Top-level system integrator.",
               cmds=["integrations system"]),
            _e("system_performance_optimizer", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "System performance optimisation.",
               cmds=["perf"]),
            _e("information_density", "murphy-general", "murphy-general",
               "TriageBot", "Information density analysis."),
            _e("information_quality", "murphy-general", "murphy-general",
               "TriageBot", "Information quality assessment."),
            _e("avatar", "murphy-general", "murphy-general",
               "TriageBot", "Avatar sub-package.", pkg=True,
               cmds=["avatar status"]),
            _e("form_intake", "murphy-general", "murphy-general",
               "TriageBot", "Form intake sub-package.", pkg=True,
               cmds=["form submit", "form list", "form status"]),
            _e("account_management", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Account management sub-package.", pkg=True,
               cmds=["account"]),
            _e("org_chart_enforcement", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Org chart policy enforcement.",
               cmds=["org enforce"]),
            _e("organization_chart_system", "murphy-general", "murphy-general",
               "TriageBot", "Org chart visualisation.", cmds=["orgchart"]),
            _e("organizational_context_system", "murphy-general", "murphy-general",
               "TriageBot", "Organisational context tracking.",
               cmds=["org context"]),
            _e("viewport_content_resolver", "murphy-general", "murphy-general",
               "TriageBot", "Viewport-aware content resolution."),
            _e("artifact_viewport", "murphy-general", "murphy-general",
               "TriageBot", "Artifact viewport display."),
            _e("artifact_viewport_api", "murphy-general", "murphy-general",
               "TriageBot", "Artifact viewport REST API."),
            _e("voice_command_interface", "murphy-general", "murphy-general",
               "TriageBot", "Voice command interface.",
               cmds=["voice"]),
            _e("murphy_repl", "murphy-general", "murphy-general",
               "TriageBot", "Interactive REPL.", cmds=["repl"]),
        ],
    ),
]
