# Copyright © 2020 Inoni Limited Liability Company
# Creator: Corey Post
# License: BSL 1.1
"""Subsystem Registry — Domain Data Part A (domains 1–13)

Owner: Platform Engineering

Contains :class:`SubsystemDomain` definitions for domains 1–13:
Triage/Orchestration, Security, Engineering, Automation, AI/LLM,
Monitoring/Observability, Trading/Crypto, Compliance/Governance,
Memory/Data, Communication, Content/Media, Deployment/Infrastructure,
Business/Operations.

Imported by :mod:`subsystem_registry`.
"""
from __future__ import annotations

from typing import List

from ._registry_types import SubsystemDomain, SubsystemEntry, _e  # noqa: F401

_DOMAINS_A: List[SubsystemDomain] = [
    # =========================================================================
    # 1. TRIAGE / ORCHESTRATION
    # =========================================================================
    SubsystemDomain(
        name="Triage/Orchestration",
        space_alias="murphy-triage",
        hivemind_bot="TriageBot",
        entries=[
            _e("triage_rollcall_adapter", "murphy-rollcall", "murphy-triage",
               "TriageBot", "Rollcall adapter for triage subsystem.",
               deps=["ticket_triage_engine"], cmds=["triage", "rollcall"]),
            _e("ticket_triage_engine", "murphy-triage-queue", "murphy-triage",
               "TriageBot", "Ticket triage and classification engine.",
               deps=["task_executor"], cmds=["triage", "ticket"]),
            _e("task_executor", "murphy-task-status", "murphy-triage",
               "TriageBot", "Executes tasks dispatched by the triage engine.",
               deps=["execution_compiler", "workflow_dag_engine"], cmds=["task", "execute"]),
            _e("workflow_dag_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "DAG-based workflow execution engine.",
               deps=["execution_compiler"], cmds=["workflow", "dag"]),
            _e("execution_compiler", "murphy-task-status", "murphy-triage",
               "TriageBot", "Compiles execution packets for dispatch.",
               deps=["execution_engine"], cmds=["compile"]),
            _e("execution", "murphy-task-status", "murphy-triage",
               "TriageBot", "Execution sub-package.",
               pkg=True, cmds=["execute"]),
            _e("execution_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "Core execution engine sub-package.",
               pkg=True, deps=["execution_compiler"]),
            _e("execution_orchestrator", "murphy-task-status", "murphy-triage",
               "TriageBot", "Execution orchestrator sub-package.",
               pkg=True, deps=["execution_engine"], cmds=["orchestrate"]),
            _e("execution_packet_compiler", "murphy-task-status", "murphy-triage",
               "TriageBot", "Packet compiler sub-package.", pkg=True),
            _e("efficiency_orchestrator", "murphy-task-status", "murphy-triage",
               "TriageBot", "Optimises task throughput and efficiency.",
               deps=["task_executor"], cmds=["efficiency"]),
            _e("modular_runtime", "murphy-task-status", "murphy-triage",
               "TriageBot", "Modular runtime controller.",
               deps=["runtime"], cmds=["runtime"]),
            _e("runtime", "murphy-task-status", "murphy-triage",
               "TriageBot", "Runtime sub-package.", pkg=True),
            _e("shutdown_manager", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Graceful shutdown controller.",
               deps=["health_monitor"], cmds=["shutdown"]),
            _e("emergency_stop_controller", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Emergency stop and kill-switch.",
               cmds=["stop", "estop"]),
            _e("finish_line_controller", "murphy-task-status", "murphy-triage",
               "TriageBot", "Marks tasks complete and triggers follow-ons."),
            _e("command_system", "murphy-general", "murphy-general",
               "TriageBot", "Core command dispatcher.",
               deps=["command_parser"], cmds=["*"]),
            _e("command_parser", "murphy-general", "murphy-general",
               "TriageBot", "Parses raw command strings.",
               cmds=["*"]),
            _e("dynamic_command_discovery", "murphy-general", "murphy-general",
               "TriageBot", "Discovers available commands at runtime.",
               cmds=["commands", "help"]),
        ],
    ),
    # =========================================================================
    # 2. SECURITY
    # =========================================================================
    SubsystemDomain(
        name="Security",
        space_alias="murphy-security",
        hivemind_bot="SecurityBot",
        entries=[
            _e("security_audit_scanner", "murphy-security-alerts", "murphy-security",
               "SecurityBot", "Scans system for security vulnerabilities.",
               cmds=["security", "scan", "audit"]),
            _e("security_hardening_config", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Security hardening configuration manager.",
               cmds=["harden"]),
            _e("security_plane", "murphy-security-alerts", "murphy-security",
               "SecurityBot", "Security plane sub-package.", pkg=True),
            _e("security_plane_adapter", "murphy-security-alerts", "murphy-security",
               "SecurityBot", "Adapter for the security control plane.",
               deps=["security_plane"], cmds=["security"]),
            _e("fastapi_security", "murphy-security-audit", "murphy-security",
               "SecurityBot", "FastAPI security middleware.",
               deps=["rbac_governance"]),
            _e("flask_security", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Flask security middleware.",
               deps=["rbac_governance"]),
            _e("rbac_governance", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Role-based access control governance.",
               cmds=["rbac", "permissions"]),
            _e("authority_gate", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Authority gate for privileged operations.",
               deps=["rbac_governance"], cmds=["gate", "authority"]),
            _e("murphy_credential_gate", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Credential validation gate.",
               deps=["secure_key_manager"], cmds=["credentials"]),
            _e("oauth_oidc_provider", "murphy-security-audit", "murphy-security",
               "SecurityBot", "OAuth 2.0 / OIDC provider.",
               cmds=["oauth", "oidc"]),
            _e("secure_key_manager", "murphy-security-audit", "murphy-security",
               "KeyManagerBot", "Secure API key management.",
               cmds=["keys", "key"]),
            _e("credential_profile_system", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Manages credential profiles.", cmds=["credentials"]),
            _e("fastapi_security", "murphy-security-audit", "murphy-security",
               "SecurityBot", "FastAPI authentication layer."),
            _e("input_validation", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Input sanitisation and validation."),
            _e("safety_gateway_integrator", "murphy-security-alerts", "murphy-security",
               "SecurityBot", "Safety gateway integration layer."),
            _e("safety_orchestrator", "murphy-security-alerts", "murphy-security",
               "SecurityBot", "Orchestrates safety checks across subsystems."),
            _e("safety_validation_pipeline", "murphy-security-alerts", "murphy-security",
               "SecurityBot", "End-to-end safety validation pipeline."),
            _e("tos_acceptance_gate", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Terms-of-service acceptance gate.", cmds=["tos"]),
            _e("signup_gateway", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "User sign-up gateway.", cmds=["signup"]),
            _e("end_user_agreement", "murphy-onboarding", "murphy-onboarding",
               "TriageBot", "End-user agreement acceptance flow."),
            _e("ip_classification_engine", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Classifies IP addresses for threat assessment."),
        ],
    ),
    # =========================================================================
    # 3. ENGINEERING / CAD / SIMULATION
    # =========================================================================
    SubsystemDomain(
        name="Engineering/CAD/Simulation",
        space_alias="murphy-engineering",
        hivemind_bot="EngineeringBot",
        entries=[
            _e("murphy_engineering_toolbox", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Multi-discipline engineering toolbox.",
               cmds=["engineer", "engineering"]),
            _e("murphy_drawing_engine", "murphy-cad-output", "murphy-engineering",
               "CADBot", "CAD drawing and 3D model generation.",
               cmds=["cad", "draw", "model"]),
            _e("simulation_engine", "murphy-simulation-results", "murphy-engineering",
               "SimulationBot", "Predictive simulation engine.",
               cmds=["simulate", "simulation"]),
            _e("digital_twin_engine", "murphy-simulation-results", "murphy-engineering",
               "SimulationBot", "Digital twin modelling and synchronisation.",
               deps=["simulation_engine"], cmds=["twin", "digital-twin"]),
            _e("additive_manufacturing_connectors", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Additive manufacturing (3D printing) connectors."),
            _e("manufacturing_automation_standards", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Manufacturing automation standards compliance."),
            _e("building_automation_connectors", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Building management system connectors."),
            _e("energy_management_connectors", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Energy management system connectors."),
            _e("computer_vision_pipeline", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Computer vision processing pipeline.",
               cmds=["vision", "cv"]),
            _e("robotics", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Robotics sub-package.", pkg=True, cmds=["robotics"]),
            _e("murphy_sensor_fusion", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Sensor data fusion for physical systems.",
               deps=["sensor_reader"], cmds=["sensor", "fusion"]),
            _e("sensor_reader", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Reads sensor data from connected devices.",
               cmds=["sensor"]),
            _e("murphy_autonomous_perception", "murphy-engineering-tasks", "murphy-engineering",
               "EngineeringBot", "Autonomous perception and scene understanding."),
            _e("causality_sandbox", "murphy-simulation-results", "murphy-engineering",
               "SimulationBot", "Causal reasoning simulation sandbox."),
        ],
    ),
    # =========================================================================
    # 4. AUTOMATION
    # =========================================================================
    SubsystemDomain(
        name="Automation",
        space_alias="murphy-triage",
        hivemind_bot="TriageBot",
        entries=[
            _e("automation_integration_hub", "murphy-task-status", "murphy-triage",
               "TriageBot", "Hub integrating all automation subsystems.",
               cmds=["automation", "automate"]),
            _e("automation_loop_connector", "murphy-task-status", "murphy-triage",
               "TriageBot", "Connects external automation loops."),
            _e("automation_marketplace", "murphy-task-status", "murphy-triage",
               "TriageBot", "Marketplace for Murphy automation recipes.",
               cmds=["marketplace"]),
            _e("automation_mode_controller", "murphy-task-status", "murphy-triage",
               "TriageBot", "Controls automation mode (manual/assisted/full)."),
            _e("automation_rbac_controller", "murphy-security-audit", "murphy-security",
               "SecurityBot", "RBAC enforcement for automation actions."),
            _e("automation_readiness_evaluator", "murphy-task-status", "murphy-triage",
               "TriageBot", "Evaluates system readiness for automation."),
            _e("automation_scaler", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Scales automation capacity.", cmds=["scale"]),
            _e("automation_scheduler", "murphy-task-status", "murphy-triage",
               "SchedulerBot", "Schedules automation runs.", cmds=["schedule"]),
            _e("automation_type_registry", "murphy-task-status", "murphy-triage",
               "TriageBot", "Registry of automation types."),
            _e("automations", "murphy-task-status", "murphy-triage",
               "TriageBot", "Automations sub-package.", pkg=True),
            _e("full_automation_controller", "murphy-task-status", "murphy-triage",
               "TriageBot", "Full end-to-end automation controller.",
               cmds=["automate", "full-auto"]),
            _e("self_automation_orchestrator", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Orchestrates self-improving automation.",
               cmds=["self-automate"]),
            _e("murphy_native_automation", "murphy-task-status", "murphy-triage",
               "TriageBot", "Murphy-native automation primitives."),
            _e("autonomous_systems", "murphy-task-status", "murphy-triage",
               "TriageBot", "Autonomous systems sub-package.", pkg=True),
            _e("autonomous_repair_system", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Autonomous system repair and recovery.",
               cmds=["repair"]),
            _e("rpa_recorder_engine", "murphy-task-status", "murphy-triage",
               "TriageBot", "RPA (Robotic Process Automation) recorder.",
               cmds=["rpa", "record"]),
            _e("ai_workflow_generator", "murphy-task-status", "murphy-triage",
               "TriageBot", "AI-powered workflow generation.",
               deps=["llm_controller"], cmds=["workflow"]),
            _e("workflow_template_marketplace", "murphy-task-status", "murphy-triage",
               "TriageBot", "Marketplace for workflow templates.",
               cmds=["templates"]),
            _e("nocode_workflow_terminal", "murphy-task-status", "murphy-triage",
               "TriageBot", "No-code workflow builder terminal.",
               cmds=["nocode", "builder"]),
            _e("murphy_repl", "murphy-general", "murphy-general",
               "TriageBot", "Interactive Murphy REPL.",
               cmds=["repl"]),
        ],
    ),
    # =========================================================================
    # 5. AI / LLM
    # =========================================================================
    SubsystemDomain(
        name="AI/LLM",
        space_alias="murphy-ai",
        hivemind_bot="AnalysisBot",
        entries=[
            _e("llm_controller", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Central LLM routing and controller.",
               cmds=["llm", "ai", "chat"]),
            _e("llm_integration", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "LLM provider integration layer.",
               deps=["llm_controller"]),
            _e("llm_integration_layer", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Multi-provider LLM integration.",
               deps=["llm_controller"]),
            _e("llm_output_validator", "murphy-llm-responses", "murphy-ai",
               "JSONBot", "Validates and sanitises LLM outputs.",
               deps=["llm_controller"]),
            _e("llm_routing_completeness", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Ensures all LLM routes are complete."),
            _e("llm_swarm_integration", "murphy-swarm-coordinator", "murphy-swarm",
               "RubixCubeBot", "Integrates LLMs into the agent swarm.",
               deps=["advanced_swarm_system", "llm_controller"]),
            _e("safe_llm_wrapper", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Safety wrapper around LLM calls.",
               deps=["llm_controller"]),
            _e("groq_key_rotator", "murphy-security-audit", "murphy-security",
               "KeyManagerBot", "Rotates Groq API keys.",
               deps=["secure_key_manager"], cmds=["keys"]),
            _e("local_llm_fallback", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Local LLM fallback when cloud is unavailable.",
               deps=["enhanced_local_llm"]),
            _e("enhanced_local_llm", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Enhanced offline LLM (default when no API keys)."),
            _e("local_inference_engine", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Local inference engine.",
               deps=["local_model_layer"]),
            _e("local_model_layer", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Local model loading and caching layer."),
            _e("openai_compatible_provider", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "OpenAI-compatible provider (openai/groq/onboard auto-detect).",
               deps=["enhanced_local_llm"]),
            _e("mock_compatible_local_llm", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Mock LLM for testing."),
            _e("large_action_model", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Large action model (LAM) for multi-step tasks.",
               deps=["llm_controller"], cmds=["lam", "action"]),
            _e("neuro_symbolic_adapter", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Neuro-symbolic reasoning adapter.",
               deps=["reasoning_engine"]),
            _e("neuro_symbolic_models", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Neuro-symbolic models sub-package.", pkg=True),
            _e("reasoning_engine", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Structured reasoning engine.",
               deps=["llm_controller"], cmds=["reason"]),
            _e("prompt_amplifier", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Amplifies and optimises prompts before LLM calls."),
            _e("aionmind", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "AionMind core AI sub-package.", pkg=True),
            _e("rag_vector_integration", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "RAG (Retrieval-Augmented Generation) vector store.",
               deps=["knowledge_graph_builder"], cmds=["rag"]),
            _e("murphy_foundation_model", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Murphy Foundation Model (MFM) sub-package.", pkg=True,
               cmds=["mfm"]),
            _e("natural_language_query", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Natural language query interface.",
               deps=["llm_controller"], cmds=["nlq", "query"]),
            _e("probabilistic_layer", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Probabilistic reasoning layer."),
            _e("concept_translation", "murphy-llm-requests", "murphy-ai",
               "AnalysisBot", "Concept translation between domains."),
            _e("smart_codegen", "murphy-llm-responses", "murphy-ai",
               "AnalysisBot", "AI-powered code generation.",
               deps=["llm_controller"], cmds=["codegen", "code"]),
            _e("multi_language_codegen", "murphy-llm-responses", "murphy-ai",
               "AnalysisBot", "Multi-language code generation.", cmds=["codegen"]),
            _e("code_generation_gateway", "murphy-llm-responses", "murphy-ai",
               "AnalysisBot", "Gateway for code generation requests.",
               deps=["smart_codegen"]),
        ],
    ),
    # =========================================================================
    # 6. MONITORING / OBSERVABILITY
    # =========================================================================
    SubsystemDomain(
        name="Monitoring/Observability",
        space_alias="murphy-monitoring",
        hivemind_bot="MonitoringBot",
        entries=[
            _e("health_monitor", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "System health monitor.",
               cmds=["health", "status"]),
            _e("unified_observability_engine", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Unified observability across all subsystems.",
               deps=["prometheus_metrics_exporter"], cmds=["observe"]),
            _e("prometheus_metrics_exporter", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Prometheus metrics exporter.",
               cmds=["metrics"]),
            _e("agent_monitor_dashboard", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Agent activity monitoring dashboard.",
               cmds=["agents", "agent"]),
            _e("telemetry_adapter", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Telemetry data adapter.",
               deps=["telemetry_system"]),
            _e("telemetry_system", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Telemetry system sub-package.", pkg=True),
            _e("telemetry_learning", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Learning-based telemetry analysis.", pkg=True),
            _e("observability_counters", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Low-level observability counters."),
            _e("bot_telemetry_normalizer", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Normalises telemetry data across bots."),
            _e("metrics", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Core metrics module.", cmds=["metrics"]),
            _e("log_analysis_engine", "murphy-logs", "murphy-monitoring",
               "MonitoringBot", "Analyses log streams for patterns.",
               cmds=["logs", "log"]),
            _e("logging_system", "murphy-logs", "murphy-monitoring",
               "MonitoringBot", "Centralised logging system."),
            _e("statistics_collector", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Collects and aggregates statistics.",
               cmds=["stats"]),
            _e("alert_rules_engine", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Rule-based alert generation.",
               cmds=["alerts"]),
            _e("heartbeat_liveness_protocol", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Heartbeat and liveness protocol."),
            _e("activated_heartbeat_runner", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Activated heartbeat execution loop."),
            _e("rosetta_stone_heartbeat", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Cross-subsystem heartbeat synchronisation."),
            _e("causal_spike_analyzer", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Analyses causal spikes in system metrics."),
            _e("operational_slo_tracker", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Tracks operational SLOs.", cmds=["slo"]),
            _e("slo_remediation_bridge", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Bridges SLO violations to remediation actions."),
            _e("mss_controls", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Murphy Stability System controls."),
            _e("mss_sequence_optimizer", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "MSS sequence optimisation."),
            _e("predictive_failure_engine", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Predicts failures before they occur.",
               deps=["health_monitor"], cmds=["predict-failure"]),
            _e("predictive_maintenance_engine", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Predictive maintenance scheduling.",
               cmds=["maintenance"]),
            _e("structural_coherence", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Monitors structural coherence of system state."),
            _e("operational_completeness", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Tracks operational completeness metrics."),
            _e("startup_validator", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Validates system state at startup.",
               cmds=["validate"]),
            _e("startup_feature_summary", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Summarises active features at startup."),
            _e("readiness_scanner", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Scans system readiness.", cmds=["ready"]),
            _e("readiness_bootstrap_orchestrator", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Orchestrates readiness bootstrap sequence."),
            _e("supervision_tree", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Process supervision tree."),
            _e("supervisor_system", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Supervisor system sub-package.", pkg=True),
            _e("synthetic_failure_generator", "murphy-health-alerts", "murphy-monitoring",
               "MonitoringBot", "Generates synthetic failures for chaos testing.",
               pkg=True, cmds=["chaos"]),
        ],
    ),
    # =========================================================================
    # 7. TRADING / CRYPTO
    # =========================================================================
    SubsystemDomain(
        name="Trading/Crypto",
        space_alias="murphy-trading",
        hivemind_bot="ScalingBot",
        entries=[
            _e("trading_bot_engine", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Core trading bot engine.",
               cmds=["trading", "trade"]),
            _e("trading_bot_lifecycle", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Manages trading bot lifecycle."),
            _e("trading_hitl_gateway", "murphy-trading-alerts", "murphy-trading",
               "ScalingBot", "HITL gateway for trading decisions.",
               deps=["hitl_autonomy_controller"], cmds=["trading-hitl"]),
            _e("trading_shadow_learner", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Shadow trading learner (paper-trade mode)."),
            _e("trading_strategy_engine", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Trading strategy generation and backtesting.",
               deps=["ml_strategy_engine"], cmds=["strategy"]),
            _e("coinbase_connector", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Coinbase exchange connector.",
               cmds=["coinbase", "crypto"]),
            _e("crypto_exchange_connector", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Generic crypto exchange connector.",
               cmds=["exchange"]),
            _e("crypto_portfolio_tracker", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Tracks crypto portfolio value.",
               cmds=["portfolio"]),
            _e("crypto_risk_manager", "murphy-trading-alerts", "murphy-trading",
               "ScalingBot", "Manages crypto trading risk.",
               cmds=["risk"]),
            _e("crypto_wallet_manager", "murphy-security-audit", "murphy-security",
               "SecurityBot", "Manages crypto wallet keys.",
               cmds=["wallet"]),
            _e("market_data_feed", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "Live market data feed.",
               cmds=["market", "feed"]),
            _e("ml_strategy_engine", "murphy-trading-signals", "murphy-trading",
               "ScalingBot", "ML-driven trading strategy engine.",
               deps=["llm_controller"]),
        ],
    ),
    # =========================================================================
    # 8. COMPLIANCE / GOVERNANCE
    # =========================================================================
    SubsystemDomain(
        name="Compliance/Governance",
        space_alias="murphy-compliance",
        hivemind_bot="CommissioningBot",
        entries=[
            _e("compliance_engine", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Core compliance assessment engine.",
               cmds=["compliance"]),
            _e("compliance_as_code_engine", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Compliance-as-code implementation."),
            _e("compliance_automation_bridge", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Bridges compliance checks to automation."),
            _e("compliance_monitoring_completeness", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Monitors compliance coverage completeness."),
            _e("compliance_orchestration_bridge", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Orchestrates compliance workflows."),
            _e("compliance_region_validator", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Validates regional compliance requirements."),
            _e("compliance_report_aggregator", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Aggregates compliance reports.", cmds=["report"]),
            _e("contractual_audit", "murphy-audit-trail", "murphy-compliance",
               "CommissioningBot", "Contractual obligation audit tracking."),
            _e("audit_logging_system", "murphy-audit-trail", "murphy-compliance",
               "CommissioningBot", "Immutable audit log system.",
               cmds=["audit"]),
            _e("blockchain_audit_trail", "murphy-audit-trail", "murphy-compliance",
               "CommissioningBot", "Blockchain-backed audit trail."),
            _e("governance_framework", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Governance framework sub-package.", pkg=True),
            _e("governance_kernel", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Core governance kernel.",
               cmds=["governance"]),
            _e("governance_toggle", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Toggles governance policies on/off."),
            _e("bot_governance_policy_mapper", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Maps bot actions to governance policies."),
            _e("verification_layer", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Cross-subsystem verification layer.",
               cmds=["verify"]),
            _e("base_governance_runtime", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Base governance runtime sub-package.", pkg=True),
            _e("constraint_system", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "System constraint management."),
            _e("risk_mitigation_tracker", "murphy-compliance-reports", "murphy-compliance",
               "CommissioningBot", "Risk mitigation action tracker.",
               cmds=["risk"]),
            _e("dependency_audit_engine", "murphy-audit-trail", "murphy-compliance",
               "CommissioningBot", "Audits module dependencies."),
        ],
    ),
    # =========================================================================
    # 9. MEMORY / DATA
    # =========================================================================
    SubsystemDomain(
        name="Memory/Data",
        space_alias="murphy-memory",
        hivemind_bot="MemoryManagerBot",
        entries=[
            _e("memory_management", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "STM/LTM memory management.",
               cmds=["memory", "stm", "ltm"]),
            _e("memory_artifact_system", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "Memory artifact storage and retrieval."),
            _e("immune_memory", "murphy-memory-ltm", "murphy-memory",
               "MemoryManagerBot", "Immune-system-inspired long-term memory."),
            _e("murphy_immune_engine", "murphy-self-healing", "murphy-self-healing",
               "OptimizationBot", "Murphy immune system engine.",
               deps=["immune_memory"]),
            _e("data_archive_manager", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Data archive management.",
               cmds=["archive"]),
            _e("data_pipeline_orchestrator", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Data pipeline orchestration.",
               cmds=["data", "pipeline"]),
            _e("cache", "murphy-memory-stm", "murphy-memory",
               "CacheManagerBot", "In-memory cache.", cmds=["cache"]),
            _e("db", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Database access layer.", cmds=["db"]),
            _e("persistence_manager", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Persistence management.",
               cmds=["persist"]),
            _e("persistence_wal", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Write-ahead log for persistence."),
            _e("persistence_replay_completeness", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Persistence replay completeness checks."),
            _e("cross_platform_data_sync", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Cross-platform data synchronisation.",
               cmds=["sync"]),
            _e("murphy_state_graph", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "Murphy state graph representation."),
            _e("state_machine", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "General-purpose state machine."),
            _e("state_schema", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "State schema definitions.",
               cmds=["state"]),
            _e("session_context", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "Per-session context management."),
            _e("environment_state_manager", "murphy-memory-stm", "murphy-memory",
               "MemoryManagerBot", "Environment state management."),
            _e("schema_registry", "murphy-data-archive", "murphy-memory",
               "MemoryManagerBot", "Schema registry sub-package.", pkg=True),
        ],
    ),
    # =========================================================================
    # 10. COMMUNICATION
    # =========================================================================
    SubsystemDomain(
        name="Communication",
        space_alias="murphy-communication",
        hivemind_bot="FeedbackBot",
        entries=[
            _e("comms", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Communications sub-package.", pkg=True),
            _e("communication_system", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Communication system sub-package.", pkg=True),
            _e("notification_system", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Multi-channel notification system.",
               cmds=["notify", "notifications"]),
            _e("customer_communication_manager", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Customer communication management.",
               cmds=["customer-comms"]),
            _e("announcer_voice_engine", "murphy-announcements", "murphy-communication",
               "FeedbackBot", "Voice announcement engine.",
               cmds=["announce"]),
            _e("conversation_handler", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Conversation flow handler.",
               cmds=["converse"]),
            _e("conversation_manager", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Conversation state manager."),
            _e("webhook_dispatcher", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Webhook event dispatcher.",
               deps=["event_backbone"], cmds=["webhook", "webhooks"]),
            _e("webhook_event_processor", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Processes inbound webhook events."),
            _e("websocket_event_server", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "WebSocket event server.", cmds=["websocket"]),
            _e("email_integration", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Email integration (SendGrid/SMTP).",
               cmds=["email"]),
            _e("delivery_adapters", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Message delivery adapters."),
            _e("delivery_channel_completeness", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Delivery channel coverage tracker."),
            _e("event_backbone", "murphy-notifications", "murphy-communication",
               "FeedbackBot", "Durable in-process event backbone.",
               cmds=["events"]),
        ],
    ),
    # =========================================================================
    # 11. CONTENT / MEDIA
    # =========================================================================
    SubsystemDomain(
        name="Content/Media",
        space_alias="murphy-content",
        hivemind_bot="VisualizationBot",
        entries=[
            _e("content_pipeline_engine", "murphy-content-output", "murphy-content",
               "VisualizationBot", "End-to-end content generation pipeline.",
               cmds=["content"]),
            _e("content_creator_platform_modulator", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Modulates content for different creator platforms."),
            _e("image_generation_engine", "murphy-content-output", "murphy-content",
               "VisualizationBot", "AI image generation engine.",
               cmds=["image", "generate"]),
            _e("video_packager", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Video packaging and export.",
               cmds=["video"]),
            _e("video_streaming_connector", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Video streaming platform connector."),
            _e("digital_asset_generator", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Digital asset generation.",
               cmds=["asset"]),
            _e("social_media_scheduler", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Social media post scheduling.",
               cmds=["social", "schedule"]),
            _e("social_media_moderation", "murphy-content-output", "murphy-content",
               "VisualizationBot", "AI-driven social media moderation."),
            _e("youtube_channel_bootstrap", "murphy-content-output", "murphy-content",
               "VisualizationBot", "YouTube channel setup automation.",
               cmds=["youtube"]),
            _e("youtube_metadata_generator", "murphy-content-output", "murphy-content",
               "VisualizationBot", "YouTube metadata generation."),
            _e("youtube_uploader", "murphy-content-output", "murphy-content",
               "VisualizationBot", "YouTube video uploader."),
            _e("seo_optimisation_engine", "murphy-content-output", "murphy-content",
               "VisualizationBot", "SEO optimisation engine.", cmds=["seo"]),
            _e("auto_documentation_engine", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Automatic documentation generation.",
               cmds=["docs", "documentation"]),
            _e("faq_generation_engine", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "FAQ generation from content.", cmds=["faq"]),
            _e("document_processor", "murphy-knowledge-base", "murphy-knowledge",
               "LibrarianBot", "Document parsing and processing.",
               cmds=["document"]),
            _e("upload_content_reviewer", "murphy-content-output", "murphy-content",
               "VisualizationBot", "Reviews uploaded content for quality."),
            _e("analytics_dashboard", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Analytics dashboard.", cmds=["analytics"]),
            _e("dashboards", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Dashboards sub-package.", pkg=True, cmds=["dashboard"]),
            _e("operational_dashboard_aggregator", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Aggregates operational dashboards."),
            _e("advanced_reports", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Advanced reporting engine.", cmds=["report"]),
        ],
    ),
    # =========================================================================
    # 12. DEPLOYMENT / INFRASTRUCTURE
    # =========================================================================
    SubsystemDomain(
        name="Deployment/Infrastructure",
        space_alias="murphy-deployment",
        hivemind_bot="KeyManagerBot",
        entries=[
            _e("docker_containerization", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Docker container build and management.",
               cmds=["docker", "deploy"]),
            _e("kubernetes_deployment", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Kubernetes deployment management.",
               cmds=["k8s", "kubernetes"]),
            _e("hetzner_deploy", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Hetzner cloud deployment.", cmds=["hetzner"]),
            _e("cloudflare_deploy", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Cloudflare deployment.", cmds=["cloudflare"]),
            _e("multi_cloud_orchestrator", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Multi-cloud orchestration.",
               cmds=["cloud", "multicloud"]),
            _e("deployment_automation_controller", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Automated deployment controller.",
               cmds=["deploy"]),
            _e("backup_disaster_recovery", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Backup and disaster recovery.",
               cmds=["backup", "dr"]),
            _e("ci_cd_pipeline_manager", "murphy-ci-cd", "murphy-deployment",
               "KeyManagerBot", "CI/CD pipeline management.",
               cmds=["ci", "cicd", "pipeline"]),
            _e("plugin_extension_sdk", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Plugin and extension SDK.",
               cmds=["plugin"]),
            _e("remote_access_connector", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Remote access connector.", cmds=["remote"]),
            _e("tenant_resource_governor", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Multi-tenant resource governance.",
               deps=["rbac_governance"], cmds=["tenant"]),
            _e("multi_tenant_workspace", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Multi-tenant workspace management.",
               cmds=["workspace"]),
            _e("geographic_load_balancer", "murphy-deployments", "murphy-deployment",
               "KeyManagerBot", "Geographic load balancing.",
               cmds=["loadbalance"]),
            _e("capacity_planning_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Capacity planning and forecasting.",
               cmds=["capacity"]),
        ],
    ),
    # =========================================================================
    # 13. BUSINESS / OPERATIONS
    # =========================================================================
    SubsystemDomain(
        name="Business/Operations",
        space_alias="murphy-business",
        hivemind_bot="ScalingBot",
        entries=[
            _e("business_scaling_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Business scaling automation.",
               cmds=["scale", "business"]),
            _e("niche_business_generator", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Generates niche business opportunities.",
               cmds=["niche"]),
            _e("sales_automation", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Sales process automation.", cmds=["sales"]),
            _e("supply_orchestrator", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Supply chain orchestration.", cmds=["supply"]),
            _e("invoice_processing_pipeline", "murphy-invoices", "murphy-business",
               "ScalingBot", "Invoice processing and management.",
               cmds=["invoice"]),
            _e("financial_reporting_engine", "murphy-invoices", "murphy-business",
               "ScalingBot", "Financial reporting and analytics.",
               cmds=["finance", "financial"]),
            _e("budget_aware_processor", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Budget-aware task processor.",
               cmds=["budget"]),
            _e("rosetta_selling_bridge", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Rosetta selling strategy bridge."),
            _e("unit_economics_analyzer", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Unit economics analysis.",
               cmds=["economics"]),
            _e("kpi_tracker", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "KPI tracking dashboard.", cmds=["kpi"]),
            _e("operations_cycle_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Business operations cycle management."),
            _e("strategic_planning_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Strategic planning and roadmapping.",
               cmds=["strategy", "plan"]),
            _e("campaign_orchestrator", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Marketing campaign orchestration.",
               cmds=["campaign"]),
            _e("adaptive_campaign_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Adaptive campaign engine."),
            _e("competitive_intelligence_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Competitive intelligence gathering.",
               cmds=["competitive", "intel"]),
            _e("marketing_analytics_aggregator", "murphy-metrics", "murphy-monitoring",
               "MonitoringBot", "Marketing analytics aggregation."),
            _e("rosetta", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Rosetta sub-package.", pkg=True),
            _e("self_selling_engine", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Self-selling engine sub-package.", pkg=True,
               cmds=["sell"]),
            _e("crm", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "CRM sub-package.", pkg=True, cmds=["crm"]),
            _e("trial_orchestrator", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Free trial orchestration.",
               cmds=["trial"]),
            _e("innovation_farmer", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Innovation opportunity farming."),
            _e("infinity_expansion_system", "murphy-business-tasks", "murphy-business",
               "ScalingBot", "Infinite expansion system.",
               cmds=["expand"]),
        ],
    ),
]
