# © 2020 Inoni Limited Liability Company by Corey Post
# License: BSL 1.1
"""Module Manifest — complete map of every Murphy module/subsystem to its
Matrix room, available commands, responsible bot persona, and event types.

This manifest is exhaustive: every ``.py`` file and every subdirectory
package under ``src/`` has an entry.

Each entry is a :class:`ModuleEntry` with:
- ``module``       — Python import path relative to ``src/``
- ``room``         — Matrix subsystem room key (matches ``SUBSYSTEM_ROOMS``)
- ``commands``     — list of ``!murphy`` command strings
- ``persona``      — responsible bot persona name
- ``emits``        — event types the module emits
- ``consumes``     — event types the module consumes
"""

from __future__ import annotations
import logging

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class ModuleEntry:
    """Manifest entry for a single Murphy module."""

    module: str
    room: str
    commands: List[str] = field(default_factory=list)
    persona: str = "TriageBot"
    emits: List[str] = field(default_factory=list)
    consumes: List[str] = field(default_factory=list)
    description: str = ""


# ---------------------------------------------------------------------------
# Complete manifest
# ---------------------------------------------------------------------------
# Every .py file and every package directory under src/ is represented.
# ---------------------------------------------------------------------------

MODULE_MANIFEST: List[ModuleEntry] = [

    # ── Core Engines ─────────────────────────────────────────────────────────
    ModuleEntry(
        module="confidence_engine",
        room="confidence-engine",
        commands=["confidence status", "confidence score", "confidence artifacts"],
        persona="TriageBot",
        emits=["recalibration_start", "metric_recorded"],
        consumes=["task_completed", "gate_evaluated"],
        description="Confidence scoring and artifact graph",
    ),
    ModuleEntry(
        module="execution_engine",
        room="execution-engine",
        commands=["exec run", "exec status", "exec queue", "exec history"],
        persona="ExecutionBot",
        emits=["task_submitted", "task_completed", "task_failed"],
        consumes=["gate_evaluated"],
        description="Core task execution engine",
    ),
    ModuleEntry(
        module="execution_orchestrator",
        room="execution-orchestrator",
        commands=["exec overview", "exec flows", "exec orchestrate"],
        persona="ExecutionBot",
        emits=["delivery_requested", "delivery_completed"],
        consumes=["task_submitted"],
        description="Execution orchestration and flow management",
    ),
    ModuleEntry(
        module="gate_synthesis",
        room="gate-synthesis",
        commands=["compliance gates", "gates status", "gates arm", "gates disarm"],
        persona="ComplianceBot",
        emits=["gate_evaluated", "gate_blocked"],
        consumes=["task_submitted", "audit_logged"],
        description="Gate synthesis and compliance enforcement",
    ),
    ModuleEntry(
        module="learning_engine",
        room="learning-engine",
        commands=["monitor telemetry", "learning feedback", "learning status"],
        persona="MonitoringBot",
        emits=["learning_feedback"],
        consumes=["task_completed", "task_failed"],
        description="Adaptive learning engine",
    ),
    ModuleEntry(
        module="integration_engine",
        room="integration-engine",
        commands=["integrations list", "integrations status", "integrations add"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=["delivery_requested"],
        description="Integration engine",
    ),
    ModuleEntry(
        module="form_intake",
        room="form-intake",
        commands=["form submit", "form list", "form status"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Form intake and processing",
    ),
    ModuleEntry(
        module="system_librarian",
        room="librarian",
        commands=["librarian query", "librarian capabilities", "librarian search"],
        persona="LibrarianBot",
        emits=[],
        consumes=["task_submitted"],
        description="System librarian and semantic search",
    ),
    ModuleEntry(
        module="security_plane",
        room="security-plane",
        commands=["security status", "security scan", "security audit"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=["gate_blocked"],
        description="Security plane and threat management",
    ),
    ModuleEntry(
        module="control_plane",
        room="control-plane",
        commands=["control status", "control plane"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Control plane management",
    ),
    ModuleEntry(
        module="compute_plane",
        room="compute-plane",
        commands=["compute status", "compute resources"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Compute plane management",
    ),

    # ── Governance & Compliance ───────────────────────────────────────────────
    ModuleEntry(
        module="governance_framework",
        room="governance-framework",
        commands=["governance policies", "governance status"],
        persona="ComplianceBot",
        emits=["audit_logged"],
        consumes=["gate_evaluated"],
        description="Governance framework",
    ),
    ModuleEntry(
        module="base_governance_runtime",
        room="base-governance-runtime",
        commands=["governance runtime", "governance toggle"],
        persona="ComplianceBot",
        emits=["audit_logged"],
        consumes=[],
        description="Base governance runtime",
    ),
    ModuleEntry(
        module="compliance_engine",
        room="compliance-engine",
        commands=["compliance status", "compliance report", "compliance audit"],
        persona="ComplianceBot",
        emits=["audit_logged", "gate_blocked"],
        consumes=["gate_evaluated"],
        description="Compliance engine",
    ),
    ModuleEntry(
        module="compliance_as_code_engine",
        room="compliance-as-code-engine",
        commands=["compliance code", "compliance policy"],
        persona="ComplianceBot",
        emits=["audit_logged"],
        consumes=[],
        description="Compliance as code",
    ),
    ModuleEntry(
        module="compliance_monitoring_completeness",
        room="compliance-monitoring",
        commands=["compliance monitoring"],
        persona="ComplianceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Compliance monitoring completeness",
    ),
    ModuleEntry(
        module="rbac_governance",
        room="rbac-governance",
        commands=["compliance rbac", "security permissions"],
        persona="ComplianceBot",
        emits=["audit_logged"],
        consumes=[],
        description="RBAC governance",
    ),
    ModuleEntry(
        module="authority_gate",
        room="authority-gate",
        commands=["gates authority"],
        persona="ComplianceBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Authority gate",
    ),
    ModuleEntry(
        module="gate_bypass_controller",
        room="gate-bypass-controller",
        commands=["gates bypass"],
        persona="ComplianceBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Gate bypass controller",
    ),
    ModuleEntry(
        module="outreach_compliance_integration",
        room="outreach-compliance-integration",
        commands=["compliance check", "compliance status"],
        persona="GovernanceBot",
        emits=["outreach_checked"],
        consumes=["outreach_requested"],
        description="Outreach compliance integration — wires governor into all outreach paths",
    ),

    # ── Safety & HITL ─────────────────────────────────────────────────────────
    ModuleEntry(
        module="hitl_autonomy_controller",
        room="hitl-autonomy-controller",
        commands=["hitl status", "hitl pending", "hitl respond"],
        persona="TriageBot",
        emits=["hitl_required", "hitl_resolved"],
        consumes=["task_submitted"],
        description="HITL autonomy controller",
    ),
    ModuleEntry(
        module="hitl_graduation_engine",
        room="hitl-graduation-engine",
        commands=["hitl graduate", "hitl level"],
        persona="TriageBot",
        emits=["hitl_resolved"],
        consumes=["hitl_required"],
        description="HITL graduation engine",
    ),
    ModuleEntry(
        module="safety_orchestrator",
        room="safety-orchestrator",
        commands=["safety status", "safety orchestrate"],
        persona="TriageBot",
        emits=["alert_fired"],
        consumes=["gate_blocked"],
        description="Safety orchestrator",
    ),
    ModuleEntry(
        module="safety_validation_pipeline",
        room="safety-validation-pipeline",
        commands=["safety validate"],
        persona="TriageBot",
        emits=["audit_logged"],
        consumes=["task_submitted"],
        description="Safety validation pipeline",
    ),
    ModuleEntry(
        module="safety_gateway_integrator",
        room="safety-gateway-integrator",
        commands=["safety gateway"],
        persona="TriageBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Safety gateway integrator",
    ),
    ModuleEntry(
        module="emergency_stop_controller",
        room="emergency-stop-controller",
        commands=["safety estop", "safety emergency"],
        persona="TriageBot",
        emits=["alert_fired"],
        consumes=[],
        description="Emergency stop controller",
    ),
    ModuleEntry(
        module="freelancer_validator",
        room="freelancer-validator",
        commands=["hitl validate", "freelancer validate"],
        persona="TriageBot",
        emits=["hitl_required"],
        consumes=[],
        description="Freelancer validator",
    ),

    # ── Automation & Execution ────────────────────────────────────────────────
    ModuleEntry(
        module="automation_scheduler",
        room="automation-scheduler",
        commands=["exec schedule", "schedule predict", "schedule list"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=[],
        description="Automation scheduler",
    ),
    ModuleEntry(
        module="automation_scaler",
        room="automation-scaler",
        commands=["exec scale"],
        persona="ExecutionBot",
        emits=["metric_recorded"],
        consumes=["task_completed"],
        description="Automation scaler",
    ),
    ModuleEntry(
        module="automation_marketplace",
        room="automation-marketplace",
        commands=["exec marketplace", "automation marketplace"],
        persona="ExecutionBot",
        emits=[],
        consumes=[],
        description="Automation marketplace",
    ),
    ModuleEntry(
        module="automation_mode_controller",
        room="automation-mode-controller",
        commands=["automation mode", "automation set-mode"],
        persona="ExecutionBot",
        emits=["audit_logged"],
        consumes=[],
        description="Automation mode controller",
    ),
    ModuleEntry(
        module="full_automation_controller",
        room="full-automation-controller",
        commands=["automation full", "automation enable"],
        persona="ExecutionBot",
        emits=["audit_logged"],
        consumes=[],
        description="Full automation controller",
    ),
    ModuleEntry(
        module="self_automation_orchestrator",
        room="self-automation-orchestrator",
        commands=["automation self", "automation orchestrate"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=["task_completed"],
        description="Self automation orchestrator",
    ),
    ModuleEntry(
        module="murphy_native_automation",
        room="murphy-native-automation",
        commands=["automation native"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=[],
        description="Murphy native automation",
    ),
    ModuleEntry(
        module="automation_integration_hub",
        room="automation-integration-hub",
        commands=["automation hub", "automation integrations"],
        persona="ExecutionBot",
        emits=[],
        consumes=[],
        description="Automation integration hub",
    ),
    ModuleEntry(
        module="automation_loop_connector",
        room="automation-loop-connector",
        commands=["automation loop"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=["task_completed"],
        description="Automation loop connector",
    ),
    ModuleEntry(
        module="automation_rbac_controller",
        room="automation-rbac-controller",
        commands=["automation rbac"],
        persona="ExecutionBot",
        emits=["audit_logged"],
        consumes=[],
        description="Automation RBAC controller",
    ),
    ModuleEntry(
        module="automation_readiness_evaluator",
        room="automation-readiness-evaluator",
        commands=["automation readiness"],
        persona="ExecutionBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Automation readiness evaluator",
    ),
    ModuleEntry(
        module="automation_type_registry",
        room="automation-type-registry",
        commands=["automation types"],
        persona="ExecutionBot",
        emits=[],
        consumes=[],
        description="Automation type registry",
    ),

    # ── LLM & AI ─────────────────────────────────────────────────────────────
    ModuleEntry(
        module="llm_integration_layer",
        room="llm-integration-layer",
        commands=["llm status", "llm providers"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="LLM integration layer",
    ),
    ModuleEntry(
        module="llm_controller",
        room="llm-controller",
        commands=["llm route", "llm model"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="LLM controller",
    ),
    ModuleEntry(
        module="llm_output_validator",
        room="llm-output-validator",
        commands=["llm validate"],
        persona="TriageBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="LLM output validator",
    ),
    ModuleEntry(
        module="llm_routing_completeness",
        room="llm-routing-completeness",
        commands=["llm routing"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="LLM routing completeness",
    ),
    ModuleEntry(
        module="llm_swarm_integration",
        room="llm-swarm-integration",
        commands=["llm swarm"],
        persona="TriageBot",
        emits=["swarm_spawned"],
        consumes=[],
        description="LLM swarm integration",
    ),
    ModuleEntry(
        module="enhanced_local_llm",
        room="enhanced-local-llm",
        commands=["llm local", "llm onboard"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Enhanced local LLM (onboard)",
    ),
    ModuleEntry(
        module="local_inference_engine",
        room="local-inference-engine",
        commands=["llm inference"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Local inference engine",
    ),
    ModuleEntry(
        module="local_llm_fallback",
        room="local-llm-fallback",
        commands=["llm fallback"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Local LLM fallback",
    ),
    ModuleEntry(
        module="local_model_layer",
        room="local-model-layer",
        commands=["llm models"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Local model layer",
    ),
    ModuleEntry(
        module="safe_llm_wrapper",
        room="safe-llm-wrapper",
        commands=["llm safe"],
        persona="TriageBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Safe LLM wrapper",
    ),
    ModuleEntry(
        module="openai_compatible_provider",
        room="openai-compatible-provider",
        commands=["llm openai", "llm groq"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="OpenAI-compatible provider (openai/groq/onboard)",
    ),
    ModuleEntry(
        module="groq_key_rotator",
        room="groq-key-rotator",
        commands=["keys groq", "llm groq-keys"],
        persona="KeyManagerBot",
        emits=["audit_logged"],
        consumes=[],
        description="Groq key rotator",
    ),
    ModuleEntry(
        module="inference_gate_engine",
        room="inference-gate-engine",
        commands=["llm gate"],
        persona="TriageBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Inference gate engine",
    ),

    # ── Swarm & Agent Systems ─────────────────────────────────────────────────
    ModuleEntry(
        module="advanced_swarm_system",
        room="advanced-swarm-system",
        commands=["swarm status", "swarm spawn", "swarm list"],
        persona="TriageBot",
        emits=["swarm_spawned"],
        consumes=["task_submitted"],
        description="Advanced swarm system",
    ),
    ModuleEntry(
        module="domain_swarms",
        room="domain-swarms",
        commands=["swarm domain"],
        persona="TriageBot",
        emits=["swarm_spawned"],
        consumes=["task_submitted"],
        description="Domain swarms",
    ),
    ModuleEntry(
        module="durable_swarm_orchestrator",
        room="durable-swarm-orchestrator",
        commands=["swarm orchestrate", "swarm durable"],
        persona="TriageBot",
        emits=["swarm_spawned"],
        consumes=[],
        description="Durable swarm orchestrator",
    ),
    ModuleEntry(
        module="murphy_crew_system",
        room="murphy-crew-system",
        commands=["swarm crew"],
        persona="TriageBot",
        emits=["swarm_spawned"],
        consumes=[],
        description="Murphy crew system",
    ),
    ModuleEntry(
        module="swarm_proposal_generator",
        room="swarm-proposal-generator",
        commands=["swarm propose"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Swarm proposal generator",
    ),
    ModuleEntry(
        module="agent_persona_library",
        room="agent-persona-library",
        commands=["agents personas", "agents list"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Agent persona library",
    ),
    ModuleEntry(
        module="agent_monitor_dashboard",
        room="agent-monitor-dashboard",
        commands=["agents monitor", "agents dashboard"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=["task_completed"],
        description="Agent monitor dashboard",
    ),
    ModuleEntry(
        module="agent_run_recorder",
        room="agent-run-recorder",
        commands=["agents runs", "agents history"],
        persona="MonitoringBot",
        emits=[],
        consumes=["task_completed"],
        description="Agent run recorder",
    ),
    ModuleEntry(
        module="agentic_api_provisioner",
        room="agentic-api-provisioner",
        commands=["agents provision-api"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Agentic API provisioner",
    ),
    ModuleEntry(
        module="agentic_onboarding_engine",
        room="agentic-onboarding-engine",
        commands=["onboard start", "onboard status"],
        persona="OnboardingBot",
        emits=["task_submitted"],
        consumes=[],
        description="Agentic onboarding engine",
    ),
    ModuleEntry(
        module="declarative_fleet_manager",
        room="declarative-fleet-manager",
        commands=["fleet status", "fleet deploy"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=[],
        description="Declarative fleet manager",
    ),

    # ── Business & Finance ────────────────────────────────────────────────────
    ModuleEntry(
        module="niche_business_generator",
        room="niche-business-generator",
        commands=["biz niche", "biz generate"],
        persona="FinanceBot",
        emits=["task_submitted"],
        consumes=[],
        description="Niche business generator",
    ),
    ModuleEntry(
        module="niche_viability_gate",
        room="niche-viability-gate",
        commands=["biz viability"],
        persona="FinanceBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Niche viability gate",
    ),
    ModuleEntry(
        module="business_scaling_engine",
        room="business-scaling-engine",
        commands=["biz scale"],
        persona="FinanceBot",
        emits=["task_submitted"],
        consumes=[],
        description="Business scaling engine",
    ),
    ModuleEntry(
        module="invoice_processing_pipeline",
        room="invoice-processing-pipeline",
        commands=["finance invoices", "finance invoice"],
        persona="FinanceBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Invoice processing pipeline",
    ),
    ModuleEntry(
        module="financial_reporting_engine",
        room="financial-reporting-engine",
        commands=["finance report", "finance summary"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Financial reporting engine",
    ),
    ModuleEntry(
        module="sales_automation",
        room="sales-automation",
        commands=["sales status", "sales pipeline"],
        persona="FinanceBot",
        emits=["task_submitted"],
        consumes=[],
        description="Sales automation",
    ),
    ModuleEntry(
        module="trading_bot_engine",
        room="trading-bot-engine",
        commands=["finance trading", "trading status"],
        persona="FinanceBot",
        emits=["task_completed", "metric_recorded"],
        consumes=["hitl_required"],
        description="Trading bot engine",
    ),
    ModuleEntry(
        module="trading_strategy_engine",
        room="trading-strategy-engine",
        commands=["trading strategy"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Trading strategy engine",
    ),
    ModuleEntry(
        module="trading_bot_lifecycle",
        room="trading-bot-lifecycle",
        commands=["trading lifecycle"],
        persona="FinanceBot",
        emits=["audit_logged"],
        consumes=[],
        description="Trading bot lifecycle",
    ),
    ModuleEntry(
        module="trading_hitl_gateway",
        room="trading-hitl-gateway",
        commands=["trading approve"],
        persona="FinanceBot",
        emits=["hitl_required"],
        consumes=["hitl_resolved"],
        description="Trading HITL gateway",
    ),
    ModuleEntry(
        module="trading_shadow_learner",
        room="trading-shadow-learner",
        commands=["trading shadow"],
        persona="FinanceBot",
        emits=["learning_feedback"],
        consumes=["task_completed"],
        description="Trading shadow learner",
    ),
    ModuleEntry(
        module="crypto_exchange_connector",
        room="crypto-exchange-connector",
        commands=["finance crypto exchange"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Crypto exchange connector",
    ),
    ModuleEntry(
        module="crypto_portfolio_tracker",
        room="crypto-portfolio-tracker",
        commands=["finance crypto portfolio"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Crypto portfolio tracker",
    ),
    ModuleEntry(
        module="crypto_risk_manager",
        room="crypto-risk-manager",
        commands=["finance crypto risk"],
        persona="FinanceBot",
        emits=["alert_fired"],
        consumes=["metric_recorded"],
        description="Crypto risk manager",
    ),
    ModuleEntry(
        module="crypto_wallet_manager",
        room="crypto-wallet-manager",
        commands=["finance crypto wallet"],
        persona="FinanceBot",
        emits=["audit_logged"],
        consumes=[],
        description="Crypto wallet manager",
    ),
    ModuleEntry(
        module="coinbase_connector",
        room="coinbase-connector",
        commands=["finance coinbase"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Coinbase connector",
    ),
    ModuleEntry(
        module="budget_aware_processor",
        room="budget-aware-processor",
        commands=["finance budget"],
        persona="FinanceBot",
        emits=["alert_fired"],
        consumes=["metric_recorded"],
        description="Budget-aware processor",
    ),
    ModuleEntry(
        module="cost_optimization_advisor",
        room="cost-optimization-advisor",
        commands=["finance costs", "costs recommendations"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Cost optimization advisor",
    ),
    ModuleEntry(
        module="cost_explosion_gate",
        room="cost-explosion-gate",
        commands=["finance cost-gate"],
        persona="FinanceBot",
        emits=["gate_blocked"],
        consumes=["metric_recorded"],
        description="Cost explosion gate",
    ),
    ModuleEntry(
        module="market_data_feed",
        room="market-data-feed",
        commands=["finance market"],
        persona="FinanceBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Market data feed",
    ),
    ModuleEntry(
        module="rosetta_selling_bridge",
        room="rosetta-selling-bridge",
        commands=["rosetta sell"],
        persona="FinanceBot",
        emits=["task_submitted"],
        consumes=[],
        description="Rosetta selling bridge",
    ),

    # ── Communication & Notifications ─────────────────────────────────────────
    ModuleEntry(
        module="email_integration",
        room="email-integration",
        commands=["email send", "email configure", "email test"],
        persona="TriageBot",
        emits=["delivery_completed"],
        consumes=["delivery_requested"],
        description="Email integration",
    ),
    ModuleEntry(
        module="notification_system",
        room="notification-system",
        commands=["notify send", "notify list", "notify configure"],
        persona="TriageBot",
        emits=["delivery_completed"],
        consumes=["delivery_requested"],
        description="Notification system",
    ),
    ModuleEntry(
        module="customer_communication_manager",
        room="customer-communication-manager",
        commands=["comms customer", "comms status"],
        persona="TriageBot",
        emits=["delivery_completed"],
        consumes=[],
        description="Customer communication manager",
    ),
    ModuleEntry(
        module="social_media_scheduler",
        room="social-media-scheduler",
        commands=["social schedule", "social post"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Social media scheduler",
    ),
    ModuleEntry(
        module="social_media_moderation",
        room="social-media-moderation",
        commands=["social moderate"],
        persona="TriageBot",
        emits=["gate_evaluated"],
        consumes=["task_submitted"],
        description="Social media moderation",
    ),
    ModuleEntry(
        module="announcer_voice_engine",
        room="announcer-voice-engine",
        commands=["announce", "announce broadcast"],
        persona="TriageBot",
        emits=["delivery_completed"],
        consumes=[],
        description="Announcer voice engine",
    ),
    ModuleEntry(
        module="content_pipeline_engine",
        room="content-pipeline-engine",
        commands=["content pipeline", "content status"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Content pipeline engine",
    ),
    ModuleEntry(
        module="content_creator_platform_modulator",
        room="content-creator-platform-modulator",
        commands=["content platform"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Content creator platform modulator",
    ),
    ModuleEntry(
        module="campaign_orchestrator",
        room="campaign-orchestrator",
        commands=["campaign run", "campaign status"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Campaign orchestrator",
    ),
    ModuleEntry(
        module="adaptive_campaign_engine",
        room="adaptive-campaign-engine",
        commands=["campaign adapt"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=["learning_feedback"],
        description="Adaptive campaign engine",
    ),
    ModuleEntry(
        module="self_marketing_orchestrator",
        room="self-marketing-orchestrator",
        commands=[
            "marketing cycle", "marketing content", "marketing social",
            "marketing outreach", "marketing b2b", "marketing partnerships",
        ],
        persona="MarketingBot",
        emits=[
            "content_published", "social_posted",
            "outreach_sent", "outreach_blocked",
            "b2b_pitch_sent", "b2b_pitch_blocked",
            "b2b_partner_interested", "b2b_partner_declined",
        ],
        consumes=["campaign_adjusted", "traction_evaluated"],
        description="Self-marketing orchestrator — Murphy markets Murphy with compliance + B2B partnerships",
    ),

    # ── Infrastructure & DevOps ───────────────────────────────────────────────
    ModuleEntry(
        module="docker_containerization",
        room="docker-containerization",
        commands=["infra docker", "docker status"],
        persona="ExecutionBot",
        emits=["task_completed"],
        consumes=[],
        description="Docker containerization",
    ),
    ModuleEntry(
        module="kubernetes_deployment",
        room="kubernetes-deployment",
        commands=["infra k8s", "k8s status"],
        persona="ExecutionBot",
        emits=["task_completed", "metric_recorded"],
        consumes=[],
        description="Kubernetes deployment",
    ),
    ModuleEntry(
        module="hetzner_deploy",
        room="hetzner-deploy",
        commands=["infra hetzner"],
        persona="ExecutionBot",
        emits=["task_completed"],
        consumes=[],
        description="Hetzner deployment",
    ),
    ModuleEntry(
        module="cloudflare_deploy",
        room="cloudflare-deploy",
        commands=["infra cloudflare"],
        persona="ExecutionBot",
        emits=["task_completed"],
        consumes=[],
        description="Cloudflare deployment",
    ),
    ModuleEntry(
        module="ci_cd_pipeline_manager",
        room="ci-cd-pipeline-manager",
        commands=["cicd status", "cicd pipeline", "cicd trigger"],
        persona="ExecutionBot",
        emits=["task_completed"],
        consumes=[],
        description="CI/CD pipeline manager",
    ),
    ModuleEntry(
        module="multi_cloud_orchestrator",
        room="multi-cloud-orchestrator",
        commands=["cloud status", "cloud orchestrate"],
        persona="ExecutionBot",
        emits=["task_completed"],
        consumes=[],
        description="Multi-cloud orchestrator",
    ),
    ModuleEntry(
        module="geographic_load_balancer",
        room="geographic-load-balancer",
        commands=["infra lb", "infra load-balancer"],
        persona="ExecutionBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Geographic load balancer",
    ),
    ModuleEntry(
        module="resource_scaling_controller",
        room="resource-scaling-controller",
        commands=["infra scale"],
        persona="ExecutionBot",
        emits=["metric_recorded"],
        consumes=["metric_recorded"],
        description="Resource scaling controller",
    ),
    ModuleEntry(
        module="capacity_planning_engine",
        room="capacity-planning-engine",
        commands=["infra capacity"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Capacity planning engine",
    ),
    ModuleEntry(
        module="backup_disaster_recovery",
        room="backup-disaster-recovery",
        commands=["infra backup", "infra dr"],
        persona="ExecutionBot",
        emits=["task_completed"],
        consumes=[],
        description="Backup & disaster recovery",
    ),

    # ── Security ──────────────────────────────────────────────────────────────
    ModuleEntry(
        module="security_plane_adapter",
        room="security-plane-adapter",
        commands=["security adapter"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="Security plane adapter",
    ),
    ModuleEntry(
        module="security_audit_scanner",
        room="security-audit-scanner",
        commands=["security scan", "security audit"],
        persona="SecurityBot",
        emits=["audit_logged", "alert_fired"],
        consumes=[],
        description="Security audit scanner",
    ),
    ModuleEntry(
        module="security_hardening_config",
        room="security-hardening-config",
        commands=["security harden"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="Security hardening config",
    ),
    ModuleEntry(
        module="fastapi_security",
        room="fastapi-security",
        commands=["security api"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="FastAPI security layer",
    ),
    ModuleEntry(
        module="flask_security",
        room="flask-security",
        commands=["security flask"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="Flask security layer",
    ),
    ModuleEntry(
        module="oauth_oidc_provider",
        room="oauth-oidc-provider",
        commands=["security oauth", "security oidc"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="OAuth/OIDC provider",
    ),
    ModuleEntry(
        module="secure_key_manager",
        room="secure-key-manager",
        commands=["keys list", "keys status", "keys create"],
        persona="KeyManagerBot",
        emits=["audit_logged"],
        consumes=[],
        description="Secure key manager",
    ),
    ModuleEntry(
        module="murphy_credential_gate",
        room="murphy-credential-gate",
        commands=["security credentials"],
        persona="SecurityBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Murphy credential gate",
    ),
    ModuleEntry(
        module="key_harvester",
        room="key-harvester",
        commands=["keys harvest"],
        persona="KeyManagerBot",
        emits=["audit_logged"],
        consumes=[],
        description="Key harvester",
    ),

    # ── Data & Knowledge ──────────────────────────────────────────────────────
    ModuleEntry(
        module="knowledge_graph_builder",
        room="knowledge-graph-builder",
        commands=["librarian graph", "kg status"],
        persona="LibrarianBot",
        emits=["rosetta_updated"],
        consumes=["task_completed"],
        description="Knowledge graph builder",
    ),
    ModuleEntry(
        module="knowledge_base_manager",
        room="knowledge-base-manager",
        commands=["librarian kb", "kb status"],
        persona="LibrarianBot",
        emits=[],
        consumes=[],
        description="Knowledge base manager",
    ),
    ModuleEntry(
        module="knowledge_gap_system",
        room="knowledge-gap-system",
        commands=["librarian gap", "kg gap"],
        persona="LibrarianBot",
        emits=["task_submitted"],
        consumes=[],
        description="Knowledge gap system",
    ),
    ModuleEntry(
        module="rag_vector_integration",
        room="rag-vector-integration",
        commands=["librarian rag", "rag search"],
        persona="LibrarianBot",
        emits=[],
        consumes=[],
        description="RAG vector integration",
    ),
    ModuleEntry(
        module="generative_knowledge_builder",
        room="generative-knowledge-builder",
        commands=["librarian generate", "kg generate"],
        persona="LibrarianBot",
        emits=["task_submitted"],
        consumes=[],
        description="Generative knowledge builder",
    ),
    ModuleEntry(
        module="concept_graph_engine",
        room="concept-graph-engine",
        commands=["kg concepts"],
        persona="LibrarianBot",
        emits=[],
        consumes=[],
        description="Concept graph engine",
    ),
    ModuleEntry(
        module="concept_translation",
        room="concept-translation",
        commands=["kg translate"],
        persona="LibrarianBot",
        emits=[],
        consumes=[],
        description="Concept translation",
    ),
    ModuleEntry(
        module="data_pipeline_orchestrator",
        room="data-pipeline-orchestrator",
        commands=["data pipeline", "data status"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Data pipeline orchestrator",
    ),
    ModuleEntry(
        module="data_archive_manager",
        room="data-archive-manager",
        commands=["data archive"],
        persona="TriageBot",
        emits=["task_completed"],
        consumes=[],
        description="Data archive manager",
    ),
    ModuleEntry(
        module="cross_platform_data_sync",
        room="cross-platform-data-sync",
        commands=["data sync"],
        persona="TriageBot",
        emits=["task_completed"],
        consumes=[],
        description="Cross-platform data sync",
    ),

    # ── Monitoring & Observability ────────────────────────────────────────────
    ModuleEntry(
        module="health_monitor",
        room="health-monitor",
        commands=["monitor health", "health status"],
        persona="MonitoringBot",
        emits=["system_health"],
        consumes=[],
        description="Health monitor",
    ),
    ModuleEntry(
        module="heartbeat_liveness_protocol",
        room="heartbeat-liveness-protocol",
        commands=["monitor heartbeat"],
        persona="MonitoringBot",
        emits=["bot_heartbeat_ok", "bot_heartbeat_failed"],
        consumes=[],
        description="Heartbeat liveness protocol",
    ),
    ModuleEntry(
        module="activated_heartbeat_runner",
        room="activated-heartbeat-runner",
        commands=["monitor heartbeat-runner"],
        persona="MonitoringBot",
        emits=["bot_heartbeat_ok"],
        consumes=[],
        description="Activated heartbeat runner",
    ),
    ModuleEntry(
        module="prometheus_metrics_exporter",
        room="prometheus-metrics-exporter",
        commands=["monitor metrics", "metrics export"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Prometheus metrics exporter",
    ),
    ModuleEntry(
        module="observability_counters",
        room="observability-counters",
        commands=["monitor counters"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Observability counters",
    ),
    ModuleEntry(
        module="murphy_trace",
        room="murphy-trace",
        commands=["monitor trace"],
        persona="MonitoringBot",
        emits=[],
        consumes=[],
        description="Murphy trace",
    ),
    ModuleEntry(
        module="bot_telemetry_normalizer",
        room="bot-telemetry-normalizer",
        commands=["monitor bot-telemetry"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Bot telemetry normalizer",
    ),
    ModuleEntry(
        module="telemetry_adapter",
        room="telemetry-adapter",
        commands=["monitor telemetry-adapter"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Telemetry adapter",
    ),
    ModuleEntry(
        module="telemetry_system",
        room="telemetry-system",
        commands=["monitor telemetry"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Telemetry system",
    ),
    ModuleEntry(
        module="telemetry_learning",
        room="telemetry-learning",
        commands=["monitor telemetry-learning"],
        persona="MonitoringBot",
        emits=["learning_feedback"],
        consumes=["metric_recorded"],
        description="Telemetry learning",
    ),
    ModuleEntry(
        module="operational_slo_tracker",
        room="operational-slo-tracker",
        commands=["monitor slo"],
        persona="MonitoringBot",
        emits=["alert_fired"],
        consumes=["metric_recorded"],
        description="Operational SLO tracker",
    ),
    ModuleEntry(
        module="slo_remediation_bridge",
        room="slo-remediation-bridge",
        commands=["monitor slo-remediate"],
        persona="MonitoringBot",
        emits=["task_submitted"],
        consumes=["alert_fired"],
        description="SLO remediation bridge",
    ),
    ModuleEntry(
        module="log_analysis_engine",
        room="log-analysis-engine",
        commands=["monitor logs"],
        persona="MonitoringBot",
        emits=["alert_fired"],
        consumes=[],
        description="Log analysis engine",
    ),
    ModuleEntry(
        module="alert_rules_engine",
        room="alert-rules-engine",
        commands=["monitor alerts"],
        persona="MonitoringBot",
        emits=["alert_fired", "alert_resolved"],
        consumes=["metric_recorded"],
        description="Alert rules engine",
    ),
    ModuleEntry(
        module="causal_spike_analyzer",
        room="causal-spike-analyzer",
        commands=["monitor spikes"],
        persona="MonitoringBot",
        emits=["alert_fired"],
        consumes=["metric_recorded"],
        description="Causal spike analyzer",
    ),

    # ── Self-Healing & Resilience ─────────────────────────────────────────────
    ModuleEntry(
        module="autonomous_repair_system",
        room="autonomous-repair-system",
        commands=["heal status", "heal repair"],
        persona="TriageBot",
        emits=["self_fix_started"],
        consumes=["alert_fired"],
        description="Autonomous repair system",
    ),
    ModuleEntry(
        module="self_fix_loop",
        room="self-fix-loop",
        commands=["heal fix"],
        persona="TriageBot",
        emits=["self_fix_started", "self_fix_completed"],
        consumes=["alert_fired"],
        description="Self-fix loop",
    ),
    ModuleEntry(
        module="self_healing_coordinator",
        room="self-healing-coordinator",
        commands=["heal coordinate"],
        persona="TriageBot",
        emits=["self_fix_started"],
        consumes=["alert_fired"],
        description="Self-healing coordinator",
    ),
    ModuleEntry(
        module="self_improvement_engine",
        room="self-improvement-engine",
        commands=["heal improve"],
        persona="TriageBot",
        emits=["learning_feedback"],
        consumes=["task_completed"],
        description="Self-improvement engine",
    ),
    ModuleEntry(
        module="self_optimisation_engine",
        room="self-optimisation-engine",
        commands=["heal optimise"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=["learning_feedback"],
        description="Self-optimisation engine",
    ),
    ModuleEntry(
        module="murphy_code_healer",
        room="murphy-code-healer",
        commands=["heal code"],
        persona="TriageBot",
        emits=["self_fix_started"],
        consumes=["alert_fired"],
        description="Murphy code healer",
    ),
    ModuleEntry(
        module="code_repair_engine",
        room="code-repair-engine",
        commands=["heal code-repair"],
        persona="TriageBot",
        emits=["self_fix_completed"],
        consumes=["self_fix_started"],
        description="Code repair engine",
    ),
    ModuleEntry(
        module="chaos_resilience_loop",
        room="chaos-resilience-loop",
        commands=["heal chaos"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Chaos resilience loop",
    ),
    ModuleEntry(
        module="murphy_immune_engine",
        room="murphy-immune-engine",
        commands=["heal immune"],
        persona="TriageBot",
        emits=["audit_logged"],
        consumes=["alert_fired"],
        description="Murphy immune engine",
    ),
    ModuleEntry(
        module="predictive_failure_engine",
        room="predictive-failure-engine",
        commands=["heal predict"],
        persona="MonitoringBot",
        emits=["alert_fired"],
        consumes=["metric_recorded"],
        description="Predictive failure engine",
    ),
    ModuleEntry(
        module="predictive_maintenance_engine",
        room="predictive-maintenance-engine",
        commands=["heal maintenance"],
        persona="MonitoringBot",
        emits=["task_submitted"],
        consumes=["metric_recorded"],
        description="Predictive maintenance engine",
    ),
    ModuleEntry(
        module="blackstart_controller",
        room="blackstart-controller",
        commands=["heal blackstart"],
        persona="TriageBot",
        emits=["system_health"],
        consumes=[],
        description="Blackstart controller",
    ),

    # ── Domain & Expert Systems ───────────────────────────────────────────────
    ModuleEntry(
        module="domain_engine",
        room="domain-engine",
        commands=["eng domain"],
        persona="EngineeringBot",
        emits=["task_submitted"],
        consumes=[],
        description="Domain engine",
    ),
    ModuleEntry(
        module="domain_expert_system",
        room="domain-expert-system",
        commands=["eng expert"],
        persona="EngineeringBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Domain expert system",
    ),
    ModuleEntry(
        module="domain_expert_integration",
        room="domain-expert-integration",
        commands=["eng expert-integrate"],
        persona="EngineeringBot",
        emits=[],
        consumes=[],
        description="Domain expert integration",
    ),
    ModuleEntry(
        module="domain_gate_generator",
        room="domain-gate-generator",
        commands=["eng gate-gen"],
        persona="EngineeringBot",
        emits=["gate_evaluated"],
        consumes=[],
        description="Domain gate generator",
    ),
    ModuleEntry(
        module="dynamic_expert_generator",
        room="dynamic-expert-generator",
        commands=["eng expert-gen"],
        persona="EngineeringBot",
        emits=["task_submitted"],
        consumes=[],
        description="Dynamic expert generator",
    ),
    ModuleEntry(
        module="murphy_engineering_toolbox",
        room="murphy-engineering-toolbox",
        commands=["eng toolbox"],
        persona="EngineeringBot",
        emits=["task_submitted"],
        consumes=[],
        description="Murphy engineering toolbox",
    ),
    ModuleEntry(
        module="simulation_engine",
        room="simulation-engine",
        commands=["eng simulate", "sim run", "sim validate"],
        persona="EngineeringBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Simulation engine",
    ),
    ModuleEntry(
        module="digital_twin_engine",
        room="digital-twin-engine",
        commands=["eng twin", "cad twin"],
        persona="CADBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Digital twin engine",
    ),
    ModuleEntry(
        module="computer_vision_pipeline",
        room="computer-vision-pipeline",
        commands=["eng vision", "vision run"],
        persona="EngineeringBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Computer vision pipeline",
    ),
    ModuleEntry(
        module="murphy_sensor_fusion",
        room="murphy-sensor-fusion",
        commands=["eng sensor"],
        persona="EngineeringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Murphy sensor fusion",
    ),
    ModuleEntry(
        module="murphy_autonomous_perception",
        room="murphy-autonomous-perception",
        commands=["eng perception"],
        persona="EngineeringBot",
        emits=["task_submitted"],
        consumes=["metric_recorded"],
        description="Murphy autonomous perception",
    ),

    # ── Org & Workflow ────────────────────────────────────────────────────────
    ModuleEntry(
        module="org_compiler",
        room="org-compiler",
        commands=["org compile", "org chart"],
        persona="TriageBot",
        emits=["task_completed"],
        consumes=[],
        description="Org compiler",
    ),
    ModuleEntry(
        module="org_chart_enforcement",
        room="org-chart-enforcement",
        commands=["org enforce"],
        persona="TriageBot",
        emits=["audit_logged"],
        consumes=[],
        description="Org chart enforcement",
    ),
    ModuleEntry(
        module="organization_chart_system",
        room="organization-chart-system",
        commands=["org orgchart"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Organization chart system",
    ),
    ModuleEntry(
        module="organizational_context_system",
        room="organizational-context-system",
        commands=["org context"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Organizational context system",
    ),
    ModuleEntry(
        module="onboarding_flow",
        room="onboarding-flow",
        commands=["onboard start", "onboard flow"],
        persona="OnboardingBot",
        emits=["task_submitted"],
        consumes=[],
        description="Onboarding flow",
    ),
    ModuleEntry(
        module="onboarding_automation_engine",
        room="onboarding-automation-engine",
        commands=["onboard automate"],
        persona="OnboardingBot",
        emits=["task_submitted"],
        consumes=[],
        description="Onboarding automation engine",
    ),
    ModuleEntry(
        module="onboarding_team_pipeline",
        room="onboarding-team-pipeline",
        commands=["onboard team"],
        persona="OnboardingBot",
        emits=["task_submitted"],
        consumes=[],
        description="Onboarding team pipeline",
    ),

    # ── Module System ─────────────────────────────────────────────────────────
    ModuleEntry(
        module="module_compiler",
        room="module-compiler",
        commands=["compile module", "modules list"],
        persona="TriageBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Module compiler",
    ),
    ModuleEntry(
        module="module_compiler_adapter",
        room="module-compiler-adapter",
        commands=["compile adapt"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Module compiler adapter",
    ),
    ModuleEntry(
        module="module_manager",
        room="module-manager",
        commands=["modules manage"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Module manager",
    ),
    ModuleEntry(
        module="module_registry",
        room="module-registry",
        commands=["modules registry"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Module registry",
    ),
    ModuleEntry(
        module="modular_runtime",
        room="modular-runtime",
        commands=["modules runtime"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Modular runtime",
    ),
    ModuleEntry(
        module="shim_compiler",
        room="shim-compiler",
        commands=["compile shim"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Shim compiler",
    ),
    ModuleEntry(
        module="plugin_extension_sdk",
        room="plugin-extension-sdk",
        commands=["modules plugins"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Plugin extension SDK",
    ),
    ModuleEntry(
        module="capability_map",
        room="capability-map",
        commands=["modules capabilities"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Capability map",
    ),

    # ── Misc Systems ──────────────────────────────────────────────────────────
    ModuleEntry(
        module="murphy_state_graph",
        room="murphy-state-graph",
        commands=["state graph"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Murphy state graph",
    ),
    ModuleEntry(
        module="murphy_template_hub",
        room="murphy-template-hub",
        commands=["templates list", "templates get"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Murphy template hub",
    ),
    ModuleEntry(
        module="murphy_drawing_engine",
        room="murphy-drawing-engine",
        commands=["cad draw", "draw generate"],
        persona="CADBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Murphy drawing engine",
    ),
    ModuleEntry(
        module="murphy_repl",
        room="murphy-repl",
        commands=["repl run", "repl eval"],
        persona="TriageBot",
        emits=["task_completed"],
        consumes=[],
        description="Murphy REPL",
    ),
    ModuleEntry(
        module="murphy_shadow_trainer",
        room="murphy-shadow-trainer",
        commands=["shadow train"],
        persona="TriageBot",
        emits=["learning_feedback"],
        consumes=["task_completed"],
        description="Murphy shadow trainer",
    ),
    ModuleEntry(
        module="murphy_osmosis_engine",
        room="murphy-osmosis-engine",
        commands=["osmosis run"],
        persona="TriageBot",
        emits=["learning_feedback"],
        consumes=[],
        description="Murphy osmosis engine",
    ),
    ModuleEntry(
        module="murphy_wingman_evolution",
        room="murphy-wingman-evolution",
        commands=["wingman evolve"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Murphy wingman evolution",
    ),
    ModuleEntry(
        module="murphy_action_engine",
        room="murphy-action-engine",
        commands=["action run", "action list"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Murphy action engine",
    ),
    ModuleEntry(
        module="nocode_workflow_terminal",
        room="nocode-workflow-terminal",
        commands=["nocode workflow", "nocode run"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="No-code workflow terminal",
    ),
    ModuleEntry(
        module="ai_workflow_generator",
        room="ai-workflow-generator",
        commands=["workflow generate", "ai workflow"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="AI workflow generator",
    ),
    ModuleEntry(
        module="rpa_recorder_engine",
        room="rpa-recorder-engine",
        commands=["rpa record", "rpa replay"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="RPA recorder engine",
    ),
    ModuleEntry(
        module="playwright_task_definitions",
        room="playwright-task-definitions",
        commands=["playwright run"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Playwright task definitions",
    ),
    ModuleEntry(
        module="image_generation_engine",
        room="image-generation-engine",
        commands=["cad image", "image generate"],
        persona="CADBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Image generation engine",
    ),
    ModuleEntry(
        module="digital_asset_generator",
        room="digital-asset-generator",
        commands=["cad asset", "asset generate"],
        persona="CADBot",
        emits=["task_completed"],
        consumes=[],
        description="Digital asset generator",
    ),
    ModuleEntry(
        module="innovation_farmer",
        room="innovation-farmer",
        commands=["innovate run", "innovate status"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Innovation farmer",
    ),
    ModuleEntry(
        module="knostalgia_engine",
        room="knostalgia-engine",
        commands=["knostalgia run"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Knostalgia engine",
    ),
    ModuleEntry(
        module="knostalgia_category_engine",
        room="knostalgia-category-engine",
        commands=["knostalgia categories"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Knostalgia category engine",
    ),
    ModuleEntry(
        module="research_engine",
        room="research-engine",
        commands=["research run", "research query"],
        persona="LibrarianBot",
        emits=["task_submitted"],
        consumes=[],
        description="Research engine",
    ),
    ModuleEntry(
        module="advanced_research",
        room="advanced-research",
        commands=["research advanced"],
        persona="LibrarianBot",
        emits=["task_submitted"],
        consumes=[],
        description="Advanced research",
    ),
    ModuleEntry(
        module="multi_source_research",
        room="multi-source-research",
        commands=["research multi"],
        persona="LibrarianBot",
        emits=["task_submitted"],
        consumes=[],
        description="Multi-source research",
    ),
    ModuleEntry(
        module="competitive_intelligence_engine",
        room="competitive-intelligence-engine",
        commands=["research competitive"],
        persona="LibrarianBot",
        emits=["task_submitted"],
        consumes=[],
        description="Competitive intelligence engine",
    ),

    # ── Runtime & State ───────────────────────────────────────────────────────
    ModuleEntry(
        module="runtime",
        room="runtime",
        commands=["runtime status"],
        persona="TriageBot",
        emits=["system_health"],
        consumes=[],
        description="Runtime package",
    ),
    ModuleEntry(
        module="recursive_stability_controller",
        room="recursive-stability-controller",
        commands=["runtime stability"],
        persona="TriageBot",
        emits=["system_health"],
        consumes=[],
        description="Recursive stability controller",
    ),
    ModuleEntry(
        module="supervision_tree",
        room="supervision-tree",
        commands=["runtime supervision"],
        persona="TriageBot",
        emits=["supervisor_child_started"],
        consumes=[],
        description="Supervision tree",
    ),
    ModuleEntry(
        module="supervisor_system",
        room="supervisor-system",
        commands=["runtime supervisor"],
        persona="TriageBot",
        emits=["supervisor_child_started", "supervisor_critical"],
        consumes=[],
        description="Supervisor system",
    ),
    ModuleEntry(
        module="persistence_manager",
        room="persistence-manager",
        commands=["runtime persistence"],
        persona="TriageBot",
        emits=["persistence_snapshot"],
        consumes=[],
        description="Persistence manager",
    ),
    ModuleEntry(
        module="persistence_wal",
        room="persistence-wal",
        commands=["runtime wal"],
        persona="TriageBot",
        emits=["persistence_snapshot"],
        consumes=[],
        description="Persistence WAL",
    ),
    ModuleEntry(
        module="persistence_replay_completeness",
        room="persistence-replay-completeness",
        commands=["runtime replay"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Persistence replay completeness",
    ),
    ModuleEntry(
        module="state_machine",
        room="state-machine",
        commands=["state machine"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="State machine",
    ),
    ModuleEntry(
        module="state_schema",
        room="state-schema",
        commands=["state schema"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="State schema",
    ),
    ModuleEntry(
        module="session_context",
        room="session-context",
        commands=["runtime session"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Session context",
    ),
    ModuleEntry(
        module="closure_engine",
        room="closure-engine",
        commands=["runtime closure"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Closure engine",
    ),
    ModuleEntry(
        module="event_backbone",
        room="event-backbone",
        commands=["events status", "events list"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Event backbone",
    ),

    # ── Integration & Adapters ────────────────────────────────────────────────
    ModuleEntry(
        module="integration_bus",
        room="integration-bus",
        commands=["integrations bus"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Integration bus",
    ),
    ModuleEntry(
        module="integrations",
        room="integrations",
        commands=["integrations all"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Integrations package",
    ),
    ModuleEntry(
        module="system_integrator",
        room="system-integrator",
        commands=["integrations system"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="System integrator",
    ),
    ModuleEntry(
        module="enterprise_integrations",
        room="enterprise-integrations",
        commands=["integrations enterprise"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Enterprise integrations",
    ),
    ModuleEntry(
        module="platform_connector_framework",
        room="platform-connector-framework",
        commands=["platforms list", "platforms connect"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Platform connector framework",
    ),
    ModuleEntry(
        module="delivery_adapters",
        room="delivery-adapters",
        commands=["delivery list"],
        persona="TriageBot",
        emits=["delivery_completed"],
        consumes=["delivery_requested"],
        description="Delivery adapters",
    ),
    ModuleEntry(
        module="delivery_channel_completeness",
        room="delivery-channel-completeness",
        commands=["delivery channels"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Delivery channel completeness",
    ),
    ModuleEntry(
        module="ticketing_adapter",
        room="ticketing-adapter",
        commands=["tickets list", "tickets create"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=[],
        description="Ticketing adapter",
    ),
    ModuleEntry(
        module="mfgc_core",
        room="mfgc-core",
        commands=["mfgc status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="MFGC core",
    ),
    ModuleEntry(
        module="mfgc_adapter",
        room="mfgc-adapter",
        commands=["mfgc adapt"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="MFGC adapter",
    ),
    ModuleEntry(
        module="mfgc_metrics",
        room="mfgc-metrics",
        commands=["mfgc metrics"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="MFGC metrics",
    ),
    ModuleEntry(
        module="remote_access_connector",
        room="remote-access-connector",
        commands=["remote connect"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Remote access connector",
    ),

    # ── IoT & Industrial ──────────────────────────────────────────────────────
    ModuleEntry(
        module="building_automation_connectors",
        room="building-automation-connectors",
        commands=["iot building"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Building automation connectors",
    ),
    ModuleEntry(
        module="energy_management_connectors",
        room="energy-management-connectors",
        commands=["iot energy"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Energy management connectors",
    ),
    ModuleEntry(
        module="additive_manufacturing_connectors",
        room="additive-manufacturing-connectors",
        commands=["iot additive"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Additive manufacturing connectors",
    ),
    ModuleEntry(
        module="manufacturing_automation_standards",
        room="manufacturing-automation-standards",
        commands=["iot manufacturing"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Manufacturing automation standards",
    ),
    ModuleEntry(
        module="sensor_reader",
        room="sensor-reader",
        commands=["iot sensors", "sensor read"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="Sensor reader",
    ),
    ModuleEntry(
        module="robotics",
        room="robotics",
        commands=["robotics status", "robotics run"],
        persona="EngineeringBot",
        emits=["task_submitted"],
        consumes=[],
        description="Robotics",
    ),

    # ── CRM & Account ─────────────────────────────────────────────────────────
    ModuleEntry(
        module="crm",
        room="crm",
        commands=["crm status", "crm leads", "crm contacts"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="CRM",
    ),
    ModuleEntry(
        module="account_management",
        room="account-management",
        commands=["account status", "account list"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Account management",
    ),
    ModuleEntry(
        module="credential_profile_system",
        room="credential-profile-system",
        commands=["credentials profile"],
        persona="KeyManagerBot",
        emits=["audit_logged"],
        consumes=[],
        description="Credential profile system",
    ),

    # ── Board & Portfolio ─────────────────────────────────────────────────────
    ModuleEntry(
        module="board_system",
        room="board-system",
        commands=["board status", "board tasks", "board sprint"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Board system",
    ),
    ModuleEntry(
        module="portfolio",
        room="portfolio",
        commands=["portfolio status", "portfolio list"],
        persona="FinanceBot",
        emits=[],
        consumes=[],
        description="Portfolio",
    ),
    ModuleEntry(
        module="time_tracking",
        room="time-tracking",
        commands=["time log", "time report"],
        persona="TriageBot",
        emits=["entry_approved", "entry_invoiced", "invoice_generated", "billable_threshold_reached"],
        consumes=[],
        description="Time tracking",
    ),

    # ── Communication Subsystems ──────────────────────────────────────────────
    ModuleEntry(
        module="comms",
        room="comms",
        commands=["comms status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Communications subsystem",
    ),
    ModuleEntry(
        module="communication_system",
        room="communication-system",
        commands=["comms system"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Communication system",
    ),
    ModuleEntry(
        module="collaboration",
        room="collaboration",
        commands=["collab status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Collaboration",
    ),
    ModuleEntry(
        module="guest_collab",
        room="guest-collab",
        commands=["collab guest"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Guest collaboration",
    ),

    # ── Additional ────────────────────────────────────────────────────────────
    ModuleEntry(
        module="bridge_layer",
        room="bridge-layer",
        commands=["bridge status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Bridge layer",
    ),
    ModuleEntry(
        module="protocols",
        room="protocols",
        commands=["protocols list"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Protocols",
    ),
    ModuleEntry(
        module="dashboards",
        room="dashboards",
        commands=["dashboard status"],
        persona="MonitoringBot",
        emits=[],
        consumes=[],
        description="Dashboards",
    ),
    ModuleEntry(
        module="dev_module",
        room="dev-module",
        commands=["dev status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Dev module",
    ),
    ModuleEntry(
        module="eq",
        room="eq",
        commands=["eq status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="EQ module",
    ),
    ModuleEntry(
        module="aionmind",
        room="aionmind",
        commands=["aionmind status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="AionMind",
    ),
    ModuleEntry(
        module="auar",
        room="auar",
        commands=["auar status", "auar route"],
        persona="TriageBot",
        emits=["metric_recorded"],
        consumes=[],
        description="AUAR (Universal Adaptive Routing)",
    ),
    ModuleEntry(
        module="avatar",
        room="avatar",
        commands=["avatar status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Avatar",
    ),
    ModuleEntry(
        module="neuro_symbolic_models",
        room="neuro-symbolic-models",
        commands=["neuro status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Neuro-symbolic models",
    ),
    ModuleEntry(
        module="rosetta",
        room="rosetta",
        commands=["rosetta status"],
        persona="TriageBot",
        emits=["rosetta_updated"],
        consumes=[],
        description="Rosetta",
    ),
    ModuleEntry(
        module="self_selling_engine",
        room="self-selling-engine",
        commands=["sell status"],
        persona="FinanceBot",
        emits=["task_submitted"],
        consumes=[],
        description="Self selling engine",
    ),
    ModuleEntry(
        module="schema_registry",
        room="schema-registry",
        commands=["schema list", "schema validate"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Schema registry",
    ),
    ModuleEntry(
        module="deterministic_compute_plane",
        room="deterministic-compute-plane",
        commands=["compute deterministic"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Deterministic compute plane",
    ),
    ModuleEntry(
        module="control_theory",
        room="control-theory",
        commands=["control theory"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Control theory",
    ),
    ModuleEntry(
        module="synthetic_failure_generator",
        room="synthetic-failure-generator",
        commands=["chaos failure"],
        persona="TriageBot",
        emits=["alert_fired"],
        consumes=[],
        description="Synthetic failure generator",
    ),
    ModuleEntry(
        module="autonomous_systems",
        room="autonomous-systems",
        commands=["autonomous status"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Autonomous systems",
    ),
    ModuleEntry(
        module="murphy_foundation_model",
        room="murphy-foundation-model",
        commands=["mfm status", "mfm train", "mfm infer"],
        persona="TriageBot",
        emits=["learning_feedback"],
        consumes=["task_completed"],
        description="Murphy Foundation Model",
    ),
    ModuleEntry(
        module="execution_packet_compiler",
        room="execution-packet-compiler",
        commands=["exec compile"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=[],
        description="Execution packet compiler",
    ),
    ModuleEntry(
        module="execution",
        room="execution",
        commands=["exec package"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=[],
        description="Execution package",
    ),

    # ── Additional .py files (non-package modules) ────────────────────────────
    ModuleEntry(
        module="ab_testing_framework",
        room="system-status",
        commands=["ab test"],
        persona="MonitoringBot",
        emits=["metric_recorded"],
        consumes=[],
        description="A/B testing framework",
    ),
    ModuleEntry(
        module="audit_logging_system",
        room="security-audit-scanner",
        commands=["audit logs"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="Audit logging system",
    ),
    ModuleEntry(
        module="auto_documentation_engine",
        room="librarian",
        commands=["docs generate", "docs status"],
        persona="LibrarianBot",
        emits=[],
        consumes=["task_completed"],
        description="Auto documentation engine",
    ),
    ModuleEntry(
        module="blockchain_audit_trail",
        room="security-audit-scanner",
        commands=["audit blockchain"],
        persona="SecurityBot",
        emits=["audit_logged"],
        consumes=[],
        description="Blockchain audit trail",
    ),
    ModuleEntry(
        module="bot_governance_policy_mapper",
        room="governance-framework",
        commands=["governance bot-policies"],
        persona="ComplianceBot",
        emits=[],
        consumes=[],
        description="Bot governance policy mapper",
    ),
    ModuleEntry(
        module="bot_inventory_library",
        room="agent-persona-library",
        commands=["bots inventory"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Bot inventory library",
    ),
    ModuleEntry(
        module="compliance_automation_bridge",
        room="compliance-engine",
        commands=["compliance automate"],
        persona="ComplianceBot",
        emits=[],
        consumes=[],
        description="Compliance automation bridge",
    ),
    ModuleEntry(
        module="compliance_orchestration_bridge",
        room="compliance-engine",
        commands=["compliance orchestrate"],
        persona="ComplianceBot",
        emits=[],
        consumes=[],
        description="Compliance orchestration bridge",
    ),
    ModuleEntry(
        module="contact_compliance_governor",
        room="contact-compliance-governor",
        commands=["compliance outreach", "compliance dnc"],
        persona="GovernanceBot",
        emits=["outreach_blocked", "contact_suppressed", "dnc_added"],
        consumes=["outreach_requested"],
        description="Contact compliance governor — cooldown, DNC, regulatory gating",
    ),
    ModuleEntry(
        module="legacy_compatibility_matrix",
        room="bridge-layer",
        commands=["bridge compat"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Legacy compatibility matrix",
    ),
    ModuleEntry(
        module="logging_system",
        room="monitoring",
        commands=["logs status", "logs query"],
        persona="MonitoringBot",
        emits=[],
        consumes=[],
        description="Logging system",
    ),
    ModuleEntry(
        module="setup_wizard",
        room="onboarding-flow",
        commands=["setup wizard"],
        persona="OnboardingBot",
        emits=[],
        consumes=[],
        description="Setup wizard",
    ),
    ModuleEntry(
        module="startup_feature_summary",
        room="system-status",
        commands=["system features"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Startup feature summary",
    ),
    ModuleEntry(
        module="startup_validator",
        room="system-status",
        commands=["system validate"],
        persona="TriageBot",
        emits=["system_health"],
        consumes=[],
        description="Startup validator",
    ),
    ModuleEntry(
        module="thread_safe_operations",
        room="runtime",
        commands=["runtime thread-safe"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Thread-safe operations",
    ),
    ModuleEntry(
        module="universal_integration_adapter",
        room="integrations",
        commands=["integrations universal"],
        persona="TriageBot",
        emits=[],
        consumes=[],
        description="Universal integration adapter",
    ),
    ModuleEntry(
        module="webhook_dispatcher",
        room="ci-cd",
        commands=["webhooks list", "webhooks dispatch"],
        persona="TriageBot",
        emits=["delivery_requested"],
        consumes=[],
        description="Webhook dispatcher",
    ),
    ModuleEntry(
        module="webhook_event_processor",
        room="ci-cd",
        commands=["webhooks process"],
        persona="TriageBot",
        emits=["task_submitted"],
        consumes=["delivery_requested"],
        description="Webhook event processor",
    ),
    ModuleEntry(
        module="workflow_dag_engine",
        room="execution-orchestrator",
        commands=["workflow dag"],
        persona="ExecutionBot",
        emits=["task_submitted"],
        consumes=[],
        description="Workflow DAG engine",
    ),
    ModuleEntry(
        module="workflow_template_marketplace",
        room="automation-marketplace",
        commands=["workflow templates"],
        persona="ExecutionBot",
        emits=[],
        consumes=[],
        description="Workflow template marketplace",
    ),

    # ── New Modules (PR #249–#252) ────────────────────────────────────────────
    ModuleEntry(
        module="self_introspection_module",
        room="self-introspection",
        commands=["introspect status", "introspect run"],
        persona="TriageBot",
        emits=["introspection_completed", "metric_recorded"],
        consumes=["task_submitted"],
        description="Self-introspection module — runtime self-analysis and reporting",
    ),
    ModuleEntry(
        module="self_codebase_swarm",
        room="self-codebase-swarm",
        commands=["swarm status", "swarm propose", "swarm build"],
        persona="EngineeringBot",
        emits=["task_completed", "task_submitted"],
        consumes=["task_submitted"],
        description="Self-codebase swarm — autonomous BMS spec generation, RFP parsing, and deliverable packaging",
    ),
    ModuleEntry(
        module="cutsheet_engine",
        room="cutsheet-engine",
        commands=["cutsheet ingest", "cutsheet list", "cutsheet verify"],
        persona="EngineeringBot",
        emits=["task_completed", "metric_recorded"],
        consumes=["task_submitted"],
        description="Cut sheet engine — manufacturer data parsing, wiring diagrams, device config generation",
    ),
    ModuleEntry(
        module="visual_swarm_builder",
        room="visual-swarm-builder",
        commands=["visual build", "visual status"],
        persona="EngineeringBot",
        emits=["task_completed"],
        consumes=["task_submitted"],
        description="Visual swarm builder — visual pipeline construction for swarm workflows",
    ),
    ModuleEntry(
        module="ceo_branch_activation",
        room="ceo-branch",
        commands=["ceo activate", "ceo status", "ceo directive", "ceo plan"],
        persona="ExecutionBot",
        emits=["ceo_branch_activated", "ceo_branch_deactivated", "ceo_directive_issued", "metric_recorded"],
        consumes=["task_completed", "task_failed", "alert_fired"],
        description="CEO branch activation — top-level autonomous decision-making, org chart automation, and operational planning",
    ),
    ModuleEntry(
        module="production_assistant_engine",
        room="production-assistant-engine",
        commands=["prod intake", "prod validate", "prod status"],
        persona="ExecutionBot",
        emits=["gate_evaluated", "task_submitted", "task_completed"],
        consumes=["task_submitted"],
        description="Production assistant engine — request lifecycle management with deliverable gate validation via EventBackbone",
    ),
]


# ---------------------------------------------------------------------------
# Index helpers
# ---------------------------------------------------------------------------

def manifest_by_module() -> Dict[str, ModuleEntry]:
    """Return ``{module_name: ModuleEntry}`` index."""
    return {e.module: e for e in MODULE_MANIFEST}


def manifest_by_room() -> Dict[str, List[ModuleEntry]]:
    """Return ``{room_key: [ModuleEntry, ...]}`` index."""
    result: Dict[str, List[ModuleEntry]] = {}
    for entry in MODULE_MANIFEST:
        result.setdefault(entry.room, []).append(entry)
    return result


def manifest_by_persona() -> Dict[str, List[ModuleEntry]]:
    """Return ``{persona_name: [ModuleEntry, ...]}`` index."""
    result: Dict[str, List[ModuleEntry]] = {}
    for entry in MODULE_MANIFEST:
        result.setdefault(entry.persona, []).append(entry)
    return result


__all__ = [
    "ModuleEntry",
    "MODULE_MANIFEST",
    "manifest_by_module",
    "manifest_by_room",
    "manifest_by_persona",
]
