"""
Founder Update Engine — Auto-Update Applicator

Design Label: ARCH-007 — Founder Update Engine: Auto-Update Applicator
Owner: Backend Team
Dependencies:
  - RecommendationEngine (ARCH-007) — source of AUTO_UPDATE recommendations
  - SubsystemRegistry (ARCH-007) — subsystem health gating and history recording
  - UpdateCoordinator (ARCH-007) — prerequisite checks
  - SelfFixLoop (ARCH-005) — optional integration for autonomous execution
  - PersistenceManager — durable application history
  - EventBackbone — event publishing

Consumes AUTO_UPDATE recommendations generated by the RecommendationEngine
and SdkUpdateScanner, applies them under controlled conditions, and records
every application for full audit traceability.

Controlled conditions:
  - ``auto_applicable=True`` must be set on the recommendation
  - Subsystem health must not be ``failed``
  - Application rate is bounded per cycle (``max_per_cycle``)
  - A dry-run mode produces all decisions without executing anything
  - Every application is idempotent: already-applied recs are skipped

Safety invariants:
  - NEVER modifies source files on disk
  - Proposals only — application records intent, not file writes
  - Thread-safe: all shared state guarded by Lock
  - Full audit trail with outcome tracking

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

from __future__ import annotations

import logging
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_MAX_APPLICATION_HISTORY = 2_000
_DEFAULT_MAX_PER_CYCLE = 10


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class ApplicationOutcome(str, Enum):
    """Result of a single auto-update application attempt."""

    APPLIED = "applied"
    SKIPPED_DRY_RUN = "skipped_dry_run"
    SKIPPED_PREREQUISITES = "skipped_prerequisites"
    SKIPPED_NOT_AUTO_APPLICABLE = "skipped_not_auto_applicable"
    SKIPPED_ALREADY_APPLIED = "skipped_already_applied"
    SKIPPED_RATE_LIMITED = "skipped_rate_limited"
    FAILED = "failed"


@dataclass
class ApplicationRecord:
    """Audit record for a single auto-update application attempt.

    Attributes:
        record_id: Unique identifier.
        recommendation_id: ID of the recommendation that was applied.
        subsystem: Target subsystem.
        outcome: Result of the application attempt.
        dry_run: Whether this was a dry-run (no real changes).
        details: Human-readable explanation of the outcome.
        applied_at: UTC timestamp of the attempt.
        cycle_id: ID of the application cycle that contains this record.
    """

    record_id: str
    recommendation_id: str
    subsystem: str
    outcome: ApplicationOutcome
    dry_run: bool
    details: str
    applied_at: datetime
    cycle_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "record_id": self.record_id,
            "recommendation_id": self.recommendation_id,
            "subsystem": self.subsystem,
            "outcome": self.outcome.value,
            "dry_run": self.dry_run,
            "details": self.details,
            "applied_at": self.applied_at.isoformat(),
            "cycle_id": self.cycle_id,
        }


@dataclass
class ApplicationCycle:
    """Summary of one full auto-update application cycle.

    Attributes:
        cycle_id: Unique identifier.
        dry_run: Whether the cycle ran in dry-run mode.
        total_candidates: Number of AUTO_UPDATE recommendations found.
        applied: Count successfully applied (or would-apply in dry-run).
        skipped: Count skipped for any reason.
        failed: Count that encountered an error.
        records: Per-recommendation application records.
        started_at: UTC timestamp of cycle start.
        completed_at: UTC timestamp of cycle end.
    """

    cycle_id: str
    dry_run: bool
    total_candidates: int
    applied: int
    skipped: int
    failed: int
    records: List[ApplicationRecord]
    started_at: datetime
    completed_at: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "cycle_id": self.cycle_id,
            "dry_run": self.dry_run,
            "total_candidates": self.total_candidates,
            "applied": self.applied,
            "skipped": self.skipped,
            "failed": self.failed,
            "records": [r.to_dict() for r in self.records],
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
        }


# ---------------------------------------------------------------------------
# Applicator
# ---------------------------------------------------------------------------

class AutoUpdateApplicator:
    """Applies AUTO_UPDATE recommendations under controlled, audited conditions.

    Design Label: ARCH-007
    Owner: Backend Team

    Works in tandem with:
    - RecommendationEngine  — provides the queue of AUTO_UPDATE recommendations
    - SdkUpdateScanner      — generates patch-level AUTO_UPDATE recommendations
    - SubsystemRegistry     — health gating; records update history
    - UpdateCoordinator     — prerequisite checks before each application

    Usage::

        applicator = AutoUpdateApplicator(
            recommendation_engine=rec_engine,
            registry=registry,
            coordinator=coordinator,
            persistence_manager=pm,
            max_per_cycle=5,
        )
        cycle = applicator.run_cycle(dry_run=False)
        print(f"Applied {cycle.applied}/{cycle.total_candidates}")
    """

    _PERSISTENCE_DOC_KEY = "founder_update_engine_auto_applicator"

    def __init__(
        self,
        recommendation_engine=None,
        registry=None,
        coordinator=None,
        self_fix_loop=None,
        event_backbone=None,
        persistence_manager=None,
        max_per_cycle: int = _DEFAULT_MAX_PER_CYCLE,
    ) -> None:
        self._rec_engine = recommendation_engine
        self._registry = registry
        self._coordinator = coordinator
        self._self_fix_loop = self_fix_loop
        self._event_backbone = event_backbone
        self._persistence = persistence_manager
        self._max_per_cycle = max(1, max_per_cycle)

        self._application_history: List[ApplicationRecord] = []
        self._cycle_history: List[ApplicationCycle] = []
        self._lock = threading.Lock()

        self._load_state()

    # ------------------------------------------------------------------
    # Cycle execution
    # ------------------------------------------------------------------

    def run_cycle(self, dry_run: bool = False) -> ApplicationCycle:
        """Execute one auto-update application cycle.

        Scans all AUTO_UPDATE recommendations marked ``pending`` or
        ``approved`` with ``auto_applicable=True``, applies each under
        gated conditions, and records the outcome.

        Args:
            dry_run: When ``True``, evaluates and logs all decisions but
                does not actually change recommendation status or registry
                state.

        Returns:
            :class:`ApplicationCycle` summarising what happened.
        """
        cycle_id = str(uuid.uuid4())
        started_at = datetime.now(timezone.utc)

        candidates = self._get_candidates()
        records: List[ApplicationRecord] = []
        applied = skipped = failed = 0
        applied_this_cycle = 0

        for rec in candidates:
            if applied_this_cycle >= self._max_per_cycle:
                record = ApplicationRecord(
                    record_id=str(uuid.uuid4()),
                    recommendation_id=rec.id,
                    subsystem=rec.subsystem,
                    outcome=ApplicationOutcome.SKIPPED_RATE_LIMITED,
                    dry_run=dry_run,
                    details=f"Rate limit reached ({self._max_per_cycle} per cycle).",
                    applied_at=datetime.now(timezone.utc),
                    cycle_id=cycle_id,
                )
                records.append(record)
                skipped += 1
                continue

            outcome, details = self._evaluate(rec, dry_run)

            if outcome == ApplicationOutcome.APPLIED:
                applied += 1
                applied_this_cycle += 1
                if not dry_run:
                    self._commit_application(rec)
            elif outcome in (
                ApplicationOutcome.SKIPPED_DRY_RUN,
                ApplicationOutcome.SKIPPED_PREREQUISITES,
                ApplicationOutcome.SKIPPED_NOT_AUTO_APPLICABLE,
                ApplicationOutcome.SKIPPED_ALREADY_APPLIED,
                ApplicationOutcome.SKIPPED_RATE_LIMITED,
            ):
                skipped += 1
            else:
                failed += 1

            record = ApplicationRecord(
                record_id=str(uuid.uuid4()),
                recommendation_id=rec.id,
                subsystem=rec.subsystem,
                outcome=outcome,
                dry_run=dry_run,
                details=details,
                applied_at=datetime.now(timezone.utc),
                cycle_id=cycle_id,
            )
            records.append(record)

        completed_at = datetime.now(timezone.utc)
        cycle = ApplicationCycle(
            cycle_id=cycle_id,
            dry_run=dry_run,
            total_candidates=len(candidates),
            applied=applied,
            skipped=skipped,
            failed=failed,
            records=records,
            started_at=started_at,
            completed_at=completed_at,
        )

        with self._lock:
            if len(self._cycle_history) >= 200:
                self._cycle_history = self._cycle_history[-199:]
            self._cycle_history.append(cycle)

            for rec_obj in records:
                if len(self._application_history) >= _MAX_APPLICATION_HISTORY:
                    self._application_history = self._application_history[
                        -(_MAX_APPLICATION_HISTORY - 1):
                    ]
                self._application_history.append(rec_obj)

        self._save_state()
        self._publish_event(cycle)

        logger.info(
            "AutoUpdateApplicator: cycle %s (%s) — %d candidates, %d applied, %d skipped, %d failed",
            cycle_id,
            "dry-run" if dry_run else "live",
            len(candidates),
            applied,
            skipped,
            failed,
        )
        return cycle

    def apply_single(self, recommendation_id: str, dry_run: bool = False) -> ApplicationRecord:
        """Apply a single recommendation by ID.

        Args:
            recommendation_id: ID of the recommendation to apply.
            dry_run: Evaluate but do not commit.

        Returns:
            :class:`ApplicationRecord` describing the outcome.
        """
        cycle_id = str(uuid.uuid4())

        if self._rec_engine is None:
            return ApplicationRecord(
                record_id=str(uuid.uuid4()),
                recommendation_id=recommendation_id,
                subsystem="unknown",
                outcome=ApplicationOutcome.FAILED,
                dry_run=dry_run,
                details="RecommendationEngine not available.",
                applied_at=datetime.now(timezone.utc),
                cycle_id=cycle_id,
            )

        with self._rec_engine._lock:
            rec = self._rec_engine._recommendations.get(recommendation_id)

        if rec is None:
            return ApplicationRecord(
                record_id=str(uuid.uuid4()),
                recommendation_id=recommendation_id,
                subsystem="unknown",
                outcome=ApplicationOutcome.FAILED,
                dry_run=dry_run,
                details=f"Recommendation {recommendation_id!r} not found.",
                applied_at=datetime.now(timezone.utc),
                cycle_id=cycle_id,
            )

        outcome, details = self._evaluate(rec, dry_run)

        if outcome == ApplicationOutcome.APPLIED and not dry_run:
            self._commit_application(rec)

        record = ApplicationRecord(
            record_id=str(uuid.uuid4()),
            recommendation_id=rec.id,
            subsystem=rec.subsystem,
            outcome=outcome,
            dry_run=dry_run,
            details=details,
            applied_at=datetime.now(timezone.utc),
            cycle_id=cycle_id,
        )

        with self._lock:
            self._application_history.append(record)
        self._save_state()
        return record

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def get_cycle_history(self, limit: int = 20) -> List[ApplicationCycle]:
        """Return the most recent application cycles (newest first).

        Args:
            limit: Maximum number of cycles to return.
        """
        with self._lock:
            return list(reversed(self._cycle_history[-limit:]))

    def get_application_history(self, limit: int = 50) -> List[ApplicationRecord]:
        """Return the most recent individual application records (newest first).

        Args:
            limit: Maximum number of records to return.
        """
        with self._lock:
            return list(reversed(self._application_history[-limit:]))

    def get_status(self) -> Dict[str, Any]:
        """Return summary statistics."""
        with self._lock:
            total_cycles = len(self._cycle_history)
            total_applied = sum(
                c.applied for c in self._cycle_history if not c.dry_run
            )
            last_cycle = self._cycle_history[-1].to_dict() if self._cycle_history else None
        return {
            "total_cycles": total_cycles,
            "total_applied": total_applied,
            "max_per_cycle": self._max_per_cycle,
            "last_cycle": last_cycle,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_candidates(self) -> list:
        """Return all AUTO_UPDATE recommendations for evaluation.

        All statuses are included so the audit trail captures every decision
        (already-applied, not-auto-applicable, rate-limited, etc.).
        """
        if self._rec_engine is None:
            return []
        from .recommendation_engine import RecommendationType

        with self._rec_engine._lock:
            return [
                r
                for r in self._rec_engine._recommendations.values()
                if r.recommendation_type == RecommendationType.AUTO_UPDATE
            ]

    def _evaluate(self, rec, dry_run: bool):
        """Evaluate whether *rec* should be applied.

        Returns:
            Tuple of (outcome, details_string).
        """
        from .recommendation_engine import RecommendationType

        # Guard: must be AUTO_UPDATE and auto_applicable
        if rec.recommendation_type != RecommendationType.AUTO_UPDATE:
            return (
                ApplicationOutcome.SKIPPED_NOT_AUTO_APPLICABLE,
                f"Type {rec.recommendation_type.value!r} is not AUTO_UPDATE.",
            )
        if not rec.auto_applicable:
            return (
                ApplicationOutcome.SKIPPED_NOT_AUTO_APPLICABLE,
                "Recommendation is not marked auto_applicable.",
            )

        # Guard: not already applied
        if rec.status == "applied":
            return (
                ApplicationOutcome.SKIPPED_ALREADY_APPLIED,
                "Recommendation already applied.",
            )

        # Gate: prerequisite check via coordinator
        if self._coordinator is not None:
            prereq = self._coordinator.check_update_prerequisites(rec.subsystem)
            if not prereq.get("prerequisites_met", True):
                details = "; ".join(prereq.get("details", ["prerequisites not met"]))
                return (ApplicationOutcome.SKIPPED_PREREQUISITES, details)

        # Gate: registry health check (direct, without coordinator)
        if self._registry is not None:
            info = self._registry.get_subsystem(rec.subsystem)
            if info is not None and info.health_status == "failed":
                return (
                    ApplicationOutcome.SKIPPED_PREREQUISITES,
                    f"Subsystem '{rec.subsystem}' health is 'failed'.",
                )

        if dry_run:
            return (
                ApplicationOutcome.SKIPPED_DRY_RUN,
                "Dry-run: would apply.",
            )

        return (ApplicationOutcome.APPLIED, "Auto-update applied successfully.")

    def _commit_application(self, rec) -> None:
        """Record the application in the recommendation engine and registry."""
        try:
            if self._rec_engine is not None:
                self._rec_engine.apply_recommendation(rec.id)
        except Exception as exc:
            logger.debug("AutoUpdateApplicator: apply_recommendation failed: %s", exc)

        try:
            if self._registry is not None:
                self._registry.record_update(
                    rec.subsystem,
                    {
                        "recommendation_id": rec.id,
                        "type": "auto_update",
                        "title": rec.title,
                        "applied_at": datetime.now(timezone.utc).isoformat(),
                    },
                )
        except Exception as exc:
            logger.debug("AutoUpdateApplicator: record_update failed: %s", exc)

    def _save_state(self) -> None:
        if self._persistence is None:
            return
        try:
            with self._lock:
                data = {
                    "application_history": [r.to_dict() for r in self._application_history],
                    "cycle_history": [c.to_dict() for c in self._cycle_history],
                }
            self._persistence.save_document(self._PERSISTENCE_DOC_KEY, data)
        except Exception as exc:
            logger.debug("AutoUpdateApplicator: failed to save state: %s", exc)

    def _load_state(self) -> None:
        if self._persistence is None:
            return
        try:
            data = self._persistence.load_document(self._PERSISTENCE_DOC_KEY)
            if not data:
                return
            with self._lock:
                for r_dict in data.get("application_history", []):
                    try:
                        self._application_history.append(
                            ApplicationRecord(
                                record_id=r_dict["record_id"],
                                recommendation_id=r_dict["recommendation_id"],
                                subsystem=r_dict.get("subsystem", ""),
                                outcome=ApplicationOutcome(r_dict["outcome"]),
                                dry_run=r_dict.get("dry_run", False),
                                details=r_dict.get("details", ""),
                                applied_at=datetime.fromisoformat(r_dict["applied_at"]),
                                cycle_id=r_dict.get("cycle_id", ""),
                            )
                        )
                    except Exception as exc:
                        logger.debug(
                            "AutoUpdateApplicator: failed to load record: %s", exc
                        )
                for c_dict in data.get("cycle_history", []):
                    try:
                        self._cycle_history.append(
                            ApplicationCycle(
                                cycle_id=c_dict["cycle_id"],
                                dry_run=c_dict.get("dry_run", False),
                                total_candidates=c_dict.get("total_candidates", 0),
                                applied=c_dict.get("applied", 0),
                                skipped=c_dict.get("skipped", 0),
                                failed=c_dict.get("failed", 0),
                                records=[],
                                started_at=datetime.fromisoformat(c_dict["started_at"]),
                                completed_at=(
                                    datetime.fromisoformat(c_dict["completed_at"])
                                    if c_dict.get("completed_at")
                                    else None
                                ),
                            )
                        )
                    except Exception as exc:
                        logger.debug(
                            "AutoUpdateApplicator: failed to load cycle: %s", exc
                        )
        except Exception as exc:
            logger.debug("AutoUpdateApplicator: failed to load state: %s", exc)

    def _publish_event(self, cycle: ApplicationCycle) -> None:
        if self._event_backbone is None:
            return
        try:
            from event_backbone import EventType  # type: ignore

            self._event_backbone.publish(
                EventType.SYSTEM_HEALTH,
                {
                    "source": "AutoUpdateApplicator",
                    "cycle_id": cycle.cycle_id,
                    "dry_run": cycle.dry_run,
                    "applied": cycle.applied,
                    "skipped": cycle.skipped,
                    "failed": cycle.failed,
                },
            )
        except Exception as exc:
            logger.debug("AutoUpdateApplicator: event publish failed: %s", exc)
