"""
Founder Update Engine — Recommendation Engine

Design Label: ARCH-007 — Founder Update Engine: Core Recommendation System
Owner: Backend Team
Dependencies:
  - SelfImprovementEngine (ARCH-001) — outcome patterns and proposals
  - BugPatternDetector (DEV-004) — error classification
  - DependencyAuditEngine (DEV-005) — SDK/dependency analysis
  - SelfHealingCoordinator (OBS-004) — remediation status
  - EventBackbone — event-driven triggers
  - PersistenceManager — durable storage

Generates multiple forms of recommendations for any Murphy subsystem:
  MAINTENANCE, SDK_UPDATE, AUTO_UPDATE, BUG_RESPONSE, PERFORMANCE,
  SECURITY, ARCHITECTURE.

Safety invariants:
  - NEVER modifies source files on disk
  - Proposals only — human or explicit approval required
  - Thread-safe: all shared state guarded by Lock

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

from __future__ import annotations

import logging
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class RecommendationType(str, Enum):
    """Categories of recommendations generated by the engine."""

    MAINTENANCE = "maintenance"
    SDK_UPDATE = "sdk_update"
    AUTO_UPDATE = "auto_update"
    BUG_RESPONSE = "bug_response"
    PERFORMANCE = "performance"
    SECURITY = "security"
    ARCHITECTURE = "architecture"


class RecommendationPriority(str, Enum):
    """Priority tiers for recommendations."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class Recommendation:
    """A concrete recommendation targeting a specific subsystem.

    Attributes:
        id: Unique recommendation identifier (UUID).
        subsystem: Name of the Murphy subsystem this recommendation targets.
        recommendation_type: Functional category of the recommendation.
        priority: Urgency tier.
        title: Short human-readable title.
        description: Full description of the recommendation.
        rationale: Why this recommendation was generated.
        proposed_actions: Ordered list of concrete steps to implement it.
        estimated_impact: Scored risk, effort, and benefit values.
        auto_applicable: Whether the update can be applied without human review.
        requires_founder_approval: Whether founder sign-off is required.
        source_analysis: Metadata about the analysis that produced this rec.
        created_at: UTC timestamp of creation.
        status: Lifecycle state (pending, approved, rejected, applied, deferred).
    """

    id: str
    subsystem: str
    recommendation_type: RecommendationType
    priority: RecommendationPriority
    title: str
    description: str
    rationale: str
    proposed_actions: List[Dict[str, Any]]
    estimated_impact: Dict[str, Any]
    auto_applicable: bool
    requires_founder_approval: bool
    source_analysis: Dict[str, Any]
    created_at: datetime
    status: str = "pending"

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to a JSON-friendly dictionary."""
        return {
            "id": self.id,
            "subsystem": self.subsystem,
            "recommendation_type": self.recommendation_type.value,
            "priority": self.priority.value,
            "title": self.title,
            "description": self.description,
            "rationale": self.rationale,
            "proposed_actions": self.proposed_actions,
            "estimated_impact": self.estimated_impact,
            "auto_applicable": self.auto_applicable,
            "requires_founder_approval": self.requires_founder_approval,
            "source_analysis": self.source_analysis,
            "created_at": self.created_at.isoformat(),
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Recommendation":
        """Deserialise from a dictionary."""
        return cls(
            id=data["id"],
            subsystem=data["subsystem"],
            recommendation_type=RecommendationType(data["recommendation_type"]),
            priority=RecommendationPriority(data["priority"]),
            title=data["title"],
            description=data["description"],
            rationale=data["rationale"],
            proposed_actions=data.get("proposed_actions", []),
            estimated_impact=data.get("estimated_impact", {}),
            auto_applicable=data.get("auto_applicable", False),
            requires_founder_approval=data.get("requires_founder_approval", False),
            source_analysis=data.get("source_analysis", {}),
            created_at=datetime.fromisoformat(data["created_at"]),
            status=data.get("status", "pending"),
        )


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class RecommendationEngine:
    """Generates multiple forms of recommendations for any Murphy subsystem.

    Design Label: ARCH-007
    Owner: Backend Team

    Integrates with:
    - SelfImprovementEngine for outcome patterns
    - BugPatternDetector for error classification
    - DependencyAuditEngine for SDK/dependency analysis
    - SelfHealingCoordinator for remediation status
    - EventBackbone for event-driven triggers
    - PersistenceManager for durable storage

    Usage::

        engine = RecommendationEngine(
            improvement_engine=SelfImprovementEngine(),
            bug_detector=BugPatternDetector(),
            dependency_audit=DependencyAuditEngine(),
            healing_coordinator=SelfHealingCoordinator(),
            event_backbone=EventBackbone(),
            persistence_manager=PersistenceManager(),
        )
        recs = engine.generate_recommendations("self_fix_loop")
    """

    _PERSISTENCE_DOC_KEY = "founder_update_engine_recommendations"

    def __init__(
        self,
        improvement_engine=None,
        bug_detector=None,
        dependency_audit=None,
        healing_coordinator=None,
        event_backbone=None,
        persistence_manager=None,
    ) -> None:
        self._improvement_engine = improvement_engine
        self._bug_detector = bug_detector
        self._dependency_audit = dependency_audit
        self._healing_coordinator = healing_coordinator
        self._event_backbone = event_backbone
        self._persistence = persistence_manager

        # In-memory store: rec_id -> Recommendation
        self._recommendations: Dict[str, Recommendation] = {}
        self._lock = threading.Lock()

        # Attempt to load previously persisted state
        self._load_state()

    # ------------------------------------------------------------------
    # Public generation API
    # ------------------------------------------------------------------

    def generate_recommendations(self, subsystem: str) -> List[Recommendation]:
        """Generate recommendations of all types for *subsystem*.

        Runs all specialist generators and returns the combined list,
        deduplicating by id.

        Args:
            subsystem: Name of the target subsystem (e.g. ``self_fix_loop``).

        Returns:
            List of newly created :class:`Recommendation` objects.
        """
        new_recs: List[Recommendation] = []
        new_recs.extend(self.generate_maintenance_recommendations(subsystem))
        new_recs.extend(self._generate_performance_recommendations(subsystem))
        new_recs.extend(self._generate_architecture_recommendations(subsystem))

        # Bug-response recs driven by current detector state
        if self._bug_detector is not None:
            try:
                report_dict = self._bug_detector.run_detection_cycle().to_dict()
                new_recs.extend(self.generate_bug_response_recommendations(report_dict))
            except Exception as exc:
                logger.debug("Bug detector unavailable during generate_recommendations: %s", exc)

        with self._lock:
            for rec in new_recs:
                self._recommendations[rec.id] = rec

        self._save_state()
        return new_recs

    def generate_maintenance_recommendations(self, subsystem: str) -> List[Recommendation]:
        """Generate routine maintenance recommendations for *subsystem*.

        Pulls patterns from SelfImprovementEngine and SelfHealingCoordinator
        to identify areas that need scheduled attention.

        Args:
            subsystem: Target subsystem name.

        Returns:
            List of MAINTENANCE-type :class:`Recommendation` objects.
        """
        recs: List[Recommendation] = []

        # From improvement engine proposals
        if self._improvement_engine is not None:
            try:
                proposals = self._improvement_engine.get_remediation_backlog()
                for proposal in proposals:
                    if proposal.category in ("routing", "delivery", "gating"):
                        rec = self._make_recommendation(
                            subsystem=subsystem,
                            rec_type=RecommendationType.MAINTENANCE,
                            priority=RecommendationPriority.MEDIUM,
                            title=f"Maintenance: {proposal.description[:60]}",
                            description=proposal.description,
                            rationale=f"SelfImprovementEngine flagged category={proposal.category}",
                            actions=[{"action": "review_proposal", "proposal_id": proposal.proposal_id}],
                            impact={"risk": "low", "effort": "medium", "benefit": "medium"},
                            auto_applicable=False,
                            requires_founder_approval=False,
                            source={"engine": "SelfImprovementEngine", "proposal_id": proposal.proposal_id},
                        )
                        recs.append(rec)
            except Exception as exc:
                logger.debug("ImprovementEngine unavailable for maintenance recs: %s", exc)

        # From healing coordinator
        if self._healing_coordinator is not None:
            try:
                status = self._healing_coordinator.get_status()
                if status.get("total_recoveries", 0) > 0:
                    rec = self._make_recommendation(
                        subsystem=subsystem,
                        rec_type=RecommendationType.MAINTENANCE,
                        priority=RecommendationPriority.LOW,
                        title="Scheduled: review recurring recovery procedures",
                        description=(
                            f"{status['total_recoveries']} automated recoveries have run. "
                            "Review recovery procedures to assess if root-cause fixes are needed."
                        ),
                        rationale="SelfHealingCoordinator reports active recovery history.",
                        actions=[{"action": "review_recovery_history"}],
                        impact={"risk": "low", "effort": "low", "benefit": "high"},
                        auto_applicable=False,
                        requires_founder_approval=False,
                        source={"engine": "SelfHealingCoordinator", "recoveries": status["total_recoveries"]},
                    )
                    recs.append(rec)
            except Exception as exc:
                logger.debug("SelfHealingCoordinator unavailable for maintenance recs: %s", exc)

        if not recs:
            # Baseline healthy-system record
            recs.append(
                self._make_recommendation(
                    subsystem=subsystem,
                    rec_type=RecommendationType.MAINTENANCE,
                    priority=RecommendationPriority.INFORMATIONAL,
                    title="Routine health check — no issues found",
                    description=f"No maintenance issues detected for {subsystem}.",
                    rationale="Baseline scan found no anomalies.",
                    actions=[],
                    impact={"risk": "none", "effort": "none", "benefit": "informational"},
                    auto_applicable=True,
                    requires_founder_approval=False,
                    source={"engine": "RecommendationEngine"},
                )
            )

        with self._lock:
            for rec in recs:
                self._recommendations[rec.id] = rec
        return recs

    def generate_sdk_update_recommendations(self) -> List[Recommendation]:
        """Generate SDK/dependency update recommendations.

        Runs the DependencyAuditEngine audit cycle and creates a
        recommendation for every finding above informational severity.

        Returns:
            List of SDK_UPDATE-type :class:`Recommendation` objects.
        """
        recs: List[Recommendation] = []

        if self._dependency_audit is not None:
            try:
                report = self._dependency_audit.run_audit_cycle()
                for finding in report.findings:
                    priority = self._severity_to_priority(finding.severity)
                    rec = self._make_recommendation(
                        subsystem=finding.dep_id,
                        rec_type=RecommendationType.SDK_UPDATE,
                        priority=priority,
                        title=f"SDK update: {finding.dep_name} — {finding.cve_id}",
                        description=finding.title,
                        rationale=f"Advisory {finding.advisory_id} (CVE: {finding.cve_id}) affects {finding.dep_name}.",
                        actions=[
                            {
                                "action": "update_dependency",
                                "package": finding.dep_name,
                                "from_version": finding.dep_version,
                                "to_version": finding.fixed_version or "latest",
                            }
                        ],
                        impact={
                            "risk": finding.severity,
                            "effort": "low",
                            "benefit": "security" if finding.severity in ("critical", "high") else "maintenance",
                        },
                        auto_applicable=priority
                        not in (RecommendationPriority.CRITICAL, RecommendationPriority.HIGH),
                        requires_founder_approval=priority == RecommendationPriority.CRITICAL,
                        source={
                            "engine": "DependencyAuditEngine",
                            "advisory_id": finding.advisory_id,
                            "finding_id": finding.finding_id,
                        },
                    )
                    recs.append(rec)
            except Exception as exc:
                logger.debug("DependencyAuditEngine unavailable for SDK recs: %s", exc)

        with self._lock:
            for rec in recs:
                self._recommendations[rec.id] = rec
        return recs

    def generate_bug_response_recommendations(self, bug_report: Dict[str, Any]) -> List[Recommendation]:
        """Generate auto-response recommendations from *bug_report*.

        Args:
            bug_report: A dictionary conforming to BugPatternDetector's
                ``BugReport.to_dict()`` schema.

        Returns:
            List of BUG_RESPONSE-type :class:`Recommendation` objects.
        """
        recs: List[Recommendation] = []
        patterns = bug_report.get("top_patterns", [])

        for pattern in patterns:
            severity = pattern.get("severity", "low")
            priority = self._severity_to_priority(severity)
            component = pattern.get("component", "unknown")
            rec = self._make_recommendation(
                subsystem=component,
                rec_type=RecommendationType.BUG_RESPONSE,
                priority=priority,
                title=f"Bug response: {pattern.get('representative_message', 'error pattern')[:60]}",
                description=(
                    f"Pattern '{pattern.get('pattern_id', '')}' has {pattern.get('occurrences', 0)} "
                    f"occurrences in {component}."
                ),
                rationale=f"BugPatternDetector classified severity={severity}.",
                actions=[
                    {
                        "action": "investigate_pattern",
                        "pattern_id": pattern.get("pattern_id"),
                        "suggested_fix": pattern.get("suggested_fix", ""),
                    }
                ],
                impact={
                    "risk": severity,
                    "effort": "medium",
                    "benefit": "stability",
                },
                auto_applicable=False,
                requires_founder_approval=priority == RecommendationPriority.CRITICAL,
                source={"engine": "BugPatternDetector", "pattern_id": pattern.get("pattern_id")},
            )
            recs.append(rec)

        with self._lock:
            for rec in recs:
                self._recommendations[rec.id] = rec
        return recs

    # ------------------------------------------------------------------
    # Query API
    # ------------------------------------------------------------------

    def get_recommendations_by_type(
        self, rec_type: RecommendationType
    ) -> List[Recommendation]:
        """Return all stored recommendations of the given type."""
        with self._lock:
            return [r for r in self._recommendations.values() if r.recommendation_type == rec_type]

    def get_recommendations_by_subsystem(self, subsystem: str) -> List[Recommendation]:
        """Return all stored recommendations targeting *subsystem*."""
        with self._lock:
            return [r for r in self._recommendations.values() if r.subsystem == subsystem]

    def get_all_recommendations(self) -> List[Recommendation]:
        """Return all stored recommendations."""
        with self._lock:
            return list(self._recommendations.values())

    # ------------------------------------------------------------------
    # Approval lifecycle
    # ------------------------------------------------------------------

    def approve_recommendation(self, rec_id: str) -> bool:
        """Mark recommendation *rec_id* as approved.

        Args:
            rec_id: Unique recommendation id.

        Returns:
            ``True`` if the recommendation was found and updated.
        """
        with self._lock:
            rec = self._recommendations.get(rec_id)
            if rec is None:
                logger.warning("approve_recommendation: id %s not found", rec_id)
                return False
            rec.status = "approved"
        self._save_state()
        logger.info("Recommendation %s approved", rec_id)
        return True

    def reject_recommendation(self, rec_id: str, reason: str) -> bool:
        """Mark recommendation *rec_id* as rejected.

        Args:
            rec_id: Unique recommendation id.
            reason: Human-readable rejection rationale.

        Returns:
            ``True`` if the recommendation was found and updated.
        """
        with self._lock:
            rec = self._recommendations.get(rec_id)
            if rec is None:
                logger.warning("reject_recommendation: id %s not found", rec_id)
                return False
            rec.status = "rejected"
            rec.source_analysis["rejection_reason"] = reason
        self._save_state()
        logger.info("Recommendation %s rejected: %s", rec_id, reason)
        return True

    def apply_recommendation(self, rec_id: str) -> Dict[str, Any]:
        """Mark recommendation *rec_id* as applied and record the result.

        This method does NOT execute any code changes; it records the
        applied status for audit purposes (proposals only).

        Args:
            rec_id: Unique recommendation id.

        Returns:
            Dict with ``success``, ``rec_id``, and ``status`` keys.
        """
        with self._lock:
            rec = self._recommendations.get(rec_id)
            if rec is None:
                logger.warning("apply_recommendation: id %s not found", rec_id)
                return {"success": False, "rec_id": rec_id, "status": "not_found"}
            if rec.status not in ("approved", "pending"):
                return {"success": False, "rec_id": rec_id, "status": rec.status}
            rec.status = "applied"
        self._save_state()
        self._publish_event(rec)
        logger.info("Recommendation %s applied", rec_id)
        return {"success": True, "rec_id": rec_id, "status": "applied"}

    def get_status(self) -> Dict[str, Any]:
        """Return summary statistics."""
        with self._lock:
            total = len(self._recommendations)
            by_status: Dict[str, int] = {}
            by_type: Dict[str, int] = {}
            for rec in self._recommendations.values():
                by_status[rec.status] = by_status.get(rec.status, 0) + 1
                by_type[rec.recommendation_type.value] = (
                    by_type.get(rec.recommendation_type.value, 0) + 1
                )
        return {
            "total_recommendations": total,
            "by_status": by_status,
            "by_type": by_type,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_performance_recommendations(self, subsystem: str) -> List[Recommendation]:
        """Create performance-oriented recommendations for *subsystem*."""
        return [
            self._make_recommendation(
                subsystem=subsystem,
                rec_type=RecommendationType.PERFORMANCE,
                priority=RecommendationPriority.LOW,
                title=f"Performance review recommended for {subsystem}",
                description=(
                    f"Periodic performance profiling of {subsystem} is advised to "
                    "identify latency hot-spots and memory pressure."
                ),
                rationale="Proactive performance review as part of founder update cycle.",
                actions=[{"action": "run_profiler", "subsystem": subsystem}],
                impact={"risk": "none", "effort": "low", "benefit": "performance"},
                auto_applicable=True,
                requires_founder_approval=False,
                source={"engine": "RecommendationEngine"},
            )
        ]

    def _generate_architecture_recommendations(self, subsystem: str) -> List[Recommendation]:
        """Create architecture improvement recommendations for *subsystem*."""
        return [
            self._make_recommendation(
                subsystem=subsystem,
                rec_type=RecommendationType.ARCHITECTURE,
                priority=RecommendationPriority.INFORMATIONAL,
                title=f"Architecture review: {subsystem}",
                description=(
                    f"Review the design of {subsystem} against current Murphy System "
                    "conventions (dataclasses, type hints, graceful degradation)."
                ),
                rationale="Regular architecture reviews keep the codebase consistent.",
                actions=[{"action": "architecture_review", "subsystem": subsystem}],
                impact={"risk": "none", "effort": "medium", "benefit": "maintainability"},
                auto_applicable=False,
                requires_founder_approval=False,
                source={"engine": "RecommendationEngine"},
            )
        ]

    @staticmethod
    def _make_recommendation(
        *,
        subsystem: str,
        rec_type: RecommendationType,
        priority: RecommendationPriority,
        title: str,
        description: str,
        rationale: str,
        actions: List[Dict[str, Any]],
        impact: Dict[str, Any],
        auto_applicable: bool,
        requires_founder_approval: bool,
        source: Dict[str, Any],
    ) -> Recommendation:
        return Recommendation(
            id=str(uuid.uuid4()),
            subsystem=subsystem,
            recommendation_type=rec_type,
            priority=priority,
            title=title,
            description=description,
            rationale=rationale,
            proposed_actions=actions,
            estimated_impact=impact,
            auto_applicable=auto_applicable,
            requires_founder_approval=requires_founder_approval,
            source_analysis=source,
            created_at=datetime.now(timezone.utc),
            status="pending",
        )

    @staticmethod
    def _severity_to_priority(severity: str) -> RecommendationPriority:
        return {
            "critical": RecommendationPriority.CRITICAL,
            "high": RecommendationPriority.HIGH,
            "medium": RecommendationPriority.MEDIUM,
            "low": RecommendationPriority.LOW,
        }.get(severity, RecommendationPriority.INFORMATIONAL)

    def _save_state(self) -> None:
        if self._persistence is None:
            return
        try:
            with self._lock:
                data = {r_id: r.to_dict() for r_id, r in self._recommendations.items()}
            self._persistence.save_document(self._PERSISTENCE_DOC_KEY, data)
        except Exception as exc:
            logger.debug("RecommendationEngine: failed to save state: %s", exc)

    def _load_state(self) -> None:
        if self._persistence is None:
            return
        try:
            data = self._persistence.load_document(self._PERSISTENCE_DOC_KEY)
            if data:
                with self._lock:
                    for r_id, r_dict in data.items():
                        try:
                            self._recommendations[r_id] = Recommendation.from_dict(r_dict)
                        except Exception as exc:
                            logger.debug("Failed to deserialise recommendation %s: %s", r_id, exc)
        except Exception as exc:
            logger.debug("RecommendationEngine: failed to load state: %s", exc)

    def _publish_event(self, rec: Recommendation) -> None:
        if self._event_backbone is None:
            return
        try:
            from event_backbone import EventType  # type: ignore

            self._event_backbone.publish(
                EventType.SYSTEM_HEALTH,
                {
                    "source": "RecommendationEngine",
                    "rec_id": rec.id,
                    "subsystem": rec.subsystem,
                    "recommendation_type": rec.recommendation_type.value,
                    "status": rec.status,
                },
            )
        except Exception as exc:
            logger.debug("RecommendationEngine: event publish failed: %s", exc)
