#!/usr/bin/env python3
"""
PATCH-418-inject — Add the 4 lens endpoints to monolith app.py.
Routes block is constructed via Python string ops to avoid heredoc-mangling.
"""
import ast
import shutil
from pathlib import Path

NL = chr(10)
MONO = Path("/opt/Murphy-System/src/runtime/app.py")

# Routes block — written with explicit chr(10) instead of literal newlines
# inside strings, so heredoc transmission cannot corrupt it.
ROUTES_LINES = [
    '',
    '    # ── PATCH-418: Rosetta cognitive lenses (recursive prompt shortcuts) ─',
    '    @app.get("/api/rosetta/lenses")',
    '    async def _rosetta_list_lenses(request: Request):',
    '        """List all available cognitive lenses. PATCH-418."""',
    '        try:',
    '            import sys',
    '            sys.path.insert(0, "/opt/Murphy-System/src")',
    '            import role_cognitive_lenses as _rcl',
    '            return JSONResponse({',
    '                "ok": True,',
    '                "count": len(_rcl.ROLE_LENSES),',
    '                "lenses": _rcl.list_lenses(),',
    '            })',
    '        except Exception as e:',
    '            return JSONResponse({"ok": False, "error": str(e)}, status_code=500)',
    '',
    '    @app.get("/api/rosetta/lens/{role_title}")',
    '    async def _rosetta_get_lens(role_title: str, request: Request):',
    '        """Return the full lens definition for one role. PATCH-418."""',
    '        try:',
    '            import sys',
    '            sys.path.insert(0, "/opt/Murphy-System/src")',
    '            import role_cognitive_lenses as _rcl',
    '            lens = _rcl.get_lens(role_title)',
    '            if not lens:',
    '                return JSONResponse(',
    '                    {"ok": False, "error": "unknown_role",',
    '                     "valid": list(_rcl.ROLE_LENSES.keys())},',
    '                    status_code=404,',
    '                )',
    '            return JSONResponse({"ok": True, "role_title": role_title, "lens": lens})',
    '        except Exception as e:',
    '            return JSONResponse({"ok": False, "error": str(e)}, status_code=500)',
    '',
    '    @app.post("/api/rosetta/think")',
    '    async def _rosetta_think(request: Request):',
    '        """Run a task through a role cognitive lens. PATCH-418."""',
    '        try:',
    '            import sys',
    '            sys.path.insert(0, "/opt/Murphy-System/src")',
    '            import role_cognitive_lenses as _rcl',
    '        except Exception as e:',
    '            return JSONResponse({"ok": False, "error": "lenses_unavailable: " + str(e)},',
    '                                status_code=500)',
    '        try:',
    '            body = await request.json()',
    '        except Exception:',
    '            return JSONResponse({"ok": False, "error": "invalid_json"}, status_code=400)',
    '        role = body.get("role")',
    '        task = body.get("task", "")',
    '        context = body.get("context", "")',
    '        execute = bool(body.get("execute", True))',
    '        max_tokens = int(body.get("max_tokens", 800))',
    '        if not role or not task:',
    '            return JSONResponse({"ok": False, "error": "role and task required"},',
    '                                status_code=400)',
    '        lens = _rcl.get_lens(role)',
    '        if not lens:',
    '            return JSONResponse({"ok": False, "error": "unknown_role",',
    '                                 "valid": list(_rcl.ROLE_LENSES.keys())},',
    '                                status_code=404)',
    '        prompt = _rcl.assemble_lens_prompt(role, task=task, context=context)',
    '        perspective_check = None',
    '        try:',
    '            import role_perspectives as _rp',
    '            perspective_check = {',
    '                "dollar_authority_usd": _rp.ROLE_PERSPECTIVES.get(role, {}).get("dollar_authority_usd"),',
    '                "escalation_triggers": _rp.ROLE_PERSPECTIVES.get(role, {}).get("escalation_triggers", []),',
    '                "forbidden": _rp.ROLE_PERSPECTIVES.get(role, {}).get("forbidden_actions", []),',
    '            }',
    '        except Exception:',
    '            pass',
    '        result = {',
    '            "ok": True,',
    '            "role": role,',
    '            "prompt_length_chars": len(prompt),',
    '            "perspective_check": perspective_check,',
    '        }',
    '        if execute:',
    '            try:',
    '                import urllib.request, json as _json',
    '                req_body = _json.dumps({',
    '                    "model": "phi3",',
    '                    "prompt": prompt,',
    '                    "stream": False,',
    '                    "options": {"num_predict": max_tokens, "temperature": 0.6},',
    '                }).encode()',
    '                req = urllib.request.Request(',
    '                    "http://127.0.0.1:11434/api/generate",',
    '                    data=req_body,',
    '                    headers={"Content-Type": "application/json"},',
    '                )',
    '                with urllib.request.urlopen(req, timeout=90) as resp:',
    '                    rdata = _json.loads(resp.read().decode())',
    '                result["response"] = rdata.get("response", "")',
    '                result["execution"] = "ollama_local"',
    '                result["model"] = rdata.get("model", "phi3")',
    '            except Exception as e:',
    '                result["response"] = None',
    '                result["execution"] = "failed: " + str(e)',
    '                result["prompt_assembled"] = prompt[:2000]',
    '        else:',
    '            result["prompt_assembled"] = prompt',
    '        try:',
    '            from event_bus import publish as _pub',
    '            _pub("rosetta.cognition.think",',
    '                 {"role": role, "task_preview": task[:120], "executed": execute})',
    '        except Exception:',
    '            pass',
    '        return JSONResponse(result)',
    '',
    '    @app.post("/api/rosetta/recurse")',
    '    async def _rosetta_recurse(request: Request):',
    '        """Role recursion: primary thinks, perspectives critique. PATCH-418."""',
    '        try:',
    '            import sys',
    '            sys.path.insert(0, "/opt/Murphy-System/src")',
    '            import role_cognitive_lenses as _rcl',
    '        except Exception as e:',
    '            return JSONResponse({"ok": False, "error": "lenses_unavailable: " + str(e)},',
    '                                status_code=500)',
    '        try:',
    '            body = await request.json()',
    '        except Exception:',
    '            return JSONResponse({"ok": False, "error": "invalid_json"}, status_code=400)',
    '        task = body.get("task", "")',
    '        primary = body.get("primary_role")',
    '        perspectives = body.get("perspectives", []) or []',
    '        context = body.get("context", "")',
    '        execute = bool(body.get("execute", True))',
    '        if not task or not primary:',
    '            return JSONResponse({"ok": False, "error": "task and primary_role required"},',
    '                                status_code=400)',
    '        if not _rcl.get_lens(primary):',
    '            return JSONResponse({"ok": False, "error": "unknown primary_role: " + primary},',
    '                                status_code=404)',
    '        result = {"ok": True, "primary_role": primary, "perspectives": perspectives}',
    '        import urllib.request, json as _json',
    '        def _run(role, task_text):',
    '            prompt = _rcl.assemble_lens_prompt(role, task=task_text, context=context)',
    '            if not execute:',
    '                return {"prompt": prompt[:1500], "response": None,',
    '                        "execution": "preview_only"}',
    '            try:',
    '                req_body = _json.dumps({',
    '                    "model": "phi3",',
    '                    "prompt": prompt,',
    '                    "stream": False,',
    '                    "options": {"num_predict": 500, "temperature": 0.6},',
    '                }).encode()',
    '                req = urllib.request.Request(',
    '                    "http://127.0.0.1:11434/api/generate",',
    '                    data=req_body,',
    '                    headers={"Content-Type": "application/json"},',
    '                )',
    '                with urllib.request.urlopen(req, timeout=120) as resp:',
    '                    rdata = _json.loads(resp.read().decode())',
    '                return {"response": rdata.get("response", ""),',
    '                        "execution": "ollama_local"}',
    '            except Exception as e:',
    '                return {"response": None, "execution": "failed: " + str(e)}',
    '        result["primary_view"] = _run(primary, task)',
    '        critiques = {}',
    '        primary_response = (result["primary_view"] or {}).get("response", "") or ""',
    '        for p_role in perspectives:',
    '            if not _rcl.get_lens(p_role):',
    '                critiques[p_role] = {"error": "unknown_role"}',
    '                continue',
    '            critique_task = (',
    '                "The " + primary + " role proposed this approach: " +',
    '                chr(10) + chr(10) + primary_response + chr(10) + chr(10) +',
    '                "From YOUR cognitive frame as " + p_role + ", what are the risks, " +',
    '                "blind spots, or improvements? Be specific. If you concur, say so briefly. " +',
    '                "Do not restate the primary view."',
    '            )',
    '            critiques[p_role] = _run(p_role, critique_task)',
    '        result["perspective_critiques"] = critiques',
    '        if execute and primary_response:',
    '            crit_text_parts = []',
    '            for r, c in critiques.items():',
    '                cr = (c or {}).get("response")',
    '                if cr:',
    '                    crit_text_parts.append("=== " + r + " says ===" + chr(10) + cr)',
    '            crit_text = (chr(10) + chr(10)).join(crit_text_parts)',
    '            synth_task = (',
    '                "Your original analysis was:" + chr(10) + chr(10) + primary_response +',
    '                chr(10) + chr(10) + "The following roles offered critiques:" +',
    '                chr(10) + chr(10) + crit_text + chr(10) + chr(10) +',
    '                "Now revise. Keep what holds up, incorporate what is right, " +',
    '                "explicitly note what you reject and why. Final answer only."',
    '            )',
    '            result["synthesis"] = _run(primary, synth_task)',
    '        else:',
    '            result["synthesis"] = None',
    '        try:',
    '            from event_bus import publish as _pub',
    '            _pub("rosetta.cognition.recursion",',
    '                 {"primary": primary, "perspectives": perspectives,',
    '                  "task_preview": task[:120]})',
    '        except Exception:',
    '            pass',
    '        return JSONResponse(result)',
    '',
]

ROUTES_BLOCK = NL.join(ROUTES_LINES)

# Verify the block alone parses (wrap it in a function for parse test)
test_wrap = "def _t(app):\n" + ROUTES_BLOCK
ast.parse(test_wrap)
print(f"  ✓ routes block parses standalone ({len(ROUTES_BLOCK)} chars)")

src = MONO.read_text()
if "PATCH-418" in src:
    print("  ⚠ PATCH-418 already present")
    raise SystemExit(0)

anchor = '@app.get("/api/rosetta/status")'
if anchor not in src:
    print("  ✗ anchor missing")
    raise SystemExit(1)

# Inject before the anchor (keeping the anchor's 4-space indent)
new_src = src.replace(anchor, ROUTES_BLOCK + NL + "    " + anchor, 1)

ast.parse(new_src)
print("  ✓ monolith parses after injection")

backup = MONO.with_suffix(".py.pre-418")
shutil.copy(MONO, backup)
print(f"  ✓ backup at {backup}")

MONO.write_text(new_src)
print(f"  ✓ monolith: {len(src)} -> {len(new_src)} bytes")
print(f"  PATCH-418 markers: {new_src.count('PATCH-418')}")
