# murphy-resolved.conf — systemd-resolved drop-in for MurphyOS
# Installs to: /etc/systemd/resolved.conf.d/murphy-resolved.conf
# © 2020 Inoni Limited Liability Company | License: BSL 1.1

[Resolve]
DNS=127.0.0.53#5354
Domains=~murphy.local
