"""
Tests for the Demo Deliverable Download feature.

Covers:
  - Predefined scenario templates (6 scenarios)
  - Custom query deliverables (LLM routing)
  - Usage limits (anon=5, free=10, paid=unlimited)
  - Branding: Murphy ASCII art logo, Apache 1.0 license, BSL 1.1 attribution
  - Usage info returned in API response

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

import os
import sys
import json
import hashlib
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def client():
    """Create a FastAPI test client for the deliverable endpoint."""
    os.environ["MURPHY_ENV"] = "development"
    os.environ["MURPHY_RATE_LIMIT_RPM"] = "6000"
    os.environ["MURPHY_RATE_LIMIT_BURST"] = "200"
    from starlette.testclient import TestClient
    from src.runtime.app import create_app
    app = create_app()
    return TestClient(app, follow_redirects=False)


def _post_deliverable(client, query, headers=None):
    """Helper: POST /api/demo/generate-deliverable with a query."""
    h = {"Content-Type": "application/json"}
    if headers:
        h.update(headers)
    return client.post(
        "/api/demo/generate-deliverable",
        content=json.dumps({"query": query}),
        headers=h,
    )


# ===========================================================================
# Generator unit tests (no HTTP)
# ===========================================================================

class TestDemoDeliverableGenerator:
    """Unit tests for the demo_deliverable_generator module."""

    def test_generate_predefined_onboarding(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        assert result["title"]
        assert "onboarding" in result["filename"].lower() or "client" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_finance(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Generate Q3 finance report")
        assert "finance" in result["filename"].lower() or "q3" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_hr(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Screen candidates for PM role")
        assert len(result["content"]) > 200
        assert result["filename"].endswith(".txt")

    def test_generate_predefined_compliance(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Run compliance audit")
        assert "compliance" in result["filename"].lower() or "audit" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_project(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Create project plan")
        assert "project" in result["filename"].lower() or "plan" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_invoice(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Process invoice batch")
        assert "invoice" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_custom_query(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Build an HVAC maintenance schedule for a 10-unit apartment building")
        assert result["title"]
        assert result["content"]
        assert result["filename"].endswith(".txt")
        # custom deliverable filename should not be a predefined scenario slug
        assert any(word in result["filename"] for word in ["custom", "hvac", "maintenance", "build", "apartment"])

    def test_has_branding(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        content = result["content"]
        # ASCII art logo block
        assert "MURPHY" in content or "Murphy" in content
        # Generated by line
        assert "murphy.systems" in content

    def test_has_apache_license(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Generate Q3 finance report")
        content = result["content"]
        assert "Apache License" in content
        assert "Version 1.0" in content or "1.0" in content

    def test_has_bsl_attribution(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Run compliance audit")
        content = result["content"]
        assert "BSL" in content or "Business Source License" in content
        assert "Inoni" in content

    def test_license_notice_cannot_be_removed_marker(self):
        """Verify the 'MAY NOT BE REMOVED' marker is present."""
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        assert "MAY NOT BE REMOVED" in result["content"]

    def test_filename_pattern_predefined(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        assert result["filename"].startswith("murphy-")
        assert result["filename"].endswith(".txt")

    def test_filename_pattern_custom(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Completely unknown workflow xyz123")
        assert result["filename"].startswith("murphy-")
        assert result["filename"].endswith(".txt")

    def test_build_branded_txt_has_all_sections(self):
        from src.demo_deliverable_generator import build_branded_txt
        txt = build_branded_txt("Test Deliverable", "Some content here", scenario_type="test")
        assert "DELIVERABLE:" in txt
        assert "Generated:" in txt
        assert "Quality:" in txt
        assert "apache" in txt.lower()
        assert "Inoni" in txt

    def test_make_fingerprint_deterministic(self):
        from src.demo_deliverable_generator import make_fingerprint
        fp1 = make_fingerprint("192.168.1.1", "Mozilla/5.0")
        fp2 = make_fingerprint("192.168.1.1", "Mozilla/5.0")
        assert fp1 == fp2

    def test_make_fingerprint_different_ips(self):
        from src.demo_deliverable_generator import make_fingerprint
        fp1 = make_fingerprint("10.0.0.1", "Mozilla/5.0")
        fp2 = make_fingerprint("10.0.0.2", "Mozilla/5.0")
        assert fp1 != fp2


# ===========================================================================
# API endpoint tests
# ===========================================================================

class TestDemoDeliverableEndpoint:
    """Tests for POST /api/demo/generate-deliverable."""

    def test_endpoint_exists(self, client):
        """Endpoint must exist and accept POST."""
        resp = _post_deliverable(client, "Onboard a new client")
        assert resp.status_code in (200, 429), f"Unexpected status {resp.status_code}"

    def test_missing_query_returns_400(self, client):
        """Empty query body returns 400."""
        resp = client.post(
            "/api/demo/generate-deliverable",
            content=json.dumps({}),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400
        assert resp.json()["error"] == "missing_query"

    def test_predefined_scenario_success(self, client):
        """A predefined scenario query returns a valid deliverable."""
        resp = _post_deliverable(client, "Generate Q3 finance report",
                                 headers={"X-Forwarded-For": "10.0.1.1"})
        if resp.status_code == 200:
            data = resp.json()
            assert data["success"] is True
            assert "deliverable" in data
            assert "title" in data["deliverable"]
            assert "content" in data["deliverable"]
            assert "filename" in data["deliverable"]
            assert data["deliverable"]["filename"].endswith(".txt")
        else:
            # 429 means limit exceeded from a previous test run — acceptable
            assert resp.status_code == 429

    def test_custom_query_success(self, client):
        """A custom query returns a deliverable."""
        resp = _post_deliverable(client, "Build a restaurant launch plan",
                                 headers={"X-Forwarded-For": "10.0.2.1"})
        if resp.status_code == 200:
            data = resp.json()
            assert data["success"] is True
            assert "deliverable" in data
            assert len(data["deliverable"]["content"]) > 100
        else:
            assert resp.status_code == 429

    def test_response_includes_usage_info(self, client):
        """Successful response includes usage stats."""
        resp = _post_deliverable(client, "Screen candidates for PM role",
                                 headers={"X-Forwarded-For": "10.0.3.1"})
        if resp.status_code == 200:
            data = resp.json()
            assert "usage" in data
            usage = data["usage"]
            assert "used" in usage
            assert "limit" in usage
            assert "remaining" in usage
            assert "tier" in usage

    def test_branding_in_response_content(self, client):
        """Returned content must contain Murphy branding."""
        resp = _post_deliverable(client, "Run compliance audit",
                                 headers={"X-Forwarded-For": "10.0.4.1"})
        if resp.status_code == 200:
            content = resp.json()["deliverable"]["content"]
            assert "murphy.systems" in content.lower() or "Murphy" in content

    def test_apache_license_in_content(self, client):
        """Returned content must contain Apache 1.0 license notice."""
        resp = _post_deliverable(client, "Create project plan",
                                 headers={"X-Forwarded-For": "10.0.5.1"})
        if resp.status_code == 200:
            content = resp.json()["deliverable"]["content"]
            assert "Apache License" in content

    def test_bsl_attribution_in_content(self, client):
        """Returned content must contain BSL 1.1 / Inoni attribution."""
        resp = _post_deliverable(client, "Process invoice batch",
                                 headers={"X-Forwarded-For": "10.0.6.1"})
        if resp.status_code == 200:
            content = resp.json()["deliverable"]["content"]
            assert "Inoni" in content
            assert "BSL" in content or "Business Source" in content


# ===========================================================================
# Usage limit tests (using SubscriptionManager directly)
# ===========================================================================

class TestDemoDeliverableUsageLimits:
    """Tests for anonymous and free-tier usage limits."""

    def test_anon_limit_is_5(self):
        """Anonymous users must be blocked after exactly 5 downloads."""
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        fp = "demo_anon_test_fingerprint_abc123"
        for i in range(5):
            result = mgr.record_anon_usage(fp)
            assert result["allowed"] is True, f"Should be allowed on attempt {i+1}"
        # 6th attempt must be blocked
        result = mgr.record_anon_usage(fp)
        assert result["allowed"] is False
        assert result["remaining"] == 0
        assert result["tier"] == "anonymous"

    def test_free_registered_limit_is_10(self):
        """Free registered users must be blocked after exactly 10 downloads."""
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        account_id = "demo_free_test_account_xyz789"
        for i in range(10):
            result = mgr.record_usage(account_id)
            assert result["allowed"] is True, f"Should be allowed on attempt {i+1}"
        # 11th attempt must be blocked
        result = mgr.record_usage(account_id)
        assert result["allowed"] is False
        assert result["remaining"] == 0

    def test_paid_users_are_unlimited(self):
        """Paid (non-free) users must never be blocked."""
        from src.subscription_manager import (
            SubscriptionManager, SubscriptionTier,
            SubscriptionRecord, SubscriptionStatus,
        )
        mgr = SubscriptionManager()
        account_id = "demo_paid_test_account_xyz789"
        mgr._subscriptions[account_id] = SubscriptionRecord(
            account_id=account_id,
            tier=SubscriptionTier.SOLO,
            status=SubscriptionStatus.ACTIVE,
        )
        for i in range(25):
            result = mgr.record_usage(account_id)
            assert result["allowed"] is True
            assert result["limit"] == -1  # unlimited

    def test_anon_usage_remaining_counts_down(self):
        """Remaining count must decrement with each use."""
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        fp = "demo_countdown_test_fp_444"
        result = mgr.record_anon_usage(fp)
        assert result["remaining"] == 4
        result = mgr.record_anon_usage(fp)
        assert result["remaining"] == 3
        result = mgr.record_anon_usage(fp)
        assert result["remaining"] == 2

    def test_limit_exceeded_response_structure(self, client):
        """When limit is exceeded, response has correct error structure."""
        from src.subscription_manager import SubscriptionManager
        # Use a custom fingerprint that's already exhausted
        mgr_ref = None
        try:
            from src.runtime.app import create_app as _ca
        except Exception:
            return  # Skip if app not available

        # Hit the limit directly via SubscriptionManager
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        fp = "demo_limit_exceeded_test_fp"
        for _ in range(5):
            mgr.record_anon_usage(fp)

        # Now simulate the API response structure
        result = mgr.record_anon_usage(fp)
        assert result["allowed"] is False
        assert "message" in result
        assert result["tier"] == "anonymous"


# ===========================================================================
# MFGC → MSS → Librarian pipeline tests
# ===========================================================================

class TestDeliverablePipeline:
    """Tests for the MFGC → MSS (Magnify/Solidify) → Librarian pipeline."""

    def test_mss_pipeline_returns_dict(self):
        """_run_mss_pipeline returns a dict (may be empty if deps unavailable)."""
        from src.demo_deliverable_generator import _run_mss_pipeline
        result = _run_mss_pipeline("Generate client onboarding workflow", {})
        assert isinstance(result, dict)

    def test_mss_pipeline_magnify_keys(self):
        """If MSS is available, magnify output has expected keys."""
        from src.demo_deliverable_generator import _run_mss_pipeline
        result = _run_mss_pipeline("Generate client onboarding workflow", {})
        if result.get("magnify"):
            assert "functional_requirements" in result["magnify"] or "concept_overview" in result["magnify"]

    def test_mss_pipeline_solidify_keys(self):
        """If MSS is available, solidify output has expected keys."""
        from src.demo_deliverable_generator import _run_mss_pipeline
        result = _run_mss_pipeline("Generate client onboarding workflow", {})
        if result.get("solidify"):
            assert "implementation_steps" in result["solidify"]

    def test_mfgc_gate_returns_dict(self):
        """_run_mfgc_gate always returns a dict and never raises."""
        from src.demo_deliverable_generator import _run_mfgc_gate
        result = _run_mfgc_gate("Build an automated invoice processing pipeline")
        assert isinstance(result, dict)
        # If MFGC ran, it should have confidence
        if result:
            assert "confidence" in result

    def test_format_mss_context_empty(self):
        """_format_mss_context returns empty string for empty input."""
        from src.demo_deliverable_generator import _format_mss_context
        assert _format_mss_context({}) == ""

    def test_format_mss_context_with_data(self):
        """_format_mss_context renders requirements and steps when data is present."""
        from src.demo_deliverable_generator import _format_mss_context
        mock = {
            "magnify": {
                "functional_requirements": ["REQ-1: Process invoices", "REQ-2: Notify on failure"],
                "technical_components": ["API connector", "Queue processor"],
            },
            "solidify": {
                "implementation_steps": [
                    "1. Define module structure",
                    "2. Implement core logic",
                    "3. Deploy and monitor",
                ],
            },
        }
        rendered = _format_mss_context(mock)
        assert "REQ-1" in rendered
        assert "API connector" in rendered
        assert "Define module structure" in rendered

    def test_format_librarian_section_empty(self):
        """_format_librarian_section returns empty string for blank input."""
        from src.demo_deliverable_generator import _format_librarian_section
        assert _format_librarian_section("") == ""
        assert _format_librarian_section(None) == ""

    def test_format_librarian_section_with_content(self):
        """_format_librarian_section includes the LIBRARIAN KNOWLEDGE LOOKUP header."""
        from src.demo_deliverable_generator import _format_librarian_section
        result = _format_librarian_section("Murphy supports SOC 2, GDPR, HIPAA frameworks.")
        assert "LIBRARIAN" in result
        assert "SOC 2" in result

    def test_detect_major_automation_positive(self):
        """_detect_major_automation returns True for automation keywords."""
        from src.demo_deliverable_generator import _detect_major_automation
        assert _detect_major_automation("automate my invoice processing") is True
        assert _detect_major_automation("create a workflow for onboarding") is True
        assert _detect_major_automation("schedule recurring payroll runs") is True
        assert _detect_major_automation("build an ETL pipeline") is True

    def test_detect_major_automation_negative(self):
        """_detect_major_automation returns False for non-automation queries."""
        from src.demo_deliverable_generator import _detect_major_automation
        assert _detect_major_automation("Write a Q3 finance report") is False
        assert _detect_major_automation("Screen candidates for PM role") is False

    def test_automation_blueprint_included_when_detected(self):
        """Automation query includes the generated workflow blueprint section."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        result = generate_custom_deliverable("Automate my invoice processing workflow")
        assert "AUTOMATION BLUEPRINT" in result["content"]
        assert "murphy.systems" in result["content"]

    def test_automation_blueprint_is_not_free(self):
        """Blueprint section must NOT claim automation is free or a bonus."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        result = generate_custom_deliverable("Automate my invoice processing workflow")
        content = result["content"]
        # These phrases from the old incorrect messaging must NOT appear
        assert "FREE BONUS" not in content
        assert "at no charge" not in content
        # The paid-tier gate message must be present
        assert "PAID" in content or "Upgrade" in content or "UPGRADE" in content

    def test_no_automation_blueprint_for_report_query(self):
        """Custom deliverable for a non-automation query excludes the blueprint."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        result = generate_custom_deliverable("Write a customer satisfaction survey analysis report")
        # Blueprint only appears when automation keywords are detected
        assert "AUTOMATION BLUEPRINT" not in result["content"]

    def test_librarian_context_injected_into_predefined(self):
        """Librarian context is appended to predefined deliverable content."""
        from src.demo_deliverable_generator import generate_predefined_deliverable
        ctx = "Murphy supports 41 compliance frameworks including SOC 2 and GDPR."
        result = generate_predefined_deliverable("compliance", "Run compliance audit", librarian_context=ctx)
        assert "LIBRARIAN" in result["content"]
        assert "SOC 2" in result["content"]

    def test_librarian_context_injected_into_custom(self):
        """Librarian context enriches the custom deliverable."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        ctx = "The Murphy knowledge base includes onboarding templates and SLA frameworks."
        result = generate_custom_deliverable("Create an HVAC maintenance schedule", librarian_context=ctx)
        assert "LIBRARIAN" in result["content"]

    def test_generate_deliverable_passes_librarian_context(self):
        """Top-level generate_deliverable passes librarian_context through."""
        from src.demo_deliverable_generator import generate_deliverable
        ctx = "Key insight: Murphy integrates with Slack, HubSpot, and QuickBooks."
        # Use a clearly custom query (not a predefined keyword match)
        result = generate_deliverable("Build a restaurant loyalty rewards program", librarian_context=ctx)
        assert result["content"]
        assert result["filename"].endswith(".txt")

    def test_build_content_from_mss_has_sections(self):
        """_build_content_from_mss produces structured content with expected headings."""
        from src.demo_deliverable_generator import _build_content_from_mss
        mock_mss = {
            "magnify": {
                "functional_requirements": ["Process data from source", "Validate schema"],
                "technical_components": ["API reader", "Validator"],
                "compliance_considerations": ["GDPR"],
                "cost_complexity_estimate": "medium",
                "concept_overview": "Data processing pipeline",
            },
            "solidify": {
                "implementation_steps": [
                    "1. Define module structure",
                    "2. Implement core logic",
                ],
                "testing_strategy": ["Unit tests for core logic"],
                "iteration_plan": "Phase 1: Core. Phase 2: Integration.",
                "documentation_updates": ["Module spec", "API reference"],
                "capability_definition": "Create a data processing pipeline",
                "architecture_placement": "pipeline_engine integrated into murphy_system",
            },
        }
        content = _build_content_from_mss("Build a data processing pipeline", mock_mss)
        assert "FUNCTIONAL REQUIREMENTS" in content
        assert "Process data from source" in content
        assert "IMPLEMENTATION PLAN" in content
        assert "Define module structure" in content

    def test_custom_query_uses_mss_when_available(self):
        """Custom query deliverable uses MSS intelligence sections when MSS is available."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        result = generate_custom_deliverable("Create a restaurant launch plan")
        # The content should be non-empty and properly formatted
        assert len(result["content"]) > 500
        # Branding must always be present
        assert "murphy.systems" in result["content"]
        assert "Apache License" in result["content"]

    # -----------------------------------------------------------------------
    # Keyword map / routing correctness tests
    # -----------------------------------------------------------------------

    def test_broad_queries_go_to_custom_pipeline(self):
        """Queries with generic words ('plan', 'report', 'resource') that do NOT
        include a domain phrase should route to the custom MSS pipeline, not a
        predefined template."""
        from src.demo_deliverable_generator import _detect_scenario
        # These should all be CUSTOM (None)
        ambiguous = [
            "Create a restaurant franchise launch plan",
            "Build a marketing resource kit",
            "Write a Q3 sustainability report",
            "Make a timeline for our office move",
            "Plan a company offsite event",
            "Billing strategy for new product",
        ]
        for q in ambiguous:
            result = _detect_scenario(q)
            assert result is None, (
                f"Query '{q}' incorrectly matched scenario '{result}' — "
                "broad keyword over-matching; should route to custom MSS pipeline"
            )

    def test_specific_queries_still_hit_predefined(self):
        """Domain-specific queries should still resolve to the correct predefined scenario."""
        from src.demo_deliverable_generator import _detect_scenario
        expected = [
            ("Onboard a new client", "onboarding"),
            ("Generate Q3 finance report", "finance"),
            ("Screen candidates for PM role", "hr"),
            ("Run compliance audit", "compliance"),
            ("Create project plan", "project"),
            ("Process invoice batch", "invoice"),
            ("Run a SOC 2 compliance report", "compliance"),
            ("Automate invoice processing workflow", "invoice"),
            ("Generate a quarterly review report", "finance"),
        ]
        for query, expected_scenario in expected:
            result = _detect_scenario(query)
            assert result == expected_scenario, (
                f"Query '{query}' → expected '{expected_scenario}' but got '{result}'"
            )

    def test_predefined_with_automation_uses_mss_steps_in_blueprint(self):
        """When a predefined scenario triggers automation detection, the blueprint
        should include MSS-generated implementation steps (not just generic fallback)."""
        from src.demo_deliverable_generator import generate_predefined_deliverable
        result = generate_predefined_deliverable(
            "invoice",
            "Automate my invoice processing and send payment reminders",
        )
        assert "AUTOMATION BLUEPRINT" in result["content"]
        # Blueprint always includes a WORKFLOW STEPS block (from AI Workflow Generator
        # or MSS Solidify fallback) — verifies real pipeline ran, not static template
        assert "WORKFLOW STEPS" in result["content"] or "Step" in result["content"]

    def test_request_note_injected_when_query_differs_from_title(self):
        """When the user's query doesn't match the template title, a YOUR REQUEST
        header is injected at the top of the content."""
        from src.demo_deliverable_generator import generate_predefined_deliverable
        result = generate_predefined_deliverable(
            "project",
            "Deploy a hotel booking SaaS platform",  # doesn't match "Project Plan"
        )
        assert "YOUR REQUEST" in result["content"]
        assert "hotel booking" in result["content"].lower()

    def test_no_request_note_when_query_matches_title(self):
        """When query closely matches the template title, no YOUR REQUEST note is added."""
        from src.demo_deliverable_generator import generate_predefined_deliverable
        # Query contains template title "Project Plan"
        result = generate_predefined_deliverable("project", "Create project plan")
        # "Create project plan" doesn't appear in "Project Plan" but is close enough
        # — the important thing is the content still contains the template sections
        assert "SECTION" in result["content"] or "MILESTONE" in result["content"]

    def test_pipeline_quality_score_elevated_by_mss(self):
        """Quality score is elevated above base 94 when MSS produces output."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        result = generate_custom_deliverable("Automate invoice processing pipeline")
        # Title is in the file; quality score appears in the metadata block
        assert "Quality:" in result["content"]
        # Score should be ≥ 94
        import re
        m = re.search(r"Quality:\s+(\d+)/100", result["content"])
        if m:
            assert int(m.group(1)) >= 94


# ===========================================================================
# Quality Plan tests
# ===========================================================================

class TestQualityPlan:
    """Tests for the _build_quality_plan function and its integration."""

    def test_quality_plan_has_service_catalog(self):
        """Quality plan includes the itemized service catalog table."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("Automate a baseball card business")
        assert "QUALITY PLAN" in plan
        assert "SERVICE CATALOG" in plan
        assert "S01" in plan
        assert "S10" in plan
        assert "Workflow Automation Engine" in plan

    def test_quality_plan_has_plan_id(self):
        """Quality plan includes a deterministic QP- plan ID."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("Test query")
        assert "QP-" in plan

    def test_quality_plan_deterministic_id(self):
        """Same query produces the same plan ID."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan1 = _build_quality_plan("Same query")
        plan2 = _build_quality_plan("Same query")
        # Extract plan IDs
        import re
        ids = re.findall(r"QP-([A-F0-9]{8})", plan1 + plan2)
        assert len(ids) == 2
        assert ids[0] == ids[1]

    def test_quality_plan_has_recommendations(self):
        """Quality plan recommends services based on query keywords."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("Automate compliance audit workflow")
        assert "RECOMMENDED FOR YOUR REQUEST" in plan
        assert "✓" in plan
        # "automate" → S01 + S07, "compliance" → S04
        assert "S01" in plan
        assert "S04" in plan

    def test_quality_plan_has_technical_spec(self):
        """Quality plan includes a technical specification section."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("Build an integration pipeline")
        assert "TECHNICAL SPECIFICATION" in plan
        assert "APIs:" in plan
        assert "Triggers:" in plan
        assert "Gates:" in plan
        assert "Bot Systems:" in plan
        assert "Modules:" in plan

    def test_quality_plan_has_optimization_suggestions(self):
        """Quality plan includes pre-optimization suggestions."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("Automate my business")
        assert "PRE-OPTIMIZATION SUGGESTIONS" in plan

    def test_quality_plan_has_client_portfolio_section(self):
        """Quality plan includes the client portfolio save/customize section."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("Make a plan for my store")
        assert "CLIENT PORTFOLIO" in plan
        assert "/api/client-portfolio/save" in plan

    def test_project_scenario_always_includes_quality_plan(self):
        """The 'project' predefined scenario always appends a quality plan."""
        from src.demo_deliverable_generator import generate_predefined_deliverable
        result = generate_predefined_deliverable("project", "Create project plan")
        assert "QUALITY PLAN" in result["content"]
        assert "SERVICE CATALOG" in result["content"]
        assert "TECHNICAL SPECIFICATION" in result["content"]

    def test_custom_deliverable_plan_query_includes_quality_plan(self):
        """Custom deliverables with 'plan' in query include quality plan."""
        from src.demo_deliverable_generator import generate_custom_deliverable
        result = generate_custom_deliverable("Make a plan for a baseball card shop")
        assert "QUALITY PLAN" in result["content"]

    def test_quality_plan_with_mss_enrichment(self):
        """Quality plan uses MSS data to enrich technical spec when available."""
        from src.demo_deliverable_generator import _build_quality_plan
        mock_mss = {
            "magnify": {
                "functional_requirements": ["Process orders", "Track inventory"],
                "components": ["OrderEngine", "InventoryTracker"],
            },
            "solidify": {
                "implementation_steps": ["Set up DB schema", "Wire API endpoints"],
                "iteration_plan": "Phase 1: Orders. Phase 2: Inventory.",
            },
        }
        plan = _build_quality_plan("Build order system", mss_result=mock_mss)
        assert "Process orders" in plan
        assert "Set up DB schema" in plan

    def test_quality_plan_default_recommendations_when_no_keywords(self):
        """Quality plan provides baseline recommendations when no keywords match."""
        from src.demo_deliverable_generator import _build_quality_plan
        plan = _build_quality_plan("xyzzy foobar unknown query")
        # Should still have S01 and S03 as baseline
        assert "S01" in plan
        assert "S03" in plan


# ===========================================================================
# Client Portfolio API tests
# ===========================================================================

class TestClientPortfolioAPI:
    """Tests for the /api/client-portfolio/* endpoints."""

    def test_save_portfolio(self, client):
        """POST /api/client-portfolio/save creates a portfolio."""
        resp = client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "client_id": "test-client-001",
                "plan_id": "QP-ABCDEF01",
                "selections": ["S01", "S03", "S09"],
                "query": "Test automation plan",
            }),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert data["portfolio"]["client_id"] == "test-client-001"
        assert data["portfolio"]["selections"] == ["S01", "S03", "S09"]
        assert data["portfolio"]["total_monthly_estimate"] == 49 + 19 + 29  # S01+S03+S09
        assert "optimization_suggestions" in data

    def test_get_portfolio(self, client):
        """GET /api/client-portfolio/{id} retrieves a saved portfolio."""
        # First save
        client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "client_id": "get-test-002",
                "plan_id": "QP-12345678",
                "selections": ["S01"],
                "query": "Test",
            }),
            headers={"Content-Type": "application/json"},
        )
        # Then retrieve
        resp = client.get("/api/client-portfolio/get-test-002")
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert data["portfolio"]["plan_id"] == "QP-12345678"

    def test_get_portfolio_not_found(self, client):
        """GET /api/client-portfolio/{id} returns 404 for unknown client."""
        resp = client.get("/api/client-portfolio/nonexistent-client")
        assert resp.status_code == 404

    def test_update_selections(self, client):
        """PUT /api/client-portfolio/{id}/selections updates services."""
        # Save first
        client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "client_id": "update-test-003",
                "plan_id": "QP-00000001",
                "selections": ["S01"],
                "query": "Test",
            }),
            headers={"Content-Type": "application/json"},
        )
        # Upgrade — add S06 and S07
        resp = client.put(
            "/api/client-portfolio/update-test-003/selections",
            content=json.dumps({"selections": ["S01", "S06", "S07"]}),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert data["change"]["type"] == "upgrade"
        assert data["change"]["new_total"] == 49 + 79 + 99  # S01+S06+S07

    def test_save_invalid_service_id(self, client):
        """Invalid service IDs are rejected."""
        resp = client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "client_id": "bad-test",
                "selections": ["S01", "S99"],
                "query": "Test",
            }),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400
        assert "S99" in resp.json()["error"]

    def test_save_empty_selections(self, client):
        """Empty selections are rejected."""
        resp = client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "client_id": "empty-test",
                "selections": [],
                "query": "Test",
            }),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400

    def test_save_missing_client_id(self, client):
        """Missing client_id is rejected."""
        resp = client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "selections": ["S01"],
                "query": "Test",
            }),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400


# ===========================================================================
# Legal / Terms of Service / Privacy Policy API tests
# ===========================================================================

class TestLegalAPI:
    """Tests for the /api/legal/* endpoints."""

    def test_terms_endpoint_exists(self, client):
        """GET /api/legal/terms returns 200."""
        resp = client.get("/api/legal/terms")
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert "terms" in data

    def test_terms_has_key_fields(self, client):
        """Terms response includes required fields."""
        resp = client.get("/api/legal/terms")
        terms = resp.json()["terms"]
        assert terms["provider"] == "Inoni Limited Liability Company"
        assert terms["creator"] == "Corey Post"
        assert "key_terms" in terms
        assert len(terms["key_terms"]) > 0

    def test_terms_service_scoped(self, client):
        """Terms with service IDs show data transparency for those services."""
        resp = client.get("/api/legal/terms?services=S01,S04")
        data = resp.json()
        transparency = data["terms"]["data_transparency"]
        assert len(transparency) == 2
        svc_ids = {t["service_id"] for t in transparency}
        assert "S01" in svc_ids
        assert "S04" in svc_ids

    def test_terms_standalone_mode(self, client):
        """Standalone mode uses standalone integration clause."""
        resp = client.get("/api/legal/terms?mode=standalone")
        clause = resp.json()["terms"]["integration_clause"]
        assert "standalone" in clause.lower()

    def test_terms_integrated_mode(self, client):
        """Integrated mode uses integration-friendly clause."""
        resp = client.get("/api/legal/terms?mode=integrated")
        clause = resp.json()["terms"]["integration_clause"]
        assert "existing automation" in clause.lower() or "alongside" in clause.lower()

    def test_privacy_endpoint_exists(self, client):
        """GET /api/legal/privacy returns 200."""
        resp = client.get("/api/legal/privacy")
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert "privacy" in data

    def test_privacy_has_core_principles(self, client):
        """Privacy response includes core principles."""
        privacy = client.get("/api/legal/privacy").json()["privacy"]
        assert "core_principles" in privacy
        assert len(privacy["core_principles"]) > 0
        # Key principle: never sell data
        assert any("never sell" in p.lower() for p in privacy["core_principles"])

    def test_privacy_has_user_rights(self, client):
        """Privacy response includes GDPR-style user rights."""
        privacy = client.get("/api/legal/privacy").json()["privacy"]
        assert "rights" in privacy
        assert "access" in privacy["rights"]
        assert "erasure" in privacy["rights"]
        assert "portability" in privacy["rights"]

    def test_privacy_service_scoped(self, client):
        """Privacy with services=S10 shows infrastructure metrics category."""
        resp = client.get("/api/legal/privacy?services=S10")
        cats = resp.json()["privacy"]["data_categories"]
        assert "infrastructure_metrics" in cats


# ===========================================================================
# AUAR Provisioning API tests
# ===========================================================================

class TestAUARProvisioningAPI:
    """Tests for the /api/auar/provision endpoint."""

    def test_provision_endpoint_exists(self, client):
        """POST /api/auar/provision returns 200."""
        resp = client.post(
            "/api/auar/provision",
            content=json.dumps({
                "client_id": "provision-test-001",
                "capability": "email_validation",
            }),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True

    def test_provision_has_billing_model(self, client):
        """Provision response includes affiliate charge-through billing model."""
        resp = client.post(
            "/api/auar/provision",
            content=json.dumps({
                "client_id": "billing-test",
                "capability": "stock_data",
            }),
            headers={"Content-Type": "application/json"},
        )
        data = resp.json()
        billing = data["provision"]["billing"]
        assert billing["model"] == "affiliate_charge_through"
        assert "markup" in billing

    def test_provision_missing_client_id(self, client):
        """Missing client_id returns 400."""
        resp = client.post(
            "/api/auar/provision",
            content=json.dumps({"capability": "test"}),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400

    def test_provision_missing_capability(self, client):
        """Missing capability returns 400."""
        resp = client.post(
            "/api/auar/provision",
            content=json.dumps({"client_id": "test"}),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400

    def test_provision_updates_portfolio(self, client):
        """Provisioning an API for a client with a portfolio updates that portfolio."""
        # First save a portfolio
        client.post(
            "/api/client-portfolio/save",
            content=json.dumps({
                "client_id": "portfolio-provision-test",
                "plan_id": "QP-AABBCCDD",
                "selections": ["S01", "S09"],
                "query": "Test with API provisioning",
            }),
            headers={"Content-Type": "application/json"},
        )
        # Then provision an API
        client.post(
            "/api/auar/provision",
            content=json.dumps({
                "client_id": "portfolio-provision-test",
                "capability": "currency_exchange",
            }),
            headers={"Content-Type": "application/json"},
        )
        # Check portfolio has the provisioned API
        resp = client.get("/api/client-portfolio/portfolio-provision-test")
        data = resp.json()
        assert "provisioned_apis" in data["portfolio"]
        assert data["portfolio"]["provisioned_apis"][0]["capability"] == "currency_exchange"
