"""
Tests for the Demo Deliverable Download feature.

Covers:
  - Predefined scenario templates (6 scenarios)
  - Custom query deliverables (LLM routing)
  - Usage limits (anon=5, free=10, paid=unlimited)
  - Branding: Murphy ASCII art logo, Apache 1.0 license, BSL 1.1 attribution
  - Usage info returned in API response

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

import os
import sys
import json
import hashlib
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def client():
    """Create a FastAPI test client for the deliverable endpoint."""
    os.environ["MURPHY_ENV"] = "development"
    os.environ["MURPHY_RATE_LIMIT_RPM"] = "6000"
    os.environ["MURPHY_RATE_LIMIT_BURST"] = "200"
    from starlette.testclient import TestClient
    from src.runtime.app import create_app
    app = create_app()
    return TestClient(app, follow_redirects=False)


def _post_deliverable(client, query, headers=None):
    """Helper: POST /api/demo/generate-deliverable with a query."""
    h = {"Content-Type": "application/json"}
    if headers:
        h.update(headers)
    return client.post(
        "/api/demo/generate-deliverable",
        content=json.dumps({"query": query}),
        headers=h,
    )


# ===========================================================================
# Generator unit tests (no HTTP)
# ===========================================================================

class TestDemoDeliverableGenerator:
    """Unit tests for the demo_deliverable_generator module."""

    def test_generate_predefined_onboarding(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        assert result["title"]
        assert "onboarding" in result["filename"].lower() or "client" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_finance(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Generate Q3 finance report")
        assert "finance" in result["filename"].lower() or "q3" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_hr(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Screen candidates for PM role")
        assert len(result["content"]) > 200
        assert result["filename"].endswith(".txt")

    def test_generate_predefined_compliance(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Run compliance audit")
        assert "compliance" in result["filename"].lower() or "audit" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_project(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Create project plan")
        assert "project" in result["filename"].lower() or "plan" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_predefined_invoice(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Process invoice batch")
        assert "invoice" in result["filename"].lower()
        assert len(result["content"]) > 200

    def test_generate_custom_query(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Build an HVAC maintenance schedule for a 10-unit apartment building")
        assert result["title"]
        assert result["content"]
        assert result["filename"].endswith(".txt")
        # custom deliverable filename should not be a predefined scenario slug
        assert any(word in result["filename"] for word in ["custom", "hvac", "maintenance", "build", "apartment"])

    def test_has_branding(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        content = result["content"]
        # ASCII art logo block
        assert "MURPHY" in content or "Murphy" in content
        # Generated by line
        assert "murphy.systems" in content

    def test_has_apache_license(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Generate Q3 finance report")
        content = result["content"]
        assert "Apache License" in content
        assert "Version 1.0" in content or "1.0" in content

    def test_has_bsl_attribution(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Run compliance audit")
        content = result["content"]
        assert "BSL" in content or "Business Source License" in content
        assert "Inoni" in content

    def test_license_notice_cannot_be_removed_marker(self):
        """Verify the 'MAY NOT BE REMOVED' marker is present."""
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        assert "MAY NOT BE REMOVED" in result["content"]

    def test_filename_pattern_predefined(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Onboard a new client")
        assert result["filename"].startswith("murphy-")
        assert result["filename"].endswith(".txt")

    def test_filename_pattern_custom(self):
        from src.demo_deliverable_generator import generate_deliverable
        result = generate_deliverable("Completely unknown workflow xyz123")
        assert result["filename"].startswith("murphy-")
        assert result["filename"].endswith(".txt")

    def test_build_branded_txt_has_all_sections(self):
        from src.demo_deliverable_generator import build_branded_txt
        txt = build_branded_txt("Test Deliverable", "Some content here", scenario_type="test")
        assert "DELIVERABLE:" in txt
        assert "Generated:" in txt
        assert "Quality:" in txt
        assert "apache" in txt.lower()
        assert "Inoni" in txt

    def test_make_fingerprint_deterministic(self):
        from src.demo_deliverable_generator import make_fingerprint
        fp1 = make_fingerprint("192.168.1.1", "Mozilla/5.0")
        fp2 = make_fingerprint("192.168.1.1", "Mozilla/5.0")
        assert fp1 == fp2

    def test_make_fingerprint_different_ips(self):
        from src.demo_deliverable_generator import make_fingerprint
        fp1 = make_fingerprint("10.0.0.1", "Mozilla/5.0")
        fp2 = make_fingerprint("10.0.0.2", "Mozilla/5.0")
        assert fp1 != fp2


# ===========================================================================
# API endpoint tests
# ===========================================================================

class TestDemoDeliverableEndpoint:
    """Tests for POST /api/demo/generate-deliverable."""

    def test_endpoint_exists(self, client):
        """Endpoint must exist and accept POST."""
        resp = _post_deliverable(client, "Onboard a new client")
        assert resp.status_code in (200, 429), f"Unexpected status {resp.status_code}"

    def test_missing_query_returns_400(self, client):
        """Empty query body returns 400."""
        resp = client.post(
            "/api/demo/generate-deliverable",
            content=json.dumps({}),
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 400
        assert resp.json()["error"] == "missing_query"

    def test_predefined_scenario_success(self, client):
        """A predefined scenario query returns a valid deliverable."""
        resp = _post_deliverable(client, "Generate Q3 finance report",
                                 headers={"X-Forwarded-For": "10.0.1.1"})
        if resp.status_code == 200:
            data = resp.json()
            assert data["success"] is True
            assert "deliverable" in data
            assert "title" in data["deliverable"]
            assert "content" in data["deliverable"]
            assert "filename" in data["deliverable"]
            assert data["deliverable"]["filename"].endswith(".txt")
        else:
            # 429 means limit exceeded from a previous test run — acceptable
            assert resp.status_code == 429

    def test_custom_query_success(self, client):
        """A custom query returns a deliverable."""
        resp = _post_deliverable(client, "Build a restaurant launch plan",
                                 headers={"X-Forwarded-For": "10.0.2.1"})
        if resp.status_code == 200:
            data = resp.json()
            assert data["success"] is True
            assert "deliverable" in data
            assert len(data["deliverable"]["content"]) > 100
        else:
            assert resp.status_code == 429

    def test_response_includes_usage_info(self, client):
        """Successful response includes usage stats."""
        resp = _post_deliverable(client, "Screen candidates for PM role",
                                 headers={"X-Forwarded-For": "10.0.3.1"})
        if resp.status_code == 200:
            data = resp.json()
            assert "usage" in data
            usage = data["usage"]
            assert "used" in usage
            assert "limit" in usage
            assert "remaining" in usage
            assert "tier" in usage

    def test_branding_in_response_content(self, client):
        """Returned content must contain Murphy branding."""
        resp = _post_deliverable(client, "Run compliance audit",
                                 headers={"X-Forwarded-For": "10.0.4.1"})
        if resp.status_code == 200:
            content = resp.json()["deliverable"]["content"]
            assert "murphy.systems" in content.lower() or "Murphy" in content

    def test_apache_license_in_content(self, client):
        """Returned content must contain Apache 1.0 license notice."""
        resp = _post_deliverable(client, "Create project plan",
                                 headers={"X-Forwarded-For": "10.0.5.1"})
        if resp.status_code == 200:
            content = resp.json()["deliverable"]["content"]
            assert "Apache License" in content

    def test_bsl_attribution_in_content(self, client):
        """Returned content must contain BSL 1.1 / Inoni attribution."""
        resp = _post_deliverable(client, "Process invoice batch",
                                 headers={"X-Forwarded-For": "10.0.6.1"})
        if resp.status_code == 200:
            content = resp.json()["deliverable"]["content"]
            assert "Inoni" in content
            assert "BSL" in content or "Business Source" in content


# ===========================================================================
# Usage limit tests (using SubscriptionManager directly)
# ===========================================================================

class TestDemoDeliverableUsageLimits:
    """Tests for anonymous and free-tier usage limits."""

    def test_anon_limit_is_5(self):
        """Anonymous users must be blocked after exactly 5 downloads."""
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        fp = "demo_anon_test_fingerprint_abc123"
        for i in range(5):
            result = mgr.record_anon_usage(fp)
            assert result["allowed"] is True, f"Should be allowed on attempt {i+1}"
        # 6th attempt must be blocked
        result = mgr.record_anon_usage(fp)
        assert result["allowed"] is False
        assert result["remaining"] == 0
        assert result["tier"] == "anonymous"

    def test_free_registered_limit_is_10(self):
        """Free registered users must be blocked after exactly 10 downloads."""
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        account_id = "demo_free_test_account_xyz789"
        for i in range(10):
            result = mgr.record_usage(account_id)
            assert result["allowed"] is True, f"Should be allowed on attempt {i+1}"
        # 11th attempt must be blocked
        result = mgr.record_usage(account_id)
        assert result["allowed"] is False
        assert result["remaining"] == 0

    def test_paid_users_are_unlimited(self):
        """Paid (non-free) users must never be blocked."""
        from src.subscription_manager import (
            SubscriptionManager, SubscriptionTier,
            SubscriptionRecord, SubscriptionStatus,
        )
        mgr = SubscriptionManager()
        account_id = "demo_paid_test_account_xyz789"
        mgr._subscriptions[account_id] = SubscriptionRecord(
            account_id=account_id,
            tier=SubscriptionTier.SOLO,
            status=SubscriptionStatus.ACTIVE,
        )
        for i in range(25):
            result = mgr.record_usage(account_id)
            assert result["allowed"] is True
            assert result["limit"] == -1  # unlimited

    def test_anon_usage_remaining_counts_down(self):
        """Remaining count must decrement with each use."""
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        fp = "demo_countdown_test_fp_444"
        result = mgr.record_anon_usage(fp)
        assert result["remaining"] == 4
        result = mgr.record_anon_usage(fp)
        assert result["remaining"] == 3
        result = mgr.record_anon_usage(fp)
        assert result["remaining"] == 2

    def test_limit_exceeded_response_structure(self, client):
        """When limit is exceeded, response has correct error structure."""
        from src.subscription_manager import SubscriptionManager
        # Use a custom fingerprint that's already exhausted
        mgr_ref = None
        try:
            from src.runtime.app import create_app as _ca
        except Exception:
            return  # Skip if app not available

        # Hit the limit directly via SubscriptionManager
        from src.subscription_manager import SubscriptionManager
        mgr = SubscriptionManager()
        fp = "demo_limit_exceeded_test_fp"
        for _ in range(5):
            mgr.record_anon_usage(fp)

        # Now simulate the API response structure
        result = mgr.record_anon_usage(fp)
        assert result["allowed"] is False
        assert "message" in result
        assert result["tier"] == "anonymous"
