"""
Murphy System — Causal Spike Analyzer
=======================================
Analyzes high-impact memory spikes to extract generalizable causal
patterns and propose cross-domain replication via HITL.

When the Knostalgia Engine flags a memory as a spike (abnormally high
impact weight), the CausalSpikeAnalyzer decomposes the spike to isolate
the causal variable and tests whether the same algorithm could produce
similar improvements in other domains / categories.

The HITL prompt format is:
  "We noticed [action] had an unusually high impact on [efficiency/profit].
   Our analysis suggests the same approach could work for [other domains].
   Should we test this?"

Thread-safe via internal Lock.
"""
from __future__ import annotations

import logging
import threading
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from src.knostalgia_category_engine import KnostalgiaCategoryEngine
from src.knostalgia_engine import KnostalgiaMemory
from src.ml_strategy_engine import _cosine_similarity

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────
# Data structures
# ──────────────────────────────────────────────────────────────────────

@dataclass
class CausalHypothesis:
    """
    A hypothesis generated by the CausalSpikeAnalyzer.

    Describes what is thought to have caused the spike and which other
    domains might benefit from the same algorithm/approach.
    """
    hypothesis_id: str
    source_memory: KnostalgiaMemory
    isolated_variable: str
    causal_strength: float
    candidate_domains: List[str]
    transferability_scores: Dict[str, float]
    hypothesis_text: str
    status: str = "PENDING"      # "PENDING" | "APPROVED" | "REJECTED"
    created_at: float = field(default_factory=time.time)


@dataclass
class ReplicationPlan:
    """Plan produced when a CausalHypothesis is approved by HITL."""
    plan_id: str
    hypothesis_id: str
    reasoning_template: Dict[str, Any]
    target_domains: List[str]
    created_at: float


# ──────────────────────────────────────────────────────────────────────
# Analyzer
# ──────────────────────────────────────────────────────────────────────

class CausalSpikeAnalyzer:
    """
    Causal analysis engine for high-impact memory spikes.

    Decomposes a spike memory into its constituent variables, estimates
    which variable most likely caused the outsized result, then identifies
    other categories where the same approach may produce similar gains.

    Uses category prototype embeddings from :class:`KnostalgiaCategoryEngine`
    to estimate structural similarity across domains.

    Thread-safe via internal Lock.
    """

    def __init__(self, category_engine: KnostalgiaCategoryEngine) -> None:
        """
        Args:
            category_engine: The live category engine used to look up
                prototype embeddings for transferability scoring.
        """
        self._category_engine = category_engine
        self._hypotheses: Dict[str, CausalHypothesis] = {}
        self._lock = threading.Lock()

        logger.info("CausalSpikeAnalyzer initialised")

    # ------------------------------------------------------------------
    # Analysis
    # ------------------------------------------------------------------

    def analyze_spike(self, memory: KnostalgiaMemory) -> CausalHypothesis:
        """Decompose a spike memory and generate a causal hypothesis.

        Steps:
        1. Decompose memory: input, category, reasoning framework, context
        2. Isolate causal variable (category / framework / action / timing)
        3. Test generalisability against other category prototypes
        4. Generate human-readable hypothesis text

        Args:
            memory: A spike-flagged :class:`KnostalgiaMemory`.

        Returns:
            A :class:`CausalHypothesis` ready for HITL review.
        """
        # Step 1: Decompose the memory into its structural parts
        category_name = memory.category
        framework = memory.reasoning_framework
        efficiency = memory.efficiency_delta
        profit = memory.profit_delta

        # Step 2: Isolate the most likely causal variable
        isolated_variable, causal_strength = self._isolate_variable(
            memory.weight, efficiency, profit, framework
        )

        # Step 3: Find candidate domains for transfer
        candidate_domains, transferability_scores = self._test_generalisability(
            memory, causal_strength
        )

        # Step 4: Generate human-readable hypothesis text
        domain_list = ", ".join(candidate_domains) if candidate_domains else "no other domains identified"
        structural_note = self._describe_structural_property(memory)

        hypothesis_text = (
            f"The algorithm [{isolated_variable}] that produced a spike in "
            f"[{category_name}] could produce similar results in "
            f"[{domain_list}] because they share [{structural_note}]."
        )

        hypothesis = CausalHypothesis(
            hypothesis_id=str(uuid.uuid4()),
            source_memory=memory,
            isolated_variable=isolated_variable,
            causal_strength=causal_strength,
            candidate_domains=candidate_domains,
            transferability_scores=transferability_scores,
            hypothesis_text=hypothesis_text,
            status="PENDING",
            created_at=time.time(),
        )

        with self._lock:
            self._hypotheses[hypothesis.hypothesis_id] = hypothesis

        logger.info(
            "CausalHypothesis created: id=%s variable=%s strength=%.3f domains=%s",
            hypothesis.hypothesis_id,
            isolated_variable,
            causal_strength,
            candidate_domains,
        )
        return hypothesis

    # ------------------------------------------------------------------
    # HITL prompt
    # ------------------------------------------------------------------

    def generate_hitl_prompt(self, hypothesis: CausalHypothesis) -> str:
        """Build the HITL confirmation prompt for a causal hypothesis.

        Format:
            "We noticed [action] had an unusually high impact on
             [efficiency/profit].  Our analysis suggests the same approach
             could work for [other domains].  Should we test this?"
        """
        memory = hypothesis.source_memory
        impact_type = (
            "efficiency" if memory.efficiency_delta >= memory.profit_delta else "profit"
        )
        domain_list = (
            ", ".join(hypothesis.candidate_domains)
            if hypothesis.candidate_domains
            else "no identified domains"
        )
        return (
            f"We noticed [{hypothesis.isolated_variable}] had an unusually high impact "
            f"on [{impact_type}]. Our analysis suggests the same approach could work for "
            f"[{domain_list}]. Should we test this?"
        )

    # ------------------------------------------------------------------
    # HITL outcomes
    # ------------------------------------------------------------------

    def on_approved(self, hypothesis_id: str) -> ReplicationPlan:
        """Process HITL approval — extract algorithm as a reasoning template
        and register it in the category prototypes for future inheritance.

        Args:
            hypothesis_id: ID of the approved hypothesis.

        Returns:
            A :class:`ReplicationPlan` with the extracted template.
        """
        with self._lock:
            hypothesis = self._hypotheses.get(hypothesis_id)
            if hypothesis is None:
                raise ValueError(f"Unknown hypothesis_id: {hypothesis_id}")
            hypothesis.status = "APPROVED"

        # Build a reusable reasoning template from the source memory
        reasoning_template: Dict[str, Any] = {
            "source_category": hypothesis.source_memory.category,
            "isolated_variable": hypothesis.isolated_variable,
            "causal_strength": hypothesis.causal_strength,
            "original_framework": hypothesis.source_memory.reasoning_framework,
            "transferability_scores": hypothesis.transferability_scores,
        }

        # Register the template as an update to each target category prototype
        for domain in hypothesis.candidate_domains:
            proto = self._category_engine.find_by_name(domain)
            if proto is not None:
                with self._category_engine._lock:
                    proto.reasoning_framework.update(
                        {f"replicated_from_{hypothesis.source_memory.category}": reasoning_template}
                    )
                logger.info(
                    "Reasoning template from hypothesis %s registered in category '%s'",
                    hypothesis_id, domain,
                )

        # Update source memory causal status
        hypothesis.source_memory.causal_status = "REPLICATED"

        plan = ReplicationPlan(
            plan_id=str(uuid.uuid4()),
            hypothesis_id=hypothesis_id,
            reasoning_template=reasoning_template,
            target_domains=list(hypothesis.candidate_domains),
            created_at=time.time(),
        )

        logger.info("ReplicationPlan created: %s for hypothesis %s", plan.plan_id, hypothesis_id)
        return plan

    def on_rejected(self, hypothesis_id: str) -> None:
        """Process HITL rejection — mark the hypothesis and update causal model.

        The source memory's causal status is set to ANALYZED to indicate
        that the spike was inspected but not considered generalisable.

        Args:
            hypothesis_id: ID of the rejected hypothesis.
        """
        with self._lock:
            hypothesis = self._hypotheses.get(hypothesis_id)
            if hypothesis is None:
                logger.warning("on_rejected: unknown hypothesis_id=%s", hypothesis_id)
                return
            hypothesis.status = "REJECTED"

        # Reduce causal strength to discourage similar transfers in future
        hypothesis.causal_strength = max(0.0, hypothesis.causal_strength - 0.2)
        hypothesis.source_memory.causal_status = "ANALYZED"

        logger.info("Hypothesis %s rejected, causal strength reduced to %.3f",
                    hypothesis_id, hypothesis.causal_strength)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_hypothesis(self, hypothesis_id: str) -> Optional[CausalHypothesis]:
        """Return hypothesis by id, or None."""
        with self._lock:
            return self._hypotheses.get(hypothesis_id)

    def all_hypotheses(self) -> List[CausalHypothesis]:
        """Return a snapshot of all hypotheses."""
        with self._lock:
            return list(self._hypotheses.values())

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _isolate_variable(
        self,
        impact_weight: float,
        efficiency_delta: float,
        profit_delta: float,
        reasoning_framework: Dict[str, Any],
    ) -> Tuple[str, float]:
        """Determine the most likely causal variable and its strength.

        Uses simple heuristics to attribute the spike:
        - If efficiency_delta dominates → "efficiency_algorithm"
        - If profit_delta dominates → "profit_algorithm"
        - If reasoning_framework has a named action → use that
        - Otherwise → "combined_impact_algorithm"

        Causal strength is derived from the normalised impact_weight.
        """
        causal_strength = min(1.0, impact_weight)

        # Check for an explicit action in the reasoning framework
        if reasoning_framework:
            for key in ("action", "algorithm", "strategy", "method"):
                if key in reasoning_framework:
                    return str(reasoning_framework[key]), causal_strength

        if efficiency_delta > profit_delta and efficiency_delta > 0:
            return "efficiency_algorithm", causal_strength
        if profit_delta > efficiency_delta and profit_delta > 0:
            return "profit_algorithm", causal_strength
        return "combined_impact_algorithm", causal_strength

    def _test_generalisability(
        self,
        memory: KnostalgiaMemory,
        causal_strength: float,
    ) -> Tuple[List[str], Dict[str, float]]:
        """Score each known category prototype for transferability.

        transferability = structural_similarity * causal_strength

        Only prototypes with transferability > 0.1 and a different name
        from the source category are included as candidates.
        """
        candidate_domains: List[str] = []
        transferability_scores: Dict[str, float] = {}

        if not memory.embedding:
            return candidate_domains, transferability_scores

        for proto in self._category_engine.all_prototypes():
            if proto.name == memory.category:
                continue
            if not proto.embedding:
                continue
            structural_similarity = _cosine_similarity(memory.embedding, proto.embedding)
            transferability = structural_similarity * causal_strength
            transferability_scores[proto.name] = round(transferability, 4)
            if transferability > 0.1:
                candidate_domains.append(proto.name)

        # Sort candidates by score descending
        candidate_domains.sort(
            key=lambda d: transferability_scores.get(d, 0.0), reverse=True
        )
        return candidate_domains, transferability_scores

    def _describe_structural_property(self, memory: KnostalgiaMemory) -> str:
        """Produce a one-line description of the shared structural property."""
        framework = memory.reasoning_framework
        if not framework:
            return "similar structural properties"
        # Use the first key-value pair as a concise description
        first_key = next(iter(framework))
        return f"{first_key}={framework[first_key]}"
