"""
Declarative Fleet Manager for Murphy System.

Provides a Kubernetes-inspired desired-state reconciliation model for Murphy's
bot ecosystem.  Users declare an entire fleet in a FleetManifest; the
FleetReconciler continuously converges actual state to match declared state.

Design principles:
  - Declarative over imperative: declare what you want, the system figures out how
  - Idempotent reconciliation: running reconcile() multiple times with the same
    manifest produces the same result
  - Dependency-ordered startup via topological sort
  - Full audit trail via EventBackbone
  - Compatible with GovernanceKernel authority bands

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

from __future__ import annotations

import json
import logging
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

import yaml  # PyYAML — already in requirements_murphy_1.0.txt

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ActionType(Enum):
    """Possible reconciliation actions."""
    SPAWN = "spawn"
    DESPAWN = "despawn"
    UPDATE = "update"
    REGISTER_HEARTBEAT = "register_heartbeat"
    WIRE_SUPERVISION = "wire_supervision"


class ActionStatus(Enum):
    """Status of a reconciliation action."""
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Data-classes
# ---------------------------------------------------------------------------

@dataclass
class HeartbeatPolicy:
    """Heartbeat policy for a bot."""
    interval_seconds: float = 30.0
    max_missed: int = 3
    recovery_strategy: str = "restart"  # restart | alert | escalate


@dataclass
class BotManifest:
    """Declares a single bot's desired state."""
    bot_id: str
    name: str
    role: str  # maps to BotRole enum value
    capabilities: List[str] = field(default_factory=list)
    heartbeat_policy: HeartbeatPolicy = field(default_factory=HeartbeatPolicy)
    governance: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)  # bot_ids started first
    replicas: int = 1
    enabled: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "bot_id": self.bot_id,
            "name": self.name,
            "role": self.role,
            "capabilities": self.capabilities,
            "heartbeat_policy": {
                "interval_seconds": self.heartbeat_policy.interval_seconds,
                "max_missed": self.heartbeat_policy.max_missed,
                "recovery_strategy": self.heartbeat_policy.recovery_strategy,
            },
            "governance": self.governance,
            "dependencies": self.dependencies,
            "replicas": self.replicas,
            "enabled": self.enabled,
        }


@dataclass
class FleetManifest:
    """Declares the entire desired fleet state."""
    fleet_id: str
    version: str
    description: str
    bots: List[BotManifest] = field(default_factory=list)
    global_policies: Dict[str, Any] = field(default_factory=dict)
    supervision_topology: Dict[str, List[str]] = field(default_factory=dict)
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    updated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "fleet_id": self.fleet_id,
            "version": self.version,
            "description": self.description,
            "bots": [b.to_dict() for b in self.bots],
            "global_policies": self.global_policies,
            "supervision_topology": self.supervision_topology,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class ReconciliationAction:
    """A single action generated by the diff engine."""
    action_id: str = field(default_factory=lambda: f"act_{uuid.uuid4().hex[:8]}")
    action_type: ActionType = ActionType.SPAWN
    target_bot_id: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    status: ActionStatus = ActionStatus.PENDING

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_id": self.action_id,
            "action_type": self.action_type.value,
            "target_bot_id": self.target_bot_id,
            "details": self.details,
            "status": self.status.value,
        }


# ---------------------------------------------------------------------------
# Manifest validation helpers
# ---------------------------------------------------------------------------

class ManifestValidationError(ValueError):
    """Raised when a FleetManifest fails validation."""


def _topological_sort(bots: List[BotManifest]) -> List[BotManifest]:
    """
    Return bots in dependency-first order (topological sort).

    Raises ManifestValidationError if a dependency cycle is detected.
    """
    bot_map: Dict[str, BotManifest] = {b.bot_id: b for b in bots}
    order: List[BotManifest] = []
    visited: set = set()
    visiting: set = set()  # cycle detection

    def visit(bot_id: str) -> None:
        if bot_id in visited:
            return
        if bot_id in visiting:
            raise ManifestValidationError(
                f"Dependency cycle detected involving bot_id '{bot_id}'"
            )
        visiting.add(bot_id)
        bot = bot_map.get(bot_id)
        if bot is not None:
            for dep in bot.dependencies:
                visit(dep)
            visiting.discard(bot_id)
            visited.add(bot_id)
            order.append(bot)

    for b in bots:
        visit(b.bot_id)
    return order


def _validate_manifest(
    manifest: FleetManifest,
    capability_registry: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Validate a FleetManifest.

    Checks:
    - replicas >= 0 for every bot
    - all dependency bot_ids exist within the manifest
    - no dependency cycles
    - if capability_registry provided, all listed capabilities must exist

    Raises ManifestValidationError on the first problem found.
    """
    known_ids = {b.bot_id for b in manifest.bots}

    for bot in manifest.bots:
        if bot.replicas < 0:
            raise ManifestValidationError(
                f"Bot '{bot.bot_id}' has negative replicas ({bot.replicas})"
            )
        for dep in bot.dependencies:
            if dep not in known_ids:
                raise ManifestValidationError(
                    f"Bot '{bot.bot_id}' references unknown dependency '{dep}'"
                )
        if capability_registry is not None:
            for cap in bot.capabilities:
                if cap not in capability_registry:
                    raise ManifestValidationError(
                        f"Bot '{bot.bot_id}' references unknown capability '{cap}'"
                    )

    # Check for cycles
    _topological_sort(manifest.bots)


# ---------------------------------------------------------------------------
# ManifestLoader
# ---------------------------------------------------------------------------

class ManifestLoader:
    """Load a FleetManifest from YAML, JSON, or a plain dict."""

    @staticmethod
    def _bot_from_dict(data: Dict[str, Any]) -> BotManifest:
        hp_data = data.get("heartbeat_policy", {})
        hp = HeartbeatPolicy(
            interval_seconds=float(hp_data.get("interval_seconds", 30.0)),
            max_missed=int(hp_data.get("max_missed", 3)),
            recovery_strategy=str(hp_data.get("recovery_strategy", "restart")),
        )
        return BotManifest(
            bot_id=str(data["bot_id"]),
            name=str(data.get("name", data["bot_id"])),
            role=str(data.get("role", "assistant")),
            capabilities=list(data.get("capabilities", [])),
            heartbeat_policy=hp,
            governance=dict(data.get("governance", {})),
            dependencies=list(data.get("dependencies", [])),
            replicas=int(data.get("replicas", 1)),
            enabled=bool(data.get("enabled", True)),
        )

    @classmethod
    def load_from_dict(
        cls,
        data: Dict[str, Any],
        capability_registry: Optional[Dict[str, Any]] = None,
    ) -> FleetManifest:
        """Build and validate a FleetManifest from a plain dictionary."""
        bots = [cls._bot_from_dict(b) for b in data.get("bots", [])]
        manifest = FleetManifest(
            fleet_id=str(data.get("fleet_id", f"fleet_{uuid.uuid4().hex[:8]}")),
            version=str(data.get("version", "1.0")),
            description=str(data.get("description", "")),
            bots=bots,
            global_policies=dict(data.get("global_policies", {})),
            supervision_topology=dict(data.get("supervision_topology", {})),
            created_at=str(
                data.get("created_at", datetime.now(timezone.utc).isoformat())
            ),
            updated_at=str(
                data.get("updated_at", datetime.now(timezone.utc).isoformat())
            ),
        )
        _validate_manifest(manifest, capability_registry)
        return manifest

    @classmethod
    def load_from_yaml(
        cls,
        path: str,
        capability_registry: Optional[Dict[str, Any]] = None,
    ) -> FleetManifest:
        """Load and validate a FleetManifest from a YAML file."""
        with open(path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        return cls.load_from_dict(data or {}, capability_registry)

    @classmethod
    def load_from_json(
        cls,
        path: str,
        capability_registry: Optional[Dict[str, Any]] = None,
    ) -> FleetManifest:
        """Load and validate a FleetManifest from a JSON file."""
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        return cls.load_from_dict(data, capability_registry)


# ---------------------------------------------------------------------------
# FleetDriftDetector
# ---------------------------------------------------------------------------

@dataclass
class DriftItem:
    """Describes a single drift between desired and actual state."""
    bot_id: str
    drift_type: str  # missing | extra | config_mismatch
    details: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "bot_id": self.bot_id,
            "drift_type": self.drift_type,
            "details": self.details,
        }


class FleetDriftDetector:
    """
    Continuously monitors for drift between declared and actual bot fleet.

    Can be wired into a heartbeat tick cycle or polled directly.
    """

    def __init__(
        self,
        manifest: Optional[FleetManifest] = None,
        bot_inventory: Optional[Any] = None,
    ) -> None:
        self._manifest = manifest
        self._bot_inventory = bot_inventory
        self._lock = threading.Lock()

    def update_manifest(self, manifest: FleetManifest) -> None:
        """Replace the current manifest."""
        with self._lock:
            self._manifest = manifest

    def check_drift(self) -> List[DriftItem]:
        """
        Compare declared state vs actual inventory state.

        Returns a list of DriftItem objects describing all detected drift.
        """
        with self._lock:
            manifest = self._manifest
            inventory = self._bot_inventory

        if manifest is None:
            return []

        drifts: List[DriftItem] = []

        if inventory is None:
            # No inventory — all enabled bots are missing
            for bot in manifest.bots:
                if bot.enabled and bot.replicas > 0:
                    drifts.append(
                        DriftItem(
                            bot_id=bot.bot_id,
                            drift_type="missing",
                            details={"expected_replicas": bot.replicas},
                        )
                    )
            return drifts

        actual: Dict[str, Any] = inventory.get_bot_inventory()
        actual_bots: Dict[str, Any] = {
            b["name"]: b for b in actual.get("all_bots", [])
        }
        desired_names = {b.name for b in manifest.bots if b.enabled and b.replicas > 0}

        for bot in manifest.bots:
            if not bot.enabled or bot.replicas == 0:
                continue
            if bot.name not in actual_bots:
                drifts.append(
                    DriftItem(
                        bot_id=bot.bot_id,
                        drift_type="missing",
                        details={"expected_name": bot.name},
                    )
                )
            else:
                actual_bot = actual_bots[bot.name]
                if actual_bot.get("role") != bot.role:
                    drifts.append(
                        DriftItem(
                            bot_id=bot.bot_id,
                            drift_type="config_mismatch",
                            details={
                                "field": "role",
                                "desired": bot.role,
                                "actual": actual_bot.get("role"),
                            },
                        )
                    )

        # Extra bots not in desired state
        for actual_name in actual_bots:
            if actual_name not in desired_names:
                drifts.append(
                    DriftItem(
                        bot_id=actual_bots[actual_name].get("agent_id", actual_name),
                        drift_type="extra",
                        details={"actual_name": actual_name},
                    )
                )

        return drifts


# ---------------------------------------------------------------------------
# FleetReconciler
# ---------------------------------------------------------------------------

class FleetReconciler:
    """
    Reconciliation engine: converges actual fleet state to declared desired state.

    Parameters
    ----------
    bot_inventory:
        BotInventoryLibrary instance used to spawn/despawn bots.
    heartbeat_monitor:
        Optional object with a register_policy(bot_id, policy) method.
    supervision_tree:
        Optional SupervisionTree instance for wiring topology.
    event_backbone:
        Optional EventBackbone for publishing audit events.
    persistence_manager:
        Optional PersistenceManager for durable state snapshots.
    """

    def __init__(
        self,
        bot_inventory: Any,
        heartbeat_monitor: Optional[Any] = None,
        supervision_tree: Optional[Any] = None,
        event_backbone: Optional[Any] = None,
        persistence_manager: Optional[Any] = None,
    ) -> None:
        self._bot_inventory = bot_inventory
        self._heartbeat_monitor = heartbeat_monitor
        self._supervision_tree = supervision_tree
        self._event_backbone = event_backbone
        self._persistence_manager = persistence_manager

        self._manifest: Optional[FleetManifest] = None
        self._actions: List[ReconciliationAction] = []
        self._lock = threading.Lock()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load_manifest(self, manifest: FleetManifest) -> None:
        """Load the desired-state manifest."""
        with self._lock:
            self._manifest = manifest
            self._actions = []
        logger.info(
            "FleetReconciler: manifest '%s' v%s loaded (%d bots)",
            manifest.fleet_id,
            manifest.version,
            len(manifest.bots),
        )

    def observe(self) -> Dict[str, Any]:
        """Snapshot actual state from the bot inventory."""
        return self._bot_inventory.get_bot_inventory()

    def diff(self) -> List[ReconciliationAction]:
        """
        Compare desired manifest vs actual inventory and return a list of
        ReconciliationActions needed to converge.
        """
        with self._lock:
            manifest = self._manifest

        if manifest is None:
            return []

        actual = self.observe()
        actual_by_name: Dict[str, Any] = {
            b["name"]: b for b in actual.get("all_bots", [])
        }

        actions: List[ReconciliationAction] = []
        ordered_bots = _topological_sort(manifest.bots)

        for bot in ordered_bots:
            if not bot.enabled or bot.replicas == 0:
                # If disabled but exists → DESPAWN
                if bot.name in actual_by_name:
                    actions.append(
                        ReconciliationAction(
                            action_type=ActionType.DESPAWN,
                            target_bot_id=bot.bot_id,
                            details={
                                "name": bot.name,
                                "agent_id": actual_by_name[bot.name]["agent_id"],
                                "reason": "disabled_in_manifest",
                            },
                        )
                    )
                continue

            if bot.name not in actual_by_name:
                actions.append(
                    ReconciliationAction(
                        action_type=ActionType.SPAWN,
                        target_bot_id=bot.bot_id,
                        details={
                            "name": bot.name,
                            "role": bot.role,
                            "capabilities": bot.capabilities,
                            "replicas": bot.replicas,
                        },
                    )
                )
            else:
                actual_bot = actual_by_name[bot.name]
                if actual_bot.get("role") != bot.role:
                    actions.append(
                        ReconciliationAction(
                            action_type=ActionType.UPDATE,
                            target_bot_id=bot.bot_id,
                            details={
                                "agent_id": actual_bot["agent_id"],
                                "name": bot.name,
                                "field": "role",
                                "desired": bot.role,
                                "actual": actual_bot.get("role"),
                            },
                        )
                    )

            # Always ensure heartbeat policy is registered
            actions.append(
                ReconciliationAction(
                    action_type=ActionType.REGISTER_HEARTBEAT,
                    target_bot_id=bot.bot_id,
                    details={
                        "interval_seconds": bot.heartbeat_policy.interval_seconds,
                        "max_missed": bot.heartbeat_policy.max_missed,
                        "recovery_strategy": bot.heartbeat_policy.recovery_strategy,
                    },
                )
            )

        # Supervision wiring
        with self._lock:
            topology = manifest.supervision_topology if manifest else {}
        for supervisor_id, children in topology.items():
            actions.append(
                ReconciliationAction(
                    action_type=ActionType.WIRE_SUPERVISION,
                    target_bot_id=supervisor_id,
                    details={"supervisor_id": supervisor_id, "children": children},
                )
            )

        # Extra bots in actual that are NOT in manifest → DESPAWN
        desired_names = {b.name for b in manifest.bots}
        for name, actual_bot in actual_by_name.items():
            if name not in desired_names:
                actions.append(
                    ReconciliationAction(
                        action_type=ActionType.DESPAWN,
                        target_bot_id=actual_bot["agent_id"],
                        details={
                            "agent_id": actual_bot["agent_id"],
                            "name": name,
                            "reason": "not_in_manifest",
                        },
                    )
                )

        with self._lock:
            self._actions = actions
        return actions

    def reconcile(self) -> Dict[str, Any]:
        """
        Execute the diff actions to converge actual state to desired state.

        Returns a status summary dict.
        """
        self._publish(
            "FLEET_RECONCILIATION_STARTED",
            {"fleet_id": self._manifest.fleet_id if self._manifest else "unknown"},
        )

        actions = self.diff()
        completed = 0
        failed = 0

        for action in actions:
            try:
                self._execute_action(action)
                action.status = ActionStatus.COMPLETED
                completed += 1
            except Exception as exc:
                logger.error(
                    "FleetReconciler: action %s failed: %s",
                    action.action_id,
                    exc,
                )
                action.status = ActionStatus.FAILED
                failed += 1

        fleet_id = self._manifest.fleet_id if self._manifest else "unknown"
        self._publish(
            "FLEET_RECONCILED",
            {
                "fleet_id": fleet_id,
                "total_actions": len(actions),
                "completed": completed,
                "failed": failed,
            },
        )

        return {
            "fleet_id": fleet_id,
            "total_actions": len(actions),
            "completed": completed,
            "failed": failed,
            "actions": [a.to_dict() for a in actions],
        }

    def get_reconciliation_status(self) -> Dict[str, Any]:
        """Return convergence progress of the last reconciliation run."""
        with self._lock:
            actions = list(self._actions)
            manifest = self._manifest

        total = len(actions)
        completed = sum(1 for a in actions if a.status == ActionStatus.COMPLETED)
        failed = sum(1 for a in actions if a.status == ActionStatus.FAILED)
        pending = sum(1 for a in actions if a.status == ActionStatus.PENDING)

        return {
            "fleet_id": manifest.fleet_id if manifest else None,
            "manifest_version": manifest.version if manifest else None,
            "total_actions": total,
            "completed": completed,
            "failed": failed,
            "pending": pending,
            "converged": total > 0 and failed == 0 and pending == 0,
            "actions": [a.to_dict() for a in actions],
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _execute_action(self, action: ReconciliationAction) -> None:
        """Dispatch a single ReconciliationAction to the appropriate handler."""
        if action.action_type == ActionType.SPAWN:
            self._do_spawn(action)
        elif action.action_type == ActionType.DESPAWN:
            self._do_despawn(action)
        elif action.action_type == ActionType.UPDATE:
            self._do_update(action)
        elif action.action_type == ActionType.REGISTER_HEARTBEAT:
            self._do_register_heartbeat(action)
        elif action.action_type == ActionType.WIRE_SUPERVISION:
            self._do_wire_supervision(action)

    def _do_spawn(self, action: ReconciliationAction) -> None:
        d = action.details
        bot = self._bot_inventory.spawn_bot(
            name=d["name"],
            role=d["role"],
            capabilities=d.get("capabilities"),
        )
        self._publish(
            "FLEET_BOT_SPAWNED",
            {
                "bot_id": action.target_bot_id,
                "agent_id": bot.agent_id,
                "name": d["name"],
                "role": d["role"],
            },
        )
        logger.info("FleetReconciler: spawned bot '%s' (%s)", d["name"], bot.agent_id)

    def _do_despawn(self, action: ReconciliationAction) -> None:
        agent_id = action.details.get("agent_id", action.target_bot_id)
        self._bot_inventory.despawn_bot(agent_id)
        self._publish(
            "FLEET_BOT_DESPAWNED",
            {"bot_id": action.target_bot_id, "agent_id": agent_id},
        )
        logger.info("FleetReconciler: despawned bot '%s'", agent_id)

    def _do_update(self, action: ReconciliationAction) -> None:
        # For a live role change: despawn and re-spawn with the correct role.
        d = action.details
        agent_id = d.get("agent_id", "")
        self._bot_inventory.despawn_bot(agent_id)
        bot = self._bot_inventory.spawn_bot(
            name=d["name"],
            role=d["desired"],
        )
        self._publish(
            "FLEET_BOT_UPDATED",
            {
                "bot_id": action.target_bot_id,
                "new_agent_id": bot.agent_id,
                "field": d.get("field"),
                "desired": d.get("desired"),
            },
        )
        logger.info(
            "FleetReconciler: updated bot '%s' field '%s' → '%s'",
            d.get("name"),
            d.get("field"),
            d.get("desired"),
        )

    def _do_register_heartbeat(self, action: ReconciliationAction) -> None:
        if self._heartbeat_monitor is None:
            return
        d = action.details
        try:
            self._heartbeat_monitor.register_policy(action.target_bot_id, d)
        except AttributeError as exc:
            logger.debug(
                "FleetReconciler: heartbeat_monitor has no register_policy: %s", exc
            )

    def _do_wire_supervision(self, action: ReconciliationAction) -> None:
        if self._supervision_tree is None:
            return
        d = action.details
        try:
            from supervision_tree import ChildSpec, SupervisionStrategy, SupervisorNode

            supervisor_id = d["supervisor_id"]
            children = d.get("children", [])
            child_specs = [
                ChildSpec(child_id=cid, start_fn=lambda: None)
                for cid in children
            ]
            node = SupervisorNode(
                supervisor_id=supervisor_id,
                strategy=SupervisionStrategy.ONE_FOR_ONE,
                children=child_specs,
            )
            self._supervision_tree.register_supervisor(node)
        except Exception as exc:
            logger.warning(
                "FleetReconciler: supervision wiring failed for '%s': %s",
                action.target_bot_id,
                exc,
            )

    def _publish(self, event_name: str, payload: Dict[str, Any]) -> None:
        """Publish an event to the EventBackbone (best-effort)."""
        if self._event_backbone is None:
            return
        try:
            from event_backbone import EventType
            event_type = EventType(event_name.lower())
            self._event_backbone.publish(event_type, payload, source="fleet_reconciler")
        except Exception as exc:
            logger.debug("FleetReconciler: event publish skipped: %s", exc)
