# Copyright © 2020 Inoni Limited Liability Company
# Creator: Corey Post
# License: BSL 1.1
"""
Demo Bundle Generator — Murphy System

Generates a professional, downloadable ZIP bundle containing:
  1. The user's deliverable (.txt)
  2. An automation proposal document (.txt)
  3. An itemized quote at 100% cost (.txt)
  4. An automation specification (.txt)
  5. A README with setup instructions
  6. A project structure that mirrors a real engagement package

Usage::

    from demo_bundle_generator import generate_demo_bundle
    result = generate_demo_bundle("Onboard a new client", deliverable, spec)
    # result["zip_bytes"] → bytes of the ZIP archive
    # result["filename"]  → suggested filename
"""
from __future__ import annotations

import io
import re
import zipfile
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from murphy_identity import MURPHY_SYSTEM_IDENTITY

# ---------------------------------------------------------------------------
# Branding constants
# ---------------------------------------------------------------------------

_LOGO_HEADER = """\
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║    Murphy System — Generated Engagement Package                      ║
║    © 2025 Inoni Limited Liability Company (Corey Post)               ║
║    https://murphy.systems                                            ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
"""

_LICENSE_NOTICE = """\
LICENSE NOTICE
══════════════

  This deliverable package was generated by Murphy System, a product of
  Inoni Limited Liability Company. The OUTPUT of this generation is
  provided under the Apache License, Version 1.0.

  Murphy System itself is licensed under BSL 1.1.
  See https://github.com/IKNOWINOT/Murphy-System/blob/main/LICENSE

  © 2025 Inoni Limited Liability Company (Corey Post)
  https://murphy.systems
"""


# ---------------------------------------------------------------------------
# Proposal builder
# ---------------------------------------------------------------------------

def _build_automation_proposal(
    query: str,
    spec: Dict[str, Any],
    deliverable: Dict[str, Any],
) -> str:
    """Build a comprehensive automation proposal document."""
    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
    spec_id = spec.get("spec_id", "SPEC-PENDING")
    title = spec.get("title", query[:80])
    workflows = spec.get("workflows", [])
    integrations = spec.get("integrations", [])
    hours_saved = spec.get("hours_saved_month", 0)
    monthly_savings = spec.get("monthly_savings_usd", 0)
    murphy_cost = spec.get("murphy_cost", 99)
    net_benefit = spec.get("net_monthly_benefit", 0)
    annual_benefit = spec.get("annual_benefit", 0)
    roi_multiple = spec.get("roi_multiple", 0)
    recommended_tier = spec.get("recommended_tier", "Solo ($99/mo)")
    business_context = spec.get("business_context", "business operations")

    lines: List[str] = [
        _LOGO_HEADER,
        "═" * 72,
        "  AUTOMATION PROPOSAL",
        f"  {title}",
        "═" * 72,
        "",
        f"  Proposal Date    : {now_str}",
        f"  Specification ID : {spec_id}",
        f"  Prepared for     : {query[:120]}",
        f"  Business Context : {business_context}",
        f"  Prepared by      : Murphy System — Inoni LLC",
        "",
        "─" * 72,
        "  1. EXECUTIVE SUMMARY",
        "─" * 72,
        "",
        f"  This proposal outlines the automation of {len(workflows)} core workflows",
        f"  for your {business_context}. Murphy System will handle end-to-end",
        "  automation — from intake and processing to reporting and monitoring —",
        "  eliminating manual effort and reducing error rates.",
        "",
        f"  Current state: {spec.get('manual_hours_month', 20)} hours/month of manual processing",
        f"  Proposed state: ~1 hour/month of oversight (Murphy handles the rest)",
        f"  Net time savings: {hours_saved} hours/month",
        "",
        "─" * 72,
        "  2. SCOPE OF WORK",
        "─" * 72,
        "",
    ]

    for i, wf in enumerate(workflows, 1):
        lines.append(f"  Workflow {i}: {wf.get('name', 'Unnamed')}")
        lines.append(f"  Trigger: {wf.get('trigger', 'Manual / Event')}")
        lines.append(f"  Hours saved: {wf.get('hours_saved_month', '?')} hrs/month")
        lines.append("")
        for step in wf.get("steps", []):
            lines.append(f"    → {step}")
        lines.append("")
        lines.append(f"  Integrations required:")
        for intg in wf.get("integrations", []):
            lines.append(f"    • {intg}")
        lines.append("")

    lines += [
        "─" * 72,
        "  3. INTEGRATION REQUIREMENTS",
        "─" * 72,
        "",
    ]
    for intg in integrations:
        lines.append(f"  ✓  {intg}")
    lines += [
        "",
        "  All integrations use OAuth 2.0 or API key authentication.",
        "  Murphy never stores credentials in plain text.",
        "",
        "─" * 72,
        "  4. IMPLEMENTATION TIMELINE",
        "─" * 72,
        "",
        "  Phase 1 — Setup & Configuration        (Week 1–2)",
        "    • Environment provisioning and API credential collection",
        "    • Murphy System installation and workspace setup",
        "    • Integration testing (read/write verification)",
        "",
        "  Phase 2 — Workflow Development           (Week 3–4)",
        "    • Build and configure all automated workflows",
        "    • Configure notification routing and alerting",
        "    • Set up monitoring dashboards",
        "",
        "  Phase 3 — QA & Handoff                  (Week 5–6)",
        "    • End-to-end testing with production-like data",
        "    • Client UAT session and sign-off",
        "    • Documentation delivery and training",
        "    • Go-live and 30-day hypercare period",
        "",
        "─" * 72,
        "  5. EXPECTED OUTCOMES",
        "─" * 72,
        "",
        f"  • Time saved per month       : {hours_saved} hours",
        f"  • Cost of manual processing  : ${spec.get('manual_hours_month', 20) * spec.get('hourly_rate', 65):,}/month",
        f"  • Murphy System cost          : ${murphy_cost}/month ({recommended_tier})",
        f"  • Net monthly savings         : ${net_benefit:,}/month",
        f"  • Annual benefit              : ${annual_benefit:,}/year",
        f"  • ROI multiple                : {roi_multiple}× in first year",
        "",
        "─" * 72,
        "  6. TERMS & CONDITIONS",
        "─" * 72,
        "",
        "  • No setup fees for standard integrations",
        "  • Month-to-month subscription — cancel anytime",
        "  • Dedicated support during hypercare period",
        "  • All data remains in your connected accounts",
        "  • SOC 2 Type II compliant infrastructure",
        "",
        f"  Next Step: Sign up at https://murphy.systems/ui/signup?spec={spec_id}",
        "",
        _LICENSE_NOTICE,
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Itemized quote builder
# ---------------------------------------------------------------------------

def _build_itemized_quote(
    query: str,
    spec: Dict[str, Any],
) -> str:
    """Build an itemized quote at 100% cost to automate."""
    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
    spec_id = spec.get("spec_id", "SPEC-PENDING")
    title = spec.get("title", query[:80])
    workflows = spec.get("workflows", [])
    murphy_cost = spec.get("murphy_cost", 99)
    recommended_tier = spec.get("recommended_tier", "Solo ($99/mo)")
    manual_hours = spec.get("manual_hours_month", 20)
    hourly_rate = spec.get("hourly_rate", 65)

    # Build per-workflow cost breakdown
    total_setup_hours = 0
    workflow_line_items: List[str] = []

    for i, wf in enumerate(workflows, 1):
        wf_name = wf.get("name", f"Workflow {i}")
        step_count = len(wf.get("steps", []))
        integration_count = len(wf.get("integrations", []))

        # Estimate setup hours: 4 base + 1.5 per step + 2 per integration
        setup_hours = 4 + (step_count * 1.5) + (integration_count * 2)
        setup_cost = round(setup_hours * hourly_rate)
        total_setup_hours += setup_hours

        workflow_line_items.append(
            f"  │ WF-{i:02d} │ {wf_name:<40s}│ {setup_hours:>5.1f} hrs │ ${setup_cost:>7,} │"
        )

    # Additional line items
    pm_hours = round(total_setup_hours * 0.15, 1)
    qa_hours = round(total_setup_hours * 0.20, 1)
    training_hours = 4.0
    documentation_hours = 8.0
    hypercare_hours = round(total_setup_hours * 0.10, 1)

    total_labor_hours = total_setup_hours + pm_hours + qa_hours + training_hours + documentation_hours + hypercare_hours
    total_labor_cost = round(total_labor_hours * hourly_rate)

    # Platform costs
    platform_monthly = murphy_cost
    platform_annual = murphy_cost * 12

    # Total project cost (first year)
    total_first_year = total_labor_cost + platform_annual

    # Monthly savings comparison
    monthly_manual_cost = manual_hours * hourly_rate
    monthly_automated_cost = murphy_cost + round(hourly_rate * 1)  # 1 hr oversight
    monthly_savings = monthly_manual_cost - monthly_automated_cost

    lines: List[str] = [
        _LOGO_HEADER,
        "═" * 72,
        "  ITEMIZED AUTOMATION QUOTE",
        f"  {title}",
        "═" * 72,
        "",
        f"  Quote Date       : {now_str}",
        f"  Quote ID         : QT-{spec_id.replace('SPEC-', '')}",
        f"  Specification    : {spec_id}",
        f"  Valid for        : 30 days from quote date",
        f"  Prepared by      : Murphy System — Inoni LLC",
        "",
        "─" * 72,
        "  SECTION A — IMPLEMENTATION LABOR (ONE-TIME)",
        "─" * 72,
        "",
        "  ┌───────┬─────────────────────────────────────────┬───────────┬──────────┐",
        "  │  ID   │ Line Item                               │   Hours   │   Cost   │",
        "  ├───────┼─────────────────────────────────────────┼───────────┼──────────┤",
    ]

    for item in workflow_line_items:
        lines.append(item)

    lines += [
        "  ├───────┼─────────────────────────────────────────┼───────────┼──────────┤",
        f"  │ PM-01 │ {'Project Management':<40s}│ {pm_hours:>5.1f} hrs │ ${round(pm_hours * hourly_rate):>7,} │",
        f"  │ QA-01 │ {'Quality Assurance & Testing':<40s}│ {qa_hours:>5.1f} hrs │ ${round(qa_hours * hourly_rate):>7,} │",
        f"  │ TR-01 │ {'Client Training (1 session)':<40s}│ {training_hours:>5.1f} hrs │ ${round(training_hours * hourly_rate):>7,} │",
        f"  │ DC-01 │ {'Documentation & Runbook':<40s}│ {documentation_hours:>5.1f} hrs │ ${round(documentation_hours * hourly_rate):>7,} │",
        f"  │ HC-01 │ {'30-Day Hypercare Support':<40s}│ {hypercare_hours:>5.1f} hrs │ ${round(hypercare_hours * hourly_rate):>7,} │",
        "  ├───────┼─────────────────────────────────────────┼───────────┼──────────┤",
        f"  │ TOTAL │ {'Implementation Labor Total':<40s}│ {total_labor_hours:>5.1f} hrs │ ${total_labor_cost:>7,} │",
        "  └───────┴─────────────────────────────────────────┴───────────┴──────────┘",
        "",
        f"  Blended hourly rate: ${hourly_rate}/hr (engineering + PM + QA)",
        "",
        "─" * 72,
        "  SECTION B — PLATFORM SUBSCRIPTION (RECURRING)",
        "─" * 72,
        "",
        "  ┌───────────────────────────────┬────────────┬────────────┐",
        "  │ Platform Tier                 │ Monthly    │ Annual     │",
        "  ├───────────────────────────────┼────────────┼────────────┤",
        f"  │ {recommended_tier:<29s} │ ${platform_monthly:>8,}/mo│ ${platform_annual:>8,}/yr│",
        "  └───────────────────────────────┴────────────┴────────────┘",
        "",
        "  Includes: Unlimited automations · AI-powered planning · Monitoring",
        "  No per-user fees · No per-task limits · Cancel anytime",
        "",
        "─" * 72,
        "  SECTION C — COST COMPARISON (MONTHLY OPERATING)",
        "─" * 72,
        "",
        "  ┌─────────────────────────────┬───────────┬───────────────┐",
        "  │ Scenario                    │ Monthly   │ Annual        │",
        "  ├─────────────────────────────┼───────────┼───────────────┤",
        f"  │ {'Current (manual)':<27s} │ ${monthly_manual_cost:>7,}/mo│ ${monthly_manual_cost * 12:>11,}/yr│",
        f"  │ {'With Murphy System':<27s} │ ${monthly_automated_cost:>7,}/mo│ ${monthly_automated_cost * 12:>11,}/yr│",
        "  ├─────────────────────────────┼───────────┼───────────────┤",
        f"  │ {'NET SAVINGS':<27s} │ ${monthly_savings:>7,}/mo│ ${monthly_savings * 12:>11,}/yr│",
        "  └─────────────────────────────┴───────────┴───────────────┘",
        "",
        "─" * 72,
        "  SECTION D — TOTAL PROJECT INVESTMENT",
        "─" * 72,
        "",
        f"  One-time implementation   : ${total_labor_cost:>10,}",
        f"  Year 1 platform cost      : ${platform_annual:>10,}",
        f"  ────────────────────────────────────────────",
        f"  Total Year 1 investment   : ${total_first_year:>10,}",
        "",
        f"  Year 1 savings            : ${monthly_savings * 12:>10,}",
        f"  Net Year 1 ROI            : ${monthly_savings * 12 - total_first_year:>10,}",
        f"  Payback period            : {round(total_first_year / max(monthly_savings, 1), 1)} months",
        "",
        "─" * 72,
        "  NOTES",
        "─" * 72,
        "",
        "  • This quote reflects 100% of the cost to fully automate the specified",
        "    workflows with Murphy System, including all labor and platform fees.",
        "  • Custom integrations beyond standard connectors may incur additional",
        "    development at the same blended rate.",
        "  • Quote valid for 30 days. Prices subject to change after expiry.",
        "  • Payment terms: 50% at project start, 50% at go-live.",
        "",
        f"  Accept this quote: https://murphy.systems/ui/signup?spec={spec_id}",
        "",
        _LICENSE_NOTICE,
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# README builder
# ---------------------------------------------------------------------------

def _build_bundle_readme(
    query: str,
    spec: Dict[str, Any],
) -> str:
    """Build a README.md for the bundle."""
    spec_id = spec.get("spec_id", "SPEC-PENDING")
    title = spec.get("title", query[:80])
    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")

    return f"""\
# Murphy System — Engagement Package

**{title}**

Generated: {now_str}
Specification ID: {spec_id}

---

## 📁 Package Contents

| File | Description |
|------|-------------|
| `deliverable.txt` | The requested deliverable — ready to use |
| `automation-proposal.txt` | Full automation proposal with scope, timeline, and outcomes |
| `itemized-quote.txt` | Itemized quote at 100% cost with labor breakdown |
| `automation-spec.txt` | Technical automation specification with workflows and integrations |
| `README.md` | This file |
| `LICENSE` | License information |

## 🚀 Next Steps

1. **Review** the deliverable and proposal documents
2. **Share** with stakeholders for alignment
3. **Sign up** at [murphy.systems](https://murphy.systems/ui/signup?spec={spec_id}) to activate
4. Murphy will auto-configure all workflows from your specification
5. Connect your tools via OAuth and go live in under 10 minutes

## 💡 About Murphy System

Murphy System is an AI-powered business automation platform by Inoni LLC.
It handles everything from client onboarding to compliance audits, financial
reporting, and custom workflow automation — all without writing code.

- Website: https://murphy.systems
- Documentation: https://murphy.systems/docs
- Support: hello@murphy.systems

## 📄 License

The OUTPUT of this generation is provided under the Apache License, Version 1.0.
Murphy System itself is licensed under BSL 1.1.

© 2025 Inoni Limited Liability Company (Corey Post)
"""


# ---------------------------------------------------------------------------
# Main bundle generator
# ---------------------------------------------------------------------------

def generate_demo_bundle(
    query: str,
    deliverable: Dict[str, Any],
    automation_spec: Dict[str, Any],
) -> Dict[str, Any]:
    """Generate a professional ZIP bundle containing all engagement documents.

    Args:
        query: The user's original request
        deliverable: Dict from generate_deliverable() with 'content', 'filename', 'title'
        automation_spec: Dict from generate_automation_spec() with full spec data

    Returns:
        dict with:
        - ``zip_bytes`` (bytes) — the ZIP file contents
        - ``filename`` (str) — suggested download filename
        - ``file_count`` (int) — number of files in the bundle
        - ``files`` (list[str]) — list of filenames in the bundle
    """
    spec_id = automation_spec.get("spec_id", "SPEC-PENDING")
    title = automation_spec.get("title", query[:60])

    # Build all documents
    proposal_txt = _build_automation_proposal(query, automation_spec, deliverable)
    quote_txt = _build_itemized_quote(query, automation_spec)
    readme_md = _build_bundle_readme(query, automation_spec)
    spec_txt = automation_spec.get("content_txt", "")
    deliverable_txt = deliverable.get("content", "")

    # Derive bundle folder name
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower())[:40].strip("-")
    folder_name = f"murphy-{slug}-{spec_id.lower()}"
    zip_filename = f"{folder_name}.zip"

    # Build the ZIP
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        files_added: List[str] = []

        def _add(name: str, content: str) -> None:
            path = f"{folder_name}/{name}"
            zf.writestr(path, content)
            files_added.append(name)

        _add("README.md", readme_md)
        _add("deliverable.txt", deliverable_txt)
        _add("automation-proposal.txt", proposal_txt)
        _add("itemized-quote.txt", quote_txt)
        if spec_txt:
            _add("automation-spec.txt", spec_txt)
        _add("LICENSE", _LICENSE_NOTICE)

    zip_bytes = buf.getvalue()

    return {
        "zip_bytes": zip_bytes,
        "filename": zip_filename,
        "file_count": len(files_added),
        "files": files_added,
        "folder_name": folder_name,
        "spec_id": spec_id,
    }