"""
End User Agreement Generator — risk mitigation and transfer framework.

Every Inoni LLC niche business generated by Murphy System carries a customised
End User Agreement (EUA) that:

  1. Mitigates risk to Inoni Limited Liability Company
  2. Transfers operational risk to the human-in-the-loop validator who
     approves physical-world or regulated activities
  3. Defines automation requirements and the limits of automated action
  4. Establishes that the HITL approver, by signing/accepting the request,
     becomes the responsible party for outcomes within their domain

Legal model: Murphy generates; the human accepts responsibility by approving.

Design Label: NBG-EUA-001
Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EUASectionType(str, Enum):
    """Type classification for sections of the End User Agreement."""
    SCOPE_OF_AUTOMATION = "scope_of_automation"
    HITL_RESPONSIBILITY = "hitl_responsibility"
    LIABILITY_LIMITATION = "liability_limitation"
    RISK_TRANSFER = "risk_transfer"
    DATA_PRIVACY = "data_privacy"
    CONTRACTOR_RESPONSIBILITY = "contractor_responsibility"
    AUTOMATION_ACCEPTANCE = "automation_acceptance"
    DISPUTE_RESOLUTION = "dispute_resolution"
    REGULATORY_COMPLIANCE = "regulatory_compliance"
    CREDENTIAL_VERIFICATION = "credential_verification"
    PARTNER_PROGRAM = "partner_program"
    SHADOW_AGENT_IP = "shadow_agent_ip"
    GENERAL = "general"


class EUAAcceptanceMethod(str, Enum):
    """How the agreement was accepted."""
    HITL_APPROVAL = "hitl_approval"       # by approving the HITL request
    EXPLICIT_SIGN = "explicit_sign"       # by explicit signature
    ELECTRONIC_ACCEPT = "electronic_accept"  # click-through acceptance
    API_ACCEPTANCE = "api_acceptance"     # programmatic acceptance via API call


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class EUASection:
    """A single section of the End User Agreement."""
    section_id: str
    section_type: EUASectionType
    title: str
    body: str
    risk_level: str                   # "low" | "medium" | "high" | "critical"
    applies_to_autonomy_classes: List[str]   # ["full_autonomy", "hybrid", "legs_required"]
    binding: bool                     # True = must be explicitly accepted


@dataclass
class RiskTransferClause:
    """
    A specific clause that transfers risk from Inoni to the accepting party.

    When the human operator approves an HITL request, they are implicitly
    accepting all risk transfer clauses applicable to that niche.
    """
    clause_id: str
    title: str
    risk_being_transferred: str       # what risk is moved
    from_party: str                   # "inoni_llc"
    to_party: str                     # "hitl_approver" | "contractor" | "end_user"
    trigger: str                      # what action triggers the transfer
    text: str                         # the actual legal clause text


@dataclass
class AutomationRequirement:
    """A specific requirement for an automated business operation."""
    requirement_id: str
    description: str
    automation_type: str              # "generation" | "dispatch" | "validation" | "delivery"
    human_oversight_required: bool    # True = HITL needed before executing
    can_execute_autonomously: bool    # True = Murphy may act without HITL for this
    failure_mode: str                 # what happens if this automation fails
    recovery_action: str              # how Murphy recovers


@dataclass
class EUAAcceptance:
    """Record of an EUA being accepted by a party."""
    acceptance_id: str
    eua_id: str
    accepted_by: str                  # operator identifier
    accepted_at: str
    acceptance_method: EUAAcceptanceMethod
    ip_address: Optional[str]         # for audit trail
    risk_clauses_accepted: List[str]  # clause_ids explicitly accepted
    conditions_noted: List[str]       # any conditions the acceptor noted
    is_valid: bool                    # True if all binding sections were accepted


@dataclass
class EUADocument:
    """
    A complete End User Agreement for a specific Inoni LLC niche business.

    This document is generated per-niche and customised based on the niche's
    autonomy class, revenue model, and whether it involves regulated activities
    or physical-world contractors.

    The EUA is the legal instrument that:
    - Limits Inoni's liability to the scope of Murphy's generation
    - Transfers physical-world and regulated-domain risk to the HITL approver
    - Defines what automation is authorised to do autonomously
    - Establishes the contractor as solely responsible for their licensed work
    """
    eua_id: str
    niche_id: str
    inoni_entity_name: str            # "Inoni [Name] LLC"
    version: str                      # e.g. "1.0"
    sections: List[EUASection]
    risk_transfer_clauses: List[RiskTransferClause]
    automation_requirements: List[AutomationRequirement]
    generated_at: str
    effective_date: str
    applies_to_autonomy_class: str
    requires_credentialed_hitl: bool  # True if any section needs licensed HITL
    acceptance_record: Optional[EUAAcceptance]
    full_text: str                    # complete rendered agreement text


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class EUAGenerator:
    """
    Generates customised End User Agreements for Inoni LLC niche businesses.

    The EUA is tailored to the niche's autonomy class and whether it involves
    regulated activities, physical contractors, or certified professionals.

    Every EUA:
    - Limits Inoni's liability to Murphy's generation scope
    - Requires HITL approval before any external action is taken
    - Makes the HITL approver the responsible party for outcomes in their domain
    - Documents what automation is and is not authorised to do

    Args:
        version: The EUA version string (default "1.0").
    """

    def __init__(self, version: str = "1.0") -> None:
        self._version = version
        self._acceptances: Dict[str, EUAAcceptance] = {}

    # ------------------------------------------------------------------
    # Document generation
    # ------------------------------------------------------------------

    def generate(
        self,
        niche_id: str,
        niche_name: str,
        inoni_entity_name: str,
        autonomy_class: str,
        revenue_model: str,
        murphy_modules_required: Optional[List[str]] = None,
        requires_licensed_professionals: bool = False,
        requires_physical_contractors: bool = False,
    ) -> EUADocument:
        """Generate a complete EUA for an Inoni LLC niche business.

        Args:
            niche_id: The niche identifier.
            niche_name: Human-readable niche name.
            inoni_entity_name: Full Inoni LLC entity name.
            autonomy_class: "full_autonomy" | "hybrid" | "legs_required"
            revenue_model: The niche's revenue model string.
            murphy_modules_required: List of required Murphy modules.
            requires_licensed_professionals: True if niche needs credentialed humans.
            requires_physical_contractors: True if niche uses on-site contractors.

        Returns:
            A populated :class:`EUADocument`.
        """
        now = datetime.now(timezone.utc).isoformat()
        eua_id = str(uuid.uuid4())

        sections = self._build_sections(
            autonomy_class,
            requires_licensed_professionals,
            requires_physical_contractors,
        )

        risk_clauses = self._build_risk_transfer_clauses(
            inoni_entity_name,
            autonomy_class,
            requires_licensed_professionals,
        )

        automation_requirements = self._build_automation_requirements(
            autonomy_class,
            murphy_modules_required or [],
        )

        full_text = self._render_full_text(
            inoni_entity_name,
            sections,
            risk_clauses,
            automation_requirements,
        )

        return EUADocument(
            eua_id=eua_id,
            niche_id=niche_id,
            inoni_entity_name=inoni_entity_name,
            version=self._version,
            sections=sections,
            risk_transfer_clauses=risk_clauses,
            automation_requirements=automation_requirements,
            generated_at=now,
            effective_date=now,
            applies_to_autonomy_class=autonomy_class,
            requires_credentialed_hitl=requires_licensed_professionals,
            acceptance_record=None,
            full_text=full_text,
        )

    def record_acceptance(
        self,
        eua: EUADocument,
        accepted_by: str,
        acceptance_method: EUAAcceptanceMethod = EUAAcceptanceMethod.HITL_APPROVAL,
        conditions_noted: Optional[List[str]] = None,
        ip_address: Optional[str] = None,
    ) -> EUAAcceptance:
        """Record that a party has accepted an EUA.

        When the HITL request is approved, this should be called automatically
        to attach the acceptance record to the EUA.  By accepting, the party
        takes on the risk transfer clauses specific to their role.

        Args:
            eua: The EUA document being accepted.
            accepted_by: Identifier of the accepting party.
            acceptance_method: How the acceptance was recorded.
            conditions_noted: Any conditions attached to the acceptance.
            ip_address: Optional IP for audit trail.

        Returns:
            A populated :class:`EUAAcceptance`.
        """
        binding_clause_ids = [
            s.section_id for s in eua.sections if s.binding
        ] + [c.clause_id for c in eua.risk_transfer_clauses]

        acceptance = EUAAcceptance(
            acceptance_id=str(uuid.uuid4()),
            eua_id=eua.eua_id,
            accepted_by=accepted_by,
            accepted_at=datetime.now(timezone.utc).isoformat(),
            acceptance_method=acceptance_method,
            ip_address=ip_address,
            risk_clauses_accepted=binding_clause_ids,
            conditions_noted=conditions_noted or [],
            is_valid=True,
        )
        self._acceptances[acceptance.acceptance_id] = acceptance
        eua.acceptance_record = acceptance

        logger.info(
            "EUA accepted: eua_id=%s accepted_by=%s method=%s",
            eua.eua_id, accepted_by, acceptance_method.value,
        )
        return acceptance

    def get_acceptance(self, acceptance_id: str) -> Optional[EUAAcceptance]:
        """Return the acceptance record for *acceptance_id*."""
        return self._acceptances.get(acceptance_id)

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _build_sections(
        self,
        autonomy_class: str,
        requires_licensed: bool,
        requires_physical: bool,
    ) -> List[EUASection]:
        """Build the applicable sections for this niche type."""
        sections: List[EUASection] = []
        all_classes = ["full_autonomy", "hybrid", "legs_required"]
        hybrid_classes = ["hybrid", "legs_required"]

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.SCOPE_OF_AUTOMATION,
            title="1. Scope of Automation",
            body=(
                "Murphy System, operated by Inoni Limited Liability Company, provides "
                "AI-powered business generation, document creation, data analysis, and "
                "workflow automation services.  Murphy generates; it does not physically "
                "execute regulated or physical-world activities.  Any such activities "
                "require a qualified human professional as described in this Agreement."
            ),
            risk_level="medium",
            applies_to_autonomy_classes=all_classes,
            binding=True,
        ))

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.AUTOMATION_ACCEPTANCE,
            title="2. Automation Acceptance and Operator Responsibility",
            body=(
                "By activating any automated operation through Murphy System, the "
                "authorising operator ('the Approver') acknowledges that: "
                "(a) they have reviewed the generated output and approve its deployment; "
                "(b) they accept responsibility for outcomes arising from their approval; "
                "(c) the Human-in-the-Loop ('HITL') approval is binding and constitutes "
                "the Approver's explicit acceptance of the financial and operational "
                "risk described in this Agreement."
            ),
            risk_level="high",
            applies_to_autonomy_classes=all_classes,
            binding=True,
        ))

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.LIABILITY_LIMITATION,
            title="3. Limitation of Inoni LLC Liability",
            body=(
                "Inoni Limited Liability Company's liability is strictly limited to the "
                "scope of Murphy System's generation and automation services.  Inoni is "
                "not liable for: (a) market outcomes, revenue shortfalls, or business "
                "performance of the generated niche; (b) the actions or omissions of "
                "third-party contractors dispatched through the system; (c) the accuracy "
                "of regulatory information generated by Murphy (human review required); "
                "(d) any loss arising after the Approver's HITL acceptance."
            ),
            risk_level="critical",
            applies_to_autonomy_classes=all_classes,
            binding=True,
        ))

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.RISK_TRANSFER,
            title="4. Risk Transfer Upon HITL Approval",
            body=(
                "Upon approval of any Human-in-the-Loop (HITL) request, ALL operational "
                "and financial risk associated with the approved deployment is transferred "
                "to the Approver.  This transfer is irrevocable for the approved operation.  "
                "The Approver warrants that they have the authority and expertise to approve "
                "the described activity, and that they accept personal and professional "
                "responsibility for its outcome."
            ),
            risk_level="critical",
            applies_to_autonomy_classes=all_classes,
            binding=True,
        ))

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.DATA_PRIVACY,
            title="5. Data Privacy and Regulatory Alignment",
            body=(
                "Murphy System is designed to be aligned with GDPR, SOC 2, HIPAA, and "
                "PCI DSS frameworks.  Alignment means Murphy's design follows these "
                "standards' principles; it does not constitute formal certification or "
                "attestation.  The Approver is responsible for ensuring that their use "
                "of generated outputs meets applicable regulatory requirements in their "
                "jurisdiction."
            ),
            risk_level="high",
            applies_to_autonomy_classes=all_classes,
            binding=False,
        ))

        if requires_physical or autonomy_class in hybrid_classes:
            sections.append(EUASection(
                section_id=str(uuid.uuid4()),
                section_type=EUASectionType.CONTRACTOR_RESPONSIBILITY,
                title="6. Contractor Sole Responsibility",
                body=(
                    "Any contractor dispatched through the system to perform physical-world "
                    "tasks (inspection, notarization, filing, calibration, etc.) is an "
                    "independent professional solely responsible for their licensed work.  "
                    "The contractor's acceptance of a task constitutes their agreement to "
                    "perform the work in accordance with their professional license and the "
                    "applicable regulatory body's standards.  Inoni LLC is not liable for "
                    "any errors, omissions, or professional failures by dispatched contractors."
                ),
                risk_level="high",
                applies_to_autonomy_classes=hybrid_classes,
                binding=True,
            ))

        if requires_licensed:
            sections.append(EUASection(
                section_id=str(uuid.uuid4()),
                section_type=EUASectionType.CREDENTIAL_VERIFICATION,
                title="7. Credentialed Human-in-the-Loop Validation",
                body=(
                    "Activities requiring a certification, license, or regulatory body "
                    "oversight must be validated by a human professional holding the relevant "
                    "credential.  As part of their HITL acceptance, the validating professional "
                    "provides their credential information (license number, issuing body, "
                    "expiry date) which is recorded in the system.  By providing this "
                    "information and accepting the task, the professional: "
                    "(a) warrants that their credential is current and valid; "
                    "(b) accepts full professional responsibility for the regulated activity; "
                    "(c) agrees that any failure in their professional duty is their sole "
                    "liability and not that of Inoni LLC or Murphy System."
                ),
                risk_level="critical",
                applies_to_autonomy_classes=all_classes,
                binding=True,
            ))

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.DISPUTE_RESOLUTION,
            title="8. Dispute Resolution",
            body=(
                "Any dispute arising from a niche business operation shall first be "
                "referred to the HITL approver who authorised the relevant operation, "
                "as the recorded risk-accepting party.  Inoni LLC is not the primary "
                "respondent in disputes arising from approved automations.  All HITL "
                "approvals, COYA records, and negotiation documents are maintained as "
                "the definitive record of what was agreed, approved, and executed."
            ),
            risk_level="high",
            applies_to_autonomy_classes=all_classes,
            binding=False,
        ))

        sections.append(EUASection(
            section_id=str(uuid.uuid4()),
            section_type=EUASectionType.SHADOW_AGENT_IP,
            title="9. Murphy System Licence Grant, User Data Ownership, and Shadow Construct Forfeiture",
            body=(
                "Inoni LLC grants the User a limited, non-exclusive, non-transferable, "
                "revocable licence to access and use Murphy System.  The platform, all "
                "underlying technology, and the shadow agent engine remain Inoni LLC's "
                "exclusive intellectual property at all times; the User acquires no "
                "ownership interest in the platform by using it.  "
                "All data the User inputs into the system ('Input Data') and all output "
                "data generated by the system on the User's behalf ('Output Data') are "
                "and remain the User's exclusive property; Inoni LLC makes no IP claim "
                "over Input Data or Output Data.  "
                "Shadow Automation Constructs (workflow configurations built using the "
                "shadow agent) are system artifacts licensed to the User for active use.  "
                "Any construct not deployed in a production workflow within five (5) years "
                "of its creation date is automatically and irrevocably forfeited to Inoni "
                "LLC without compensation; user data that flowed through previously active "
                "constructs is not affected by this forfeiture.  "
                "Community forum content belongs exclusively to the posting user or their "
                "organisation; Inoni LLC makes no claim over forum ideas or discussions."
            ),
            risk_level="medium",
            applies_to_autonomy_classes=all_classes,
            binding=True,
        ))

        return sections

    def _build_risk_transfer_clauses(
        self,
        inoni_entity_name: str,
        autonomy_class: str,
        requires_licensed: bool,
    ) -> List[RiskTransferClause]:
        """Build risk transfer clauses for this niche."""
        clauses: List[RiskTransferClause] = []

        clauses.append(RiskTransferClause(
            clause_id=str(uuid.uuid4()),
            title="HITL Financial Risk Transfer",
            risk_being_transferred="Financial loss from deployment cost vs. revenue shortfall",
            from_party="inoni_llc",
            to_party="hitl_approver",
            trigger="HITL request approval with risk_accepted=True",
            text=(
                f"Upon approval of the {inoni_entity_name} HITL deployment request with "
                f"explicit risk acceptance, the total financial exposure (build cost vs. "
                f"projected revenue) is transferred to the approving operator. "
                f"Inoni LLC's liability is capped at the cost of Murphy's generation services."
            ),
        ))

        clauses.append(RiskTransferClause(
            clause_id=str(uuid.uuid4()),
            title="Automation Output Risk Transfer",
            risk_being_transferred="Accuracy and suitability of automated generated content",
            from_party="inoni_llc",
            to_party="hitl_approver",
            trigger="Approval of any generated output for delivery to end users",
            text=(
                "Generated content, documents, analyses, and reports are provided as-is.  "
                "By approving delivery of any generated output, the Approver accepts "
                "responsibility for its accuracy, suitability, and regulatory compliance "
                "for the intended use.  Murphy System's generation is the input to the "
                "Approver's professional judgment, not a substitute for it."
            ),
        ))

        if autonomy_class in ("hybrid", "legs_required"):
            clauses.append(RiskTransferClause(
                clause_id=str(uuid.uuid4()),
                title="Contractor Dispatch Risk Transfer",
                risk_being_transferred="Physical-world contractor task outcomes",
                from_party="inoni_llc",
                to_party="contractor",
                trigger="Contractor acceptance of a dispatched task",
                text=(
                    "By accepting a dispatched task and providing their credential "
                    "information, the contractor accepts sole responsibility for the "
                    "physical-world activity they perform.  The negotiation record and "
                    "COYA document constitute the binding scope of their responsibility."
                ),
            ))

        if requires_licensed:
            clauses.append(RiskTransferClause(
                clause_id=str(uuid.uuid4()),
                title="Regulatory Domain Risk Transfer",
                risk_being_transferred="Regulated professional activity outcomes",
                from_party="inoni_llc",
                to_party="credentialed_professional",
                trigger="Credentialed professional's acceptance of a task with credential provision",
                text=(
                    "The licensed/certified professional who accepts a regulated task "
                    "and provides their credential information takes on full professional "
                    "liability for that activity under their regulatory body's standards.  "
                    "Murphy System provides the framework and documentation; the professional "
                    "is responsible for all regulated acts within that framework."
                ),
            ))

        return clauses

    def _build_automation_requirements(
        self,
        autonomy_class: str,
        murphy_modules_required: List[str],
    ) -> List[AutomationRequirement]:
        """Build the automation requirements list for this niche."""
        requirements: List[AutomationRequirement] = []

        requirements.append(AutomationRequirement(
            requirement_id=str(uuid.uuid4()),
            description="Content and document generation via LLM + MSS pipeline",
            automation_type="generation",
            human_oversight_required=False,
            can_execute_autonomously=True,
            failure_mode="Generation fails → fallback to simplified output → HITL notified",
            recovery_action="Retry with simplified input; if persistent, escalate to HITL",
        ))

        requirements.append(AutomationRequirement(
            requirement_id=str(uuid.uuid4()),
            description="Niche business viability gate evaluation",
            automation_type="validation",
            human_oversight_required=False,
            can_execute_autonomously=True,
            failure_mode="Gate evaluation fails → NOT_DEPLOYABLE returned",
            recovery_action="Pipeline checkpoint triggers recovery; re-run from last safe stage",
        ))

        requirements.append(AutomationRequirement(
            requirement_id=str(uuid.uuid4()),
            description="HITL request creation and routing to operator",
            automation_type="dispatch",
            human_oversight_required=True,
            can_execute_autonomously=False,
            failure_mode="HITL not responded to → deployment paused; periodic reminder sent",
            recovery_action="Operator must act; system waits indefinitely with notifications",
        ))

        requirements.append(AutomationRequirement(
            requirement_id=str(uuid.uuid4()),
            description="Delivery of approved outputs to end users",
            automation_type="delivery",
            human_oversight_required=False,
            can_execute_autonomously=True,
            failure_mode="Delivery fails → retry 3× → escalate to HITL",
            recovery_action="Checkpoint restart from last verified delivery state",
        ))

        if autonomy_class in ("hybrid", "legs_required"):
            requirements.append(AutomationRequirement(
                requirement_id=str(uuid.uuid4()),
                description="Contractor bid solicitation and selection (internal)",
                automation_type="dispatch",
                human_oversight_required=False,
                can_execute_autonomously=True,
                failure_mode="No qualifying bids → HITL notified; manual contractor search required",
                recovery_action="Expand bid pool; lower qualification threshold with HITL approval",
            ))

            requirements.append(AutomationRequirement(
                requirement_id=str(uuid.uuid4()),
                description="Contractor task dispatch (external — post HITL only)",
                automation_type="dispatch",
                human_oversight_required=True,
                can_execute_autonomously=False,
                failure_mode="Dispatch fails → task remains pending; HITL notified",
                recovery_action="Re-dispatch to backup contractor; escalate to HITL if all fail",
            ))

        return requirements

    def _render_full_text(
        self,
        inoni_entity_name: str,
        sections: List[EUASection],
        risk_clauses: List[RiskTransferClause],
        automation_requirements: List[AutomationRequirement],
    ) -> str:
        """Render the complete agreement as a text document."""
        lines: List[str] = [
            "END USER AGREEMENT",
            f"{'=' * 60}",
            f"Entity: {inoni_entity_name}",
            "Powered by: Murphy System",
            "Operated by: Inoni Limited Liability Company",
            "License: BSL 1.1",
            "",
            "This End User Agreement ('Agreement') governs your use of the services",
            f"provided by {inoni_entity_name}, powered by Murphy System and operated",
            "by Inoni Limited Liability Company ('Inoni').",
            "",
        ]

        for section in sections:
            lines.extend([
                f"{section.title}",
                f"{'-' * len(section.title)}",
                section.body,
                "",
            ])

        lines.extend([
            "RISK TRANSFER CLAUSES",
            f"{'=' * 40}",
            "The following risk transfer clauses are binding upon HITL approval:",
            "",
        ])
        for clause in risk_clauses:
            lines.extend([
                f"[{clause.title}]",
                f"Risk transferred: {clause.risk_being_transferred}",
                f"From: {clause.from_party} → To: {clause.to_party}",
                f"Trigger: {clause.trigger}",
                clause.text,
                "",
            ])

        lines.extend([
            "AUTOMATION REQUIREMENTS",
            f"{'=' * 40}",
            "",
        ])
        for req in automation_requirements:
            oversight = "HITL required" if req.human_oversight_required else "Autonomous"
            lines.extend([
                f"[{oversight}] {req.description}",
                f"  Failure: {req.failure_mode}",
                f"  Recovery: {req.recovery_action}",
                "",
            ])

        lines.extend([
            f"{'=' * 60}",
            "BY APPROVING ANY HITL REQUEST ASSOCIATED WITH THIS AGREEMENT,",
            "YOU ACCEPT ALL TERMS, RISK TRANSFER CLAUSES, AND AUTOMATION",
            "REQUIREMENTS DESCRIBED HEREIN.",
            f"{'=' * 60}",
        ])

        return "\n".join(lines)
