"""
Signup Gateway — Murphy System

Implements signup, email validation, EULA acceptance, and user profile
management. Provides the UserProfile data model and backend logic for
the Part 1 requirements: Signup Gateway and Profile-Gated Terminals.

Design Principles:
  - HITL everywhere: no access until signup + email validation + EULA
  - Alpha disclaimer: BSL 1.1, no warranty
  - Ownership model: shadow automations → user IP, corporate → org IP
  - Thread-safe with bounded audit log

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import re
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

try:
    from thread_safe_operations import capped_append
except ImportError:
    def capped_append(target_list: list, item: Any, max_size: int = 10_000) -> None:
        """Fallback bounded append (CWE-770)."""
        if len(target_list) >= max_size:
            del target_list[: max_size // 10]
        target_list.append(item)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# PII Redaction Helpers
# ---------------------------------------------------------------------------

def _redact_email(email: str) -> str:
    """Redact email for safe logging: u***@domain.com."""
    if not email or "@" not in email:
        return "[REDACTED_EMAIL]"
    local, domain = email.split("@", 1)
    return f"{local[:1]}***@{domain}"


def _redact_ip(ip: str) -> str:
    """Redact IP address for safe logging: 192.168.xxx.xxx."""
    if not ip:
        return "[REDACTED_IP]"
    parts = ip.split(".")
    if len(parts) == 4:
        return f"{parts[0]}.{parts[1]}.xxx.xxx"
    return "[REDACTED_IP]"

# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

_EMAIL_RE = re.compile(
    r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$"
)

_PHONE_RE = re.compile(r"^\+\d{10,15}$|^\d{10,15}$")

_EMAIL_TOKEN_EXPIRY = timedelta(hours=24)

_OTP_EXPIRY = timedelta(minutes=10)

_OTP_MAX_ATTEMPTS = 5

_OTP_LOCKOUT_WINDOW = 300  # seconds

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EULA_VERSION = "1.1-alpha"

EULA_TEXT = """\
END USER AGREEMENT — MURPHY SYSTEM (ALPHA)
Version: {version}
Copyright © 2020 Inoni Limited Liability Company. All rights reserved worldwide.

IMPORTANT: READ CAREFULLY BEFORE PROCEEDING. THIS AGREEMENT CONTAINS BINDING
ARBITRATION, LIMITATION OF LIABILITY, AND INTELLECTUAL PROPERTY FORFEITURE
PROVISIONS THAT AFFECT YOUR LEGAL RIGHTS. IF YOU DO NOT AGREE, DO NOT USE THE
PLATFORM.

1. ALPHA SOFTWARE DISCLAIMER
   Murphy System is alpha software provided "AS IS" with NO WARRANTY OF ANY
   KIND, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE. Inoni LLC expressly
   disclaims all warranties, including but not limited to merchantability,
   fitness for a particular purpose, title, accuracy, quiet enjoyment, and
   non-infringement. Murphy System may contain bugs, errors, and incomplete
   features. OUTPUT GENERATED BY THE SYSTEM IS NOT PROFESSIONAL, LEGAL,
   FINANCIAL, MEDICAL, OR REGULATORY ADVICE. USE AT YOUR OWN RISK. No oral
   or written statements by Inoni LLC or its representatives create any
   warranty not stated herein.

2. LIABILITY SPLIT AND LIMITATIONS
   a. HITL Validators are solely and exclusively liable for every validation
      decision they make within the platform. The act of HITL approval is an
      affirmative legal act by the Validator.
   b. The subscribing Business or Organisation is solely liable for all
      business decisions, commercial actions, and downstream consequences
      arising from or in connection with Murphy System outputs.
   c. Inoni LLC's aggregate liability to any User for any and all claims
      arising under or in connection with this Agreement shall not exceed the
      greater of (i) the total fees paid by that User to Inoni LLC in the
      twelve (12) calendar months immediately preceding the claim, or
      (ii) one hundred United States dollars (USD 100.00).
   d. IN NO EVENT SHALL INONI LLC BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
      SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT
      NOT LIMITED TO LOSS OF PROFITS, LOSS OF REVENUE, LOSS OF DATA, LOSS
      OF GOODWILL, BUSINESS INTERRUPTION, OR COST OF SUBSTITUTE SERVICES,
      EVEN IF INONI LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
      THIS LIMITATION APPLIES TO ALL THEORIES OF LIABILITY INCLUDING
      CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, AND STATUTE.

3. DATA, LOGS, AND SYSTEM TELEMETRY
   a. All system logs, interaction data, API call telemetry, error reports,
      and aggregated usage statistics generated by your use of the platform
      are available to Inoni LLC for platform diagnostics, improvements,
      abuse prevention, and security monitoring.
   b. Individual user data is NOT sold, rented, or transferred to third
      parties for advertising, profiling, or commercial purposes unrelated
      to the operation of the platform.
   c. Free-tier users receive the same data-privacy protections as paid
      users. Inoni LLC does not engage in predatory data monetisation
      practices against free-tier users. Free-tier community spaces are
      operated on a non-extractive basis consistent with the principles of
      open collaborative platforms.

4. INTELLECTUAL PROPERTY — LICENCE GRANT, USER DATA, AND SYSTEM OWNERSHIP
   a. Licence Grant: Subject to your acceptance of and compliance with this
      Agreement, Inoni LLC grants you a limited, non-exclusive,
      non-transferable, revocable licence to access and use Murphy System
      solely for your own internal business or personal purposes. No rights
      are granted except as expressly stated in this Agreement.
   b. System IP — Inoni Ownership: Murphy System, all underlying and future
      technology, algorithms, AI models, shadow agent engine, automation
      frameworks, code, interfaces, brand assets, and the Murphy System design
      language are and shall remain the exclusive intellectual property of
      Inoni LLC. All rights reserved worldwide under applicable copyright,
      trade secret, patent, and trademark law. You acquire no ownership
      interest in the platform by using it.
   c. Your Data — User Ownership: All data you input into Murphy System
      ("Input Data") and all output data generated by the system on your
      behalf ("Output Data") are and remain your exclusive property. Inoni
      LLC makes no claim of intellectual property ownership over your Input
      Data or Output Data. Inoni LLC's right to process your data is limited
      to what is necessary to operate the platform as described in Section 3
      and the Privacy Policy.
   d. Shadow Automation Constructs: Workflow configurations and automation
      templates you build using the shadow agent ("Shadow Automation
      Constructs") are system artifacts created on top of Inoni's licensed
      platform. You are granted a licence to use, operate, and modify your
      Shadow Automation Constructs for as long as your account is active and
      the construct is deployed in a production workflow. The underlying
      system technology that powers those constructs remains Inoni's
      exclusive property at all times.
   e. Forfeiture of Unmade Automation Constructs: Any Shadow Automation
      Construct that has not been deployed or activated in a production
      workflow within five (5) years of its creation date ("Unmade
      Construct") is automatically and irrevocably forfeited to Inoni LLC
      upon expiry of that five-year period, without any further notice or
      compensation. Upon forfeiture, the licence for that construct
      terminates and Inoni LLC may use, develop, or commercialise the
      Unmade Construct without restriction. User data that flowed through
      any previously active constructs is not affected by this forfeiture.
   f. Corporate and Org-Chart Automation Constructs: Automation constructs
      created within an organisation's workspace are licensed to that
      organisation and are subject to the same five-year forfeiture clause
      for Unmade Constructs under section 4(exc) above.
   g. Community Forum Content: Posts, discussions, ideas, and content
      submitted to community forums or group spaces belong exclusively to
      the user or their organisation/group. Inoni LLC makes no claim of
      ownership over community forum content. Community spaces are operated
      on a non-extractive basis and Inoni LLC will not commercialise or
      appropriate individual users' forum ideas.
   h. Feedback Submitted Directly to Inoni: Suggestions, bug reports, and
      improvement requests submitted directly to Inoni LLC through official
      support or feedback channels (not community forums) grant Inoni LLC a
      perpetual, irrevocable, worldwide, royalty-free, sublicensable licence
      to use, incorporate, and build upon that feedback to improve the
      Service without any obligation of attribution or compensation.

5. ACCESS CONDITIONS
   Access to any Murphy System terminal or authenticated service requires:
   - Completed signup with accurate and current contact information
   - Email address validation
   - Acceptance of this End User Agreement
   - Ongoing compliance with all terms herein
   Inoni LLC reserves the right to suspend or terminate access for
   breach of any provision of this Agreement, immediately and without
   notice where required for security or legal compliance.

6. GENERAL PROVISIONS
   a. Governing Law and Jurisdiction: This Agreement is governed by and
      construed in accordance with the laws of the State of Delaware,
      United States of America, without regard to conflict-of-law
      principles. For users located in the European Union or United
      Kingdom, mandatory consumer-protection provisions of applicable
      local law are not excluded by this choice-of-law clause.
   b. Dispute Resolution and Binding Arbitration: Except for claims that
      qualify for small-claims court, all disputes arising out of or
      relating to this Agreement shall be resolved by binding arbitration
      administered by the American Arbitration Association ("AAA") under
      its Commercial Arbitration Rules. Arbitration shall take place in
      Delaware, USA, or by remote hearing. The arbitrator's award shall
      be final and binding and may be entered as a judgment in any court
      of competent jurisdiction. CLASS ACTION WAIVER: You waive any right
      to bring or participate in a class-action lawsuit or class-wide
      arbitration against Inoni LLC.
   c. Severability: If any provision of this Agreement is held invalid,
      illegal, or unenforceable by a court or arbitrator of competent
      jurisdiction, that provision shall be limited or eliminated to the
      minimum extent necessary, and the remaining provisions shall remain
      in full force and effect.
   d. No Waiver: Inoni LLC's failure to enforce any right or provision of
      this Agreement does not constitute a waiver of that right or
      provision. A waiver is effective only if made in writing signed by an
      authorised representative of Inoni LLC.
   e. Entire Agreement: This Agreement, together with the Privacy Policy and
      any applicable Order Form, constitutes the entire agreement between
      you and Inoni LLC with respect to the subject matter hereof and
      supersedes all prior and contemporaneous agreements, representations,
      and understandings.
   f. Language: This Agreement is written in English. Translated versions
      are provided for convenience only. In the event of any conflict
      between the English version and a translation, the English version
      controls.
   g. Updates to This Agreement: Inoni LLC may update this Agreement at any
      time. Material changes will be communicated via in-platform notice or
      email at least 14 days before taking effect for existing users. Your
      continued use of the platform after the effective date of any update
      constitutes acceptance of the revised Agreement. If you do not agree
      to an update, your sole remedy is to discontinue use and close your
      account.

By clicking "I Accept" you acknowledge that you have read, understood, and
agree to be bound by this End User Agreement in its entirety.
""".format(version=EULA_VERSION)

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class UserProfile:
    """Complete user profile created during onboarding signup."""

    user_id: str = field(default_factory=lambda: uuid.uuid4().hex[:16])
    email: str = ""
    name: str = ""
    position: str = ""
    department: str = ""
    employee_letter: str = ""      # text content or file reference
    justification: str = ""
    org_id: str = ""
    role: str = "worker"           # "founder_admin" | "manager" | "worker"
    shadow_agent_id: str = ""      # assigned after onboarding
    eula_accepted: bool = False
    eula_version: str = ""
    eula_accepted_at: str = ""
    email_validated: bool = False
    email_validation_token: str = field(
        default_factory=lambda: uuid.uuid4().hex
    )
    email_validation_token_created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    phone: str = ""
    phone_validated: bool = False
    phone_validation_code: str = ""
    phone_otp_created_at: str = ""
    terminal_config: Dict[str, Any] = field(default_factory=dict)
    preferred_terminal: str = ""  # saved from onboarding dashboard selection
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    updated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain-dict representation of the signup request."""
        return {
            "user_id": self.user_id,
            "email": self.email,
            "name": self.name,
            "position": self.position,
            "department": self.department,
            "employee_letter": self.employee_letter,
            "justification": self.justification,
            "org_id": self.org_id,
            "role": self.role,
            "shadow_agent_id": self.shadow_agent_id,
            "eula_accepted": self.eula_accepted,
            "eula_version": self.eula_version,
            "eula_accepted_at": self.eula_accepted_at,
            "email_validated": self.email_validated,
            "phone": self.phone,
            "phone_validated": self.phone_validated,
            "terminal_config": self.terminal_config,
            "preferred_terminal": self.preferred_terminal,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    def is_fully_onboarded(self) -> bool:
        """Return True only when signup, email validation, and EULA are done."""
        return self.email_validated and self.eula_accepted


@dataclass
class Organization:
    """An organization in the Murphy System account plane."""

    org_id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    name: str = ""
    founder_user_id: str = ""
    member_ids: List[str] = field(default_factory=list)
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain-dict representation of the organisation record."""
        return {
            "org_id": self.org_id,
            "name": self.name,
            "founder_user_id": self.founder_user_id,
            "member_ids": self.member_ids,
            "created_at": self.created_at,
        }


@dataclass
class EulaRecord:
    """Immutable record of a user's EULA acceptance."""

    record_id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    user_id: str = ""
    eula_version: str = EULA_VERSION
    accepted_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    ip_address: str = ""
    user_agent: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain-dict representation of the EULA acceptance record."""
        return {
            "record_id": self.record_id,
            "user_id": self.user_id,
            "eula_version": self.eula_version,
            "accepted_at": self.accepted_at,
            "ip_address": self.ip_address,
            "user_agent": self.user_agent,
        }


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class SignupError(Exception):
    """Raised when signup validation fails."""


class AuthError(Exception):
    """Raised when authentication/authorization fails."""


# ---------------------------------------------------------------------------
# SignupGateway
# ---------------------------------------------------------------------------

_MAX_AUDIT_LOG = 10_000


class SignupGateway:
    """Backend logic for signup, email validation, EULA, and profiles.

    All public methods are thread-safe. The audit log is bounded to
    prevent unbounded memory growth.

    Usage::

        gw = SignupGateway()
        profile = gw.signup(
            name="Alice",
            email="alice@example.com",
            position="Engineer",
            justification="Need to automate CI",
            new_org_name="Acme Corp",
        )
        gw.validate_email(profile.user_id, profile.email_validation_token)
        gw.accept_eula(profile.user_id, ip_address="127.0.0.1")
        assert gw.get_profile(profile.user_id).is_fully_onboarded()
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._profiles: Dict[str, UserProfile] = {}
        self._orgs: Dict[str, Organization] = {}
        self._eula_records: Dict[str, EulaRecord] = {}  # user_id → record
        self._audit_log: List[Dict[str, Any]] = []
        self._otp_attempts: Dict[str, List[float]] = {}  # user_id → [timestamps]
        self._otp_lockouts: Dict[str, float] = {}  # user_id → lockout_until

    # ------------------------------------------------------------------
    # Signup
    # ------------------------------------------------------------------

    def signup(
        self,
        name: str,
        email: str,
        position: str,
        justification: str,
        department: str = "",
        employee_letter: str = "",
        org_id: Optional[str] = None,
        new_org_name: Optional[str] = None,
        phone: Optional[str] = None,
    ) -> UserProfile:
        """Create a new user account.

        Either ``org_id`` (join existing) or ``new_org_name`` (create new)
        must be provided.  When creating a new org the user becomes the
        ``founder_admin``.
        """
        if not name or not name.strip():
            raise SignupError("name is required")
        if not email or not email.strip():
            raise SignupError("email is required")
        if not _EMAIL_RE.match(email.strip()):
            raise SignupError("invalid email format")
        if not position or not position.strip():
            raise SignupError("position is required")
        if not justification or not justification.strip():
            raise SignupError("justification is required")
        if org_id is None and not new_org_name:
            raise SignupError("org_id or new_org_name is required")

        with self._lock:
            # Duplicate email check
            for p in self._profiles.values():
                if p.email.lower() == email.lower().strip():
                    raise SignupError("email already registered")

            role = "worker"
            resolved_org_id = org_id or ""

            if new_org_name:
                org = Organization(name=new_org_name.strip())
                role = "founder_admin"
                resolved_org_id = org.org_id
                self._orgs[org.org_id] = org

            profile = UserProfile(
                name=name.strip(),
                email=email.lower().strip(),
                position=position.strip(),
                department=department.strip(),
                employee_letter=employee_letter,
                justification=justification.strip(),
                org_id=resolved_org_id,
                role=role,
                phone=phone.strip() if phone else "",
            )

            if new_org_name:
                self._orgs[resolved_org_id].founder_user_id = profile.user_id
                self._orgs[resolved_org_id].member_ids.append(profile.user_id)
            elif org_id and org_id in self._orgs:
                self._orgs[org_id].member_ids.append(profile.user_id)

            self._profiles[profile.user_id] = profile
            self._audit("signup", profile.user_id, {"email": _redact_email(profile.email), "role": role})

        logger.info("Signup: user_id=%s email=%s role=%s", profile.user_id, _redact_email(profile.email), role)
        return profile

    # ------------------------------------------------------------------
    # Email validation
    # ------------------------------------------------------------------

    def validate_email(self, user_id: str, token: str) -> UserProfile:
        """Validate the email token for a user.

        Tokens expire after 24 hours.  Uses constant-time comparison
        to prevent timing-based token guessing.
        """
        with self._lock:
            profile = self._profiles.get(user_id)
            if profile is None:
                raise AuthError("user not found")
            if profile.email_validated:
                return profile
            # Check token expiry
            if profile.email_validation_token_created_at:
                created = datetime.fromisoformat(profile.email_validation_token_created_at)
                if datetime.now(timezone.utc) - created > _EMAIL_TOKEN_EXPIRY:
                    raise AuthError("email validation token has expired")
            if not hmac.compare_digest(profile.email_validation_token, token):
                raise AuthError("invalid email validation token")
            profile.email_validated = True
            profile.updated_at = datetime.now(timezone.utc).isoformat()
            self._audit("validate_email", user_id, {})

        logger.info("Email validated: user_id=%s", user_id)
        return profile

    # ------------------------------------------------------------------
    # Phone OTP
    # ------------------------------------------------------------------

    def send_phone_otp(self, user_id: str) -> str:
        """Generate and store a 6-digit OTP for phone verification.

        Returns the OTP code (in production this would be sent via SMS,
        e.g. through the Twilio API).  Validates phone number format
        (E.164 / 10–15 digit) before generating.
        """
        import random
        otp = f"{random.randint(0, 999999):06d}"
        with self._lock:
            profile = self._profiles.get(user_id)
            if profile is None:
                raise AuthError("user not found")
            if not profile.phone:
                raise SignupError("no phone number on file")
            if not _PHONE_RE.match(profile.phone):
                raise SignupError("invalid phone number format")
            profile.phone_validation_code = otp
            profile.phone_otp_created_at = datetime.now(timezone.utc).isoformat()
            profile.updated_at = datetime.now(timezone.utc).isoformat()
            self._otp_attempts.pop(user_id, None)
            self._otp_lockouts.pop(user_id, None)
            self._audit("send_phone_otp", user_id, {})

        # Production: call Twilio here, e.g.:
        #   twilio_client.messages.create(to=profile.phone, body=f"Your Murphy OTP: {otp}", ...)
        logger.info("Phone OTP generated: user_id=%s", user_id)
        return otp

    def validate_phone(self, user_id: str, otp: str) -> UserProfile:
        """Verify the 6-digit OTP and mark the phone number as validated.

        Hardening:
        - Constant-time comparison via ``hmac.compare_digest``
        - OTP expires after 10 minutes
        - Max 5 failed attempts before 5-minute lockout
        """
        now = time.time()
        with self._lock:
            profile = self._profiles.get(user_id)
            if profile is None:
                raise AuthError("user not found")

            # Check lockout
            lockout_until = self._otp_lockouts.get(user_id, 0.0)
            if now < lockout_until:
                raise AuthError("too many failed OTP attempts — try again later")

            if not profile.phone:
                raise SignupError("no phone number on file")
            if not profile.phone_validation_code:
                raise AuthError("no OTP issued — call send_phone_otp first")

            # Check OTP expiry
            if profile.phone_otp_created_at:
                created = datetime.fromisoformat(profile.phone_otp_created_at)
                if datetime.now(timezone.utc) - created > _OTP_EXPIRY:
                    profile.phone_validation_code = ""
                    raise AuthError("OTP has expired — request a new one")

            if not hmac.compare_digest(profile.phone_validation_code, otp):
                attempts = self._otp_attempts.setdefault(user_id, [])
                attempts.append(now)
                # Prune old attempts outside the window
                attempts[:] = [t for t in attempts if now - t < _OTP_LOCKOUT_WINDOW]
                if len(attempts) >= _OTP_MAX_ATTEMPTS:
                    self._otp_lockouts[user_id] = now + _OTP_LOCKOUT_WINDOW
                    logger.warning("OTP lockout triggered: user_id=%s", user_id)
                raise AuthError("invalid phone OTP")

            profile.phone_validated = True
            profile.phone_validation_code = ""
            profile.phone_otp_created_at = ""
            profile.updated_at = datetime.now(timezone.utc).isoformat()
            self._otp_attempts.pop(user_id, None)
            self._otp_lockouts.pop(user_id, None)
            self._audit("validate_phone", user_id, {})

        logger.info("Phone validated: user_id=%s", user_id)
        return profile

    # ------------------------------------------------------------------
    # EULA
    # ------------------------------------------------------------------

    def get_eula(self) -> Dict[str, str]:
        """Return the current EULA text and version."""
        return {"version": EULA_VERSION, "text": EULA_TEXT}

    def accept_eula(
        self,
        user_id: str,
        ip_address: str = "",
        user_agent: str = "",
    ) -> EulaRecord:
        """Record that the user has accepted the EULA."""
        with self._lock:
            profile = self._profiles.get(user_id)
            if profile is None:
                raise AuthError("user not found")
            if not profile.email_validated:
                raise AuthError("email must be validated before accepting EULA")

            record = EulaRecord(
                user_id=user_id,
                eula_version=EULA_VERSION,
                ip_address=ip_address,
                user_agent=user_agent,
            )
            profile.eula_accepted = True
            profile.eula_version = EULA_VERSION
            profile.eula_accepted_at = record.accepted_at
            profile.updated_at = record.accepted_at
            self._eula_records[user_id] = record
            self._audit("accept_eula", user_id, {"version": EULA_VERSION, "ip": _redact_ip(ip_address)})

        logger.info("EULA accepted: user_id=%s version=%s", user_id, EULA_VERSION)
        return record

    # ------------------------------------------------------------------
    # Profile management
    # ------------------------------------------------------------------

    def get_profile(self, user_id: str) -> UserProfile:
        """Return a user's profile (raises AuthError if not found)."""
        with self._lock:
            profile = self._profiles.get(user_id)
        if profile is None:
            raise AuthError("user not found")
        return profile

    def update_profile(
        self,
        user_id: str,
        updates: Dict[str, Any],
    ) -> UserProfile:
        """Apply a dict of updates to the user's profile."""
        _IMMUTABLE = {"user_id", "email", "created_at", "email_validation_token"}
        with self._lock:
            profile = self._profiles.get(user_id)
            if profile is None:
                raise AuthError("user not found")
            for key, value in updates.items():
                if key in _IMMUTABLE:
                    continue
                if hasattr(profile, key):
                    setattr(profile, key, value)
            profile.updated_at = datetime.now(timezone.utc).isoformat()
            self._audit("update_profile", user_id, {"fields": list(updates.keys())})
        return profile

    def get_org_profiles(self, org_id: str) -> List[UserProfile]:
        """Return all profiles belonging to an org."""
        with self._lock:
            return [p for p in self._profiles.values() if p.org_id == org_id]

    # ------------------------------------------------------------------
    # Terminal config
    # ------------------------------------------------------------------

    def assemble_terminal_config(self, user_id: str) -> Dict[str, Any]:
        """Assemble a terminal_config for the user based on their profile.

        Murphy infers which features to expose based on the user's position,
        department, role, and employee letter.  In production this would
        invoke an LLM planning pass; here we provide rule-based inference.
        """
        with self._lock:
            profile = self._profiles.get(user_id)
        if profile is None:
            raise AuthError("user not found")
        if not profile.is_fully_onboarded():
            raise AuthError("user is not fully onboarded")

        config: Dict[str, Any] = {
            "user_id": user_id,
            "role": profile.role,
            "features": {},
            "commands": [],
            "assembled_at": datetime.now(timezone.utc).isoformat(),
        }

        # Founder/admin gets full access
        if profile.role == "founder_admin":
            config["features"] = {
                "architect_terminal": True,
                "org_chart_editor": True,
                "user_management": True,
                "shadow_agent_config": True,
                "automation_library": True,
                "analytics_dashboard": True,
                "audit_log_viewer": True,
            }
            config["commands"] = ["*"]
        elif profile.role in ("admin", "org_admin"):
            config["features"] = {
                "architect_terminal": True,
                "org_chart_editor": True,
                "system_config": True,
                "compliance_dashboard": True,
                "full_audit_log": True,
            }
            config["terminal_path"] = "/ui/terminal-architect"
            config["commands"] = ["configure_system", "manage_org", "view_compliance", "audit"]
        elif profile.role in ("manager", "team_lead"):
            config["features"] = {
                "worker_terminal": True,
                "enhanced_terminal": True,
                "team_dashboard": True,
                "project_oversight": True,
                "hitl_review": True,
                "schedule_view": True,
                "automation_library": True,
                "analytics_dashboard": True,
                "shadow_agent_config": False,
            }
            config["terminal_path"] = "/ui/terminal-enhanced"
            config["commands"] = ["run", "status", "report", "assign",
                                   "manage_team", "review_outputs", "view_schedule", "approve"]
        elif profile.role == "employee":
            config["features"] = {
                "worker_terminal": True,
                "task_queue": True,
                "personal_deliverables": True,
                "chat_support": True,
            }
            config["terminal_path"] = "/ui/terminal-worker"
            config["commands"] = ["submit_work", "view_tasks", "chat"]
        elif profile.role in ("worker", "employee", "staff"):
            pos_lower = profile.position.lower()
            config["features"] = {
                "task_inbox": True,
                "deliverable_viewer": True,
                "time_tracker": True,
                "automation_library": "engineer" in pos_lower or "developer" in pos_lower,
                "analytics_dashboard": "analyst" in pos_lower,
            }
            config["terminal_path"] = "/ui/terminal-worker"
            config["commands"] = ["run", "submit_work", "view_tasks", "clock_in", "status"]
        elif profile.role in ("manager", "team_lead", "supervisor"):
            config["features"] = {
                "team_dashboard": True,
                "project_oversight": True,
                "approval_queue": True,
                "schedule_editor": True,
            }
            config["terminal_path"] = "/ui/terminal-enhanced"
            config["commands"] = ["approve", "assign", "review", "schedule"]
        elif profile.role in ("admin", "org_admin", "system_admin"):
            config["features"] = {
                "architect_terminal": True,
                "org_chart_editor": True,
                "system_config": True,
                "user_management": True,
                "compliance_dashboard": True,
            }
            config["terminal_path"] = "/ui/terminal-architect"
            config["commands"] = ["configure", "manage_users", "audit", "deploy"]
        else:
            # Fallback — infer from position text
            pos_lower = profile.position.lower()
            config["features"] = {
                "worker_terminal": True,
                "task_queue": True,
                "personal_deliverables": True,
                "chat_support": True,
                "automation_library": "engineer" in pos_lower or "developer" in pos_lower,
                "analytics_dashboard": "analyst" in pos_lower,
                "shadow_agent_config": False,
            }
            config["commands"] = ["run", "status", "submit_work", "view_tasks", "chat"]

        # Add recommended_terminal and allowed_terminals based on role
        if profile.role == "founder_admin":
            config["recommended_terminal"] = "/ui/terminal-unified"
            config["allowed_terminals"] = [
                "/ui/terminal-unified",
                "/ui/terminal-worker",
                "/ui/terminal-enhanced",
                "/ui/terminal-architect",
            ]
        elif profile.role in ("admin", "org_admin", "system_admin"):
            config["recommended_terminal"] = "/ui/terminal-architect"
            config["allowed_terminals"] = [
                "/ui/terminal-architect",
                "/ui/terminal-enhanced",
                "/ui/terminal-worker",
            ]
        elif profile.role in ("manager", "team_lead", "supervisor"):
            config["recommended_terminal"] = "/ui/terminal-enhanced"
            config["allowed_terminals"] = [
                "/ui/terminal-enhanced",
                "/ui/terminal-worker",
            ]
        elif profile.role in ("admin", "org_admin"):
            config["recommended_terminal"] = "/ui/terminal-architect"
            config["allowed_terminals"] = [
                "/ui/terminal-architect",
                "/ui/terminal-enhanced",
                "/ui/terminal-unified",
            ]
        elif profile.role in ("worker", "employee"):
            config["recommended_terminal"] = "/ui/terminal-worker"
            config["allowed_terminals"] = ["/ui/terminal-worker"]
        else:
            # Default — unified dashboard
            config["recommended_terminal"] = "/ui/terminal-unified"
            config["allowed_terminals"] = ["/ui/terminal-unified", "/ui/terminal-worker"]

        # Resolve terminal_path: honour user preference when it is allowed,
        # otherwise fall back to role default or recommended.
        if profile.preferred_terminal and profile.preferred_terminal in config["allowed_terminals"]:
            config["terminal_path"] = profile.preferred_terminal
        elif "terminal_path" not in config:
            config["terminal_path"] = config["recommended_terminal"]
        elif profile.role in ("worker", "employee", "staff"):
            config["recommended_terminal"] = "/ui/terminal-worker"
            config["allowed_terminals"] = ["/ui/terminal-worker"]
        else:
            # Legacy "manager" role kept for backwards-compat
            config["recommended_terminal"] = "/ui/terminal-enhanced"
            config["allowed_terminals"] = [
                "/ui/terminal-enhanced",
                "/ui/terminal-worker",
            ]

        # If the user has saved a preferred terminal, honour it when permitted
        if profile.preferred_terminal and profile.preferred_terminal in config.get("allowed_terminals", []):
            config["recommended_terminal"] = profile.preferred_terminal

        # Save back into profile
        with self._lock:
            self._profiles[user_id].terminal_config = config
            self._audit("assemble_terminal_config", user_id, {"role": profile.role})

        return config

    def set_dashboard_preference(self, user_id: str, terminal_path: str) -> None:
        """Save the user's preferred dashboard/terminal from onboarding."""
        with self._lock:
            profile = self._profiles.get(user_id)
        if profile is None:
            raise AuthError("user not found")
        profile.preferred_terminal = terminal_path
        capped_append(self._audit_log, {
            "event": "dashboard_preference_set",
            "user_id": user_id,
            "terminal_path": terminal_path,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })
        """Save user's preferred dashboard/terminal from onboarding."""
        with self._lock:
            profile = self._profiles.get(user_id)
            if profile is None:
                raise AuthError("user not found")
            profile.preferred_terminal = terminal_path
            capped_append(self._audit_log, {
                "event": "dashboard_preference_set",
                "user_id": user_id,
                "terminal_path": terminal_path,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    # ------------------------------------------------------------------
    # Session / auth check
    # ------------------------------------------------------------------

    def check_terminal_access(self, user_id: str, terminal_path: str = "") -> Dict[str, Any]:
        """Return access status for a user trying to open a terminal.

        Returns::
            {"allowed": bool, "reason": str, "profile": dict | None}
        """
        try:
            profile = self.get_profile(user_id)
        except AuthError:
            return {"allowed": False, "reason": "user_not_found", "profile": None}

        if not profile.email_validated:
            return {
                "allowed": False,
                "reason": "email_not_validated",
                "profile": profile.to_dict(),
            }
        if not profile.eula_accepted:
            return {
                "allowed": False,
                "reason": "eula_not_accepted",
                "profile": profile.to_dict(),
            }

        # If a specific terminal is requested, validate role-based access
        if terminal_path:
            tc = self.assemble_terminal_config(user_id)
            if terminal_path not in tc.get("allowed_terminals", []):
                return {
                    "allowed": False,
                    "reason": "terminal_not_permitted_for_role",
                    "profile": profile.to_dict(),
                    "allowed_terminals": tc.get("allowed_terminals", []),
                }

        return {"allowed": True, "reason": "ok", "profile": profile.to_dict()}

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _audit(self, action: str, user_id: str, details: Dict[str, Any]) -> None:
        entry = {
            "action": action,
            "user_id": user_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **details,
        }
        capped_append(self._audit_log, entry, max_size=_MAX_AUDIT_LOG)

    def get_audit_log(self) -> List[Dict[str, Any]]:
        """Return a copy of the audit log."""
        with self._lock:
            return list(self._audit_log)
