"""
Enhanced System Librarian
Maintains transcript logs, generates documentation, and manages system knowledge
Provides complete system understanding from any module's perspective
"""

import json
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger("system_librarian")


class DocumentType(Enum):
    """Types of documents generated by librarian"""
    TRANSCRIPT = "transcript"
    TECHNICAL_DOC = "technical_documentation"
    API_REFERENCE = "api_reference"
    USER_MANUAL = "user_manual"
    MODULE_GUIDE = "module_guide"
    REPORT = "report"
    AUDIT_LOG = "audit_log"


@dataclass
class TranscriptEntry:
    """Single entry in system transcript"""
    entry_id: str
    timestamp: str
    module: str
    action: str
    details: Dict[str, Any]
    actor: str  # user or bot_id
    success: bool
    duration_ms: Optional[int] = None

    def to_dict(self) -> Dict:
        return {
            "entry_id": self.entry_id,
            "timestamp": self.timestamp,
            "module": self.module,
            "action": self.action,
            "details": self.details,
            "actor": self.actor,
            "success": self.success,
            "duration_ms": self.duration_ms
        }


@dataclass
class SystemKnowledge:
    """Knowledge entry about system aspect"""
    knowledge_id: str
    category: str
    topic: str
    description: str
    related_modules: List[str]
    related_functions: List[str]
    references: List[str]
    created_at: str
    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict:
        return {
            "knowledge_id": self.knowledge_id,
            "category": self.category,
            "topic": self.topic,
            "description": self.description,
            "related_modules": self.related_modules,
            "related_functions": self.related_functions,
            "references": self.references,
            "created_at": self.created_at,
            "updated_at": self.updated_at
        }


@dataclass
class GeneratedDocument:
    """Document generated by librarian"""
    doc_id: str
    doc_type: DocumentType
    title: str
    content: str
    format: str  # markdown, html, json
    metadata: Dict[str, Any]
    created_at: str
    version: str = "1.0"

    def to_dict(self) -> Dict:
        return {
            "doc_id": self.doc_id,
            "doc_type": self.doc_type.value,
            "title": self.title,
            "content": self.content,
            "format": self.format,
            "metadata": self.metadata,
            "created_at": self.created_at,
            "version": self.version
        }


class SystemLibrarian:
    """
    Enhanced system librarian
    Maintains complete transcript logs and generates documentation
    Provides system understanding from any module's perspective
    """

    def __init__(self):
        self.transcripts: List[TranscriptEntry] = []
        self.knowledge_base: Dict[str, SystemKnowledge] = {}
        self.documents: Dict[str, GeneratedDocument] = {}

        self.entry_count = 0
        self.knowledge_count = 0
        self.doc_count = 0

        # Initialize system knowledge
        self._initialize_system_knowledge()

        # Module function mappings
        self.module_functions = self._load_module_functions()

        # Module capabilities
        self.module_capabilities = self._load_module_capabilities()

    def _initialize_system_knowledge(self):
        """Initialize system knowledge base"""
        knowledge_entries = [
            {
                "category": "expert_generation",
                "topic": "Dynamic Expert Generation",
                "description": "System automatically generates domain experts based on requirements using templates and LLM prompts",
                "related_modules": ["dynamic_expert_generator"],
                "related_functions": ["generate_expert", "generate_expert_team"],
                "references": ["expert_templates", "domain_knowledge"]
            },
            {
                "category": "gate_generation",
                "topic": "Domain Gate Generation",
                "description": "System generates safety gates with wired functions based on domain requirements and librarian knowledge",
                "related_modules": ["domain_gate_generator"],
                "related_functions": ["generate_gate", "generate_gates_for_system"],
                "references": ["gate_templates", "wired_functions"]
            },
            {
                "category": "constraint_management",
                "topic": "Multi-Factor Constraint System",
                "description": "Manages budget, regulatory, architectural constraints with validation and conflict resolution",
                "related_modules": ["constraint_system"],
                "related_functions": ["add_constraint", "validate_constraints"],
                "references": ["constraint_templates", "validation_engine"]
            },
            {
                "category": "document_processing",
                "topic": "Design Document Processing",
                "description": "Uploads design documents, extracts requirements, selects equipment, generates triggers",
                "related_modules": ["document_processor"],
                "related_functions": ["upload_document", "get_document_summary"],
                "references": ["equipment_catalog", "trigger_templates"]
            },
            {
                "category": "reasoning",
                "topic": "Inquisitory Choice Engine",
                "description": "Uses deductive reasoning and statistical knowledge to provide recommendations and analyze choices",
                "related_modules": ["inquisitory_engine"],
                "related_functions": ["analyze_choice", "deductive_reasoning"],
                "references": ["decision_trees", "organization_patterns"]
            },
            {
                "category": "llm_integration",
                "topic": "LLM Integration Layer",
                "description": "Coordinates Aristotle (deterministic), Wulfrum (fuzzy), and Groq (generative) APIs with domain routing",
                "related_modules": ["llm_integration_layer"],
                "related_functions": ["route_request", "validate_response"],
                "references": ["domain_routing", "validation_triggers"]
            },
            {
                "category": "system_integration",
                "topic": "System Integrator",
                "description": "Wires all components together and provides unified API for frontend interaction",
                "related_modules": ["system_integrator"],
                "related_functions": ["process_user_request", "get_system_state"],
                "references": ["all_modules", "request_routing"]
            },
            {
                "category": "bot_management",
                "topic": "Bot Inventory Library",
                "description": "Manages bot spawning, despawning, lifecycle, and capabilities with complete inventory",
                "related_modules": ["bot_inventory_library"],
                "related_functions": ["spawn_bot", "despawn_bot", "get_bot_inventory"],
                "references": ["bot_templates", "capability_registry"]
            },
            {
                "category": "audit",
                "topic": "Contractual Audit System",
                "description": "Detects productivity flow gaps, creates contractual agreements, monitors agent drift",
                "related_modules": ["contractual_audit"],
                "related_functions": ["audit_productivity", "generate_contract", "monitor_agent_drift"],
                "references": ["org_statistics", "gap_thresholds"]
            },
            {
                "category": "engineering_drawing",
                "topic": "Murphy Drawing Engine",
                "description": "Vector drawing engine for engineering drawings with SVG/DXF export, BOM extraction, parametric constraints, and natural-language agentic drawing commands",
                "related_modules": ["murphy_drawing_engine"],
                "related_functions": ["export_svg", "export_dxf", "extract_bom", "execute_command"],
                "references": ["drawing_projects", "engineering_symbols", "sheet_sizes"]
            },
            {
                "category": "engineering_toolbox",
                "topic": "Murphy Engineering Toolbox",
                "description": "Developer utilities for engineering workflows: schema scaffolding, stub generation, diff tools, and engineering calculation helpers",
                "related_modules": ["murphy_engineering_toolbox"],
                "related_functions": ["scaffold_schema", "generate_stub", "diff_schemas"],
                "references": ["engineering_schemas", "stub_templates"]
            }
        ]

        for entry in knowledge_entries:
            self.knowledge_count += 1
            knowledge = SystemKnowledge(
                knowledge_id=f"know_{self.knowledge_count}",
                category=entry["category"],
                topic=entry["topic"],
                description=entry["description"],
                related_modules=entry["related_modules"],
                related_functions=entry["related_functions"],
                references=entry["references"],
                created_at=datetime.now(timezone.utc).isoformat()
            )
            self.knowledge_base[knowledge.knowledge_id] = knowledge

    def _load_module_functions(self) -> Dict[str, Dict]:
        """Load all module functions"""
        return {
            "dynamic_expert_generator": {
                "generate_expert": {
                    "description": "Generate a single expert",
                    "parameters": ["title", "domain", "level", "specializations"],
                    "returns": "GeneratedExpert",
                    "help_visible": True,
                    "coupled": True
                },
                "generate_expert_team": {
                    "description": "Generate a team of experts",
                    "parameters": ["requirements", "budget"],
                    "returns": "Tuple[List[GeneratedExpert], Dict]",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "domain_gate_generator": {
                "generate_gate": {
                    "description": "Generate a single domain gate",
                    "parameters": ["name", "description", "gate_type", "severity"],
                    "returns": "DomainGate",
                    "help_visible": True,
                    "coupled": True
                },
                "generate_gates_for_system": {
                    "description": "Generate gates for entire system",
                    "parameters": ["system_requirements"],
                    "returns": "Tuple[List[DomainGate], Dict]",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "constraint_system": {
                "add_constraint": {
                    "description": "Add a constraint to system",
                    "parameters": ["name", "constraint_type", "parameter", "operator", "threshold_value"],
                    "returns": "Constraint",
                    "help_visible": True,
                    "coupled": True
                },
                "validate_constraints": {
                    "description": "Validate system against constraints",
                    "parameters": ["system_state"],
                    "returns": "Tuple[Dict, List[str]]",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "document_processor": {
                "upload_document": {
                    "description": "Upload and process design document",
                    "parameters": ["name", "file_type", "content"],
                    "returns": "DocumentMetadata",
                    "help_visible": True,
                    "coupled": True
                },
                "get_document_summary": {
                    "description": "Get summary of processed document",
                    "parameters": ["document_id"],
                    "returns": "Dict",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "inquisitory_engine": {
                "analyze_choice": {
                    "description": "Analyze a choice and provide recommendation",
                    "parameters": ["question", "choice_type", "options", "context"],
                    "returns": "ChoiceRecommendation",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "llm_integration_layer": {
                "route_request": {
                    "description": "Route request to appropriate LLM provider",
                    "parameters": ["prompt", "domain", "context"],
                    "returns": "LLMResponse",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "system_integrator": {
                "process_user_request": {
                    "description": "Process user request through system",
                    "parameters": ["user_input", "parameters"],
                    "returns": "SystemResponse",
                    "help_visible": True,
                    "coupled": True
                },
                "get_system_state": {
                    "description": "Get current system state",
                    "parameters": [],
                    "returns": "SystemState",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "bot_inventory_library": {
                "spawn_bot": {
                    "description": "Spawn a new bot agent",
                    "parameters": ["name", "role", "capabilities"],
                    "returns": "BotAgent",
                    "help_visible": True,
                    "coupled": True
                },
                "despawn_bot": {
                    "description": "Despawn a bot agent",
                    "parameters": ["agent_id"],
                    "returns": "bool",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "contractual_audit": {
                "audit_productivity": {
                    "description": "Audit system productivity",
                    "parameters": ["system_state", "agent_metrics"],
                    "returns": "Tuple[List[ProductivityGap], Dict]",
                    "help_visible": True,
                    "coupled": True
                },
                "generate_contract": {
                    "description": "Generate contractual agreement",
                    "parameters": ["gap_id", "agents", "agreement_type"],
                    "returns": "ContractualAgreement",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "murphy_drawing_engine": {
                "create_project": {
                    "description": "Create a new drawing project with discipline and units",
                    "parameters": ["name", "discipline", "units"],
                    "returns": "DrawingProject",
                    "help_visible": True,
                    "coupled": True
                },
                "export_svg": {
                    "description": "Export drawing project to SVG format",
                    "parameters": ["project"],
                    "returns": "str",
                    "help_visible": True,
                    "coupled": True
                },
                "export_dxf": {
                    "description": "Export drawing project to DXF format",
                    "parameters": ["project"],
                    "returns": "str",
                    "help_visible": True,
                    "coupled": True
                },
                "extract_bom": {
                    "description": "Extract bill of materials from drawing project",
                    "parameters": ["project"],
                    "returns": "List[Dict]",
                    "help_visible": True,
                    "coupled": True
                },
                "execute_command": {
                    "description": "Execute natural-language drawing command via agentic assistant",
                    "parameters": ["command"],
                    "returns": "Dict[str, Any]",
                    "help_visible": True,
                    "coupled": True
                }
            },
            "murphy_engineering_toolbox": {
                "scaffold_schema": {
                    "description": "Generate schema scaffolding for engineering modules",
                    "parameters": ["module_name", "schema_type"],
                    "returns": "Dict",
                    "help_visible": True,
                    "coupled": True
                },
                "generate_stub": {
                    "description": "Generate stub implementation for engineering interface",
                    "parameters": ["interface_spec"],
                    "returns": "str",
                    "help_visible": True,
                    "coupled": True
                }
            }
        }

    def _load_module_capabilities(self) -> Dict[str, List[str]]:
        """Load capabilities for each module"""
        return {
            "dynamic_expert_generator": [
                "Generate domain experts dynamically",
                "Create expert teams",
                "Map expert knowledge domains",
                "Score expert capabilities"
            ],
            "domain_gate_generator": [
                "Generate domain-specific gates",
                "Wire gates to functions",
                "Validate gate execution",
                "Integrate with librarian knowledge"
            ],
            "constraint_system": [
                "Manage multi-factor constraints",
                "Validate system state",
                "Detect and resolve conflicts",
                "Analyze constraint impact"
            ],
            "document_processor": [
                "Upload design documents",
                "Extract requirements",
                "Select equipment",
                "Generate triggers"
            ],
            "inquisitory_engine": [
                "Analyze choices",
                "Use deductive reasoning",
                "Provide recommendations",
                "Navigate decision trees"
            ],
            "llm_integration_layer": [
                "Route to Aristotle for deterministic validation",
                "Route to Wulfrum for fuzzy matching",
                "Route to Groq for generative tasks",
                "Handle human-in-the-loop triggers"
            ],
            "system_integrator": [
                "Process user requests",
                "Wire all components",
                "Generate system reports",
                "Provide unified API"
            ],
            "bot_inventory_library": [
                "Spawn bot agents",
                "Despawn bot agents",
                "Manage bot lifecycle",
                "Maintain capability registry"
            ],
            "contractual_audit": [
                "Audit productivity",
                "Detect gaps",
                "Generate contracts",
                "Monitor agent drift"
            ],
            "murphy_drawing_engine": [
                "Create engineering drawing projects",
                "Export drawings to SVG format",
                "Export drawings to DXF format",
                "Extract bill of materials from drawings",
                "Execute natural-language drawing commands",
                "Manage drawing sheets and elements",
                "Apply parametric constraints"
            ],
            "murphy_engineering_toolbox": [
                "Scaffold engineering schemas",
                "Generate stub implementations",
                "Diff engineering schemas",
                "Provide engineering calculation helpers"
            ],
            # PROD-001 — Production Assistant
            "production_assistant": [
                "Submit production proposal",
                "Validate proposal",
                "Create work order",
                "Validate work order match deliverable",
                "Advance production lifecycle",
                "List production profiles",
                "List proposals",
                "Get production audit log",
            ],
            # CAMP-001 — Outreach Campaign Planner
            "outreach_campaign_planner": [
                "Check campaign system health",
                "Create outreach campaign for segment",
                "Execute campaign step",
                "Add contact to suppression list",
                "Check contact suppression status",
                "List campaigns",
                "Activate campaign",
                "Pause campaign",
                "Get outreach audit log",
                "Get execution history",
            ],
        }

    def log_transcript(
        self,
        module: str,
        action: str,
        details: Dict[str, Any],
        actor: str,
        success: bool,
        duration_ms: Optional[int] = None
    ):
        """
        Log an entry to system transcript

        Args:
            module: Module performing action
            action: Action performed
            details: Action details
            actor: Actor (user or bot_id)
            success: Whether action succeeded
            duration_ms: Duration of action in milliseconds
        """
        self.entry_count += 1
        entry = TranscriptEntry(
            entry_id=f"entry_{self.entry_count}",
            timestamp=datetime.now(timezone.utc).isoformat(),
            module=module,
            action=action,
            details=details,
            actor=actor,
            success=success,
            duration_ms=duration_ms
        )
        self.transcripts.append(entry)

    def get_transcripts(
        self,
        module: Optional[str] = None,
        actor: Optional[str] = None,
        limit: Optional[int] = None
    ) -> List[TranscriptEntry]:
        """
        Get transcripts filtered by criteria

        Args:
            module: Filter by module
            actor: Filter by actor
            limit: Limit number of entries

        Returns:
            List of transcript entries
        """
        filtered = self.transcripts

        if module:
            filtered = [t for t in filtered if t.module == module]

        if actor:
            filtered = [t for t in filtered if t.actor == actor]

        if limit:
            filtered = filtered[-limit:]

        return filtered

    def get_module_documentation(self, module_name: str) -> Dict[str, Any]:
        """
        Get complete documentation for a module

        Args:
            module_name: Name of module

        Returns:
            Module documentation
        """
        # Get module functions
        functions = self.module_functions.get(module_name, {})

        # Get module capabilities
        capabilities = self.module_capabilities.get(module_name, [])

        # Get related knowledge
        related_knowledge = [
            k.to_dict() for k in self.knowledge_base.values()
            if module_name in k.related_modules
        ]

        # Get module transcripts
        module_transcripts = self.get_transcripts(module=module_name, limit=50)

        return {
            "module_name": module_name,
            "functions": functions,
            "capabilities": capabilities,
            "related_knowledge": related_knowledge,
            "recent_activity": [t.to_dict() for t in module_transcripts],
            "coupled": True,
            "help_visible": True
        }

    def get_function_documentation(self, module_name: str, function_name: str) -> Optional[Dict]:
        """
        Get documentation for a specific function

        Args:
            module_name: Name of module
            function_name: Name of function

        Returns:
            Function documentation
        """
        module_functions = self.module_functions.get(module_name, {})
        return module_functions.get(function_name)

    def generate_module_guide(self, module_name: str) -> GeneratedDocument:
        """
        Generate comprehensive module guide

        Args:
            module_name: Name of module

        Returns:
            GeneratedDocument object
        """
        doc = self.get_module_documentation(module_name)

        # Build markdown content
        content = f"# {module_name.title()} Module Guide\n\n"

        content += "## Overview\n\n"
        content += f"The {module_name} module provides the following capabilities:\n\n"
        for capability in doc["capabilities"]:
            content += f"- {capability}\n"

        content += "\n## Functions\n\n"
        for func_name, func_data in doc["functions"].items():
            content += f"### {func_name}\n\n"
            content += f"**Description**: {func_data['description']}\n\n"
            content += f"**Parameters**: {', '.join(func_data['parameters'])}\n\n"
            content += f"**Returns**: {func_data['returns']}\n\n"

        content += "\n## Recent Activity\n\n"
        for transcript in doc["recent_activity"][-10:]:
            content += f"- {transcript['timestamp']}: {transcript['action']} ({'✓' if transcript['success'] else '✗'})\n"

        self.doc_count += 1
        document = GeneratedDocument(
            doc_id=f"doc_{self.doc_count}",
            doc_type=DocumentType.MODULE_GUIDE,
            title=f"{module_name.title()} Module Guide",
            content=content,
            format="markdown",
            metadata={
                "module": module_name,
                "version": "1.0",
                "generated_at": datetime.now(timezone.utc).isoformat()
            },
            created_at=datetime.now(timezone.utc).isoformat()
        )

        self.documents[document.doc_id] = document
        return document

    def generate_complete_transcript(self) -> GeneratedDocument:
        """Generate complete system transcript document"""
        content = "# Complete System Transcript\n\n"
        content += f"Generated at: {datetime.now(timezone.utc).isoformat()}\n\n"
        content += f"Total entries: {len(self.transcripts)}\n\n"

        # Group by module
        by_module = {}
        for entry in self.transcripts:
            if entry.module not in by_module:
                by_module[entry.module] = []
            by_module[entry.module].append(entry)

        for module, entries in by_module.items():
            content += f"\n## {module}\n\n"
            for entry in entries[-20:]:  # Last 20 entries per module
                status = "✓" if entry.success else "✗"
                content += f"- [{entry.timestamp}] {entry.action} by {entry.actor} {status}\n"
                if entry.details:
                    content += f"  Details: {json.dumps(entry.details, indent=2)}\n"

        self.doc_count += 1
        document = GeneratedDocument(
            doc_id=f"doc_{self.doc_count}",
            doc_type=DocumentType.TRANSCRIPT,
            title="Complete System Transcript",
            content=content,
            format="markdown",
            metadata={
                "total_entries": len(self.transcripts),
                "modules": list(by_module.keys()),
                "generated_at": datetime.now(timezone.utc).isoformat()
            },
            created_at=datetime.now(timezone.utc).isoformat()
        )

        self.documents[document.doc_id] = document
        return document

    def search_knowledge(self, query: str) -> List[SystemKnowledge]:
        """
        Search knowledge base

        Args:
            query: Search query

        Returns:
            List of matching knowledge entries
        """
        query_lower = query.lower()
        results = []

        for knowledge in self.knowledge_base.values():
            # Search in topic, description, category
            if (query_lower in knowledge.topic.lower() or
                query_lower in knowledge.description.lower() or
                query_lower in knowledge.category.lower()):
                results.append(knowledge)

        return results

    def get_system_overview(self) -> Dict[str, Any]:
        """Get complete system overview from librarian perspective"""
        return {
            "total_modules": len(self.module_functions),
            "total_functions": sum(len(funcs) for funcs in self.module_functions.values()),
            "total_transcripts": len(self.transcripts),
            "total_knowledge": len(self.knowledge_base),
            "total_documents": len(self.documents),
            "modules": list(self.module_functions.keys()),
            "module_summary": {
                module: {
                    "functions": len(funcs),
                    "capabilities": len(caps)
                }
                for module, funcs, caps in zip(
                    self.module_functions.keys(),
                    self.module_functions.values(),
                    self.module_capabilities.values()
                )
            }
        }

    def get_documentation(self, topic: str = "capabilities") -> Dict[str, Any]:
        """Convenience method: get documentation by topic"""
        results = self.search_knowledge(topic)
        if results:
            return {"topic": topic, "entries": [r.__dict__ if hasattr(r, '__dict__') else str(r) for r in results]}
        return self.get_system_overview()

    def get_help(self) -> Dict[str, Any]:
        """Convenience method: get help overview"""
        return self.get_system_overview()

    def answer_question(self, question: str) -> Dict[str, Any]:
        """Convenience method: answer a question using the knowledge base"""
        results = self.search_knowledge(question)
        entries = [r.__dict__ if hasattr(r, '__dict__') else str(r) for r in results]
        return {"question": question, "answer": entries if entries else ["No specific answer found."], "results": entries}

    def troubleshoot(self, issue: str) -> Dict[str, Any]:
        """Convenience method: troubleshoot an issue"""
        results = self.search_knowledge(issue)
        entries = [r.__dict__ if hasattr(r, '__dict__') else str(r) for r in results]
        return {"issue": issue, "suggestions": entries if entries else ["Check system logs for more details."]}

    def add_knowledge_entry(self, entry: Dict[str, Any]) -> "SystemKnowledge":
        """Add a single knowledge entry to the knowledge base.

        Args:
            entry: Dict with keys ``category``, ``topic``, ``description``,
                   ``related_modules``, ``related_functions``, ``references``.

        Returns:
            The newly created SystemKnowledge object.
        """
        self.knowledge_count += 1
        knowledge = SystemKnowledge(
            knowledge_id=f"know_{self.knowledge_count}",
            category=entry.get("category", "general"),
            topic=entry.get("topic", ""),
            description=entry.get("description", ""),
            related_modules=entry.get("related_modules", []),
            related_functions=entry.get("related_functions", []),
            references=entry.get("references", []),
            created_at=datetime.now(timezone.utc).isoformat(),
        )
        self.knowledge_base[knowledge.knowledge_id] = knowledge
        return knowledge

    def register_schema_knowledge(self, registry: Any) -> int:
        """Index all registered schemas from a SchemaRegistry into the knowledge base.

        Args:
            registry: A SchemaRegistry instance whose ``schemas`` dict will be
                      indexed.

        Returns:
            Number of knowledge entries added.
        """
        count = 0
        for key, schema in registry.schemas.items():
            self.add_knowledge_entry({
                "category": "schema_contract",
                "topic": f"Schema: {schema.artifact_name} ({schema.direction})",
                "description": f"I/O schema for {schema.artifact_name}",
                "related_modules": [key.split(":")[0]],  # bot_name
                "related_functions": [],
                "references": [f"schema:{key}"],
            })
            count += 1
        return count

    # ------------------------------------------------------------------
    # Librarian-driven routing support
    # ------------------------------------------------------------------

    def find_capabilities(
        self,
        task: Dict[str, Any],
        top_n: int = 5,
        module_registry: Optional[Any] = None,
    ) -> List[Any]:
        """Return a ranked list of :class:`~task_router.CapabilityMatch` objects.

        Two-phase discovery:

        **Phase 1 — Pre-filter**: capabilities incompatible with the task domain
        are flagged but still returned (with ``filtered=True``) so operators can
        see what was excluded and why.

        **Phase 2 — Score and rank**: surviving capabilities are scored using
        keyword overlap between the task text and the capability description.
        The top *top_n* matches are returned, sorted by descending score.

        Args:
            task: Task dict, e.g. ``{"task": "generate invoice for Acme $5000"}``.
            top_n: Maximum number of unfiltered matches to return.
            module_registry: Optional :class:`~module_registry.ModuleRegistry`
                instance.  When supplied its live capability map is merged with
                the built-in ``module_capabilities`` map for broader coverage.

        Returns:
            List of ``CapabilityMatch`` instances (unfiltered ones first, sorted
            by descending score; filtered ones appended at the end).
        """
        # Import here to avoid circular imports at module load time
        try:
            from task_router import CapabilityMatch  # type: ignore[import]
        except ImportError:
            # Fallback: define a minimal CapabilityMatch locally if task_router
            # is not yet on sys.path (e.g. during isolated unit tests)
            from dataclasses import dataclass
            from dataclasses import field as _field

            @dataclass  # type: ignore[no-redef]
            class CapabilityMatch:  # type: ignore[no-redef]
                capability_id: str
                module_path: str
                score: float
                match_reasons: List[str] = _field(default_factory=list)
                cost_estimate: str = "medium"
                determinism: str = "deterministic"
                gate_compatibility: Dict[str, str] = _field(default_factory=dict)
                filtered: bool = False
                filter_reason: Optional[str] = None

        task_text = str(task.get("task", task.get("description", ""))).lower()
        task_words = set(task_text.split())

        # Build the combined capability map
        combined: Dict[str, List[str]] = {}
        # 1. Built-in per-module capability descriptions
        for module_name, cap_list in self.module_capabilities.items():
            for cap in cap_list:
                cap_key = cap.lower().replace(" ", "_")
                combined.setdefault(cap_key, []).append(module_name)

        # 2. Live ModuleRegistry capabilities (tag-style)
        if module_registry is not None:
            try:
                live_caps = module_registry.get_capabilities()
                if isinstance(live_caps, dict):
                    for cap_tag, modules in live_caps.items():
                        mods = modules if isinstance(modules, list) else [modules]
                        combined.setdefault(cap_tag.lower(), []).extend(mods)
            except Exception as exc:
                logger.debug("SystemLibrarian.find_capabilities: registry error: %s", exc)

        matches: List[Any] = []
        seen_caps: set = set()

        for cap_key, modules in combined.items():
            if cap_key in seen_caps:
                continue
            seen_caps.add(cap_key)

            cap_words = set(cap_key.replace("_", " ").split())
            overlap = task_words & cap_words
            if not task_words:
                score = 0.0
            else:
                score = len(overlap) / max(len(task_words), len(cap_words))

            module_name = modules[0] if modules else "unknown"
            match = CapabilityMatch(
                capability_id=cap_key,
                module_path=f"src.{module_name}",
                score=round(score, 4),
                match_reasons=[f"keyword overlap: {sorted(overlap)}"] if overlap else ["no direct overlap"],
                cost_estimate="medium",
                determinism="deterministic",
                gate_compatibility={},
                filtered=False,
                filter_reason=None,
            )
            matches.append(match)

        # Sort by descending score
        matches.sort(key=lambda m: m.score, reverse=True)

        # Return top_n unfiltered + all filtered ones
        unfiltered = [m for m in matches if not m.filtered][:top_n]
        filtered = [m for m in matches if m.filtered]
        return unfiltered + filtered


if __name__ == "__main__":
    # Test system librarian
    librarian = SystemLibrarian()

    # Test 1: Log transcripts
    logger.info("=== Test 1: Log Transcripts ===")
    librarian.log_transcript(
        module="dynamic_expert_generator",
        action="generate_expert",
        details={"expert_name": "Software Architect", "domain": "software"},
        actor="user",
        success=True,
        duration_ms=150
    )

    librarian.log_transcript(
        module="domain_gate_generator",
        action="generate_gate",
        details={"gate_name": "Security Gate", "gate_type": "security"},
        actor="system",
        success=True,
        duration_ms=200
    )

    logger.info(f"Transcript entries: {len(librarian.transcripts)}")

    # Test 2: Get module documentation
    logger.info("\n=== Test 2: Get Module Documentation ===")
    doc = librarian.get_module_documentation("dynamic_expert_generator")
    logger.info(f"Module: {doc['module_name']}")
    logger.info(f"Functions: {len(doc['functions'])}")
    logger.info(f"Capabilities: {doc['capabilities']}")
    logger.info(f"Related knowledge: {len(doc['related_knowledge'])}")

    # Test 3: Get function documentation
    logger.info("\n=== Test 3: Get Function Documentation ===")
    func_doc = librarian.get_function_documentation(
        "dynamic_expert_generator",
        "generate_expert"
    )
    if func_doc:
        logger.info("Function: generate_expert")
        logger.info(f"Description: {func_doc['description']}")
        logger.info(f"Parameters: {func_doc['parameters']}")

    # Test 4: Generate module guide
    logger.info("\n=== Test 4: Generate Module Guide ===")
    guide = librarian.generate_module_guide("system_integrator")
    logger.info(f"Guide generated: {guide.title}")
    logger.info(f"Content length: {len(guide.content)}")

    # Test 5: Search knowledge
    logger.info("\n=== Test 5: Search Knowledge ===")
    results = librarian.search_knowledge("gate")
    logger.info(f"Results: {len(results)}")
    for result in results:
        logger.info(f"  - {result.topic}")

    # Test 6: Get system overview
    logger.info("\n=== Test 6: System Overview ===")
    overview = librarian.get_system_overview()
    logger.info(f"Total modules: {overview['total_modules']}")
    logger.info(f"Total functions: {overview['total_functions']}")
    logger.info(f"Total transcripts: {overview['total_transcripts']}")
    logger.info(f"Total knowledge: {overview['total_knowledge']}")

    # Test 7: Generate complete transcript
    logger.info("\n=== Test 7: Generate Complete Transcript ===")
    transcript_doc = librarian.generate_complete_transcript()
    logger.info(f"Transcript document generated: {transcript_doc.title}")
