"""
PRESET-001 through PRESET-009 — Professional Services Presets
==============================================================

Industry presets for law firms, accounting, consulting, architecture/engineering,
medical/dental/veterinary practices, therapy, and real estate.

Copyright 2024 Inoni LLC – BSL-1.1
"""

from __future__ import annotations

import logging
from typing import List

from .base import (
    AgentPersona,
    ComplianceRule,
    IndustryPreset,
    IntegrationMapping,
    KPIDefinition,
    WorkflowTemplate,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# PRESET-001 — Legal Practice Preset
# ---------------------------------------------------------------------------

LEGAL_PRACTICE = IndustryPreset(
    preset_id="PRESET-001",
    name="Legal Practice",
    industry="Professional Services",
    sub_industry="Law Firm",
    description="End-to-end case management, document review, billing, and court filing for law firms.",
    version="1.0.0",
    tags=["legal", "law-firm", "compliance", "billing", "case-management"],
    compatible_with=["PRESET-002", "PRESET-009"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-LEGAL-001",
            name="New Matter Intake",
            description="Onboard a new client matter from conflict check through retainer execution.",
            steps=[
                {
                    "step_name": "Conflict of Interest Check",
                    "step_type": "automated_check",
                    "agent_persona": "Legal Operations Analyst",
                    "integrations": ["Clio", "LexisNexis"],
                    "compliance_gates": ["attorney-client-privilege", "bar-conflict-rules"],
                    "kpis": ["conflict_check_time"],
                },
                {
                    "step_name": "Engagement Letter Generation",
                    "step_type": "document_generation",
                    "agent_persona": "Legal Document Drafter",
                    "integrations": ["DocuSign", "Clio"],
                    "compliance_gates": ["retainer-requirements"],
                    "kpis": ["retainer_execution_time"],
                },
                {
                    "step_name": "Matter Setup in DMS",
                    "step_type": "data_entry",
                    "agent_persona": "Legal Operations Analyst",
                    "integrations": ["Clio", "MyCase"],
                    "compliance_gates": [],
                    "kpis": ["matter_setup_time"],
                },
            ],
            triggers=["new_client_inquiry", "referral_received"],
            outputs=["matter_record", "signed_retainer", "billing_account"],
        ),
        WorkflowTemplate(
            template_id="WF-LEGAL-002",
            name="Billing and Invoice Cycle",
            description="Capture time entries, generate invoices, and reconcile trust accounts.",
            steps=[
                {
                    "step_name": "Time Entry Capture",
                    "step_type": "data_collection",
                    "agent_persona": "Legal Billing Coordinator",
                    "integrations": ["Clio"],
                    "compliance_gates": ["trust-accounting-rules"],
                    "kpis": ["billing_hours"],
                },
                {
                    "step_name": "Pre-bill Review",
                    "step_type": "human_review",
                    "agent_persona": "Legal Billing Coordinator",
                    "integrations": ["Clio", "MyCase"],
                    "compliance_gates": ["iolta-compliance"],
                    "kpis": ["invoice_accuracy"],
                },
                {
                    "step_name": "Invoice Dispatch",
                    "step_type": "communication",
                    "agent_persona": "Legal Billing Coordinator",
                    "integrations": ["Clio", "DocuSign"],
                    "compliance_gates": [],
                    "kpis": ["days_to_collection"],
                },
            ],
            triggers=["billing_cycle_end", "matter_close"],
            outputs=["invoice", "trust_ledger_update", "ar_record"],
        ),
        WorkflowTemplate(
            template_id="WF-LEGAL-003",
            name="Court Filing Management",
            description="Track deadlines, prepare filings, and confirm court submissions.",
            steps=[
                {
                    "step_name": "Deadline Calendar Sync",
                    "step_type": "automated_check",
                    "agent_persona": "Legal Operations Analyst",
                    "integrations": ["Clio", "CourtAlert"],
                    "compliance_gates": ["statute-of-limitations", "local-rules"],
                    "kpis": ["missed_deadline_rate"],
                },
                {
                    "step_name": "Document Preparation",
                    "step_type": "document_generation",
                    "agent_persona": "Legal Document Drafter",
                    "integrations": ["LexisNexis", "DocuSign"],
                    "compliance_gates": ["court-formatting-rules"],
                    "kpis": ["filing_prep_time"],
                },
                {
                    "step_name": "E-Filing Submission",
                    "step_type": "integration_action",
                    "agent_persona": "Legal Operations Analyst",
                    "integrations": ["PACER", "CourtAlert"],
                    "compliance_gates": ["efiling-requirements"],
                    "kpis": ["filing_success_rate"],
                },
            ],
            triggers=["deadline_approaching", "motion_scheduled"],
            outputs=["filed_document", "confirmation_receipt", "docket_update"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-LEGAL-001",
            name="Legal Operations Analyst",
            role="Operations Coordinator",
            domain="Legal",
            capabilities=["conflict_check", "deadline_tracking", "matter_setup", "efiling"],
            tools=["Clio", "LexisNexis", "PACER", "CourtAlert"],
            personality_traits=["detail-oriented", "compliance-focused", "proactive"],
        ),
        AgentPersona(
            persona_id="AP-LEGAL-002",
            name="Legal Document Drafter",
            role="Document Specialist",
            domain="Legal",
            capabilities=["contract_drafting", "motion_writing", "template_management", "document_review"],
            tools=["DocuSign", "LexisNexis", "Clio"],
            personality_traits=["precise", "research-driven", "thorough"],
        ),
        AgentPersona(
            persona_id="AP-LEGAL-003",
            name="Legal Billing Coordinator",
            role="Finance Coordinator",
            domain="Legal",
            capabilities=["time_entry", "invoice_generation", "trust_accounting", "collections"],
            tools=["Clio", "MyCase", "QuickBooks"],
            personality_traits=["accurate", "organized", "client-focused"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Clio",
            connector_type="practice_management",
            required=True,
            config_template={"api_key": "", "base_url": "https://app.clio.com/api/v4"},
            purpose="Primary practice management, matter tracking, and billing.",
        ),
        IntegrationMapping(
            connector_name="DocuSign",
            connector_type="esignature",
            required=True,
            config_template={"integration_key": "", "account_id": ""},
            purpose="Electronic signatures for retainers and client documents.",
        ),
        IntegrationMapping(
            connector_name="LexisNexis",
            connector_type="legal_research",
            required=False,
            config_template={"api_key": "", "subscription_tier": ""},
            purpose="Legal research and case law database.",
        ),
        IntegrationMapping(
            connector_name="MyCase",
            connector_type="practice_management",
            required=False,
            config_template={"api_key": ""},
            purpose="Alternative practice management system.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-LEGAL-001",
            standard="Attorney-Client Privilege",
            description="All client communications and matter data must be handled with strict confidentiality per ABA Model Rules.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-LEGAL-002",
            standard="ABA Model Rules of Professional Conduct",
            description="Conflict of interest checks must be completed before matter acceptance.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-LEGAL-003",
            standard="IOLTA Trust Accounting",
            description="Client funds must be maintained in segregated IOLTA trust accounts with complete audit trail.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-LEGAL-001",
            name="Case Close Rate",
            description="Percentage of opened matters closed within target timeframe.",
            unit="%",
            target_value=85.0,
            warning_threshold=70.0,
            critical_threshold=55.0,
            measurement_method="closed_matters / opened_matters * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-LEGAL-002",
            name="Billable Hours per Attorney",
            description="Average billable hours logged per attorney per month.",
            unit="hours",
            target_value=150.0,
            warning_threshold=120.0,
            critical_threshold=100.0,
            measurement_method="total_billable_hours / attorney_count",
        ),
        KPIDefinition(
            kpi_id="KPI-LEGAL-003",
            name="Client Satisfaction Score",
            description="Post-matter client satisfaction survey score (0–10 NPS-style).",
            unit="score",
            target_value=8.5,
            warning_threshold=7.0,
            critical_threshold=5.0,
            measurement_method="average(post_matter_survey_scores)",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-002 — Accounting Firm Preset
# ---------------------------------------------------------------------------

ACCOUNTING_FIRM = IndustryPreset(
    preset_id="PRESET-002",
    name="Accounting Firm",
    industry="Professional Services",
    sub_industry="Accounting & Tax",
    description="Tax preparation, audit management, bookkeeping, and payroll services for CPA and accounting firms.",
    version="1.0.0",
    tags=["accounting", "tax", "audit", "payroll", "bookkeeping", "CPA"],
    compatible_with=["PRESET-001", "PRESET-003"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-ACCT-001",
            name="Tax Return Preparation",
            description="Client document collection through e-filing and delivery.",
            steps=[
                {
                    "step_name": "Document Request & Collection",
                    "step_type": "data_collection",
                    "agent_persona": "Tax Preparation Specialist",
                    "integrations": ["TaxSlayer", "QuickBooks"],
                    "compliance_gates": ["IRS-deadline-tracking"],
                    "kpis": ["document_collection_cycle_time"],
                },
                {
                    "step_name": "Tax Return Preparation",
                    "step_type": "processing",
                    "agent_persona": "Tax Preparation Specialist",
                    "integrations": ["TaxSlayer", "Xero"],
                    "compliance_gates": ["GAAP", "IRS-regulations"],
                    "kpis": ["return_prep_time", "error_rate"],
                },
                {
                    "step_name": "Manager Review & Client Approval",
                    "step_type": "human_review",
                    "agent_persona": "Audit & Compliance Manager",
                    "integrations": ["DocuSign"],
                    "compliance_gates": ["CPA-sign-off-requirements"],
                    "kpis": ["review_cycle_time"],
                },
                {
                    "step_name": "E-File Submission",
                    "step_type": "integration_action",
                    "agent_persona": "Tax Preparation Specialist",
                    "integrations": ["TaxSlayer", "IRS-e-services"],
                    "compliance_gates": ["IRS-efiling-standards"],
                    "kpis": ["filing_success_rate"],
                },
            ],
            triggers=["tax_season_open", "extension_filed", "client_doc_received"],
            outputs=["filed_tax_return", "client_copy", "billing_record"],
        ),
        WorkflowTemplate(
            template_id="WF-ACCT-002",
            name="Monthly Bookkeeping Close",
            description="Reconcile accounts, categorize transactions, and deliver financial statements.",
            steps=[
                {
                    "step_name": "Transaction Import & Categorization",
                    "step_type": "automated_check",
                    "agent_persona": "Bookkeeping & Payroll Agent",
                    "integrations": ["QuickBooks", "Xero"],
                    "compliance_gates": ["GAAP"],
                    "kpis": ["categorization_accuracy"],
                },
                {
                    "step_name": "Bank Reconciliation",
                    "step_type": "processing",
                    "agent_persona": "Bookkeeping & Payroll Agent",
                    "integrations": ["QuickBooks", "Xero"],
                    "compliance_gates": ["GAAP"],
                    "kpis": ["reconciliation_time"],
                },
                {
                    "step_name": "Financial Statement Generation",
                    "step_type": "document_generation",
                    "agent_persona": "Audit & Compliance Manager",
                    "integrations": ["QuickBooks", "Xero"],
                    "compliance_gates": ["GAAP", "SOX"],
                    "kpis": ["close_cycle_time"],
                },
            ],
            triggers=["month_end", "client_request"],
            outputs=["income_statement", "balance_sheet", "cash_flow_statement"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-ACCT-001",
            name="Tax Preparation Specialist",
            role="Tax Analyst",
            domain="Accounting",
            capabilities=["tax_return_prep", "efile_submission", "document_review", "client_communication"],
            tools=["TaxSlayer", "QuickBooks", "Xero", "IRS-e-services"],
            personality_traits=["detail-oriented", "deadline-driven", "regulatory-aware"],
        ),
        AgentPersona(
            persona_id="AP-ACCT-002",
            name="Audit & Compliance Manager",
            role="Quality Assurance",
            domain="Accounting",
            capabilities=["audit_management", "SOX_compliance", "financial_review", "risk_assessment"],
            tools=["QuickBooks", "ADP", "DocuSign"],
            personality_traits=["analytical", "compliance-focused", "methodical"],
        ),
        AgentPersona(
            persona_id="AP-ACCT-003",
            name="Bookkeeping & Payroll Agent",
            role="Bookkeeper",
            domain="Accounting",
            capabilities=["transaction_categorization", "bank_reconciliation", "payroll_processing", "accounts_payable"],
            tools=["QuickBooks", "Xero", "ADP"],
            personality_traits=["precise", "organized", "efficient"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="QuickBooks",
            connector_type="accounting",
            required=True,
            config_template={"client_id": "", "client_secret": "", "environment": "production"},
            purpose="Core accounting, bookkeeping, and financial reporting.",
        ),
        IntegrationMapping(
            connector_name="TaxSlayer",
            connector_type="tax_software",
            required=True,
            config_template={"api_key": "", "efin": ""},
            purpose="Federal and state tax return preparation and e-filing.",
        ),
        IntegrationMapping(
            connector_name="ADP",
            connector_type="payroll",
            required=False,
            config_template={"client_id": "", "client_secret": ""},
            purpose="Payroll processing and HR data integration.",
        ),
        IntegrationMapping(
            connector_name="Xero",
            connector_type="accounting",
            required=False,
            config_template={"client_id": "", "client_secret": ""},
            purpose="Alternative cloud accounting platform.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-ACCT-001",
            standard="GAAP",
            description="Financial statements must adhere to Generally Accepted Accounting Principles.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-ACCT-002",
            standard="IRS Regulations",
            description="All tax filings must meet IRS standards; penalties apply for late or inaccurate submissions.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-ACCT-003",
            standard="SOX (Sarbanes-Oxley)",
            description="Public company clients require SOX-compliant internal controls and audit trails.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-ACCT-001",
            name="Client Retention Rate",
            description="Percentage of clients retained year-over-year.",
            unit="%",
            target_value=92.0,
            warning_threshold=85.0,
            critical_threshold=75.0,
            measurement_method="retained_clients / prior_year_clients * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-ACCT-002",
            name="Audit Completion Rate On-Time",
            description="Percentage of audit engagements completed by agreed deadline.",
            unit="%",
            target_value=95.0,
            warning_threshold=88.0,
            critical_threshold=75.0,
            measurement_method="on_time_audits / total_audits * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-ACCT-003",
            name="Error Rate",
            description="Percentage of returns/reports requiring material correction post-delivery.",
            unit="%",
            target_value=0.5,
            warning_threshold=2.0,
            critical_threshold=5.0,
            measurement_method="corrections / total_filings * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-003 — Consulting Preset
# ---------------------------------------------------------------------------

CONSULTING = IndustryPreset(
    preset_id="PRESET-003",
    name="Consulting Firm",
    industry="Professional Services",
    sub_industry="Strategy & Management Consulting",
    description="Strategy consulting, deliverable management, and client relationship workflows.",
    version="1.0.0",
    tags=["consulting", "strategy", "deliverables", "client-management", "utilization"],
    compatible_with=["PRESET-002", "PRESET-018"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-CONSULT-001",
            name="Engagement Kickoff",
            description="Scope definition, resource allocation, and project plan creation.",
            steps=[
                {
                    "step_name": "Scope of Work Definition",
                    "step_type": "document_generation",
                    "agent_persona": "Engagement Manager",
                    "integrations": ["Salesforce", "Notion"],
                    "compliance_gates": ["engagement-letter-approval"],
                    "kpis": ["time_to_kickoff"],
                },
                {
                    "step_name": "Resource & Staffing Plan",
                    "step_type": "planning",
                    "agent_persona": "Engagement Manager",
                    "integrations": ["Salesforce", "Slack"],
                    "compliance_gates": [],
                    "kpis": ["utilization_rate"],
                },
                {
                    "step_name": "Project Plan & Timeline",
                    "step_type": "planning",
                    "agent_persona": "Project Delivery Analyst",
                    "integrations": ["Notion", "PowerBI"],
                    "compliance_gates": [],
                    "kpis": ["project_margin"],
                },
            ],
            triggers=["contract_signed", "engagement_start_date"],
            outputs=["project_plan", "staffing_model", "kickoff_deck"],
        ),
        WorkflowTemplate(
            template_id="WF-CONSULT-002",
            name="Deliverable Review & Approval",
            description="Draft, review, client feedback, and final delivery pipeline.",
            steps=[
                {
                    "step_name": "Deliverable Draft",
                    "step_type": "processing",
                    "agent_persona": "Project Delivery Analyst",
                    "integrations": ["Notion", "Slack"],
                    "compliance_gates": [],
                    "kpis": ["deliverable_cycle_time"],
                },
                {
                    "step_name": "Internal QA Review",
                    "step_type": "human_review",
                    "agent_persona": "Engagement Manager",
                    "integrations": ["Notion"],
                    "compliance_gates": ["quality-gate"],
                    "kpis": ["revision_cycles"],
                },
                {
                    "step_name": "Client Delivery & Sign-off",
                    "step_type": "communication",
                    "agent_persona": "Client Relationship Manager",
                    "integrations": ["Salesforce", "DocuSign"],
                    "compliance_gates": [],
                    "kpis": ["NPS"],
                },
            ],
            triggers=["milestone_due", "client_review_scheduled"],
            outputs=["approved_deliverable", "client_feedback_record", "billing_milestone"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-CONSULT-001",
            name="Engagement Manager",
            role="Project Lead",
            domain="Consulting",
            capabilities=["scope_management", "resource_planning", "client_communication", "risk_management"],
            tools=["Salesforce", "Notion", "Slack"],
            personality_traits=["strategic", "decisive", "client-focused"],
        ),
        AgentPersona(
            persona_id="AP-CONSULT-002",
            name="Project Delivery Analyst",
            role="Analyst",
            domain="Consulting",
            capabilities=["data_analysis", "deliverable_creation", "research", "PowerBI_reporting"],
            tools=["Notion", "PowerBI", "Slack"],
            personality_traits=["analytical", "detail-oriented", "fast-learner"],
        ),
        AgentPersona(
            persona_id="AP-CONSULT-003",
            name="Client Relationship Manager",
            role="Account Manager",
            domain="Consulting",
            capabilities=["stakeholder_management", "upsell_identification", "satisfaction_tracking", "renewal_management"],
            tools=["Salesforce", "DocuSign"],
            personality_traits=["empathetic", "communicative", "results-driven"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Salesforce",
            connector_type="crm",
            required=True,
            config_template={"client_id": "", "client_secret": "", "instance_url": ""},
            purpose="Client relationship management, opportunity tracking, and account data.",
        ),
        IntegrationMapping(
            connector_name="Notion",
            connector_type="project_management",
            required=True,
            config_template={"api_key": "", "workspace_id": ""},
            purpose="Project wikis, deliverable management, and team knowledge base.",
        ),
        IntegrationMapping(
            connector_name="Slack",
            connector_type="communications",
            required=False,
            config_template={"bot_token": "", "signing_secret": ""},
            purpose="Team and client communication channel.",
        ),
        IntegrationMapping(
            connector_name="PowerBI",
            connector_type="analytics",
            required=False,
            config_template={"tenant_id": "", "client_id": ""},
            purpose="Client-facing dashboards and analytics deliverables.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-CONSULT-001",
            standard="NDA / Confidentiality",
            description="Client data and engagement details must be covered by executed NDA before work commences.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-CONSULT-002",
            standard="Conflict of Interest Policy",
            description="No concurrent engagements with direct competitors without explicit client disclosure.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-CONSULT-001",
            name="Consultant Utilization Rate",
            description="Billable hours as a percentage of total available hours.",
            unit="%",
            target_value=75.0,
            warning_threshold=65.0,
            critical_threshold=55.0,
            measurement_method="billable_hours / available_hours * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-CONSULT-002",
            name="Project Gross Margin",
            description="Revenue minus direct project costs as a percentage of revenue.",
            unit="%",
            target_value=40.0,
            warning_threshold=30.0,
            critical_threshold=20.0,
            measurement_method="(revenue - direct_costs) / revenue * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-CONSULT-003",
            name="Net Promoter Score",
            description="Client NPS measured at engagement close.",
            unit="score",
            target_value=50.0,
            warning_threshold=30.0,
            critical_threshold=10.0,
            measurement_method="promoters_pct - detractors_pct",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-004 — Architecture & Engineering Preset
# ---------------------------------------------------------------------------

ARCHITECTURE_ENGINEERING = IndustryPreset(
    preset_id="PRESET-004",
    name="Architecture & Engineering Firm",
    industry="Professional Services",
    sub_industry="Architecture & Engineering",
    description="CAD/BIM workflows, project management, permit tracking, and construction administration.",
    version="1.0.0",
    tags=["architecture", "engineering", "AEC", "CAD", "BIM", "permits"],
    compatible_with=["PRESET-017", "PRESET-026"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-AEC-001",
            name="Project Design & Documentation",
            description="BIM modeling, drawing production, and internal design reviews.",
            steps=[
                {
                    "step_name": "Schematic Design",
                    "step_type": "design",
                    "agent_persona": "Design Project Manager",
                    "integrations": ["Revit", "AutoCAD"],
                    "compliance_gates": ["building-codes", "zoning-ordinances"],
                    "kpis": ["design_phase_schedule_variance"],
                },
                {
                    "step_name": "Internal Drawing Review",
                    "step_type": "human_review",
                    "agent_persona": "Technical QA Engineer",
                    "integrations": ["BlueBeam", "Procore"],
                    "compliance_gates": ["PE-stamp-requirements"],
                    "kpis": ["drawing_revision_count"],
                },
                {
                    "step_name": "Client Design Approval",
                    "step_type": "communication",
                    "agent_persona": "Design Project Manager",
                    "integrations": ["Procore", "DocuSign"],
                    "compliance_gates": [],
                    "kpis": ["client_approval_cycle_time"],
                },
            ],
            triggers=["project_phase_start", "design_milestone"],
            outputs=["approved_drawings", "BIM_model", "specification_set"],
        ),
        WorkflowTemplate(
            template_id="WF-AEC-002",
            name="Permit Tracking & Submission",
            description="Track permit applications, agency reviews, and approvals.",
            steps=[
                {
                    "step_name": "Permit Application Preparation",
                    "step_type": "document_generation",
                    "agent_persona": "Permit & Compliance Coordinator",
                    "integrations": ["Procore", "BlueBeam"],
                    "compliance_gates": ["local-building-codes", "ADA-compliance"],
                    "kpis": ["permit_prep_time"],
                },
                {
                    "step_name": "Agency Submission & Tracking",
                    "step_type": "integration_action",
                    "agent_persona": "Permit & Compliance Coordinator",
                    "integrations": ["Procore"],
                    "compliance_gates": ["permit-checklist"],
                    "kpis": ["permit_approval_cycle_time"],
                },
            ],
            triggers=["design_documents_approved", "permit_resubmittal_required"],
            outputs=["issued_permit", "permit_log", "agency_correspondence"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-AEC-001",
            name="Design Project Manager",
            role="Project Manager",
            domain="Architecture & Engineering",
            capabilities=["project_scheduling", "client_management", "BIM_coordination", "fee_management"],
            tools=["Revit", "Procore", "AutoCAD"],
            personality_traits=["organized", "client-focused", "technically-proficient"],
        ),
        AgentPersona(
            persona_id="AP-AEC-002",
            name="Technical QA Engineer",
            role="Quality Assurance",
            domain="Architecture & Engineering",
            capabilities=["drawing_review", "code_compliance_check", "coordination_clash_detection", "specification_review"],
            tools=["BlueBeam", "Revit", "AutoCAD"],
            personality_traits=["detail-oriented", "standards-focused", "systematic"],
        ),
        AgentPersona(
            persona_id="AP-AEC-003",
            name="Permit & Compliance Coordinator",
            role="Compliance Specialist",
            domain="Architecture & Engineering",
            capabilities=["permit_applications", "agency_liaison", "code_research", "inspection_scheduling"],
            tools=["Procore", "BlueBeam"],
            personality_traits=["persistent", "organized", "regulatory-aware"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Procore",
            connector_type="project_management",
            required=True,
            config_template={"client_id": "", "client_secret": "", "company_id": ""},
            purpose="Project management, RFIs, submittals, and document control.",
        ),
        IntegrationMapping(
            connector_name="Revit",
            connector_type="BIM",
            required=True,
            config_template={"forge_client_id": "", "forge_client_secret": ""},
            purpose="BIM modeling and design documentation.",
        ),
        IntegrationMapping(
            connector_name="BlueBeam",
            connector_type="document_review",
            required=False,
            config_template={"api_key": ""},
            purpose="PDF markup and document collaboration.",
        ),
        IntegrationMapping(
            connector_name="AutoCAD",
            connector_type="CAD",
            required=False,
            config_template={"forge_client_id": ""},
            purpose="2D drafting and legacy drawing production.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-AEC-001",
            standard="Building Codes (IBC/IRC)",
            description="All design documents must comply with applicable International Building Code and local amendments.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-AEC-002",
            standard="PE Stamp Requirements",
            description="Structural, MEP, and civil drawings must bear a licensed Professional Engineer's stamp.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-AEC-003",
            standard="ADA Compliance",
            description="All public-facing designs must meet Americans with Disabilities Act accessibility standards.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-AEC-001",
            name="Project On-Time Delivery Rate",
            description="Percentage of projects delivered within the contracted schedule.",
            unit="%",
            target_value=85.0,
            warning_threshold=75.0,
            critical_threshold=60.0,
            measurement_method="on_time_projects / total_projects * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-AEC-002",
            name="Change Order Rate",
            description="Change orders as a percentage of original contract value.",
            unit="%",
            target_value=5.0,
            warning_threshold=10.0,
            critical_threshold=20.0,
            measurement_method="change_order_value / contract_value * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-AEC-003",
            name="Permit Approval Cycle Time",
            description="Average days from permit submission to approval.",
            unit="days",
            target_value=30.0,
            warning_threshold=60.0,
            critical_threshold=90.0,
            measurement_method="avg(permit_approval_date - submission_date)",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-005 — Medical Practice Preset
# ---------------------------------------------------------------------------

MEDICAL_PRACTICE = IndustryPreset(
    preset_id="PRESET-005",
    name="Medical Practice",
    industry="Professional Services",
    sub_industry="Medical Practice",
    description="Patient intake, scheduling, clinical documentation, EHR management, and medical billing.",
    version="1.0.0",
    tags=["medical", "healthcare", "EHR", "HIPAA", "billing", "patient-care"],
    compatible_with=["PRESET-035", "PRESET-038"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-MED-001",
            name="Patient Intake & Scheduling",
            description="New patient registration, insurance verification, and appointment scheduling.",
            steps=[
                {
                    "step_name": "New Patient Registration",
                    "step_type": "data_collection",
                    "agent_persona": "Medical Practice Coordinator",
                    "integrations": ["Epic", "DrChrono"],
                    "compliance_gates": ["HIPAA-privacy-notice"],
                    "kpis": ["intake_cycle_time"],
                },
                {
                    "step_name": "Insurance Eligibility Verification",
                    "step_type": "automated_check",
                    "agent_persona": "Medical Billing Specialist",
                    "integrations": ["AdvancedMD", "Epic"],
                    "compliance_gates": ["CMS-billing-rules"],
                    "kpis": ["eligibility_check_time", "claim_denial_rate"],
                },
                {
                    "step_name": "Appointment Scheduling",
                    "step_type": "scheduling",
                    "agent_persona": "Medical Practice Coordinator",
                    "integrations": ["Epic", "Cerner"],
                    "compliance_gates": [],
                    "kpis": ["no_show_rate", "schedule_fill_rate"],
                },
            ],
            triggers=["patient_inquiry", "referral_received"],
            outputs=["patient_record", "scheduled_appointment", "insurance_auth"],
        ),
        WorkflowTemplate(
            template_id="WF-MED-002",
            name="Medical Billing & Claims",
            description="Charge capture, claim submission, denial management, and payment posting.",
            steps=[
                {
                    "step_name": "Charge Capture & Coding",
                    "step_type": "processing",
                    "agent_persona": "Medical Billing Specialist",
                    "integrations": ["Epic", "AdvancedMD"],
                    "compliance_gates": ["ICD-10-coding", "CPT-coding", "AMA-guidelines"],
                    "kpis": ["coding_accuracy"],
                },
                {
                    "step_name": "Claim Submission",
                    "step_type": "integration_action",
                    "agent_persona": "Medical Billing Specialist",
                    "integrations": ["AdvancedMD", "Cerner"],
                    "compliance_gates": ["CMS-1500-requirements", "HIPAA-5010"],
                    "kpis": ["clean_claim_rate"],
                },
                {
                    "step_name": "Denial Management & Appeals",
                    "step_type": "processing",
                    "agent_persona": "Medical Billing Specialist",
                    "integrations": ["AdvancedMD"],
                    "compliance_gates": ["timely-filing-limits"],
                    "kpis": ["claim_denial_rate", "denial_resolution_time"],
                },
            ],
            triggers=["encounter_complete", "claim_denied"],
            outputs=["submitted_claim", "payment_posting", "denial_appeal"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-MED-001",
            name="Medical Practice Coordinator",
            role="Front Office Coordinator",
            domain="Medical Practice",
            capabilities=["scheduling", "patient_registration", "insurance_verification", "referral_management"],
            tools=["Epic", "Cerner", "DrChrono"],
            personality_traits=["compassionate", "organized", "HIPAA-conscious"],
        ),
        AgentPersona(
            persona_id="AP-MED-002",
            name="Medical Billing Specialist",
            role="Revenue Cycle Specialist",
            domain="Medical Practice",
            capabilities=["charge_capture", "claim_submission", "denial_management", "payment_posting", "coding"],
            tools=["AdvancedMD", "Epic", "CMS-1500"],
            personality_traits=["detail-oriented", "persistent", "compliance-driven"],
        ),
        AgentPersona(
            persona_id="AP-MED-003",
            name="Clinical Documentation Specialist",
            role="Clinical Support",
            domain="Medical Practice",
            capabilities=["EHR_documentation", "SOAP_notes", "prescription_management", "care_coordination"],
            tools=["Epic", "Cerner", "DrChrono"],
            personality_traits=["thorough", "clinically-aware", "accurate"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Epic",
            connector_type="EHR",
            required=True,
            config_template={"client_id": "", "fhir_base_url": ""},
            purpose="Electronic health records, scheduling, and clinical documentation.",
        ),
        IntegrationMapping(
            connector_name="AdvancedMD",
            connector_type="practice_management",
            required=True,
            config_template={"username": "", "password": "", "office_key": ""},
            purpose="Medical billing, revenue cycle management, and patient scheduling.",
        ),
        IntegrationMapping(
            connector_name="Cerner",
            connector_type="EHR",
            required=False,
            config_template={"client_id": "", "fhir_base_url": ""},
            purpose="Alternative EHR platform for clinical workflows.",
        ),
        IntegrationMapping(
            connector_name="DrChrono",
            connector_type="EHR",
            required=False,
            config_template={"api_key": ""},
            purpose="Lightweight EHR option for small practices.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-MED-001",
            standard="HIPAA",
            description="All PHI must be handled per HIPAA Privacy and Security Rules; BAAs required for all vendors.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-MED-002",
            standard="CMS Conditions of Participation",
            description="Participation in Medicare/Medicaid requires adherence to CMS conditions including documentation standards.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-MED-003",
            standard="AMA CPT Coding Guidelines",
            description="All billable services must be coded per AMA CPT guidelines to ensure accurate reimbursement.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-MED-001",
            name="Patient Satisfaction Score",
            description="CAHPS or practice-specific satisfaction survey average score.",
            unit="score",
            target_value=4.5,
            warning_threshold=3.8,
            critical_threshold=3.0,
            measurement_method="avg(patient_satisfaction_surveys)",
        ),
        KPIDefinition(
            kpi_id="KPI-MED-002",
            name="No-Show Rate",
            description="Percentage of scheduled appointments missed without cancellation.",
            unit="%",
            target_value=5.0,
            warning_threshold=10.0,
            critical_threshold=15.0,
            measurement_method="no_shows / scheduled_appointments * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-MED-003",
            name="Claim Denial Rate",
            description="Percentage of submitted claims denied by payers.",
            unit="%",
            target_value=3.0,
            warning_threshold=7.0,
            critical_threshold=12.0,
            measurement_method="denied_claims / submitted_claims * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-006 — Dental Practice Preset
# ---------------------------------------------------------------------------

DENTAL_PRACTICE = IndustryPreset(
    preset_id="PRESET-006",
    name="Dental Practice",
    industry="Professional Services",
    sub_industry="Dental Practice",
    description="Patient scheduling, treatment planning, insurance claims, and practice analytics for dental offices.",
    version="1.0.0",
    tags=["dental", "healthcare", "HIPAA", "insurance", "treatment-planning"],
    compatible_with=["PRESET-005", "PRESET-035"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-DENTAL-001",
            name="Treatment Plan Presentation & Acceptance",
            description="Diagnose, present treatment options, obtain consent, and schedule procedures.",
            steps=[
                {
                    "step_name": "Clinical Diagnosis & Charting",
                    "step_type": "processing",
                    "agent_persona": "Dental Office Coordinator",
                    "integrations": ["Dentrix", "Carestream"],
                    "compliance_gates": ["HIPAA", "ADA-coding-standards"],
                    "kpis": ["case_acceptance_rate"],
                },
                {
                    "step_name": "Insurance Pre-Authorization",
                    "step_type": "automated_check",
                    "agent_persona": "Dental Billing Specialist",
                    "integrations": ["Dentrix", "Eaglesoft"],
                    "compliance_gates": ["ADA-CDT-codes"],
                    "kpis": ["preauth_approval_rate"],
                },
                {
                    "step_name": "Treatment Presentation & Consent",
                    "step_type": "human_review",
                    "agent_persona": "Dental Office Coordinator",
                    "integrations": ["Dentrix"],
                    "compliance_gates": ["informed-consent-requirements"],
                    "kpis": ["case_acceptance_rate"],
                },
            ],
            triggers=["exam_completed", "recall_due"],
            outputs=["signed_treatment_plan", "insurance_preauth", "scheduled_appointments"],
        ),
        WorkflowTemplate(
            template_id="WF-DENTAL-002",
            name="Insurance Claims Processing",
            description="Submit claims, track payments, and manage claim rejections.",
            steps=[
                {
                    "step_name": "Claim Submission",
                    "step_type": "integration_action",
                    "agent_persona": "Dental Billing Specialist",
                    "integrations": ["Dentrix", "Eaglesoft"],
                    "compliance_gates": ["ADA-CDT-coding", "HIPAA-5010"],
                    "kpis": ["clean_claim_rate", "collections_rate"],
                },
                {
                    "step_name": "Payment Posting & Reconciliation",
                    "step_type": "processing",
                    "agent_persona": "Dental Billing Specialist",
                    "integrations": ["Dentrix"],
                    "compliance_gates": [],
                    "kpis": ["collections_rate", "ar_days"],
                },
            ],
            triggers=["procedure_completed", "eob_received"],
            outputs=["posted_payment", "patient_statement", "ar_report"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-DENTAL-001",
            name="Dental Office Coordinator",
            role="Front Desk Coordinator",
            domain="Dental",
            capabilities=["scheduling", "patient_communication", "treatment_presentation", "recall_management"],
            tools=["Dentrix", "Carestream"],
            personality_traits=["friendly", "organized", "patient-centered"],
        ),
        AgentPersona(
            persona_id="AP-DENTAL-002",
            name="Dental Billing Specialist",
            role="Billing Coordinator",
            domain="Dental",
            capabilities=["claim_submission", "insurance_verification", "payment_posting", "denial_management"],
            tools=["Dentrix", "Eaglesoft"],
            personality_traits=["detail-oriented", "persistent", "compliance-aware"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Dentrix",
            connector_type="practice_management",
            required=True,
            config_template={"api_key": "", "site_id": ""},
            purpose="Dental practice management, scheduling, and clinical records.",
        ),
        IntegrationMapping(
            connector_name="Eaglesoft",
            connector_type="practice_management",
            required=False,
            config_template={"api_key": ""},
            purpose="Alternative dental practice management system.",
        ),
        IntegrationMapping(
            connector_name="Carestream",
            connector_type="imaging",
            required=False,
            config_template={"server_url": ""},
            purpose="Digital dental imaging and radiograph management.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-DENTAL-001",
            standard="HIPAA",
            description="Patient dental records and PHI must comply with HIPAA Privacy and Security Rules.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-DENTAL-002",
            standard="ADA Code of Ethics",
            description="Treatment recommendations must align with ADA professional standards and evidence-based dentistry.",
            required_approvals=1,
            penalty_severity="medium",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-DENTAL-003",
            standard="ADA CDT Coding",
            description="All dental procedures must be coded with current ADA Current Dental Terminology codes.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-DENTAL-001",
            name="Case Acceptance Rate",
            description="Percentage of presented treatment plans accepted by patients.",
            unit="%",
            target_value=75.0,
            warning_threshold=60.0,
            critical_threshold=45.0,
            measurement_method="accepted_plans / presented_plans * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-DENTAL-002",
            name="Collections Rate",
            description="Percentage of billed amounts actually collected.",
            unit="%",
            target_value=97.0,
            warning_threshold=92.0,
            critical_threshold=85.0,
            measurement_method="collected / billed * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-DENTAL-003",
            name="Recall Effectiveness Rate",
            description="Percentage of active patients who complete recommended recall appointments.",
            unit="%",
            target_value=70.0,
            warning_threshold=55.0,
            critical_threshold=40.0,
            measurement_method="completed_recalls / due_recalls * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-007 — Veterinary Practice Preset
# ---------------------------------------------------------------------------

VETERINARY = IndustryPreset(
    preset_id="PRESET-007",
    name="Veterinary Practice",
    industry="Professional Services",
    sub_industry="Veterinary Medicine",
    description="Animal records, appointment scheduling, pharmacy management, and client communication for veterinary clinics.",
    version="1.0.0",
    tags=["veterinary", "animal-health", "DEA", "pharmacy", "scheduling"],
    compatible_with=["PRESET-005", "PRESET-056"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-VET-001",
            name="Patient Visit & Clinical Documentation",
            description="Check-in, exam documentation, treatment, and prescription management.",
            steps=[
                {
                    "step_name": "Patient Check-In & History Review",
                    "step_type": "data_collection",
                    "agent_persona": "Veterinary Practice Coordinator",
                    "integrations": ["Cornerstone", "AVImark"],
                    "compliance_gates": ["state-vet-licensing"],
                    "kpis": ["avg_wait_time"],
                },
                {
                    "step_name": "Clinical Exam & SOAP Documentation",
                    "step_type": "processing",
                    "agent_persona": "Veterinary Clinical Agent",
                    "integrations": ["Cornerstone"],
                    "compliance_gates": ["VCPR-requirements"],
                    "kpis": ["documentation_completeness"],
                },
                {
                    "step_name": "Prescription & Pharmacy Dispensing",
                    "step_type": "processing",
                    "agent_persona": "Veterinary Clinical Agent",
                    "integrations": ["AVImark", "VetSuccess"],
                    "compliance_gates": ["DEA-controlled-substance-log", "state-pharmacy-rules"],
                    "kpis": ["avg_transaction_value"],
                },
            ],
            triggers=["appointment_start", "walk_in_arrival"],
            outputs=["visit_record", "prescription", "invoice"],
        ),
        WorkflowTemplate(
            template_id="WF-VET-002",
            name="Preventive Care Recall",
            description="Automated reminders for vaccinations, wellness exams, and heartworm tests.",
            steps=[
                {
                    "step_name": "Recall List Generation",
                    "step_type": "automated_check",
                    "agent_persona": "Veterinary Practice Coordinator",
                    "integrations": ["VetSuccess", "Cornerstone"],
                    "compliance_gates": [],
                    "kpis": ["client_retention_rate"],
                },
                {
                    "step_name": "Client Outreach Campaign",
                    "step_type": "communication",
                    "agent_persona": "Veterinary Practice Coordinator",
                    "integrations": ["VetSuccess"],
                    "compliance_gates": [],
                    "kpis": ["recall_response_rate"],
                },
            ],
            triggers=["monthly_recall_run", "vaccination_due_date"],
            outputs=["scheduled_appointments", "communication_log"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-VET-001",
            name="Veterinary Practice Coordinator",
            role="Front Office Coordinator",
            domain="Veterinary",
            capabilities=["scheduling", "client_communication", "recall_management", "invoicing"],
            tools=["Cornerstone", "AVImark", "VetSuccess"],
            personality_traits=["animal-loving", "organized", "empathetic"],
        ),
        AgentPersona(
            persona_id="AP-VET-002",
            name="Veterinary Clinical Agent",
            role="Clinical Support Specialist",
            domain="Veterinary",
            capabilities=["SOAP_documentation", "prescription_management", "DEA_log_maintenance", "lab_order_management"],
            tools=["Cornerstone", "AVImark"],
            personality_traits=["clinically-aware", "precise", "compliance-conscious"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Cornerstone",
            connector_type="practice_management",
            required=True,
            config_template={"api_key": "", "practice_id": ""},
            purpose="Veterinary practice management, records, and pharmacy.",
        ),
        IntegrationMapping(
            connector_name="AVImark",
            connector_type="practice_management",
            required=False,
            config_template={"server_url": "", "api_key": ""},
            purpose="Alternative veterinary practice management system.",
        ),
        IntegrationMapping(
            connector_name="VetSuccess",
            connector_type="analytics_crm",
            required=False,
            config_template={"api_key": ""},
            purpose="Client communication, recall campaigns, and practice analytics.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-VET-001",
            standard="DEA Controlled Substance Regulations",
            description="Controlled substances must be logged per DEA requirements including dispensing records and inventory audits.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-VET-002",
            standard="State Veterinary Licensing",
            description="All practicing veterinarians must hold current state licenses; practice must maintain facility permits.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-VET-003",
            standard="VCPR — Veterinarian-Client-Patient Relationship",
            description="Prescriptions may only be written within an established VCPR as defined by state law.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-VET-001",
            name="Client Retention Rate",
            description="Percentage of active clients returning within a 12-month period.",
            unit="%",
            target_value=75.0,
            warning_threshold=60.0,
            critical_threshold=45.0,
            measurement_method="returning_clients / active_clients * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-VET-002",
            name="Average Transaction Value",
            description="Average revenue per client visit.",
            unit="USD",
            target_value=180.0,
            warning_threshold=130.0,
            critical_threshold=90.0,
            measurement_method="total_revenue / total_visits",
        ),
        KPIDefinition(
            kpi_id="KPI-VET-003",
            name="Controlled Substance Audit Variance",
            description="Discrepancy count in controlled substance inventory audits.",
            unit="count",
            target_value=0.0,
            warning_threshold=1.0,
            critical_threshold=3.0,
            measurement_method="count(cs_inventory_discrepancies)",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-008 — Therapy & Counseling Preset
# ---------------------------------------------------------------------------

THERAPY_COUNSELING = IndustryPreset(
    preset_id="PRESET-008",
    name="Therapy & Counseling Practice",
    industry="Professional Services",
    sub_industry="Mental Health",
    description="Session management, clinical notes, insurance billing, and HIPAA-compliant communication for therapists and counselors.",
    version="1.0.0",
    tags=["therapy", "counseling", "mental-health", "HIPAA", "insurance", "sessions"],
    compatible_with=["PRESET-005", "PRESET-035"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-THERAPY-001",
            name="Client Intake & Session Management",
            description="New client onboarding through first session and ongoing session documentation.",
            steps=[
                {
                    "step_name": "Client Intake Forms",
                    "step_type": "data_collection",
                    "agent_persona": "Therapy Practice Coordinator",
                    "integrations": ["SimplePractice", "TherapyNotes"],
                    "compliance_gates": ["HIPAA-intake-forms", "informed-consent"],
                    "kpis": ["intake_completion_rate"],
                },
                {
                    "step_name": "Insurance Verification",
                    "step_type": "automated_check",
                    "agent_persona": "Therapy Billing Specialist",
                    "integrations": ["SimplePractice", "Office Ally"],
                    "compliance_gates": ["parity-law-compliance"],
                    "kpis": ["eligibility_verification_rate"],
                },
                {
                    "step_name": "Session Notes & Treatment Plan",
                    "step_type": "processing",
                    "agent_persona": "Clinical Documentation Agent",
                    "integrations": ["SimplePractice", "TherapyNotes"],
                    "compliance_gates": ["HIPAA-minimum-necessary", "state-licensing-board-note-standards"],
                    "kpis": ["session_completion_rate", "notes_timeliness"],
                },
            ],
            triggers=["new_client_referral", "session_completed"],
            outputs=["intake_packet", "session_note", "treatment_plan"],
        ),
        WorkflowTemplate(
            template_id="WF-THERAPY-002",
            name="Insurance Billing & Claims",
            description="Superbill generation, claim submission, and ERA posting.",
            steps=[
                {
                    "step_name": "Superbill / Claim Generation",
                    "step_type": "document_generation",
                    "agent_persona": "Therapy Billing Specialist",
                    "integrations": ["SimplePractice", "Office Ally"],
                    "compliance_gates": ["DSM-5-coding", "CPT-therapy-codes"],
                    "kpis": ["clean_claim_rate"],
                },
                {
                    "step_name": "Claim Submission & Tracking",
                    "step_type": "integration_action",
                    "agent_persona": "Therapy Billing Specialist",
                    "integrations": ["Office Ally"],
                    "compliance_gates": ["HIPAA-5010", "timely-filing"],
                    "kpis": ["insurance_claim_rate", "days_in_ar"],
                },
            ],
            triggers=["session_note_signed", "month_end"],
            outputs=["submitted_claim", "era_posting", "client_statement"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-THERAPY-001",
            name="Therapy Practice Coordinator",
            role="Practice Coordinator",
            domain="Mental Health",
            capabilities=["scheduling", "intake_management", "client_communication", "crisis_protocol_routing"],
            tools=["SimplePractice", "TherapyNotes"],
            personality_traits=["empathetic", "organized", "HIPAA-aware"],
        ),
        AgentPersona(
            persona_id="AP-THERAPY-002",
            name="Therapy Billing Specialist",
            role="Billing Coordinator",
            domain="Mental Health",
            capabilities=["insurance_verification", "claim_submission", "ERA_posting", "denial_management"],
            tools=["SimplePractice", "Office Ally"],
            personality_traits=["precise", "persistent", "compliance-conscious"],
        ),
        AgentPersona(
            persona_id="AP-THERAPY-003",
            name="Clinical Documentation Agent",
            role="Clinical Support",
            domain="Mental Health",
            capabilities=["session_note_drafting", "treatment_plan_management", "progress_tracking", "diagnostic_coding"],
            tools=["SimplePractice", "TherapyNotes"],
            personality_traits=["empathetic", "thorough", "confidential"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="SimplePractice",
            connector_type="practice_management",
            required=True,
            config_template={"api_key": "", "subdomain": ""},
            purpose="Practice management, scheduling, notes, and telehealth.",
        ),
        IntegrationMapping(
            connector_name="TherapyNotes",
            connector_type="practice_management",
            required=False,
            config_template={"api_key": ""},
            purpose="Alternative EHR with insurance billing integration.",
        ),
        IntegrationMapping(
            connector_name="Office Ally",
            connector_type="clearinghouse",
            required=True,
            config_template={"username": "", "password": ""},
            purpose="Insurance claim clearinghouse and ERA retrieval.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-THERAPY-001",
            standard="HIPAA",
            description="All PHI including session notes must be encrypted, access-controlled, and covered by BAAs.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-THERAPY-002",
            standard="State Licensing Board Requirements",
            description="Session documentation must meet state-specific licensing board standards for note-keeping and supervision.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-THERAPY-003",
            standard="Mental Health Parity Act",
            description="Insurance billing must comply with the Mental Health Parity and Addiction Equity Act.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-THERAPY-001",
            name="Session Completion Rate",
            description="Percentage of scheduled sessions that are completed (not cancelled/no-show).",
            unit="%",
            target_value=85.0,
            warning_threshold=75.0,
            critical_threshold=65.0,
            measurement_method="completed_sessions / scheduled_sessions * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-THERAPY-002",
            name="Insurance Claim Acceptance Rate",
            description="Percentage of claims accepted by payers on first submission.",
            unit="%",
            target_value=95.0,
            warning_threshold=88.0,
            critical_threshold=78.0,
            measurement_method="accepted_claims / submitted_claims * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-THERAPY-003",
            name="Average Client Tenure",
            description="Average number of sessions per client before discharge.",
            unit="sessions",
            target_value=16.0,
            warning_threshold=8.0,
            critical_threshold=4.0,
            measurement_method="avg(sessions_per_discharged_client)",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-009 — Real Estate Preset
# ---------------------------------------------------------------------------

REAL_ESTATE = IndustryPreset(
    preset_id="PRESET-009",
    name="Real Estate Brokerage",
    industry="Professional Services",
    sub_industry="Real Estate",
    description="Listing management, buyer/seller CRM, transaction coordination, and MLS integration.",
    version="1.0.0",
    tags=["real-estate", "listings", "MLS", "transactions", "CRM", "RESPA"],
    compatible_with=["PRESET-001", "PRESET-002"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-RE-001",
            name="Listing to Close",
            description="Manage property listings from intake through closing.",
            steps=[
                {
                    "step_name": "Listing Agreement & MLS Entry",
                    "step_type": "document_generation",
                    "agent_persona": "Transaction Coordinator",
                    "integrations": ["MLS", "DocuSign", "Zillow"],
                    "compliance_gates": ["Fair-Housing-Act", "RESPA-disclosures"],
                    "kpis": ["days_to_mls_listing"],
                },
                {
                    "step_name": "Offer Review & Negotiation",
                    "step_type": "human_review",
                    "agent_persona": "Real Estate CRM Agent",
                    "integrations": ["Salesforce", "DocuSign"],
                    "compliance_gates": ["disclosure-requirements", "earnest-money-handling"],
                    "kpis": ["offer_to_acceptance_time"],
                },
                {
                    "step_name": "Transaction Coordination & Close",
                    "step_type": "processing",
                    "agent_persona": "Transaction Coordinator",
                    "integrations": ["DocuSign", "MLS", "Salesforce"],
                    "compliance_gates": ["RESPA-settlement-statement", "title-clearance"],
                    "kpis": ["list_to_sell_ratio", "days_on_market"],
                },
            ],
            triggers=["listing_agreement_signed", "offer_received"],
            outputs=["mls_listing", "accepted_contract", "closed_transaction"],
        ),
        WorkflowTemplate(
            template_id="WF-RE-002",
            name="Buyer Lead Management",
            description="Capture, qualify, and nurture buyer leads to active client status.",
            steps=[
                {
                    "step_name": "Lead Capture & CRM Entry",
                    "step_type": "data_collection",
                    "agent_persona": "Real Estate CRM Agent",
                    "integrations": ["Salesforce", "Zillow"],
                    "compliance_gates": [],
                    "kpis": ["lead_response_time"],
                },
                {
                    "step_name": "Pre-Qualification & Buyer Consultation",
                    "step_type": "communication",
                    "agent_persona": "Real Estate CRM Agent",
                    "integrations": ["Salesforce"],
                    "compliance_gates": ["Fair-Housing-Act"],
                    "kpis": ["lead_to_client_conversion_rate"],
                },
            ],
            triggers=["lead_form_submission", "zillow_inquiry"],
            outputs=["qualified_buyer_record", "buyer_consultation_notes"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-RE-001",
            name="Transaction Coordinator",
            role="Transaction Specialist",
            domain="Real Estate",
            capabilities=["listing_management", "contract_coordination", "deadline_tracking", "closing_management"],
            tools=["MLS", "DocuSign", "Salesforce"],
            personality_traits=["organized", "deadline-driven", "detail-oriented"],
        ),
        AgentPersona(
            persona_id="AP-RE-002",
            name="Real Estate CRM Agent",
            role="Sales & Marketing Coordinator",
            domain="Real Estate",
            capabilities=["lead_management", "buyer_qualification", "market_analysis", "listing_marketing"],
            tools=["Salesforce", "Zillow", "DocuSign"],
            personality_traits=["persuasive", "responsive", "market-savvy"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="MLS",
            connector_type="listing_service",
            required=True,
            config_template={"member_id": "", "rets_url": "", "api_key": ""},
            purpose="Multiple Listing Service for property listings and market data.",
        ),
        IntegrationMapping(
            connector_name="DocuSign",
            connector_type="esignature",
            required=True,
            config_template={"integration_key": "", "account_id": ""},
            purpose="Electronic signatures for contracts, disclosures, and agreements.",
        ),
        IntegrationMapping(
            connector_name="Salesforce",
            connector_type="crm",
            required=True,
            config_template={"client_id": "", "instance_url": ""},
            purpose="CRM for lead management, client relationships, and pipeline tracking.",
        ),
        IntegrationMapping(
            connector_name="Zillow",
            connector_type="listing_portal",
            required=False,
            config_template={"api_key": ""},
            purpose="Listing syndication and buyer lead capture.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-RE-001",
            standard="RESPA",
            description="Real Estate Settlement Procedures Act requires disclosure of all settlement costs and prohibits kickbacks.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-RE-002",
            standard="Fair Housing Act",
            description="No discrimination in housing based on race, color, national origin, religion, sex, disability, or family status.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-RE-003",
            standard="State License Law",
            description="All agents must hold current state real estate licenses; brokerage must maintain sponsorship records.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-RE-001",
            name="Days on Market",
            description="Average number of days listed properties remain active before going under contract.",
            unit="days",
            target_value=30.0,
            warning_threshold=60.0,
            critical_threshold=90.0,
            measurement_method="avg(contract_date - list_date)",
        ),
        KPIDefinition(
            kpi_id="KPI-RE-002",
            name="List-to-Sell Price Ratio",
            description="Average sale price as a percentage of original list price.",
            unit="%",
            target_value=98.0,
            warning_threshold=95.0,
            critical_threshold=90.0,
            measurement_method="avg(sale_price / list_price * 100)",
        ),
        KPIDefinition(
            kpi_id="KPI-RE-003",
            name="Lead Conversion Rate",
            description="Percentage of captured leads that convert to closed transactions.",
            unit="%",
            target_value=5.0,
            warning_threshold=3.0,
            critical_threshold=1.5,
            measurement_method="closed_transactions / total_leads * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# Module export
# ---------------------------------------------------------------------------

ALL_PROFESSIONAL_PRESETS: List[IndustryPreset] = [
    LEGAL_PRACTICE,
    ACCOUNTING_FIRM,
    CONSULTING,
    ARCHITECTURE_ENGINEERING,
    MEDICAL_PRACTICE,
    DENTAL_PRACTICE,
    VETERINARY,
    THERAPY_COUNSELING,
    REAL_ESTATE,
]
