# © 2020 Inoni Limited Liability Company · Creator: Corey Post · License: BSL 1.1
"""Task catalog: 127-task onboarding DAG for Murphy's business infrastructure."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class OnboardingTask:
    task_id: str
    section: str
    title: str
    description: str
    why: str
    target_url: str
    time_estimate_minutes: int
    task_type: str          # "human_required"|"agent_assisted"|"agent_auto"|"recurring"
    hitl_level: str         # "auto"|"needs_review"|"blocked_human_required"
    category: str           # "grant"|"api_key"|"cloud_credit"|"compliance"|"marketplace"|"financing"|"international"
    value_type: str         # "free_money"|"revenue_channel"|"prerequisite"|"trust_signal"
    estimated_value: Optional[str]
    depends_on: List[str]
    blocks: List[str]       # computed reverse of depends_on
    external_wait_days: Optional[int]
    is_conditional: bool
    condition: Optional[str]
    recurrence: Optional[str]
    prefill_fields: Dict[str, str]


# ---------------------------------------------------------------------------
# Raw task definitions (blocks computed after)
# ---------------------------------------------------------------------------

_RAW: List[dict] = [
    # ── Section 1 — Federal Identity ──────────────────────────────────────
    dict(task_id="1.01", section="1", title="SAM.gov registration",
         description="Register your business in the System for Award Management",
         why="Required for all federal grants, contracts, and SBIR applications",
         target_url="https://sam.gov",
         time_estimate_minutes=60, task_type="human_required",
         hitl_level="blocked_human_required", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.02"], external_wait_days=10,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"legal_name": "company_name", "ein": "ein", "address": "address"}),
    dict(task_id="1.02", section="1", title="Get EIN from IRS",
         description="Apply for Employer Identification Number from IRS online",
         why="EIN required for SAM.gov, banking, and all federal filings",
         target_url="https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online",
         time_estimate_minutes=5, task_type="human_required",
         hitl_level="blocked_human_required", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"legal_name": "company_name", "state": "state"}),
    dict(task_id="1.03", section="1", title="Grants.gov account",
         description="Create account on Grants.gov federal grant portal",
         why="Required to apply for most federal grants",
         target_url="https://www.grants.gov/register",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name", "ein": "ein"}),
    dict(task_id="1.04", section="1", title="NAICS code selection",
         description="Select appropriate NAICS codes for your business activities",
         why="Required for SAM.gov and determines grant eligibility",
         target_url="https://www.naics.com/search/",
         time_estimate_minutes=5, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="1.05", section="1", title="SBIR.gov registration",
         description="Register on the SBIR/STTR funding portal",
         why="Required to apply for SBIR and STTR grants",
         target_url="https://www.sbir.gov/registration",
         time_estimate_minutes=20, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name", "ein": "ein"}),
    dict(task_id="1.06", section="1", title="Research.gov account",
         description="Create account on NSF Research.gov portal",
         why="Required for NSF grant applications and research reporting",
         target_url="https://www.research.gov/research-web/homepage",
         time_estimate_minutes=15, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="1.07", section="1", title="NIST MEP registration",
         description="Register with NIST Manufacturing Extension Partnership",
         why="Enables access to manufacturing grants and technical assistance",
         target_url="https://www.nist.gov/mep",
         time_estimate_minutes=20, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="1.08", section="1", title="CAGE code confirmation",
         description="Verify CAGE code assigned during SAM.gov registration",
         why="CAGE code is required for defense contracts and some grants",
         target_url="https://sam.gov",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="1.09", section="1", title="SAM.gov annual renewal reminder",
         description="Set reminder for annual SAM.gov registration renewal",
         why="SAM.gov registration expires annually — lapse blocks all federal work",
         target_url="https://sam.gov",
         time_estimate_minutes=15, task_type="recurring",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="annual", prefill_fields={}),
    dict(task_id="1.10", section="1", title="DUNS to UEI migration verification",
         description="Verify migration from DUNS number to Unique Entity ID in SAM.gov",
         why="DUNS deprecated; UEI is now required for all federal interactions",
         target_url="https://sam.gov",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 2 — Grant Applications Track A ────────────────────────────
    dict(task_id="2.01", section="2", title="SBIR Phase I application",
         description="Apply for NSF/DoD/NIH SBIR Phase I grant",
         why="Up to $275K non-dilutive funding for early R&D",
         target_url="https://www.sbir.gov/apply",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$275K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name", "ein": "ein"}),
    dict(task_id="2.02", section="2", title="STTR Phase I application",
         description="Apply for STTR Phase I grant with research institution partner",
         why="Up to $275K for joint industry-university R&D",
         target_url="https://www.sbir.gov/apply",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$275K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name", "ein": "ein"}),
    dict(task_id="2.03", section="2", title="DOE ARPA-E application",
         description="Apply for DOE Advanced Research Projects Agency Energy grant",
         why="Up to $5M for transformative energy technology R&D",
         target_url="https://arpa-e.energy.gov/technologies/apply-project",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$500K-$5M", depends_on=["1.01", "1.03"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.04", section="2", title="NSF SBIR application",
         description="Apply for NSF Seed Fund SBIR/STTR grant",
         why="Up to $2M for deep-tech commercialization",
         target_url="https://seedfund.nsf.gov/apply/",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$275K-$2M", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.05", section="2", title="DoD SBIR application",
         description="Apply for Department of Defense SBIR grant",
         why="Up to $2M for defense-relevant technology R&D",
         target_url="https://www.defense.gov/sbir",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$2M", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.06", section="2", title="DOE Office of Science grant",
         description="Apply for DOE Office of Science research grant",
         why="Up to $1M for fundamental energy science research",
         target_url="https://science.osti.gov/grants",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$100K-$1M", depends_on=["1.01", "1.03"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.07", section="2", title="USDA SBIR grant",
         description="Apply for USDA National Institute of Food and Agriculture SBIR grant",
         why="Up to $500K for agricultural technology innovation",
         target_url="https://nifa.usda.gov/program/small-business-innovation-research-program-sbir",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$100K-$500K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.08", section="2", title="EPA SBIR grant",
         description="Apply for EPA Small Business Innovation Research grant",
         why="Up to $400K for environmental technology innovation",
         target_url="https://www.epa.gov/sbir",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$100K-$400K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.09", section="2", title="NIH SBIR grant",
         description="Apply for NIH SEED Small Business Funding grant",
         why="Up to $1.7M for healthcare and biomedical innovation",
         target_url="https://seed.nih.gov/small-business-funding/apply",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$1.7M", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.10", section="2", title="DHS SBIR grant",
         description="Apply for Department of Homeland Security SBIR grant",
         why="Up to $750K for homeland security technology",
         target_url="https://www.dhs.gov/science-and-technology/sbir",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$750K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.11", section="2", title="NASA SBIR grant",
         description="Apply for NASA Small Business Innovation Research grant",
         why="Up to $750K for aerospace and exploration technology",
         target_url="https://sbir.nasa.gov",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$125K-$750K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.12", section="2", title="DOT SBIR grant",
         description="Apply for Department of Transportation SBIR grant",
         why="Up to $750K for transportation technology innovation",
         target_url="https://www.transportation.gov/sbir",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$750K", depends_on=["1.01", "1.03", "1.05"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.13", section="2", title="NSF RAISE grant",
         description="Apply for NSF Research Advanced by Interdisciplinary Science and Engineering grant",
         why="Up to $5M for high-risk interdisciplinary research",
         target_url="https://www.nsf.gov/funding/opportunities/raise",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$1M-$5M", depends_on=["1.01", "1.03"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.14", section="2", title="IRA DOE efficiency grant",
         description="Apply for Inflation Reduction Act DOE energy efficiency grant",
         why="Up to $500K for energy efficiency technology deployment",
         target_url="https://www.energy.gov/scep/slsc/ira",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$100K-$500K", depends_on=["1.01", "1.03"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.15", section="2", title="EDA Build to Scale grant",
         description="Apply for Economic Development Administration Build to Scale grant",
         why="Up to $1.5M for regional innovation ecosystem development",
         target_url="https://eda.gov/programs/buildtoscale",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$100K-$1.5M", depends_on=["1.01", "1.03"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.16", section="2", title="NIST Manufacturing Extension program",
         description="Enroll in NIST MEP technical assistance program",
         why="Up to $200K in manufacturing technical assistance",
         target_url="https://www.nist.gov/mep",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="$50K-$200K", depends_on=["1.01", "1.07"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name"}),
    dict(task_id="2.17", section="2", title="R&D Tax Credit application",
         description="Apply for federal R&D tax credit (Section 41)",
         why="15-20% credit on qualified R&D expenses — significant cash recovery",
         target_url="https://www.irs.gov/businesses/small-businesses-self-employed/research-credit",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value="15-20% of qualified R&D spend", depends_on=["1.02"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"ein": "ein", "company_name": "company_name"}),
    dict(task_id="2.18", section="2", title="SBA 7(a) loan application",
         description="Apply for SBA 7(a) small business loan",
         why="Up to $5M in SBA-guaranteed financing for working capital",
         target_url="https://www.sba.gov/funding-programs/loans/7a-loans",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value="Up to $5M", depends_on=["1.01", "1.02"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name", "ein": "ein"}),
    dict(task_id="2.19", section="2", title="SBA 504 loan application",
         description="Apply for SBA 504 loan for fixed assets",
         why="Up to $5.5M in below-market financing for equipment and real estate",
         target_url="https://www.sba.gov/funding-programs/loans/504-loans",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value="Up to $5.5M", depends_on=["1.01", "1.02"],
         external_wait_days=None, is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"company_name": "company_name", "ein": "ein"}),

    # ── Section 3 — Customer Financing Track B ────────────────────────────
    dict(task_id="3.01", section="3", title="C-PACE commercial financing registration",
         description="Register for Commercial Property Assessed Clean Energy financing",
         why="Enables long-term low-cost energy financing for commercial customers",
         target_url="https://www.pacenation.org",
         time_estimate_minutes=60, task_type="human_required",
         hitl_level="blocked_human_required", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.02", section="3", title="On-bill financing utility registration",
         description="Register for utility on-bill financing program",
         why="Enables customers to finance upgrades through utility bills",
         target_url="https://www.energy.gov/eere/better-buildings/financing-navigation-tool",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.03", section="3", title="Property Assessed Clean Energy eligibility check",
         description="Check PACE financing eligibility for customer properties",
         why="Identify eligible customers for PACE financing opportunities",
         target_url="https://www.pacenation.org/pace-market-data/",
         time_estimate_minutes=15, task_type="agent_auto",
         hitl_level="auto", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.04", section="3", title="Affirm business financing",
         description="Set up Affirm BNPL for business customer financing",
         why="Increases deal close rates by offering installment payment options",
         target_url="https://www.affirm.com/business",
         time_estimate_minutes=45, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.10"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.05", section="3", title="Klarna business financing",
         description="Set up Klarna BNPL for business customer financing",
         why="Increases deal close rates with buy-now-pay-later options",
         target_url="https://www.klarna.com/us/business/",
         time_estimate_minutes=45, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.10"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.06", section="3", title="Afterpay business account",
         description="Set up Afterpay for business customer financing",
         why="Enables 4-installment payment plans for customers",
         target_url="https://www.afterpay.com/en-US/business",
         time_estimate_minutes=45, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.10"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.07", section="3", title="Splitit merchant account",
         description="Set up Splitit installment payment solution",
         why="Enables interest-free installments using existing credit cards",
         target_url="https://www.splitit.com/merchants/",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.10"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.08", section="3", title="PayBright merchant account",
         description="Set up PayBright Canadian BNPL solution",
         why="Enables Canadian customer financing through Affirm partner",
         target_url="https://www.paybright.com/merchant/",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.11"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.09", section="3", title="Green financing program registration",
         description="Register with Green America green business financing program",
         why="Access to green financing options and sustainability certification",
         target_url="https://www.greenamerica.org/green-business",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="revenue_channel",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="3.10", section="3", title="ENERGY STAR partner registration",
         description="Register as ENERGY STAR partner",
         why="ENERGY STAR certification enables premium pricing and financing access",
         target_url="https://www.energystar.gov/partner_resources/become_a_partner",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="financing", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 4 — Cloud Credits ─────────────────────────────────────────
    dict(task_id="4.01", section="4", title="AWS Activate credits",
         description="Apply for AWS Activate startup cloud credits",
         why="Up to $100K in AWS credits for infrastructure costs",
         target_url="https://aws.amazon.com/activate/",
         time_estimate_minutes=15, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$100K credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.02", section="4", title="Google Cloud Startup credits",
         description="Apply for Google Cloud for Startups program credits",
         why="Up to $200K in GCP credits",
         target_url="https://cloud.google.com/startup",
         time_estimate_minutes=15, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$200K credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.03", section="4", title="Microsoft Azure Founders Hub",
         description="Apply for Microsoft for Startups Founders Hub Azure credits",
         why="Up to $150K in Azure credits plus GitHub Copilot access",
         target_url="https://www.microsoft.com/en-us/startups",
         time_estimate_minutes=15, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$150K credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.04", section="4", title="NVIDIA Inception Program",
         description="Apply for NVIDIA Inception startup program GPU credits",
         why="Up to $50K in GPU compute credits for AI workloads",
         target_url="https://www.nvidia.com/en-us/startups/",
         time_estimate_minutes=20, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$50K GPU credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.05", section="4", title="IBM Startup Program",
         description="Apply for IBM for Startups program cloud credits",
         why="Up to $120K in IBM Cloud credits",
         target_url="https://developer.ibm.com/startups/",
         time_estimate_minutes=15, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$120K credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.06", section="4", title="Oracle for Startups",
         description="Apply for Oracle for Startups cloud credits program",
         why="Up to $100K in Oracle Cloud credits",
         target_url="https://www.oracle.com/startup/",
         time_estimate_minutes=15, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$100K credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.07", section="4", title="Hugging Face Startup Program",
         description="Apply for Hugging Face startup program compute credits",
         why="$5K in compute credits for ML model training and inference",
         target_url="https://huggingface.co/startups",
         time_estimate_minutes=10, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$5K compute credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="4.08", section="4", title="Vultr Startup Program",
         description="Apply for Vultr startup program cloud credits",
         why="$1K in Vultr Cloud credits for infrastructure",
         target_url="https://www.vultr.com/promo/startup/",
         time_estimate_minutes=10, task_type="agent_assisted",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value="$1K credits", depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 5 — API Keys & Developer Accounts ─────────────────────────
    dict(task_id="5.01", section="5", title="OpenAI API key",
         description="Create OpenAI developer account and obtain API key",
         why="Required for GPT-4/o1 model access in Murphy AI features",
         target_url="https://platform.openai.com/signup",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.02", section="5", title="Anthropic API key",
         description="Create Anthropic account and obtain Claude API key",
         why="Required for Claude model access in Murphy AI features",
         target_url="https://console.anthropic.com/login",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.03", section="5", title="Google AI Studio key",
         description="Create Google AI Studio account and obtain Gemini API key",
         why="Required for Gemini model access",
         target_url="https://aistudio.google.com/app/apikey",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.04", section="5", title="Cohere API key",
         description="Create Cohere developer account and obtain API key",
         why="Required for Command/Embed model access",
         target_url="https://dashboard.cohere.com/api-keys",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.05", section="5", title="Mistral API key",
         description="Create Mistral AI account and obtain API key",
         why="Required for Mistral model access",
         target_url="https://console.mistral.ai/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.06", section="5", title="Together AI key",
         description="Create Together AI account and obtain API key",
         why="Required for open-source model inference at scale",
         target_url="https://api.together.xyz/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.07", section="5", title="HubSpot API key",
         description="Create HubSpot developer account and obtain API key",
         why="Required for CRM integration and marketing automation",
         target_url="https://app.hubspot.com/signup",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.08", section="5", title="Salesforce developer account",
         description="Create Salesforce developer edition account",
         why="Required for Salesforce CRM integration development",
         target_url="https://developer.salesforce.com/signup",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.09", section="5", title="Salesforce API key",
         description="Obtain Salesforce Connected App API credentials",
         why="Required for Salesforce CRM data integration",
         target_url="https://developer.salesforce.com/signup",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.10", section="5", title="Stripe API key",
         description="Create Stripe account and obtain API keys",
         why="Required for payment processing and billing automation",
         target_url="https://dashboard.stripe.com/register",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.11", section="5", title="PayPal developer account",
         description="Create PayPal developer account and obtain API credentials",
         why="Required for PayPal payment processing integration",
         target_url="https://developer.paypal.com/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.12", section="5", title="Twilio API key",
         description="Create Twilio account and obtain API keys",
         why="Required for SMS, voice, and communication automation",
         target_url="https://www.twilio.com/try-twilio",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.13", section="5", title="SendGrid API key",
         description="Create SendGrid account and obtain API key",
         why="Required for transactional email delivery",
         target_url="https://signup.sendgrid.com/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.14", section="5", title="Mailchimp API key",
         description="Create Mailchimp account and obtain API key",
         why="Required for email marketing automation",
         target_url="https://login.mailchimp.com/signup/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.15", section="5", title="Slack app token",
         description="Create Slack app and obtain OAuth token",
         why="Required for Slack workspace integration and notifications",
         target_url="https://api.slack.com/apps",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.16", section="5", title="Microsoft Teams app",
         description="Register Microsoft Teams app in developer portal",
         why="Required for Teams workspace integration",
         target_url="https://dev.teams.microsoft.com/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.17", section="5", title="Zoom API key",
         description="Create Zoom marketplace app and obtain API credentials",
         why="Required for video conferencing integration",
         target_url="https://marketplace.zoom.us/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.18", section="5", title="GitHub personal token",
         description="Generate GitHub personal access token",
         why="Required for GitHub API access and CI/CD automation",
         target_url="https://github.com/settings/tokens",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.19", section="5", title="GitLab API token",
         description="Generate GitLab personal access token",
         why="Required for GitLab API access",
         target_url="https://gitlab.com/-/user_settings/personal_access_tokens",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.20", section="5", title="Jira API token",
         description="Generate Atlassian/Jira API token",
         why="Required for Jira project management integration",
         target_url="https://id.atlassian.com/manage-profile/security/api-tokens",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.21", section="5", title="AWS IAM key",
         description="Create AWS IAM user and obtain access key credentials",
         why="Required for AWS API access and infrastructure automation",
         target_url="https://console.aws.amazon.com/iam/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.22", section="5", title="Cloudflare API key",
         description="Create Cloudflare account and obtain API key",
         why="Required for DNS management, CDN, and DDoS protection",
         target_url="https://dash.cloudflare.com/sign-up",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.23", section="5", title="Datadog API key",
         description="Create Datadog account and obtain API key",
         why="Required for infrastructure monitoring and APM",
         target_url="https://app.datadoghq.com/account/settings",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.24", section="5", title="PagerDuty API key",
         description="Create PagerDuty account and obtain API key",
         why="Required for incident management and on-call automation",
         target_url="https://www.pagerduty.com/sign-up/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.25", section="5", title="Snowflake trial account",
         description="Create Snowflake trial account",
         why="Required for cloud data warehouse capabilities",
         target_url="https://signup.snowflake.com/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.26", section="5", title="Databricks trial",
         description="Create Databricks community edition account",
         why="Required for Apache Spark and ML pipeline capabilities",
         target_url="https://www.databricks.com/try-databricks",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.27", section="5", title="Tableau API key",
         description="Obtain Tableau REST API credentials",
         why="Required for data visualization integration",
         target_url="https://www.tableau.com/products/trial",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.28", section="5", title="Power BI embed key",
         description="Obtain Power BI Embedded API credentials",
         why="Required for Power BI dashboard embedding",
         target_url="https://powerbi.microsoft.com/en-us/get-started/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.29", section="5", title="Zapier API key",
         description="Create Zapier developer account and obtain API key",
         why="Required for no-code automation integrations",
         target_url="https://developer.zapier.com/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.30", section="5", title="Make (Integromat) API key",
         description="Create Make.com account and obtain API key",
         why="Required for visual workflow automation platform",
         target_url="https://www.make.com/en/register",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.31", section="5", title="n8n cloud account",
         description="Create n8n cloud account",
         why="Required for open-source workflow automation",
         target_url="https://app.n8n.cloud/register",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.32", section="5", title="DocuSign API key",
         description="Create DocuSign developer account and obtain API key",
         why="Required for e-signature workflow automation",
         target_url="https://developers.docusign.com/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.33", section="5", title="Adobe Sign API key",
         description="Create Adobe Sign developer account and obtain API key",
         why="Required for Adobe e-signature integration",
         target_url="https://www.adobe.com/sign/api.html",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.34", section="5", title="Plaid API key",
         description="Create Plaid developer account and obtain API key",
         why="Required for bank account verification and financial data access",
         target_url="https://dashboard.plaid.com/signup",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.35", section="5", title="Brex API key",
         description="Create Brex business account and obtain API key",
         why="Required for corporate card and expense management integration",
         target_url="https://www.brex.com/signup",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.36", section="5", title="QuickBooks API key",
         description="Create Intuit developer account and obtain QuickBooks API key",
         why="Required for accounting and financial reporting integration",
         target_url="https://developer.intuit.com/app/developer/qbo/docs/get-started",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.37", section="5", title="Xero API key",
         description="Create Xero developer account and obtain API key",
         why="Required for Xero accounting integration",
         target_url="https://developer.xero.com/documentation/getting-started-guide/",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.38", section="5", title="Shopify partner account",
         description="Create Shopify Partner account and obtain API credentials",
         why="Required for Shopify app development and e-commerce integration",
         target_url="https://partners.shopify.com/signup",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.39", section="5", title="WooCommerce API key",
         description="Generate WooCommerce REST API key",
         why="Required for WooCommerce e-commerce integration",
         target_url="https://woocommerce.com/document/woocommerce-rest-api/",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.40", section="5", title="Magento API key",
         description="Generate Magento REST API integration credentials",
         why="Required for Magento e-commerce platform integration",
         target_url="https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication.html",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.41", section="5", title="Twitch API key",
         description="Register Twitch app and obtain client credentials",
         why="Required for Twitch streaming and community integration",
         target_url="https://dev.twitch.tv/console",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.42", section="5", title="YouTube Data API key",
         description="Enable YouTube Data API and obtain API key in GCP Console",
         why="Required for YouTube content and analytics integration",
         target_url="https://console.cloud.google.com/apis/library/youtube.googleapis.com",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.43", section="5", title="LinkedIn API key",
         description="Create LinkedIn app and obtain OAuth credentials",
         why="Required for LinkedIn marketing and professional network integration",
         target_url="https://www.linkedin.com/developers/apps",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.44", section="5", title="Twitter/X API key",
         description="Create Twitter/X developer app and obtain API credentials",
         why="Required for social media automation and engagement",
         target_url="https://developer.twitter.com/en/portal/dashboard",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.45", section="5", title="GCP service account",
         description="Create GCP service account and download JSON key",
         why="Required for Google Cloud API access and automation",
         target_url="https://console.cloud.google.com/iam-admin/serviceaccounts",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.46", section="5", title="Azure service principal",
         description="Create Azure Active Directory service principal",
         why="Required for Azure API access and resource automation",
         target_url="https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps",
         time_estimate_minutes=10, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.47", section="5", title="DigitalOcean API key",
         description="Create DigitalOcean personal access token",
         why="Required for DigitalOcean cloud infrastructure management",
         target_url="https://cloud.digitalocean.com/account/api/tokens",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.48", section="5", title="Heroku API key",
         description="Obtain Heroku API key from account settings",
         why="Required for Heroku PaaS deployment automation",
         target_url="https://dashboard.heroku.com/account",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.49", section="5", title="Vercel API key",
         description="Create Vercel personal access token",
         why="Required for Vercel frontend deployment automation",
         target_url="https://vercel.com/account/tokens",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="5.50", section="5", title="Netlify personal access token",
         description="Create Netlify personal access token",
         why="Required for Netlify JAMstack deployment automation",
         target_url="https://app.netlify.com/user/applications",
         time_estimate_minutes=5, task_type="agent_auto",
         hitl_level="auto", category="api_key", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 6 — Security & Compliance ─────────────────────────────────
    dict(task_id="6.01", section="6", title="SOC 2 Type II audit",
         description="Initiate SOC 2 Type II compliance audit",
         why="Enterprise trust signal enabling Fortune 500 procurement",
         target_url="https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services",
         time_estimate_minutes=2400, task_type="human_required",
         hitl_level="blocked_human_required", category="compliance", value_type="trust_signal",
         estimated_value="enterprise trust", depends_on=[], external_wait_days=None,
         is_conditional=True, condition="annual_revenue>500000", recurrence=None,
         prefill_fields={}),
    dict(task_id="6.02", section="6", title="ISO 27001 certification",
         description="Initiate ISO 27001 information security management certification",
         why="International security standard required for enterprise and government customers",
         target_url="https://www.iso.org/isoiec-27001-information-security.html",
         time_estimate_minutes=4800, task_type="human_required",
         hitl_level="blocked_human_required", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=True, condition="annual_revenue>500000", recurrence=None,
         prefill_fields={}),
    dict(task_id="6.03", section="6", title="IEC 62443 certification",
         description="Obtain IEC 62443 industrial cybersecurity certification",
         why="Required for industrial control system customers",
         target_url="https://www.iec.ch/homepage",
         time_estimate_minutes=4800, task_type="human_required",
         hitl_level="blocked_human_required", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=True, condition="has_ics_customers=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="6.04", section="6", title="NIST CSF self-assessment",
         description="Complete NIST Cybersecurity Framework self-assessment",
         why="Baseline security posture assessment — required for FedRAMP readiness",
         target_url="https://www.nist.gov/cyberframework",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="6.05", section="6", title="CIS Controls self-assessment",
         description="Complete Center for Internet Security Controls self-assessment",
         why="Establishes security controls baseline for enterprise sales",
         target_url="https://www.cisecurity.org/controls/",
         time_estimate_minutes=90, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="6.06", section="6", title="GDPR compliance review",
         description="Complete GDPR compliance checklist and implement required controls",
         why="Required for EU customer data processing",
         target_url="https://gdpr.eu/checklist/",
         time_estimate_minutes=180, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="6.07", section="6", title="CCPA compliance review",
         description="Complete California Consumer Privacy Act compliance review",
         why="Required for California consumer data processing",
         target_url="https://oag.ca.gov/privacy/ccpa",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="6.08", section="6", title="FedRAMP readiness assessment",
         description="Complete FedRAMP readiness assessment for federal cloud authorization",
         why="Required for federal government cloud sales",
         target_url="https://www.fedramp.gov/program-basics/",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=["6.04"], external_wait_days=None,
         is_conditional=True, condition="has_federal_customers=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="6.09", section="6", title="HIPAA risk assessment",
         description="Complete HIPAA security risk assessment",
         why="Required for healthcare customer data processing",
         target_url="https://www.hhs.gov/hipaa/for-professionals/security/guidance/index.html",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=True, condition="has_healthcare_customers=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="6.10", section="6", title="PCI DSS compliance review",
         description="Complete PCI DSS compliance review for payment card processing",
         why="Required for accepting and storing payment card data",
         target_url="https://www.pcisecuritystandards.org/pci_security/starting_point",
         time_estimate_minutes=180, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=["5.10", "5.11"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="6.11", section="6", title="Privacy policy & ToS publication",
         description="Generate and publish privacy policy and terms of service",
         why="Legal requirement for any customer-facing product",
         target_url="https://app.termly.io/signup",
         time_estimate_minutes=60, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="6.12", section="6", title="Vulnerability disclosure program",
         description="Set up coordinated vulnerability disclosure program",
         why="Security best practice required for enterprise and government customers",
         target_url="https://www.cisa.gov/coordinated-vulnerability-disclosure-process",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 7 — Marketplace & Partner Listings ────────────────────────
    dict(task_id="7.01", section="7", title="AWS Marketplace listing",
         description="Create AWS Marketplace product listing",
         why="Access to 300K+ AWS customers with simplified procurement",
         target_url="https://aws.amazon.com/marketplace/management/tour/",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.21"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.02", section="7", title="Google Cloud Marketplace listing",
         description="Create Google Cloud Marketplace product listing",
         why="Access to GCP customers with integrated billing",
         target_url="https://cloud.google.com/marketplace/docs/partners",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.45"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.03", section="7", title="Azure Marketplace listing",
         description="Create Microsoft Azure Marketplace product listing",
         why="Access to Azure customers through Microsoft commercial marketplace",
         target_url="https://partner.microsoft.com/en-us/solutions/microsoft-commercial-marketplace",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.46"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.04", section="7", title="Salesforce AppExchange listing",
         description="Create Salesforce AppExchange partner app listing",
         why="Access to 150K+ Salesforce customers globally",
         target_url="https://partners.salesforce.com/partnerProgram/s/",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.09"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.05", section="7", title="HubSpot App Marketplace listing",
         description="Create HubSpot App Marketplace listing",
         why="Access to HubSpot's 177K+ customers",
         target_url="https://developers.hubspot.com/docs/api/creating-an-app",
         time_estimate_minutes=180, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.07"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.06", section="7", title="Zapier integration listing",
         description="Create Zapier public integration listing",
         why="Access to 6M+ Zapier users for no-code automation",
         target_url="https://platform.zapier.com/",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.29"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.07", section="7", title="Make (Integromat) app listing",
         description="Create Make.com public app/integration listing",
         why="Access to Make.com automation users",
         target_url="https://www.make.com/en/integrations",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.30"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.08", section="7", title="Shopify App Store listing",
         description="Submit app to Shopify App Store",
         why="Access to 1M+ Shopify merchants",
         target_url="https://shopify.dev/apps/getting-started",
         time_estimate_minutes=180, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.38"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.09", section="7", title="G Suite Marketplace listing",
         description="Create Google Workspace Marketplace listing",
         why="Access to Google Workspace's 6M+ business customers",
         target_url="https://workspace.google.com/marketplace/publish",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.45"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.10", section="7", title="Microsoft Teams App Store listing",
         description="Publish app to Microsoft Teams App Store",
         why="Access to 320M+ Teams users",
         target_url="https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview",
         time_estimate_minutes=180, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.16"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.11", section="7", title="Slack App Directory listing",
         description="Submit app to Slack App Directory",
         why="Access to 750K+ Slack workplaces",
         target_url="https://api.slack.com/start/distributing/directory",
         time_estimate_minutes=120, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=["5.15"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.12", section="7", title="Product Hunt launch",
         description="Launch product on Product Hunt",
         why="Product Hunt launch drives initial awareness and early adopters",
         target_url="https://www.producthunt.com/posts/new",
         time_estimate_minutes=60, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="revenue_channel",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="7.13", section="7", title="Capterra/G2 profile",
         description="Create Capterra and G2 software review profiles",
         why="Review profiles drive B2B discovery and trust",
         target_url="https://www.capterra.com/vendors/sign-up",
         time_estimate_minutes=30, task_type="agent_assisted",
         hitl_level="needs_review", category="marketplace", value_type="trust_signal",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 8 — International Grants ──────────────────────────────────
    dict(task_id="8.01", section="8", title="Canada SR&ED tax credit",
         description="Apply for Canada Scientific Research & Experimental Development tax credit",
         why="Up to 35% refundable tax credit on Canadian R&D expenditures",
         target_url="https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program.html",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_canada_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.02", section="8", title="UK Innovate UK SMART grant",
         description="Apply for Innovate UK SMART grant for innovation projects",
         why="Up to £250K for UK-based innovation projects",
         target_url="https://www.ukri.org/councils/innovate-uk/",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_uk_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.03", section="8", title="EU Horizon Europe grant",
         description="Apply for EU Horizon Europe research and innovation grant",
         why="Up to €2M for EU-based R&D and innovation projects",
         target_url="https://erc.europa.eu/apply-grant",
         time_estimate_minutes=480, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_eu_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.04", section="8", title="Australia RDTI tax incentive",
         description="Apply for Australia R&D Tax Incentive program",
         why="43.5% refundable tax offset for Australian R&D activities",
         target_url="https://business.gov.au/grants-and-programs/research-and-development-tax-incentive",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_australia_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.05", section="8", title="Singapore Enterprise Development Grant",
         description="Apply for Enterprise Singapore EDG for capability development",
         why="Up to 70% grant support for Singapore business development",
         target_url="https://www.enterprisesg.gov.sg/financial-support/enterprise-development-grant",
         time_estimate_minutes=180, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_singapore_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.06", section="8", title="Israel Innovation Authority grant",
         description="Apply for Israel Innovation Authority R&D grant",
         why="Up to 40-50% grant for Israeli R&D expenditures",
         target_url="https://innovationisrael.org.il/en/",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_israel_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.07", section="8", title="Germany BMWi innovation grant",
         description="Apply for German Federal Ministry of Economics innovation grant",
         why="Up to €200K for German technology innovation projects",
         target_url="https://www.bmbf.de/bmbf/en/research/innovation-funding/innovation-funding.html",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_germany_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.08", section="8", title="Japan NEDO technology grant",
         description="Apply for Japan New Energy and Industrial Technology Development Organization grant",
         why="Funding for Japanese energy and industrial technology R&D",
         target_url="https://www.nedo.go.jp/english/index.html",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_japan_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.09", section="8", title="New Zealand Callaghan Innovation",
         description="Apply for Callaghan Innovation R&D grant",
         why="Up to 20% R&D co-funding for New Zealand businesses",
         target_url="https://www.callaghaninnovation.govt.nz/grants",
         time_estimate_minutes=240, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_nz_entity=true", recurrence=None,
         prefill_fields={}),
    dict(task_id="8.10", section="8", title="South Korea KOITA R&D grant",
         description="Apply for Korea Industrial Technology Association R&D grant",
         why="Korean government funding for industrial R&D projects",
         target_url="https://www.koita.or.kr/english/",
         time_estimate_minutes=360, task_type="agent_assisted",
         hitl_level="needs_review", category="international", value_type="free_money",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=True, condition="has_korea_entity=true", recurrence=None,
         prefill_fields={}),

    # ── Section 9 — Domain & Infrastructure ───────────────────────────────
    dict(task_id="9.01", section="9", title="Domain registration",
         description="Register primary business domain name",
         why="Foundation for email, web presence, and brand identity",
         target_url="https://domains.google.com",
         time_estimate_minutes=15, task_type="human_required",
         hitl_level="blocked_human_required", category="compliance", value_type="prerequisite",
         estimated_value=None, depends_on=[], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None,
         prefill_fields={"domain": "company_domain"}),
    dict(task_id="9.02", section="9", title="SSL certificate setup",
         description="Set up Let's Encrypt SSL certificate for domain",
         why="HTTPS required for security, SEO, and user trust",
         target_url="https://letsencrypt.org/getting-started/",
         time_estimate_minutes=30, task_type="agent_auto",
         hitl_level="auto", category="compliance", value_type="prerequisite",
         estimated_value=None, depends_on=["9.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="9.03", section="9", title="DNS configuration",
         description="Configure DNS records for domain",
         why="Proper DNS configuration required for email and web services",
         target_url="https://dns.google",
         time_estimate_minutes=20, task_type="agent_auto",
         hitl_level="auto", category="compliance", value_type="prerequisite",
         estimated_value=None, depends_on=["9.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="9.04", section="9", title="CDN setup (Cloudflare)",
         description="Configure Cloudflare CDN for performance and DDoS protection",
         why="CDN improves performance and provides DDoS protection",
         target_url="https://dash.cloudflare.com/sign-up",
         time_estimate_minutes=30, task_type="agent_auto",
         hitl_level="auto", category="compliance", value_type="prerequisite",
         estimated_value=None, depends_on=["9.01", "5.22"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),
    dict(task_id="9.05", section="9", title="Email domain verification (DKIM/SPF)",
         description="Configure DKIM and SPF records for email domain verification",
         why="Required for email deliverability and anti-spoofing",
         target_url="https://toolbox.googleapps.com/apps/checkmx/",
         time_estimate_minutes=20, task_type="agent_auto",
         hitl_level="auto", category="compliance", value_type="prerequisite",
         estimated_value=None, depends_on=["9.01", "5.13"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence=None, prefill_fields={}),

    # ── Section 10 — Recurring Operations ─────────────────────────────────
    dict(task_id="10.01", section="10", title="SAM.gov annual renewal",
         description="Renew SAM.gov registration annually",
         why="SAM.gov must be renewed annually to maintain federal procurement eligibility",
         target_url="https://sam.gov",
         time_estimate_minutes=15, task_type="recurring",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="annual", prefill_fields={}),
    dict(task_id="10.02", section="10", title="Grants.gov account renewal",
         description="Renew Grants.gov account annually",
         why="Account renewal required to maintain grant application access",
         target_url="https://www.grants.gov",
         time_estimate_minutes=10, task_type="recurring",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.03"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="annual", prefill_fields={}),
    dict(task_id="10.03", section="10", title="Annual R&D tax credit filing",
         description="File annual R&D tax credit claim (Form 6765)",
         why="Annual filing required to capture R&D tax credits",
         target_url="https://www.irs.gov/forms-pubs/about-form-6765",
         time_estimate_minutes=120, task_type="recurring",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value=None, depends_on=["2.17"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="annual", prefill_fields={}),
    dict(task_id="10.04", section="10", title="SOC 2 annual surveillance audit",
         description="Complete annual SOC 2 surveillance audit",
         why="Annual audit required to maintain SOC 2 Type II certification",
         target_url="https://www.aicpa-cima.com",
         time_estimate_minutes=480, task_type="recurring",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=["6.01"], external_wait_days=None,
         is_conditional=True, condition="annual_revenue>500000", recurrence="annual",
         prefill_fields={}),
    dict(task_id="10.05", section="10", title="ISO 27001 annual surveillance",
         description="Complete annual ISO 27001 surveillance audit",
         why="Annual surveillance required to maintain ISO 27001 certification",
         target_url="https://www.iso.org/isoiec-27001-information-security.html",
         time_estimate_minutes=240, task_type="recurring",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=["6.02"], external_wait_days=None,
         is_conditional=True, condition=None, recurrence="annual", prefill_fields={}),
    dict(task_id="10.06", section="10", title="API key rotation",
         description="Rotate all production API keys quarterly",
         why="Regular key rotation reduces blast radius of credential compromise",
         target_url="https://dashboard.stripe.com",
         time_estimate_minutes=30, task_type="recurring",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=["5.10"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="quarterly", prefill_fields={}),
    dict(task_id="10.07", section="10", title="Cloud cost optimization review",
         description="Monthly review of cloud costs and optimization opportunities",
         why="Systematic cost reviews prevent cloud bill surprises and waste",
         target_url="https://aws.amazon.com/aws-cost-management/",
         time_estimate_minutes=60, task_type="recurring",
         hitl_level="needs_review", category="cloud_credit", value_type="free_money",
         estimated_value=None, depends_on=["4.01"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="monthly", prefill_fields={}),
    dict(task_id="10.08", section="10", title="Grant deadline calendar update",
         description="Monthly update of upcoming grant deadlines calendar",
         why="Tracking grant deadlines ensures no funding opportunities are missed",
         target_url="https://www.grants.gov/search-grants",
         time_estimate_minutes=30, task_type="recurring",
         hitl_level="needs_review", category="grant", value_type="free_money",
         estimated_value=None, depends_on=["1.03"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="monthly", prefill_fields={}),
    dict(task_id="10.09", section="10", title="NAICS code review",
         description="Annual review and update of NAICS codes",
         why="NAICS codes affect grant eligibility — keep current with business activities",
         target_url="https://www.naics.com/search/",
         time_estimate_minutes=15, task_type="recurring",
         hitl_level="needs_review", category="grant", value_type="prerequisite",
         estimated_value=None, depends_on=["1.04"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="annual", prefill_fields={}),
    dict(task_id="10.10", section="10", title="Security vulnerability scan",
         description="Monthly automated security vulnerability scan",
         why="Regular scans detect vulnerabilities before they are exploited",
         target_url="https://owasp.org/www-project-zap/",
         time_estimate_minutes=60, task_type="recurring",
         hitl_level="needs_review", category="compliance", value_type="trust_signal",
         estimated_value=None, depends_on=["6.04"], external_wait_days=None,
         is_conditional=False, condition=None, recurrence="monthly", prefill_fields={}),
]


def _build_catalog() -> List[OnboardingTask]:
    """Build TASK_CATALOG, computing the `blocks` reverse-dependency list."""
    # First pass: create all tasks with empty blocks
    tasks = []
    for raw in _RAW:
        tasks.append(OnboardingTask(
            task_id=raw["task_id"],
            section=raw["section"],
            title=raw["title"],
            description=raw["description"],
            why=raw["why"],
            target_url=raw["target_url"],
            time_estimate_minutes=raw["time_estimate_minutes"],
            task_type=raw["task_type"],
            hitl_level=raw["hitl_level"],
            category=raw["category"],
            value_type=raw["value_type"],
            estimated_value=raw.get("estimated_value"),
            depends_on=raw.get("depends_on", []),
            blocks=[],
            external_wait_days=raw.get("external_wait_days"),
            is_conditional=raw.get("is_conditional", False),
            condition=raw.get("condition"),
            recurrence=raw.get("recurrence"),
            prefill_fields=raw.get("prefill_fields", {}),
        ))

    # Second pass: populate blocks
    task_map = {t.task_id: t for t in tasks}
    for task in tasks:
        for dep_id in task.depends_on:
            if dep_id in task_map:
                task_map[dep_id].blocks.append(task.task_id)

    return tasks


TASK_CATALOG: List[OnboardingTask] = _build_catalog()
