"""
PRESET-010 through PRESET-017 — Manufacturing & Industrial Presets
===================================================================

Industry presets for discrete/process manufacturing, food & beverage,
pharmaceutical, automotive, aerospace/defense, construction, and mining.

Copyright 2024 Inoni LLC – BSL-1.1
"""

from __future__ import annotations

import logging
from typing import List

from .base import (
    AgentPersona,
    ComplianceRule,
    IndustryPreset,
    IntegrationMapping,
    KPIDefinition,
    WorkflowTemplate,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# PRESET-010 — Discrete Manufacturing
# ---------------------------------------------------------------------------

DISCRETE_MANUFACTURING = IndustryPreset(
    preset_id="PRESET-010",
    name="Discrete Manufacturing",
    industry="Manufacturing",
    sub_industry="Discrete Manufacturing",
    description="Production scheduling, quality control, BOM management, and shop floor automation.",
    version="1.0.0",
    tags=["manufacturing", "production", "quality", "BOM", "ISO-9001", "OEE"],
    compatible_with=["PRESET-014", "PRESET-052"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-DISCRETE-001",
            name="Production Order Management",
            description="Release work orders, schedule shop floor, and track completion.",
            steps=[
                {
                    "step_name": "BOM Explosion & Material Check",
                    "step_type": "automated_check",
                    "agent_persona": "Production Planner",
                    "integrations": ["SAP", "Oracle MFG"],
                    "compliance_gates": ["ISO-9001-planning"],
                    "kpis": ["material_availability_rate"],
                },
                {
                    "step_name": "Work Order Release & Scheduling",
                    "step_type": "processing",
                    "agent_persona": "Production Planner",
                    "integrations": ["SAP", "Plex"],
                    "compliance_gates": [],
                    "kpis": ["OEE", "on_time_delivery"],
                },
                {
                    "step_name": "Quality Inspection & Release",
                    "step_type": "human_review",
                    "agent_persona": "Quality Control Inspector",
                    "integrations": ["SAP", "Plex"],
                    "compliance_gates": ["ISO-9001-inspection"],
                    "kpis": ["scrap_rate", "first_pass_yield"],
                },
            ],
            triggers=["sales_order_confirmed", "forecast_demand"],
            outputs=["completed_work_order", "quality_record", "inventory_update"],
        ),
        WorkflowTemplate(
            template_id="WF-DISCRETE-002",
            name="Non-Conformance & CAPA",
            description="Identify quality escapes, document NCRs, and drive corrective actions.",
            steps=[
                {
                    "step_name": "Non-Conformance Identification",
                    "step_type": "data_collection",
                    "agent_persona": "Quality Control Inspector",
                    "integrations": ["SAP", "Plex"],
                    "compliance_gates": ["ISO-9001-NCR"],
                    "kpis": ["scrap_rate"],
                },
                {
                    "step_name": "Root Cause Analysis",
                    "step_type": "human_review",
                    "agent_persona": "Quality Control Inspector",
                    "integrations": ["SAP"],
                    "compliance_gates": ["ISO-9001-CAPA"],
                    "kpis": ["CAPA_cycle_time"],
                },
                {
                    "step_name": "Corrective Action Implementation",
                    "step_type": "processing",
                    "agent_persona": "Production Planner",
                    "integrations": ["SAP"],
                    "compliance_gates": ["ISO-9001-effectiveness-check"],
                    "kpis": ["CAPA_effectiveness_rate"],
                },
            ],
            triggers=["inspection_failure", "customer_complaint"],
            outputs=["NCR_record", "CAPA_plan", "effectiveness_check_result"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-DISCRETE-001",
            name="Production Planner",
            role="Manufacturing Planner",
            domain="Discrete Manufacturing",
            capabilities=["production_scheduling", "capacity_planning", "BOM_management", "work_order_management"],
            tools=["SAP", "Oracle MFG", "Plex"],
            personality_traits=["analytical", "systematic", "efficiency-focused"],
        ),
        AgentPersona(
            persona_id="AP-DISCRETE-002",
            name="Quality Control Inspector",
            role="Quality Assurance",
            domain="Discrete Manufacturing",
            capabilities=["incoming_inspection", "in_process_inspection", "NCR_management", "CAPA_coordination"],
            tools=["SAP", "Plex"],
            personality_traits=["detail-oriented", "standards-driven", "methodical"],
        ),
        AgentPersona(
            persona_id="AP-DISCRETE-003",
            name="Shop Floor Operations Agent",
            role="Operations Coordinator",
            domain="Discrete Manufacturing",
            capabilities=["work_order_dispatch", "labor_reporting", "machine_monitoring", "inventory_transactions"],
            tools=["SAP", "Plex"],
            personality_traits=["responsive", "hands-on", "safety-conscious"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="SAP",
            connector_type="ERP",
            required=True,
            config_template={"host": "", "client": "", "system_id": ""},
            purpose="Core ERP for production planning, inventory, and financials.",
        ),
        IntegrationMapping(
            connector_name="Plex",
            connector_type="MES",
            required=False,
            config_template={"api_key": "", "base_url": ""},
            purpose="Manufacturing Execution System for shop floor control.",
        ),
        IntegrationMapping(
            connector_name="Oracle MFG",
            connector_type="ERP",
            required=False,
            config_template={"host": "", "port": 1521, "service_name": ""},
            purpose="Alternative ERP for manufacturing operations.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-DISCRETE-001",
            standard="ISO 9001",
            description="Quality management system must meet ISO 9001 requirements including documented procedures and management review.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-DISCRETE-002",
            standard="OSHA 29 CFR 1910",
            description="General industry safety standards must be maintained; LOTO procedures required for machinery.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-DISCRETE-001",
            name="Overall Equipment Effectiveness (OEE)",
            description="Combined measure of availability, performance, and quality for production equipment.",
            unit="%",
            target_value=85.0,
            warning_threshold=75.0,
            critical_threshold=65.0,
            measurement_method="availability * performance * quality * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-DISCRETE-002",
            name="Scrap Rate",
            description="Percentage of production units scrapped due to quality failures.",
            unit="%",
            target_value=1.0,
            warning_threshold=3.0,
            critical_threshold=5.0,
            measurement_method="scrapped_units / total_units * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-DISCRETE-003",
            name="On-Time Delivery",
            description="Percentage of customer orders shipped on or before committed date.",
            unit="%",
            target_value=95.0,
            warning_threshold=88.0,
            critical_threshold=80.0,
            measurement_method="on_time_shipments / total_shipments * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-011 — Process Manufacturing
# ---------------------------------------------------------------------------

PROCESS_MANUFACTURING = IndustryPreset(
    preset_id="PRESET-011",
    name="Process Manufacturing",
    industry="Manufacturing",
    sub_industry="Process Manufacturing",
    description="Batch tracking, recipe/formula management, and continuous process optimization.",
    version="1.0.0",
    tags=["process-manufacturing", "batch", "recipe", "FDA", "yield"],
    compatible_with=["PRESET-012", "PRESET-013"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-PROCESS-001",
            name="Batch Production Execution",
            description="Recipe retrieval, batch setup, in-process monitoring, and batch disposition.",
            steps=[
                {
                    "step_name": "Recipe / Formula Retrieval",
                    "step_type": "automated_check",
                    "agent_persona": "Batch Production Coordinator",
                    "integrations": ["BatchMaster", "AVEVA"],
                    "compliance_gates": ["recipe-version-control", "FDA-21-CFR-110"],
                    "kpis": ["recipe_compliance_rate"],
                },
                {
                    "step_name": "Raw Material Weighing & Dispensing",
                    "step_type": "processing",
                    "agent_persona": "Batch Production Coordinator",
                    "integrations": ["OSIsoft PI", "BatchMaster"],
                    "compliance_gates": ["material-traceability"],
                    "kpis": ["batch_accuracy"],
                },
                {
                    "step_name": "Batch Review & Disposition",
                    "step_type": "human_review",
                    "agent_persona": "Process Quality Manager",
                    "integrations": ["BatchMaster"],
                    "compliance_gates": ["batch-record-completeness"],
                    "kpis": ["batch_cycle_time", "yield"],
                },
            ],
            triggers=["production_order_released", "demand_signal"],
            outputs=["completed_batch_record", "inventory_update", "quality_certificate"],
        ),
        WorkflowTemplate(
            template_id="WF-PROCESS-002",
            name="Recipe Management & Change Control",
            description="Manage formula versions, approve changes, and distribute to production.",
            steps=[
                {
                    "step_name": "Change Request Initiation",
                    "step_type": "data_collection",
                    "agent_persona": "Process Quality Manager",
                    "integrations": ["BatchMaster"],
                    "compliance_gates": ["change-control-SOP"],
                    "kpis": ["change_cycle_time"],
                },
                {
                    "step_name": "Technical Review & Approval",
                    "step_type": "human_review",
                    "agent_persona": "Process Quality Manager",
                    "integrations": ["BatchMaster"],
                    "compliance_gates": ["FDA-21-CFR-110-change-control"],
                    "kpis": ["recipe_approval_cycle_time"],
                },
            ],
            triggers=["formula_change_request", "raw_material_substitution"],
            outputs=["approved_recipe", "change_control_record"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-PROCESS-001",
            name="Batch Production Coordinator",
            role="Production Coordinator",
            domain="Process Manufacturing",
            capabilities=["batch_setup", "in_process_monitoring", "material_dispensing", "batch_record_completion"],
            tools=["BatchMaster", "AVEVA", "OSIsoft PI"],
            personality_traits=["precise", "safety-conscious", "process-driven"],
        ),
        AgentPersona(
            persona_id="AP-PROCESS-002",
            name="Process Quality Manager",
            role="Quality Manager",
            domain="Process Manufacturing",
            capabilities=["batch_review", "recipe_management", "deviation_handling", "regulatory_reporting"],
            tools=["BatchMaster", "OSIsoft PI"],
            personality_traits=["analytical", "regulatory-aware", "improvement-focused"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="BatchMaster",
            connector_type="ERP",
            required=True,
            config_template={"api_key": "", "server": ""},
            purpose="Process manufacturing ERP with recipe and batch management.",
        ),
        IntegrationMapping(
            connector_name="AVEVA",
            connector_type="SCADA",
            required=False,
            config_template={"server": "", "port": 80},
            purpose="SCADA and process automation integration.",
        ),
        IntegrationMapping(
            connector_name="OSIsoft PI",
            connector_type="historian",
            required=False,
            config_template={"pi_server": "", "username": ""},
            purpose="Process data historian for real-time and historical trend analysis.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-PROCESS-001",
            standard="FDA 21 CFR Part 110",
            description="Current Good Manufacturing Practice in Manufacturing, Packing, or Holding Human Food.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-PROCESS-002",
            standard="Batch Record Completeness",
            description="Every batch must have a complete, legible, and accurate batch production record.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-PROCESS-001",
            name="Batch Yield",
            description="Actual output as a percentage of theoretical maximum yield.",
            unit="%",
            target_value=96.0,
            warning_threshold=92.0,
            critical_threshold=88.0,
            measurement_method="actual_output / theoretical_output * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-PROCESS-002",
            name="Batch Cycle Time",
            description="Average hours from batch initiation to disposition.",
            unit="hours",
            target_value=8.0,
            warning_threshold=12.0,
            critical_threshold=18.0,
            measurement_method="avg(disposition_time - start_time)",
        ),
        KPIDefinition(
            kpi_id="KPI-PROCESS-003",
            name="Right First Time Rate",
            description="Percentage of batches passing all quality checks on first review.",
            unit="%",
            target_value=95.0,
            warning_threshold=88.0,
            critical_threshold=80.0,
            measurement_method="batches_passed_first_review / total_batches * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-012 — Food & Beverage
# ---------------------------------------------------------------------------

FOOD_BEVERAGE = IndustryPreset(
    preset_id="PRESET-012",
    name="Food & Beverage Manufacturing",
    industry="Manufacturing",
    sub_industry="Food & Beverage",
    description="Recipe management, HACCP compliance, traceability, and food safety management.",
    version="1.0.0",
    tags=["food", "beverage", "HACCP", "FSMA", "FDA", "traceability", "food-safety"],
    compatible_with=["PRESET-011", "PRESET-027"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-FB-001",
            name="HACCP Critical Control Point Monitoring",
            description="Monitor CCPs, record deviations, and trigger corrective actions.",
            steps=[
                {
                    "step_name": "CCP Parameter Monitoring",
                    "step_type": "automated_check",
                    "agent_persona": "Food Safety & Quality Coordinator",
                    "integrations": ["SafetyChain", "TraceGains"],
                    "compliance_gates": ["HACCP-plan", "FSMA-preventive-controls"],
                    "kpis": ["food_safety_incidents"],
                },
                {
                    "step_name": "Deviation Recording & Corrective Action",
                    "step_type": "processing",
                    "agent_persona": "Food Safety & Quality Coordinator",
                    "integrations": ["SafetyChain"],
                    "compliance_gates": ["HACCP-corrective-action-procedure"],
                    "kpis": ["CCP_deviation_rate"],
                },
                {
                    "step_name": "Verification & Validation",
                    "step_type": "human_review",
                    "agent_persona": "Food Safety & Quality Coordinator",
                    "integrations": ["SafetyChain", "FoodLogiQ"],
                    "compliance_gates": ["HACCP-verification", "FDA-FSMA"],
                    "kpis": ["HACCP_verification_rate"],
                },
            ],
            triggers=["production_shift_start", "CCP_alarm"],
            outputs=["HACCP_monitoring_record", "deviation_report", "corrective_action"],
        ),
        WorkflowTemplate(
            template_id="WF-FB-002",
            name="Supplier Traceability & Ingredient Recall",
            description="Trace ingredients from supplier to finished goods; initiate mock recalls.",
            steps=[
                {
                    "step_name": "Ingredient Lot Traceability",
                    "step_type": "automated_check",
                    "agent_persona": "Supply Chain & Traceability Agent",
                    "integrations": ["TraceGains", "FoodLogiQ"],
                    "compliance_gates": ["FSMA-traceability-rule"],
                    "kpis": ["traceability_completeness"],
                },
                {
                    "step_name": "Mock Recall Execution",
                    "step_type": "processing",
                    "agent_persona": "Food Safety & Quality Coordinator",
                    "integrations": ["FoodLogiQ"],
                    "compliance_gates": ["FDA-recall-procedure"],
                    "kpis": ["mock_recall_completion_time"],
                },
            ],
            triggers=["supplier_alert", "customer_complaint", "scheduled_mock_recall"],
            outputs=["traceability_report", "recall_scope_document"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-FB-001",
            name="Food Safety & Quality Coordinator",
            role="Food Safety Manager",
            domain="Food & Beverage",
            capabilities=["HACCP_monitoring", "deviation_management", "sanitation_verification", "audit_coordination"],
            tools=["SafetyChain", "TraceGains", "FoodLogiQ"],
            personality_traits=["safety-first", "detail-oriented", "regulatory-aware"],
        ),
        AgentPersona(
            persona_id="AP-FB-002",
            name="Supply Chain & Traceability Agent",
            role="Supply Chain Coordinator",
            domain="Food & Beverage",
            capabilities=["ingredient_traceability", "supplier_qualification", "lot_tracking", "recall_coordination"],
            tools=["TraceGains", "FoodLogiQ"],
            personality_traits=["systematic", "organized", "crisis-ready"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="TraceGains",
            connector_type="supplier_quality",
            required=True,
            config_template={"api_key": "", "tenant_id": ""},
            purpose="Supplier documentation, ingredient traceability, and compliance records.",
        ),
        IntegrationMapping(
            connector_name="SafetyChain",
            connector_type="food_safety",
            required=True,
            config_template={"api_key": "", "base_url": ""},
            purpose="HACCP monitoring, CCP data collection, and food safety records.",
        ),
        IntegrationMapping(
            connector_name="FoodLogiQ",
            connector_type="traceability",
            required=False,
            config_template={"api_key": ""},
            purpose="End-to-end supply chain traceability and recall management.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-FB-001",
            standard="HACCP",
            description="Hazard Analysis and Critical Control Points plan must be current, validated, and actively monitored.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-FB-002",
            standard="FDA FSMA",
            description="Food Safety Modernization Act preventive controls and traceability requirements must be maintained.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-FB-003",
            standard="SQF / BRC / GFSI",
            description="Global Food Safety Initiative benchmark scheme certification must be maintained for retail customer compliance.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-FB-001",
            name="Food Safety Incidents",
            description="Number of food safety incidents (recalls, illness outbreaks, regulatory actions) per year.",
            unit="count",
            target_value=0.0,
            warning_threshold=1.0,
            critical_threshold=2.0,
            measurement_method="count(food_safety_incidents_per_year)",
        ),
        KPIDefinition(
            kpi_id="KPI-FB-002",
            name="Waste Percentage",
            description="Product waste as a percentage of total production volume.",
            unit="%",
            target_value=2.0,
            warning_threshold=4.0,
            critical_threshold=7.0,
            measurement_method="waste_volume / production_volume * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-FB-003",
            name="Shelf Life Achievement Rate",
            description="Percentage of finished goods meeting target shelf life at time of distribution.",
            unit="%",
            target_value=98.0,
            warning_threshold=95.0,
            critical_threshold=90.0,
            measurement_method="units_meeting_shelf_life / total_units * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-013 — Pharmaceutical Manufacturing
# ---------------------------------------------------------------------------

PHARMACEUTICAL = IndustryPreset(
    preset_id="PRESET-013",
    name="Pharmaceutical Manufacturing",
    industry="Manufacturing",
    sub_industry="Pharmaceutical",
    description="GxP-compliant batch records, 21 CFR Part 11 electronic records, and FDA submission readiness.",
    version="1.0.0",
    tags=["pharma", "GMP", "FDA", "21-CFR-11", "batch-records", "EMA", "validation"],
    compatible_with=["PRESET-011", "PRESET-035"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-PHARMA-001",
            name="Batch Record Execution & Review",
            description="Execute electronic batch records with GMP controls and release review.",
            steps=[
                {
                    "step_name": "Master Batch Record Issuance",
                    "step_type": "document_generation",
                    "agent_persona": "Pharma QA Specialist",
                    "integrations": ["Veeva Vault", "MasterControl"],
                    "compliance_gates": ["FDA-21-CFR-211", "GMP-batch-record-requirements"],
                    "kpis": ["batch_record_issuance_time"],
                },
                {
                    "step_name": "In-Process Controls & Data Entry",
                    "step_type": "processing",
                    "agent_persona": "Manufacturing Operations Agent",
                    "integrations": ["SAP QM", "Veeva Vault"],
                    "compliance_gates": ["FDA-21-CFR-Part-11", "data-integrity-ALCOA"],
                    "kpis": ["data_integrity_incidents"],
                },
                {
                    "step_name": "QA Batch Review & Release",
                    "step_type": "human_review",
                    "agent_persona": "Pharma QA Specialist",
                    "integrations": ["Veeva Vault", "MasterControl"],
                    "compliance_gates": ["GMP-batch-release", "OOS-investigation"],
                    "kpis": ["batch_release_cycle_time", "OOS_rate"],
                },
            ],
            triggers=["production_order_approved", "batch_complete"],
            outputs=["completed_batch_record", "certificate_of_analysis", "release_decision"],
        ),
        WorkflowTemplate(
            template_id="WF-PHARMA-002",
            name="Deviation & CAPA Management",
            description="Report deviations, perform impact assessments, and close CAPAs.",
            steps=[
                {
                    "step_name": "Deviation Initiation & Classification",
                    "step_type": "data_collection",
                    "agent_persona": "Pharma QA Specialist",
                    "integrations": ["Veeva Vault", "MasterControl"],
                    "compliance_gates": ["GMP-deviation-SOP"],
                    "kpis": ["deviation_rate"],
                },
                {
                    "step_name": "Investigation & Root Cause",
                    "step_type": "human_review",
                    "agent_persona": "Pharma QA Specialist",
                    "integrations": ["Veeva Vault"],
                    "compliance_gates": ["GMP-investigation-timeline"],
                    "kpis": ["CAPA_cycle_time"],
                },
            ],
            triggers=["deviation_observed", "OOS_result"],
            outputs=["deviation_report", "CAPA_record", "effectiveness_check"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-PHARMA-001",
            name="Pharma QA Specialist",
            role="Quality Assurance",
            domain="Pharmaceutical",
            capabilities=["batch_review", "deviation_management", "CAPA_coordination", "regulatory_reporting", "validation"],
            tools=["Veeva Vault", "MasterControl", "SAP QM"],
            personality_traits=["meticulous", "regulatory-focused", "data-integrity-driven"],
        ),
        AgentPersona(
            persona_id="AP-PHARMA-002",
            name="Manufacturing Operations Agent",
            role="Manufacturing Specialist",
            domain="Pharmaceutical",
            capabilities=["batch_execution", "in_process_testing", "equipment_operation", "GMP_documentation"],
            tools=["SAP QM", "Veeva Vault"],
            personality_traits=["precise", "GMP-disciplined", "safety-conscious"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Veeva Vault",
            connector_type="quality_management",
            required=True,
            config_template={"vault_dns": "", "client_id": ""},
            purpose="Document management, quality events, and regulatory submissions.",
        ),
        IntegrationMapping(
            connector_name="MasterControl",
            connector_type="eQMS",
            required=False,
            config_template={"url": "", "api_key": ""},
            purpose="Electronic quality management system for docs, training, and CAPA.",
        ),
        IntegrationMapping(
            connector_name="SAP QM",
            connector_type="ERP",
            required=False,
            config_template={"host": "", "client": ""},
            purpose="Quality management module within SAP ERP.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-PHARMA-001",
            standard="FDA 21 CFR Part 211 (GMP)",
            description="Current Good Manufacturing Practice for finished pharmaceuticals must be implemented and maintained.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-PHARMA-002",
            standard="FDA 21 CFR Part 11",
            description="Electronic records and signatures must meet Part 11 requirements for audit trail, access control, and validation.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-PHARMA-003",
            standard="ALCOA+ Data Integrity",
            description="All GMP data must be Attributable, Legible, Contemporaneous, Original, and Accurate.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-PHARMA-001",
            name="Batch Release Cycle Time",
            description="Average calendar days from batch completion to QA release.",
            unit="days",
            target_value=5.0,
            warning_threshold=10.0,
            critical_threshold=15.0,
            measurement_method="avg(release_date - batch_complete_date)",
        ),
        KPIDefinition(
            kpi_id="KPI-PHARMA-002",
            name="OOS (Out-of-Specification) Rate",
            description="Percentage of test results outside specification limits.",
            unit="%",
            target_value=0.5,
            warning_threshold=1.5,
            critical_threshold=3.0,
            measurement_method="OOS_results / total_results * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-PHARMA-003",
            name="CAPA On-Time Closure Rate",
            description="Percentage of CAPAs closed within committed due date.",
            unit="%",
            target_value=95.0,
            warning_threshold=85.0,
            critical_threshold=75.0,
            measurement_method="on_time_closed_CAPAs / total_CAPAs * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-014 — Automotive Manufacturing
# ---------------------------------------------------------------------------

AUTOMOTIVE = IndustryPreset(
    preset_id="PRESET-014",
    name="Automotive Manufacturing",
    industry="Manufacturing",
    sub_industry="Automotive",
    description="JIT production, quality systems (APQP/PPAP), supply chain management, and IATF 16949 compliance.",
    version="1.0.0",
    tags=["automotive", "IATF-16949", "PPAP", "JIT", "supply-chain", "APQP"],
    compatible_with=["PRESET-010", "PRESET-052"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-AUTO-001",
            name="PPAP Submission",
            description="Prepare and submit Production Part Approval Process documentation to OEM customers.",
            steps=[
                {
                    "step_name": "PPAP Plan & Checklist",
                    "step_type": "planning",
                    "agent_persona": "Automotive Quality Engineer",
                    "integrations": ["SAP", "IATF portal"],
                    "compliance_gates": ["IATF-16949", "PPAP-4th-edition"],
                    "kpis": ["PPAP_on_time_submission"],
                },
                {
                    "step_name": "PFMEA & Control Plan",
                    "step_type": "human_review",
                    "agent_persona": "Automotive Quality Engineer",
                    "integrations": ["Siemens Teamcenter"],
                    "compliance_gates": ["AIAG-VDA-FMEA"],
                    "kpis": ["PFMEA_risk_reduction"],
                },
                {
                    "step_name": "Customer Submission & Approval",
                    "step_type": "integration_action",
                    "agent_persona": "Automotive Quality Engineer",
                    "integrations": ["IATF portal"],
                    "compliance_gates": ["OEM-PPAP-requirements"],
                    "kpis": ["PPAP_approval_cycle_time"],
                },
            ],
            triggers=["new_program_launch", "design_change", "process_change"],
            outputs=["PPAP_package", "customer_approval", "production_release"],
        ),
        WorkflowTemplate(
            template_id="WF-AUTO-002",
            name="JIT Production Scheduling",
            description="Synchronize production schedule with customer pull signals and supplier delivery.",
            steps=[
                {
                    "step_name": "Customer Kanban / EDI Signal Processing",
                    "step_type": "automated_check",
                    "agent_persona": "Production Planning Agent",
                    "integrations": ["SAP"],
                    "compliance_gates": [],
                    "kpis": ["schedule_attainment"],
                },
                {
                    "step_name": "Supplier Release & Delivery Management",
                    "step_type": "processing",
                    "agent_persona": "Production Planning Agent",
                    "integrations": ["SAP"],
                    "compliance_gates": [],
                    "kpis": ["supplier_on_time_delivery"],
                },
            ],
            triggers=["customer_EDI_signal", "daily_production_schedule"],
            outputs=["production_schedule", "supplier_releases", "shipping_plan"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-AUTO-001",
            name="Automotive Quality Engineer",
            role="Quality Engineer",
            domain="Automotive",
            capabilities=["PPAP_management", "FMEA_facilitation", "MSA_studies", "customer_quality_reporting"],
            tools=["SAP", "IATF portal", "Siemens Teamcenter"],
            personality_traits=["analytical", "standards-driven", "customer-focused"],
        ),
        AgentPersona(
            persona_id="AP-AUTO-002",
            name="Production Planning Agent",
            role="Production Planner",
            domain="Automotive",
            capabilities=["MRP_execution", "kanban_management", "supplier_scheduling", "capacity_analysis"],
            tools=["SAP"],
            personality_traits=["systematic", "responsive", "supply-chain-aware"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="SAP",
            connector_type="ERP",
            required=True,
            config_template={"host": "", "client": "", "system_id": ""},
            purpose="ERP for production planning, MRP, and financial management.",
        ),
        IntegrationMapping(
            connector_name="Siemens Teamcenter",
            connector_type="PLM",
            required=False,
            config_template={"server_url": "", "username": ""},
            purpose="Product Lifecycle Management for engineering data and PPAP documentation.",
        ),
        IntegrationMapping(
            connector_name="IATF portal",
            connector_type="quality_portal",
            required=False,
            config_template={"portal_url": "", "credentials": ""},
            purpose="OEM quality portal for PPAP submission and customer quality reporting.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-AUTO-001",
            standard="IATF 16949",
            description="Automotive quality management system certification required for OEM supplier status.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-AUTO-002",
            standard="PPAP (Production Part Approval Process)",
            description="Approved PPAP required before shipping production parts to OEM customers.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-AUTO-001",
            name="DPMO (Defects Per Million Opportunities)",
            description="Quality metric measuring defects relative to opportunities.",
            unit="PPM",
            target_value=50.0,
            warning_threshold=200.0,
            critical_threshold=500.0,
            measurement_method="(defects / opportunities) * 1_000_000",
        ),
        KPIDefinition(
            kpi_id="KPI-AUTO-002",
            name="On-Time Delivery to Customer",
            description="Percentage of shipments delivered on time per customer release schedule.",
            unit="%",
            target_value=99.0,
            warning_threshold=97.0,
            critical_threshold=95.0,
            measurement_method="on_time_deliveries / total_deliveries * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-AUTO-003",
            name="PPM (Parts Per Million) Defects",
            description="Customer-reported defective parts per million parts shipped.",
            unit="PPM",
            target_value=10.0,
            warning_threshold=50.0,
            critical_threshold=100.0,
            measurement_method="(customer_returned_defects / shipped_parts) * 1_000_000",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-015 — Aerospace & Defense
# ---------------------------------------------------------------------------

AEROSPACE_DEFENSE = IndustryPreset(
    preset_id="PRESET-015",
    name="Aerospace & Defense",
    industry="Manufacturing",
    sub_industry="Aerospace & Defense",
    description="AS9100 quality systems, ITAR compliance, configuration management, and DoD contract requirements.",
    version="1.0.0",
    tags=["aerospace", "defense", "AS9100", "ITAR", "DFARS", "configuration-management"],
    compatible_with=["PRESET-010", "PRESET-014"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-ASD-001",
            name="First Article Inspection (FAI)",
            description="Conduct AS9102 First Article Inspection for new or changed production.",
            steps=[
                {
                    "step_name": "FAI Planning & Checklist",
                    "step_type": "planning",
                    "agent_persona": "Aerospace Quality Engineer",
                    "integrations": ["PTC Windchill", "JAMA"],
                    "compliance_gates": ["AS9102-FAI-requirements", "AS9100"],
                    "kpis": ["FAI_completion_rate"],
                },
                {
                    "step_name": "Dimensional & Material Verification",
                    "step_type": "processing",
                    "agent_persona": "Aerospace Quality Engineer",
                    "integrations": ["PTC Windchill"],
                    "compliance_gates": ["drawing-requirements", "material-certifications"],
                    "kpis": ["FAI_on_time_completion"],
                },
                {
                    "step_name": "FAI Report Approval",
                    "step_type": "human_review",
                    "agent_persona": "Aerospace Quality Engineer",
                    "integrations": ["PTC Windchill", "DCSA"],
                    "compliance_gates": ["customer-FAI-approval"],
                    "kpis": ["escape_rate"],
                },
            ],
            triggers=["new_part_introduction", "engineering_change_order"],
            outputs=["FAI_report", "customer_approval", "baseline_established"],
        ),
        WorkflowTemplate(
            template_id="WF-ASD-002",
            name="ITAR Export Control Review",
            description="Screen export transactions for ITAR compliance before shipment or data transfer.",
            steps=[
                {
                    "step_name": "Transaction Screening",
                    "step_type": "automated_check",
                    "agent_persona": "Export Compliance Officer",
                    "integrations": ["DCSA"],
                    "compliance_gates": ["ITAR-22-CFR-120-130", "EAR-15-CFR"],
                    "kpis": ["ITAR_screening_completeness"],
                },
                {
                    "step_name": "License Determination & Application",
                    "step_type": "human_review",
                    "agent_persona": "Export Compliance Officer",
                    "integrations": ["DCSA"],
                    "compliance_gates": ["DDTC-license-requirements"],
                    "kpis": ["license_application_cycle_time"],
                },
            ],
            triggers=["export_transaction_initiated", "foreign_national_access_request"],
            outputs=["export_authorization", "compliance_record"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-ASD-001",
            name="Aerospace Quality Engineer",
            role="Quality Engineer",
            domain="Aerospace & Defense",
            capabilities=["FAI_coordination", "supplier_quality", "AS9100_auditing", "configuration_management"],
            tools=["PTC Windchill", "JAMA", "DCSA"],
            personality_traits=["methodical", "standards-rigorous", "detail-oriented"],
        ),
        AgentPersona(
            persona_id="AP-ASD-002",
            name="Export Compliance Officer",
            role="Compliance Officer",
            domain="Aerospace & Defense",
            capabilities=["ITAR_screening", "EAR_classification", "license_management", "training_administration"],
            tools=["DCSA"],
            personality_traits=["regulatory-expert", "risk-averse", "meticulous"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="PTC Windchill",
            connector_type="PLM",
            required=True,
            config_template={"server_url": "", "username": ""},
            purpose="PLM for engineering data, configuration management, and quality records.",
        ),
        IntegrationMapping(
            connector_name="JAMA",
            connector_type="requirements_management",
            required=False,
            config_template={"api_key": "", "base_url": ""},
            purpose="Requirements and test traceability for complex systems.",
        ),
        IntegrationMapping(
            connector_name="DCSA",
            connector_type="government_portal",
            required=False,
            config_template={"portal_url": "", "facility_clearance_id": ""},
            purpose="Defense Counterintelligence and Security Agency portal for clearance and ITAR.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-ASD-001",
            standard="AS9100 Rev D",
            description="Aerospace quality management system certification required for aerospace supply chain participation.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-ASD-002",
            standard="ITAR (22 CFR 120-130)",
            description="International Traffic in Arms Regulations control export of defense articles and services.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-ASD-003",
            standard="DFARS",
            description="Defense Federal Acquisition Regulation Supplement requirements including cybersecurity (CMMC).",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-ASD-001",
            name="On-Time Delivery Rate",
            description="Percentage of deliveries made on or before customer required date.",
            unit="%",
            target_value=95.0,
            warning_threshold=90.0,
            critical_threshold=85.0,
            measurement_method="on_time_deliveries / total_deliveries * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-ASD-002",
            name="Escape Rate",
            description="Defective units that escaped to the customer per million units shipped.",
            unit="PPM",
            target_value=5.0,
            warning_threshold=20.0,
            critical_threshold=50.0,
            measurement_method="(customer_escapes / shipped_units) * 1_000_000",
        ),
        KPIDefinition(
            kpi_id="KPI-ASD-003",
            name="AS9100 Audit Score",
            description="Score from most recent AS9100 surveillance or recertification audit.",
            unit="score",
            target_value=95.0,
            warning_threshold=85.0,
            critical_threshold=75.0,
            measurement_method="auditor_scored_points / total_possible_points * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-016 — Construction
# ---------------------------------------------------------------------------

CONSTRUCTION = IndustryPreset(
    preset_id="PRESET-016",
    name="Construction",
    industry="Manufacturing",
    sub_industry="Construction",
    description="Project scheduling, subcontractor management, safety compliance, and construction financials.",
    version="1.0.0",
    tags=["construction", "GC", "subcontractor", "OSHA", "Procore", "safety", "LEED"],
    compatible_with=["PRESET-004", "PRESET-017"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-CONST-001",
            name="Subcontractor Management",
            description="Qualify subs, issue scopes, manage RFIs, and process payment applications.",
            steps=[
                {
                    "step_name": "Subcontractor Prequalification",
                    "step_type": "automated_check",
                    "agent_persona": "Construction Project Manager",
                    "integrations": ["Procore", "Buildertrend"],
                    "compliance_gates": ["COI-requirements", "license-verification"],
                    "kpis": ["subcontractor_prequalification_rate"],
                },
                {
                    "step_name": "Scope & Contract Execution",
                    "step_type": "document_generation",
                    "agent_persona": "Construction Project Manager",
                    "integrations": ["Procore", "DocuSign"],
                    "compliance_gates": ["lien-waiver-requirements", "insurance-minimums"],
                    "kpis": ["subcontract_execution_time"],
                },
                {
                    "step_name": "Pay Application Review & Approval",
                    "step_type": "human_review",
                    "agent_persona": "Construction Financial Agent",
                    "integrations": ["Procore"],
                    "compliance_gates": ["AIA-G702-G703-forms"],
                    "kpis": ["payment_cycle_time"],
                },
            ],
            triggers=["bid_award", "monthly_billing_cycle"],
            outputs=["subcontract", "approved_pay_application", "lien_waiver"],
        ),
        WorkflowTemplate(
            template_id="WF-CONST-002",
            name="Safety Incident Management",
            description="Report, investigate, and close out safety incidents per OSHA requirements.",
            steps=[
                {
                    "step_name": "Incident Reporting",
                    "step_type": "data_collection",
                    "agent_persona": "Construction Safety Officer",
                    "integrations": ["Procore"],
                    "compliance_gates": ["OSHA-300-log", "OSHA-recordability-criteria"],
                    "kpis": ["safety_incident_rate"],
                },
                {
                    "step_name": "Root Cause & Corrective Action",
                    "step_type": "human_review",
                    "agent_persona": "Construction Safety Officer",
                    "integrations": ["Procore"],
                    "compliance_gates": ["OSHA-investigation-requirements"],
                    "kpis": ["corrective_action_closure_rate"],
                },
            ],
            triggers=["safety_incident_observed", "near_miss_reported"],
            outputs=["incident_report", "OSHA_300_entry", "corrective_action_plan"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-CONST-001",
            name="Construction Project Manager",
            role="Project Manager",
            domain="Construction",
            capabilities=["schedule_management", "subcontractor_coordination", "RFI_management", "change_order_management"],
            tools=["Procore", "Primavera P6", "Buildertrend"],
            personality_traits=["organized", "decisive", "field-savvy"],
        ),
        AgentPersona(
            persona_id="AP-CONST-002",
            name="Construction Safety Officer",
            role="Safety Manager",
            domain="Construction",
            capabilities=["site_inspections", "incident_investigation", "OSHA_compliance", "safety_training"],
            tools=["Procore"],
            personality_traits=["safety-first", "observant", "authoritative"],
        ),
        AgentPersona(
            persona_id="AP-CONST-003",
            name="Construction Financial Agent",
            role="Project Accountant",
            domain="Construction",
            capabilities=["pay_application_review", "job_cost_tracking", "budget_management", "lien_waiver_management"],
            tools=["Procore", "QuickBooks"],
            personality_traits=["detail-oriented", "financial-focused", "organized"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Procore",
            connector_type="project_management",
            required=True,
            config_template={"client_id": "", "client_secret": "", "company_id": ""},
            purpose="Construction project management, drawings, and financials.",
        ),
        IntegrationMapping(
            connector_name="Primavera P6",
            connector_type="scheduling",
            required=False,
            config_template={"server_url": "", "database": ""},
            purpose="Enterprise project scheduling for complex construction programs.",
        ),
        IntegrationMapping(
            connector_name="Buildertrend",
            connector_type="project_management",
            required=False,
            config_template={"api_key": ""},
            purpose="Residential/light commercial construction management.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-CONST-001",
            standard="OSHA 29 CFR 1926 (Construction)",
            description="Construction safety standards must be enforced including fall protection, hazard communication, and scaffolding.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-CONST-002",
            standard="Building Codes / AHJ",
            description="All construction must comply with applicable building codes and receive required inspections from AHJ.",
            required_approvals=1,
            penalty_severity="critical",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-CONST-003",
            standard="Lien Law Compliance",
            description="Proper lien waiver collection and preliminary notice requirements must be met per state law.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-CONST-001",
            name="Schedule Performance Index (SPI)",
            description="Ratio of earned value to planned value; measures schedule efficiency.",
            unit="ratio",
            target_value=1.0,
            warning_threshold=0.9,
            critical_threshold=0.8,
            measurement_method="earned_value / planned_value",
        ),
        KPIDefinition(
            kpi_id="KPI-CONST-002",
            name="Safety Incident Rate (TRIR)",
            description="Total Recordable Incident Rate per 200,000 hours worked.",
            unit="rate",
            target_value=1.0,
            warning_threshold=2.0,
            critical_threshold=4.0,
            measurement_method="(recordable_incidents * 200000) / hours_worked",
        ),
        KPIDefinition(
            kpi_id="KPI-CONST-003",
            name="Cost Performance Index (CPI)",
            description="Ratio of earned value to actual costs; measures cost efficiency.",
            unit="ratio",
            target_value=1.0,
            warning_threshold=0.9,
            critical_threshold=0.8,
            measurement_method="earned_value / actual_cost",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-017 — Mining & Extraction
# ---------------------------------------------------------------------------

MINING_EXTRACTION = IndustryPreset(
    preset_id="PRESET-017",
    name="Mining & Extraction",
    industry="Manufacturing",
    sub_industry="Mining & Extraction",
    description="Resource planning, mine safety, environmental compliance, and production reporting.",
    version="1.0.0",
    tags=["mining", "extraction", "MSHA", "EPA", "ESG", "safety", "ore-recovery"],
    compatible_with=["PRESET-016", "PRESET-061"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-MINING-001",
            name="Mine Safety Inspection & Reporting",
            description="Conduct required safety inspections and submit MSHA reports.",
            steps=[
                {
                    "step_name": "Pre-shift Safety Inspection",
                    "step_type": "processing",
                    "agent_persona": "Mine Safety & Compliance Officer",
                    "integrations": ["Hexagon GDMS"],
                    "compliance_gates": ["MSHA-30-CFR", "pre-shift-inspection-requirements"],
                    "kpis": ["safety_incidents_per_million_hours"],
                },
                {
                    "step_name": "Hazard Identification & Reporting",
                    "step_type": "data_collection",
                    "agent_persona": "Mine Safety & Compliance Officer",
                    "integrations": ["Hexagon GDMS", "Minesite"],
                    "compliance_gates": ["MSHA-hazard-reporting"],
                    "kpis": ["near_miss_reporting_rate"],
                },
            ],
            triggers=["shift_start", "blasting_scheduled"],
            outputs=["inspection_record", "MSHA_report", "hazard_log"],
        ),
        WorkflowTemplate(
            template_id="WF-MINING-002",
            name="Production & Ore Grade Reporting",
            description="Track ore extraction, grade sampling, and production targets.",
            steps=[
                {
                    "step_name": "Ore Extraction & Grade Sampling",
                    "step_type": "processing",
                    "agent_persona": "Mine Production Planner",
                    "integrations": ["Minesite", "Trimble"],
                    "compliance_gates": ["environmental-permit-limits"],
                    "kpis": ["ore_recovery_rate"],
                },
                {
                    "step_name": "Production Reporting",
                    "step_type": "document_generation",
                    "agent_persona": "Mine Production Planner",
                    "integrations": ["Minesite"],
                    "compliance_gates": ["royalty-reporting-requirements"],
                    "kpis": ["production_vs_plan"],
                },
            ],
            triggers=["shift_end", "blast_complete"],
            outputs=["production_report", "grade_certificate", "royalty_report"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-MINING-001",
            name="Mine Safety & Compliance Officer",
            role="Safety Officer",
            domain="Mining",
            capabilities=["safety_inspections", "MSHA_reporting", "hazard_identification", "emergency_response"],
            tools=["Hexagon GDMS", "Minesite"],
            personality_traits=["safety-first", "regulatory-aware", "assertive"],
        ),
        AgentPersona(
            persona_id="AP-MINING-002",
            name="Mine Production Planner",
            role="Production Planner",
            domain="Mining",
            capabilities=["production_scheduling", "grade_control", "equipment_planning", "environmental_monitoring"],
            tools=["Minesite", "Trimble"],
            personality_traits=["analytical", "efficiency-focused", "environmental-aware"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Minesite",
            connector_type="mine_management",
            required=True,
            config_template={"api_key": "", "site_id": ""},
            purpose="Mine site management, production tracking, and safety records.",
        ),
        IntegrationMapping(
            connector_name="Hexagon GDMS",
            connector_type="geospatial",
            required=False,
            config_template={"server_url": "", "username": ""},
            purpose="Geospatial data management and mine planning.",
        ),
        IntegrationMapping(
            connector_name="Trimble",
            connector_type="survey_positioning",
            required=False,
            config_template={"api_key": ""},
            purpose="Survey, positioning, and machine guidance systems.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-MINING-001",
            standard="MSHA 30 CFR",
            description="Mine Safety and Health Administration regulations govern all underground and surface mining operations.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-MINING-002",
            standard="EPA Environmental Permits",
            description="Air, water, and land disturbance permits must be maintained; exceedances must be reported.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-MINING-003",
            standard="ESG Reporting Standards",
            description="Environmental, Social, and Governance reporting per GRI or industry frameworks.",
            required_approvals=1,
            penalty_severity="medium",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-MINING-001",
            name="Ore Recovery Rate",
            description="Actual ore recovery as a percentage of estimated resource.",
            unit="%",
            target_value=92.0,
            warning_threshold=85.0,
            critical_threshold=78.0,
            measurement_method="actual_ore_recovered / estimated_ore * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-MINING-002",
            name="Safety Incidents per Million Hours",
            description="Total recordable incident rate normalized to one million hours worked.",
            unit="rate",
            target_value=2.0,
            warning_threshold=5.0,
            critical_threshold=10.0,
            measurement_method="(recordable_incidents * 1_000_000) / hours_worked",
        ),
        KPIDefinition(
            kpi_id="KPI-MINING-003",
            name="Production vs Plan",
            description="Actual production as a percentage of planned production target.",
            unit="%",
            target_value=95.0,
            warning_threshold=88.0,
            critical_threshold=80.0,
            measurement_method="actual_production / planned_production * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# Module export
# ---------------------------------------------------------------------------

ALL_MANUFACTURING_PRESETS: List[IndustryPreset] = [
    DISCRETE_MANUFACTURING,
    PROCESS_MANUFACTURING,
    FOOD_BEVERAGE,
    PHARMACEUTICAL,
    AUTOMOTIVE,
    AEROSPACE_DEFENSE,
    CONSTRUCTION,
    MINING_EXTRACTION,
]
