"""
Test Suite: Deficiency Fixes Validation

Validates that all deficiencies identified in docs/STORYBOARD_DEFICIENCY_REPORT.md
have been resolved:

  DEF-001: CORS origins include common development ports
  DEF-002: CSP headers whitelist Swagger UI CDN resources
  DEF-003: Blocked execution returns clarifying questions to raise confidence
  DEF-004: Onboarding wizard error messages are accurate
  DEF-005: Chat endpoint populates both "response" and "message" fields
  DEF-006: Resolves with DEF-001 (CORS allows status check)

Additional requirements:
  - Librarian is always active (onboard mode without LLM API, llm mode with API)
  - Clarifying questions generated by LLM when available, onboard librarian otherwise

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

import importlib
import importlib.util
import os
import re
from pathlib import Path
from unittest.mock import patch

import pytest

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"



def _load_runtime():
    """Import murphy_system_1.0_runtime despite the dots in the filename."""
    runtime_path = PROJECT_ROOT / "murphy_system_1.0_runtime.py"
    spec = importlib.util.spec_from_file_location("murphy_runtime", str(runtime_path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_runtime = _load_runtime()
MurphySystem = _runtime.MurphySystem


# ===========================================================================
# DEF-001: CORS Origins Include Common Development Ports
# ===========================================================================


class TestDEF001_CORSOrigins:
    """CORS default allowlist must include ports 5000, 8000, 8080, 9000."""

    def test_default_origins_include_port_9000(self):
        from src.fastapi_security import get_cors_origins
        # Clear env to test default
        with patch.dict(os.environ, {}, clear=True):
            origins = get_cors_origins()
        assert "http://localhost:9000" in origins, (
            "Port 9000 must be in default CORS origins so HTML UIs served "
            "on that port can reach the API."
        )

    def test_default_origins_include_port_5000(self):
        from src.fastapi_security import get_cors_origins
        with patch.dict(os.environ, {}, clear=True):
            origins = get_cors_origins()
        assert "http://localhost:5000" in origins

    def test_default_origins_include_port_8000(self):
        from src.fastapi_security import get_cors_origins
        with patch.dict(os.environ, {}, clear=True):
            origins = get_cors_origins()
        assert "http://localhost:8000" in origins

    def test_default_origins_include_port_8080(self):
        from src.fastapi_security import get_cors_origins
        with patch.dict(os.environ, {}, clear=True):
            origins = get_cors_origins()
        assert "http://localhost:8080" in origins

    def test_default_origins_include_port_3000(self):
        from src.fastapi_security import get_cors_origins
        with patch.dict(os.environ, {}, clear=True):
            origins = get_cors_origins()
        assert "http://localhost:3000" in origins

    def test_env_override_still_works(self):
        from src.fastapi_security import get_cors_origins
        with patch.dict(os.environ, {"MURPHY_CORS_ORIGINS": "http://example.com"}):
            origins = get_cors_origins()
        assert origins == ["http://example.com"]
        assert "http://localhost:9000" not in origins  # env overrides defaults


# ===========================================================================
# DEF-002: CSP Headers Whitelist Swagger UI CDN
# ===========================================================================


class TestDEF002_CSPHeaders:
    """Content-Security-Policy must allow Swagger UI CDN resources."""

    def test_csp_allows_jsdelivr_scripts(self):
        from src.fastapi_security import _SECURITY_HEADERS
        csp = _SECURITY_HEADERS["Content-Security-Policy"]
        assert "https://cdn.jsdelivr.net" in csp, (
            "CSP script-src must whitelist cdn.jsdelivr.net for Swagger UI JS"
        )

    def test_csp_allows_jsdelivr_styles(self):
        from src.fastapi_security import _SECURITY_HEADERS
        csp = _SECURITY_HEADERS["Content-Security-Policy"]
        style_match = re.search(r"style-src\s+([^;]+)", csp)
        assert style_match, "CSP must have a style-src directive"
        assert "cdn.jsdelivr.net" in style_match.group(1)

    def test_csp_allows_fastapi_favicon(self):
        from src.fastapi_security import _SECURITY_HEADERS
        csp = _SECURITY_HEADERS["Content-Security-Policy"]
        img_match = re.search(r"img-src\s+([^;]+)", csp)
        assert img_match, "CSP must have an img-src directive"
        assert "fastapi.tiangolo.com" in img_match.group(1)

    def test_csp_allows_inline_scripts(self):
        """Swagger UI injects inline scripts; CSP must allow them."""
        from src.fastapi_security import _SECURITY_HEADERS
        csp = _SECURITY_HEADERS["Content-Security-Policy"]
        script_match = re.search(r"script-src\s+([^;]+)", csp)
        assert script_match, "CSP must have a script-src directive"
        assert "'unsafe-inline'" in script_match.group(1)


# ===========================================================================
# DEF-003: Blocked Execution Returns Clarifying Questions
# ===========================================================================


class TestDEF003_ClarifyingQuestions:
    """When execution is blocked, the response must include clarifying questions."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        self.murphy = MurphySystem()

    @pytest.mark.asyncio
    async def test_blocked_response_has_clarifying_questions(self):
        """Submitting a vague task should return clarifying_questions."""
        result = await self.murphy.execute_task(
            task_description="Generate a sales report for Q4",
            task_type="general",
        )
        assert result["success"] is False
        assert "clarifying_questions" in result, (
            "Blocked response must include 'clarifying_questions' to help "
            "the user provide information that raises confidence."
        )
        questions = result["clarifying_questions"]
        assert isinstance(questions, list)
        assert len(questions) > 0, (
            "At least one clarifying question must be returned when execution "
            "is blocked so the user knows what information to provide."
        )

    @pytest.mark.asyncio
    async def test_clarifying_questions_have_required_fields(self):
        """Each clarifying question must have id, question, and category."""
        result = await self.murphy.execute_task(
            task_description="Do something",
            task_type="general",
        )
        if result.get("clarifying_questions"):
            for q in result["clarifying_questions"]:
                assert "id" in q, "Each question must have an 'id'"
                assert "question" in q, "Each question must have a 'question' text"
                assert "category" in q, "Each question must have a 'category'"

    def test_onboard_clarifying_questions_from_information_gaps(self):
        """_onboard_clarifying_questions should extract from information_gaps."""
        activation_preview = {
            "dynamic_implementation": {
                "information_gaps": [
                    {"id": "requirements_identification", "label": "Requirements",
                     "owner": "user", "reason": "Missing onboarding answers."},
                ],
                "next_actions": ["Collect missing onboarding answers to lock requirements."],
            },
            "confidence": 0.3,
        }
        questions = self.murphy._onboard_clarifying_questions(
            "some task", activation_preview
        )
        assert len(questions) > 0
        gap_qs = [q for q in questions if q["category"] == "information_gap"]
        assert len(gap_qs) >= 1

    def test_onboard_clarifying_questions_fallback_for_low_confidence(self):
        """When confidence is very low and no gaps, generate generic questions."""
        activation_preview = {
            "dynamic_implementation": {
                "information_gaps": [],
                "next_actions": [],
            },
            "confidence": 0.2,
        }
        questions = self.murphy._onboard_clarifying_questions(
            "some vague task", activation_preview
        )
        assert len(questions) >= 3, (
            "With very low confidence and no gaps, fallback questions should be generated"
        )
        categories = {q["category"] for q in questions}
        assert "task_clarification" in categories

    def test_llm_question_generation_returns_empty_without_api(self):
        """Without an LLM API key, _try_llm_clarifying_questions returns empty list."""
        with patch.dict(os.environ, {}, clear=True):
            activation_preview = {
                "dynamic_implementation": {
                    "information_gaps": [],
                    "next_actions": [],
                },
                "confidence": 0.3,
            }
            questions = self.murphy._try_llm_clarifying_questions(
                "some task", activation_preview
            )
            assert questions == [], (
                "Without LLM API key, LLM question generation should return empty "
                "and fall back to onboard questions."
            )

    def test_build_clarifying_questions_delegates_correctly(self):
        """_build_clarifying_questions should use onboard when no LLM API."""
        with patch.dict(os.environ, {}, clear=True):
            activation_preview = {
                "dynamic_implementation": {
                    "information_gaps": [
                        {"id": "req", "label": "Requirements", "owner": "user",
                         "reason": "Describe your requirements."},
                    ],
                    "next_actions": [],
                },
                "confidence": 0.3,
            }
            questions = self.murphy._build_clarifying_questions(
                "some task", activation_preview
            )
            assert len(questions) > 0
            # Should be from onboard since no LLM
            assert any(q["category"] == "information_gap" for q in questions)


# ===========================================================================
# DEF-004: Onboarding Wizard Error Messages
# ===========================================================================


class TestDEF004_OnboardingWizardMessages:
    """Onboarding wizard should not say 'backend is not running' for CORS issues."""

    def test_no_misleading_not_running_message(self):
        html_path = PROJECT_ROOT / "onboarding_wizard.html"
        content = html_path.read_text(encoding="utf-8")
        assert "backend is not running" not in content, (
            "The wizard must not say 'backend is not running' — "
            "use a message that accounts for CORS/network issues."
        )

    def test_error_message_mentions_cors(self):
        html_path = PROJECT_ROOT / "onboarding_wizard.html"
        content = html_path.read_text(encoding="utf-8")
        assert "CORS" in content, (
            "Error messages should mention CORS as a possible cause "
            "when the backend cannot be reached."
        )


# ===========================================================================
# DEF-005: Chat Endpoint Returns Both Response and Message Fields
# ===========================================================================


class TestDEF005_ChatResponseFields:
    """Chat endpoint must populate both 'response' and 'message' fields."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        self.murphy = MurphySystem()

    def test_chat_response_has_both_fields(self):
        result = self.murphy.handle_chat(
            message="help",
            session_id=None,
            use_mfgc=False,
        )
        assert "message" in result, "Chat response must have 'message' field"
        assert "response" in result, "Chat response must have 'response' field"

    def test_chat_response_fields_match(self):
        result = self.murphy.handle_chat(
            message="help",
            session_id=None,
            use_mfgc=False,
        )
        assert result["message"] == result["response"], (
            "'message' and 'response' must contain the same text"
        )

    def test_chat_response_is_not_empty(self):
        result = self.murphy.handle_chat(
            message="help",
            session_id=None,
            use_mfgc=False,
        )
        assert result["response"], "Chat 'response' field must not be empty"
        assert result["message"], "Chat 'message' field must not be empty"

    def test_chat_status_intent(self):
        result = self.murphy.handle_chat(
            message="status",
            session_id=None,
            use_mfgc=False,
        )
        assert result.get("success") is True
        assert result.get("response"), "Status response must not be empty"
        assert result.get("message"), "Status message must not be empty"


# ===========================================================================
# Librarian Always Active + LLM/Onboard Mode
# ===========================================================================


class TestLibrarianAlwaysActive:
    """Librarian must always be operational — onboard mode or LLM mode."""

    @pytest.fixture(autouse=True)
    def _setup(self):
        self.murphy = MurphySystem()

    def test_librarian_status_enabled_without_llm(self):
        """Even without LLM API key, librarian reports enabled=True."""
        with patch.dict(os.environ, {}, clear=True):
            status = self.murphy._get_librarian_status()
        assert status["enabled"] is True, "Librarian must always be enabled"
        assert status["mode"] == "onboard", (
            "Without LLM API key, librarian should be in 'onboard' mode"
        )

    def test_librarian_status_mode_llm_with_key(self):
        """With LLM API key set, librarian reports mode='llm'."""
        with patch.dict(os.environ, {
            "MURPHY_LLM_PROVIDER": "groq",
            "GROQ_API_KEY": "test_key"
        }):
            status = self.murphy._get_librarian_status()
        assert status["enabled"] is True
        assert status["mode"] == "llm"
        assert status["llm_provider"] == "groq"

    def test_librarian_ask_works_without_llm(self):
        """Librarian must respond in onboard mode without any LLM key."""
        with patch.dict(os.environ, {}, clear=True):
            result = self.murphy.librarian_ask("How do I get started?")
        assert result["success"] is True, "Librarian must always succeed in onboard mode"
        assert result["mode"] == "onboard"
        assert result["message"], "Librarian onboard response must not be empty"
        assert result["response"], "Librarian onboard response field must not be empty"

    def test_librarian_ask_returns_response_field(self):
        """librarian_ask response must have both 'response' and 'message'."""
        result = self.murphy.librarian_ask("help")
        assert "response" in result
        assert "message" in result
        assert result["response"] == result["message"]

    def test_librarian_mode_shown_in_system_status(self):
        """System status should show librarian mode."""
        status = self.murphy.get_system_status()
        lib = status.get("librarian", {})
        assert lib.get("enabled") is True
        assert "mode" in lib

