"""
Dynamic Projection Gate System
Gates are generated by CEO/Orchestration agents based on:
- Current metrics and measurable units
- Future projections (short-term and long-term)
- Goal achievement status
- Resource optimization recommendations

Example: $10M sale in Q2 → reduce Q3 advertising if goal was only $1M
"""

from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
from dataclasses import dataclass
import json

@dataclass
class Metric:
    """Measurable unit that defines current state"""
    name: str
    current_value: float
    target_value: float
    unit: str
    timestamp: datetime
    
    def achievement_percentage(self) -> float:
        """Calculate how much of target is achieved"""
        if self.target_value == 0:
            return 100.0
        return (self.current_value / self.target_value) * 100

@dataclass
class Projection:
    """Future projection (short or long term)"""
    timeframe: str  # "Q1", "Q2", "2025", "next_month", etc.
    metric_name: str
    projected_value: float
    confidence: float
    basis: str  # What this projection is based on

@dataclass
class DynamicGate:
    """Gate recommended by CEO/Orchestration agents"""
    gate_id: str
    gate_type: str  # "resource_allocation", "budget_adjustment", "strategy_shift", etc.
    recommendation: str
    reasoning: str
    metrics_basis: List[str]  # Which metrics led to this recommendation
    impact_timeframe: str  # When this should take effect
    projected_impact: Dict[str, Any]
    confidence: float
    priority: str  # "critical", "high", "medium", "low"
    
class CEOAgent:
    """CEO Agent that analyzes metrics and generates strategic gates"""
    
    def __init__(self):
        self.current_metrics = {}
        self.projections = {}
        self.goals = {}
        
    def update_metric(self, metric: Metric):
        """Update current metric"""
        self.current_metrics[metric.name] = metric
        
    def add_projection(self, projection: Projection):
        """Add future projection"""
        key = f"{projection.metric_name}_{projection.timeframe}"
        self.projections[key] = projection
        
    def set_goal(self, metric_name: str, timeframe: str, target: float):
        """Set business goal"""
        self.goals[f"{metric_name}_{timeframe}"] = target
        
    def analyze_and_generate_gates(self) -> List[DynamicGate]:
        """
        Analyze current state + projections and generate strategic gates
        
        Example Logic:
        - If Q2 sales = $10M and Q2 goal = $1M → Reduce Q3 ad spend
        - If customer acquisition cost rising → Increase retention focus
        - If revenue ahead of schedule → Invest in expansion
        """
        gates = []
        
        # Check revenue vs goals
        revenue_gates = self._analyze_revenue_performance()
        gates.extend(revenue_gates)
        
        # Check resource utilization
        resource_gates = self._analyze_resource_efficiency()
        gates.extend(resource_gates)
        
        # Check growth trajectory
        growth_gates = self._analyze_growth_trajectory()
        gates.extend(growth_gates)
        
        # Check risk exposure
        risk_gates = self._analyze_risk_exposure()
        gates.extend(risk_gates)
        
        return gates
    
    def _analyze_revenue_performance(self) -> List[DynamicGate]:
        """Analyze revenue vs goals and generate gates"""
        gates = []
        
        # Example: Q2 sales exceeded goal significantly
        if "revenue_Q2" in self.current_metrics:
            q2_revenue = self.current_metrics["revenue_Q2"]
            q2_goal = self.goals.get("revenue_Q2", q2_revenue.target_value)
            
            if q2_revenue.current_value >= q2_goal * 5:  # 5x or more the goal!
                # Recommend reducing Q3 advertising
                gates.append(DynamicGate(
                    gate_id=f"budget_adjustment_{datetime.now().timestamp()}",
                    gate_type="budget_adjustment",
                    recommendation="Reduce Q3 advertising budget by 60%",
                    reasoning=f"Q2 revenue of ${q2_revenue.current_value:,.0f} exceeded goal of ${q2_goal:,.0f} by 10x. Market demand is strong. Reduce ad spend and reallocate to product development.",
                    metrics_basis=["revenue_Q2", "ad_spend_Q2"],
                    impact_timeframe="Q3_2025",
                    projected_impact={
                        "cost_savings": q2_goal * 0.6,
                        "revenue_impact": "minimal - organic demand is high",
                        "reallocation": "product_development"
                    },
                    confidence=0.92,
                    priority="high"
                ))
                
                # Recommend investing in capacity
                gates.append(DynamicGate(
                    gate_id=f"capacity_expansion_{datetime.now().timestamp()}",
                    gate_type="resource_allocation",
                    recommendation="Increase production/service capacity by 40%",
                    reasoning="Strong Q2 performance indicates sustained demand. Invest in capacity to capture market opportunity.",
                    metrics_basis=["revenue_Q2", "demand_trend"],
                    impact_timeframe="Q3_Q4_2025",
                    projected_impact={
                        "capacity_increase": "40%",
                        "investment_required": q2_revenue.current_value * 0.15,
                        "projected_roi": "250% over 6 months"
                    },
                    confidence=0.88,
                    priority="critical"
                ))
        
        return gates
    
    def _analyze_resource_efficiency(self) -> List[DynamicGate]:
        """Analyze resource utilization and generate optimization gates"""
        gates = []
        
        # Check if resources are underutilized
        if "resource_utilization" in self.current_metrics:
            utilization = self.current_metrics["resource_utilization"]
            
            if utilization.current_value < 60:  # Less than 60% utilized
                gates.append(DynamicGate(
                    gate_id=f"resource_optimization_{datetime.now().timestamp()}",
                    gate_type="resource_allocation",
                    recommendation="Consolidate resources and reduce overhead by 25%",
                    reasoning=f"Current utilization at {utilization.current_value}% indicates excess capacity. Consolidate to improve efficiency.",
                    metrics_basis=["resource_utilization", "overhead_costs"],
                    impact_timeframe="immediate",
                    projected_impact={
                        "cost_reduction": "25%",
                        "efficiency_gain": "40%",
                        "timeline": "30 days"
                    },
                    confidence=0.85,
                    priority="high"
                ))
        
        return gates
    
    def _analyze_growth_trajectory(self) -> List[DynamicGate]:
        """Analyze growth trends and generate strategic gates"""
        gates = []
        
        # Check if growth is accelerating
        if "growth_rate" in self.current_metrics:
            growth = self.current_metrics["growth_rate"]
            
            if growth.current_value > growth.target_value * 1.5:
                gates.append(DynamicGate(
                    gate_id=f"expansion_strategy_{datetime.now().timestamp()}",
                    gate_type="strategy_shift",
                    recommendation="Accelerate market expansion - enter 3 new markets",
                    reasoning=f"Growth rate of {growth.current_value}% exceeds target by 50%. Market conditions favorable for expansion.",
                    metrics_basis=["growth_rate", "market_share", "customer_satisfaction"],
                    impact_timeframe="Q4_2025_Q1_2026",
                    projected_impact={
                        "new_markets": 3,
                        "revenue_increase": "60-80%",
                        "investment": "moderate",
                        "risk": "medium"
                    },
                    confidence=0.78,
                    priority="medium"
                ))
        
        return gates
    
    def _analyze_risk_exposure(self) -> List[DynamicGate]:
        """Analyze risk levels and generate mitigation gates"""
        gates = []
        
        # Check if single customer represents too much revenue
        if "customer_concentration" in self.current_metrics:
            concentration = self.current_metrics["customer_concentration"]
            
            if concentration.current_value > 40:  # Single customer > 40% of revenue
                gates.append(DynamicGate(
                    gate_id=f"risk_mitigation_{datetime.now().timestamp()}",
                    gate_type="risk_management",
                    recommendation="Diversify customer base - target 20 new enterprise clients",
                    reasoning=f"Customer concentration at {concentration.current_value}% creates significant risk. Diversify to reduce dependency.",
                    metrics_basis=["customer_concentration", "revenue_stability"],
                    impact_timeframe="Q3_Q4_2025",
                    projected_impact={
                        "risk_reduction": "50%",
                        "new_customers": 20,
                        "revenue_stability": "high"
                    },
                    confidence=0.90,
                    priority="critical"
                ))
        
        return gates

class OrchestrationAgent:
    """Orchestration Agent that coordinates execution based on CEO gates"""
    
    def __init__(self):
        self.active_gates = []
        self.execution_plan = {}
        
    def receive_gates(self, gates: List[DynamicGate]):
        """Receive gates from CEO agent"""
        self.active_gates = gates
        self._prioritize_gates()
        
    def _prioritize_gates(self):
        """Sort gates by priority and confidence"""
        priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        self.active_gates.sort(
            key=lambda g: (priority_order.get(g.priority, 4), -g.confidence)
        )
    
    def generate_execution_plan(self) -> Dict[str, Any]:
        """Generate detailed execution plan from gates"""
        plan = {
            "immediate_actions": [],
            "short_term_actions": [],
            "long_term_actions": [],
            "resource_requirements": {},
            "expected_outcomes": {}
        }
        
        for gate in self.active_gates:
            action = {
                "gate_id": gate.gate_id,
                "action": gate.recommendation,
                "reasoning": gate.reasoning,
                "priority": gate.priority,
                "confidence": gate.confidence,
                "impact": gate.projected_impact
            }
            
            # Categorize by timeframe
            if "immediate" in gate.impact_timeframe.lower():
                plan["immediate_actions"].append(action)
            elif any(q in gate.impact_timeframe for q in ["Q3", "Q4", "next"]):
                plan["short_term_actions"].append(action)
            else:
                plan["long_term_actions"].append(action)
        
        return plan
    
    def execute_gate(self, gate_id: str) -> Dict[str, Any]:
        """Execute a specific gate recommendation"""
        gate = next((g for g in self.active_gates if g.gate_id == gate_id), None)
        
        if not gate:
            return {"success": False, "error": "Gate not found"}
        
        # In real implementation, this would trigger actual actions
        return {
            "success": True,
            "gate_id": gate_id,
            "action_taken": gate.recommendation,
            "status": "executing",
            "estimated_completion": self._estimate_completion(gate)
        }
    
    def _estimate_completion(self, gate: DynamicGate) -> str:
        """Estimate when gate execution will complete"""
        if "immediate" in gate.impact_timeframe.lower():
            return "1-7 days"
        elif "Q3" in gate.impact_timeframe:
            return "30-60 days"
        else:
            return "90+ days"

class DynamicProjectionGateSystem:
    """Main system that coordinates CEO and Orchestration agents"""
    
    def __init__(self):
        self.ceo_agent = CEOAgent()
        self.orchestration_agent = OrchestrationAgent()
        self.metrics_history = []
        
    def update_metrics(self, metrics: List[Metric]):
        """Update current metrics"""
        for metric in metrics:
            self.ceo_agent.update_metric(metric)
            self.metrics_history.append(metric)
    
    def add_projections(self, projections: List[Projection]):
        """Add future projections"""
        for projection in projections:
            self.ceo_agent.add_projection(projection)
    
    def set_goals(self, goals: Dict[str, Dict[str, float]]):
        """Set business goals"""
        for metric_name, timeframes in goals.items():
            for timeframe, target in timeframes.items():
                self.ceo_agent.set_goal(metric_name, timeframe, target)
    
    def generate_strategic_gates(self) -> Dict[str, Any]:
        """Generate gates based on current state and projections"""
        # CEO analyzes and generates gates
        gates = self.ceo_agent.analyze_and_generate_gates()
        
        # Orchestration agent receives and plans
        self.orchestration_agent.receive_gates(gates)
        execution_plan = self.orchestration_agent.generate_execution_plan()
        
        return {
            "success": True,
            "gates_generated": len(gates),
            "gates": [self._gate_to_dict(g) for g in gates],
            "execution_plan": execution_plan,
            "timestamp": datetime.now().isoformat()
        }
    
    def _gate_to_dict(self, gate: DynamicGate) -> Dict[str, Any]:
        """Convert gate to dictionary"""
        return {
            "gate_id": gate.gate_id,
            "gate_type": gate.gate_type,
            "recommendation": gate.recommendation,
            "reasoning": gate.reasoning,
            "metrics_basis": gate.metrics_basis,
            "impact_timeframe": gate.impact_timeframe,
            "projected_impact": gate.projected_impact,
            "confidence": gate.confidence,
            "priority": gate.priority
        }

def integrate_dynamic_projection_gates(app, librarian_system):
    """Integrate dynamic projection gate system with Flask app"""
    
    gate_system = DynamicProjectionGateSystem()
    
    @app.route('/api/gates/dynamic/update-metrics', methods=['POST'])
    def update_metrics():
        """Update current metrics"""
        from flask import request, jsonify
        
        try:
            data = request.json
            metrics_data = data.get('metrics', [])
            
            metrics = []
            for m in metrics_data:
                metric = Metric(
                    name=m['name'],
                    current_value=m['current_value'],
                    target_value=m['target_value'],
                    unit=m['unit'],
                    timestamp=datetime.now()
                )
                metrics.append(metric)
            
            gate_system.update_metrics(metrics)
            
            return jsonify({
                'success': True,
                'metrics_updated': len(metrics)
            })
            
        except Exception as e:
            return jsonify({'success': False, 'error': str(e)}), 500
    
    @app.route('/api/gates/dynamic/add-projections', methods=['POST'])
    def add_projections():
        """Add future projections"""
        from flask import request, jsonify
        
        try:
            data = request.json
            projections_data = data.get('projections', [])
            
            projections = []
            for p in projections_data:
                projection = Projection(
                    timeframe=p['timeframe'],
                    metric_name=p['metric_name'],
                    projected_value=p['projected_value'],
                    confidence=p.get('confidence', 0.8),
                    basis=p.get('basis', 'historical_trend')
                )
                projections.append(projection)
            
            gate_system.add_projections(projections)
            
            return jsonify({
                'success': True,
                'projections_added': len(projections)
            })
            
        except Exception as e:
            return jsonify({'success': False, 'error': str(e)}), 500
    
    @app.route('/api/gates/dynamic/set-goals', methods=['POST'])
    def set_goals():
        """Set business goals"""
        from flask import request, jsonify
        
        try:
            data = request.json
            goals = data.get('goals', {})
            
            gate_system.set_goals(goals)
            
            return jsonify({
                'success': True,
                'goals_set': len(goals)
            })
            
        except Exception as e:
            return jsonify({'success': False, 'error': str(e)}), 500
    
    @app.route('/api/gates/dynamic/generate', methods=['POST'])
    def generate_strategic_gates():
        """Generate strategic gates based on metrics and projections"""
        from flask import jsonify
        
        try:
            result = gate_system.generate_strategic_gates()
            return jsonify(result)
            
        except Exception as e:
            return jsonify({'success': False, 'error': str(e)}), 500
    
    @app.route('/api/gates/dynamic/execute/<gate_id>', methods=['POST'])
    def execute_gate(gate_id):
        """Execute a specific gate"""
        from flask import jsonify
        
        try:
            result = gate_system.orchestration_agent.execute_gate(gate_id)
            return jsonify(result)
            
        except Exception as e:
            return jsonify({'success': False, 'error': str(e)}), 500
    
    return gate_system