"""
PRESET-018 through PRESET-024 — Technology Presets
====================================================

Industry presets for SaaS companies, software agencies, data science labs,
cybersecurity firms, IT MSPs, game studios, and AI/ML startups.

Copyright 2024 Inoni LLC – BSL-1.1
"""

from __future__ import annotations

import logging
from typing import List

from .base import (
    AgentPersona,
    ComplianceRule,
    IndustryPreset,
    IntegrationMapping,
    KPIDefinition,
    WorkflowTemplate,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# PRESET-018 — SaaS Company
# ---------------------------------------------------------------------------

SAAS_COMPANY = IndustryPreset(
    preset_id="PRESET-018",
    name="SaaS Company",
    industry="Technology",
    sub_industry="Software-as-a-Service",
    description="Product development, CI/CD, customer success, billing, and SOC 2 compliance for B2B SaaS.",
    version="1.0.0",
    tags=["saas", "product", "ci-cd", "customer-success", "SOC2", "GDPR", "MRR"],
    compatible_with=["PRESET-019", "PRESET-022"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-SAAS-001",
            name="Sprint Development Cycle",
            description="Plan, build, test, and release product features in two-week sprints.",
            steps=[
                {
                    "step_name": "Sprint Planning & Backlog Grooming",
                    "step_type": "planning",
                    "agent_persona": "Product Engineering Lead",
                    "integrations": ["Jira", "GitHub"],
                    "compliance_gates": [],
                    "kpis": ["sprint_velocity"],
                },
                {
                    "step_name": "Development & Code Review",
                    "step_type": "processing",
                    "agent_persona": "Product Engineering Lead",
                    "integrations": ["GitHub"],
                    "compliance_gates": ["SOC-2-change-management"],
                    "kpis": ["code_review_turnaround"],
                },
                {
                    "step_name": "CI/CD Pipeline & Automated Tests",
                    "step_type": "automated_check",
                    "agent_persona": "Product Engineering Lead",
                    "integrations": ["GitHub"],
                    "compliance_gates": ["SOC-2-testing-requirements"],
                    "kpis": ["deployment_success_rate"],
                },
                {
                    "step_name": "Feature Release & Monitoring",
                    "step_type": "integration_action",
                    "agent_persona": "Customer Success Agent",
                    "integrations": ["GitHub", "Intercom"],
                    "compliance_gates": ["GDPR-release-privacy-review"],
                    "kpis": ["release_frequency", "mean_time_to_recovery"],
                },
            ],
            triggers=["sprint_start", "hotfix_required"],
            outputs=["deployed_feature", "release_notes", "monitoring_dashboard"],
        ),
        WorkflowTemplate(
            template_id="WF-SAAS-002",
            name="Customer Onboarding & Retention",
            description="Trial conversion, onboarding, health monitoring, and churn prevention.",
            steps=[
                {
                    "step_name": "Trial to Paid Conversion",
                    "step_type": "processing",
                    "agent_persona": "Customer Success Agent",
                    "integrations": ["Salesforce", "Stripe"],
                    "compliance_gates": ["GDPR-consent", "billing-disclosure"],
                    "kpis": ["trial_conversion_rate"],
                },
                {
                    "step_name": "Onboarding Sequence",
                    "step_type": "communication",
                    "agent_persona": "Customer Success Agent",
                    "integrations": ["Intercom", "Salesforce"],
                    "compliance_gates": [],
                    "kpis": ["time_to_value", "NPS"],
                },
                {
                    "step_name": "Health Scoring & Churn Detection",
                    "step_type": "automated_check",
                    "agent_persona": "Customer Success Agent",
                    "integrations": ["Salesforce", "Intercom"],
                    "compliance_gates": [],
                    "kpis": ["churn_rate", "NPS"],
                },
            ],
            triggers=["trial_signup", "health_score_drops", "renewal_due"],
            outputs=["paid_subscription", "onboarding_completion", "renewal_confirmation"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-SAAS-001",
            name="Product Engineering Lead",
            role="Engineering Manager",
            domain="SaaS",
            capabilities=["sprint_planning", "code_review", "CI_CD_management", "architecture_decisions"],
            tools=["GitHub", "Jira"],
            personality_traits=["technical", "velocity-focused", "quality-driven"],
        ),
        AgentPersona(
            persona_id="AP-SAAS-002",
            name="Customer Success Agent",
            role="Customer Success Manager",
            domain="SaaS",
            capabilities=["onboarding", "health_monitoring", "churn_prevention", "expansion_revenue", "NPS_programs"],
            tools=["Salesforce", "Intercom", "Stripe"],
            personality_traits=["proactive", "empathetic", "data-driven"],
        ),
        AgentPersona(
            persona_id="AP-SAAS-003",
            name="Billing & Revenue Ops Agent",
            role="Revenue Operations",
            domain="SaaS",
            capabilities=["subscription_management", "billing_automation", "MRR_reporting", "dunning_management"],
            tools=["Stripe", "Salesforce"],
            personality_traits=["analytical", "process-oriented", "financial-savvy"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="GitHub",
            connector_type="source_control",
            required=True,
            config_template={"app_id": "", "private_key": "", "org": ""},
            purpose="Source control, CI/CD, and code review workflows.",
        ),
        IntegrationMapping(
            connector_name="Jira",
            connector_type="project_management",
            required=True,
            config_template={"domain": "", "email": "", "api_token": ""},
            purpose="Sprint management and issue tracking.",
        ),
        IntegrationMapping(
            connector_name="Stripe",
            connector_type="billing",
            required=True,
            config_template={"secret_key": "", "webhook_secret": ""},
            purpose="Subscription billing and payment processing.",
        ),
        IntegrationMapping(
            connector_name="Salesforce",
            connector_type="crm",
            required=True,
            config_template={"client_id": "", "instance_url": ""},
            purpose="CRM for leads, accounts, and customer health tracking.",
        ),
        IntegrationMapping(
            connector_name="Intercom",
            connector_type="customer_engagement",
            required=False,
            config_template={"access_token": ""},
            purpose="In-app messaging, onboarding, and support.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-SAAS-001",
            standard="SOC 2 Type II",
            description="Annual SOC 2 audit covering security, availability, processing integrity, confidentiality, and privacy.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-SAAS-002",
            standard="GDPR",
            description="EU General Data Protection Regulation requires consent management, data subject rights, and DPA agreements.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-SAAS-001",
            name="Monthly Recurring Revenue (MRR)",
            description="Total normalized monthly subscription revenue.",
            unit="USD",
            target_value=100000.0,
            warning_threshold=85000.0,
            critical_threshold=70000.0,
            measurement_method="sum(active_subscriptions * monthly_value)",
        ),
        KPIDefinition(
            kpi_id="KPI-SAAS-002",
            name="Churn Rate",
            description="Monthly percentage of MRR lost from cancellations.",
            unit="%",
            target_value=1.5,
            warning_threshold=3.0,
            critical_threshold=5.0,
            measurement_method="churned_MRR / beginning_MRR * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-SAAS-003",
            name="Net Promoter Score",
            description="Customer NPS measured quarterly.",
            unit="score",
            target_value=45.0,
            warning_threshold=25.0,
            critical_threshold=10.0,
            measurement_method="promoters_pct - detractors_pct",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-019 — Software Agency
# ---------------------------------------------------------------------------

SOFTWARE_AGENCY = IndustryPreset(
    preset_id="PRESET-019",
    name="Software Development Agency",
    industry="Technology",
    sub_industry="Software Agency",
    description="Client project delivery, sprint management, time tracking, and agency financial health.",
    version="1.0.0",
    tags=["software-agency", "consulting", "project-delivery", "utilization", "sprints"],
    compatible_with=["PRESET-018", "PRESET-003"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-SW-AGENCY-001",
            name="Project Kick-off & Sprint Setup",
            description="Discovery, scoping, team assembly, and first sprint launch.",
            steps=[
                {
                    "step_name": "Discovery & Requirements",
                    "step_type": "data_collection",
                    "agent_persona": "Agency Delivery Manager",
                    "integrations": ["Linear", "HubSpot"],
                    "compliance_gates": ["MSA-SOW-execution"],
                    "kpis": ["time_to_project_start"],
                },
                {
                    "step_name": "Sprint Planning & Resource Allocation",
                    "step_type": "planning",
                    "agent_persona": "Agency Delivery Manager",
                    "integrations": ["Linear", "Harvest"],
                    "compliance_gates": [],
                    "kpis": ["utilization_rate"],
                },
                {
                    "step_name": "Client Portal Setup",
                    "step_type": "integration_action",
                    "agent_persona": "Agency Delivery Manager",
                    "integrations": ["Linear"],
                    "compliance_gates": [],
                    "kpis": ["client_satisfaction"],
                },
            ],
            triggers=["contract_signed", "new_engagement_start"],
            outputs=["project_plan", "sprint_backlog", "client_portal"],
        ),
        WorkflowTemplate(
            template_id="WF-SW-AGENCY-002",
            name="Monthly Invoicing & Utilization Review",
            description="Track billable hours, generate invoices, and review team utilization.",
            steps=[
                {
                    "step_name": "Timesheet Reconciliation",
                    "step_type": "automated_check",
                    "agent_persona": "Agency Finance & Ops Agent",
                    "integrations": ["Harvest"],
                    "compliance_gates": [],
                    "kpis": ["timesheet_submission_rate"],
                },
                {
                    "step_name": "Invoice Generation & Delivery",
                    "step_type": "document_generation",
                    "agent_persona": "Agency Finance & Ops Agent",
                    "integrations": ["Harvest", "QuickBooks"],
                    "compliance_gates": [],
                    "kpis": ["days_to_invoice", "project_gross_margin"],
                },
            ],
            triggers=["month_end", "milestone_complete"],
            outputs=["invoice", "utilization_report", "project_P&L"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-SW-AGENCY-001",
            name="Agency Delivery Manager",
            role="Project Manager / Delivery Lead",
            domain="Software Agency",
            capabilities=["project_scoping", "sprint_management", "client_communication", "risk_management"],
            tools=["Linear", "Harvest", "HubSpot"],
            personality_traits=["organized", "client-focused", "technically-aware"],
        ),
        AgentPersona(
            persona_id="AP-SW-AGENCY-002",
            name="Agency Finance & Ops Agent",
            role="Operations & Finance",
            domain="Software Agency",
            capabilities=["invoicing", "utilization_tracking", "P&L_analysis", "resource_forecasting"],
            tools=["Harvest", "QuickBooks"],
            personality_traits=["analytical", "detail-oriented", "efficiency-focused"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="GitHub",
            connector_type="source_control",
            required=True,
            config_template={"app_id": "", "org": ""},
            purpose="Source control and CI/CD for client projects.",
        ),
        IntegrationMapping(
            connector_name="Linear",
            connector_type="project_management",
            required=True,
            config_template={"api_key": "", "team_id": ""},
            purpose="Issue tracking and sprint management.",
        ),
        IntegrationMapping(
            connector_name="Harvest",
            connector_type="time_tracking",
            required=True,
            config_template={"account_id": "", "access_token": ""},
            purpose="Time tracking, invoicing, and project profitability.",
        ),
        IntegrationMapping(
            connector_name="HubSpot",
            connector_type="crm",
            required=False,
            config_template={"api_key": ""},
            purpose="Client CRM and sales pipeline.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-SW-AGENCY-001",
            standard="Client NDA / IP Assignment",
            description="All client engagements must have executed NDA and IP assignment agreements before work starts.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-SW-AGENCY-002",
            standard="Data Handling Agreement",
            description="Client data processed during development must be governed by a DHA/DPA if personal data is involved.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-SW-AGENCY-001",
            name="Billable Utilization Rate",
            description="Billable hours as a percentage of total available developer hours.",
            unit="%",
            target_value=78.0,
            warning_threshold=68.0,
            critical_threshold=58.0,
            measurement_method="billable_hours / available_hours * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-SW-AGENCY-002",
            name="Project Gross Margin",
            description="Revenue minus direct project costs as a percentage of revenue.",
            unit="%",
            target_value=45.0,
            warning_threshold=35.0,
            critical_threshold=25.0,
            measurement_method="(revenue - direct_costs) / revenue * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-SW-AGENCY-003",
            name="Client Retention Rate",
            description="Percentage of clients returning for additional engagements.",
            unit="%",
            target_value=80.0,
            warning_threshold=65.0,
            critical_threshold=50.0,
            measurement_method="returning_clients / total_clients * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-020 — Data Science Lab
# ---------------------------------------------------------------------------

DATA_SCIENCE_LAB = IndustryPreset(
    preset_id="PRESET-020",
    name="Data Science Lab",
    industry="Technology",
    sub_industry="Data Science & ML",
    description="ML experiment tracking, model registry, data pipelines, and model serving infrastructure.",
    version="1.0.0",
    tags=["data-science", "ML", "experiment-tracking", "model-registry", "pipelines", "Snowflake"],
    compatible_with=["PRESET-024", "PRESET-018"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-DS-001",
            name="ML Experiment & Model Development",
            description="Design experiments, track runs, evaluate models, and register production candidates.",
            steps=[
                {
                    "step_name": "Data Ingestion & Validation",
                    "step_type": "automated_check",
                    "agent_persona": "ML Research Engineer",
                    "integrations": ["Snowflake", "DVC"],
                    "compliance_gates": ["data-privacy-review"],
                    "kpis": ["data_pipeline_uptime"],
                },
                {
                    "step_name": "Experiment Tracking & Hyperparameter Tuning",
                    "step_type": "processing",
                    "agent_persona": "ML Research Engineer",
                    "integrations": ["MLflow", "Weights & Biases"],
                    "compliance_gates": [],
                    "kpis": ["experiment_velocity"],
                },
                {
                    "step_name": "Model Evaluation & Registry Promotion",
                    "step_type": "human_review",
                    "agent_persona": "ML Research Engineer",
                    "integrations": ["MLflow"],
                    "compliance_gates": ["model-approval-gate"],
                    "kpis": ["model_accuracy"],
                },
            ],
            triggers=["dataset_updated", "scheduled_retraining"],
            outputs=["registered_model", "experiment_report", "performance_benchmark"],
        ),
        WorkflowTemplate(
            template_id="WF-DS-002",
            name="Model Deployment & Monitoring",
            description="Deploy models to production and monitor drift and performance.",
            steps=[
                {
                    "step_name": "Model Deployment",
                    "step_type": "integration_action",
                    "agent_persona": "ML Ops Engineer",
                    "integrations": ["MLflow", "AWS SageMaker"],
                    "compliance_gates": ["privacy-impact-assessment"],
                    "kpis": ["deployment_success_rate"],
                },
                {
                    "step_name": "Performance & Drift Monitoring",
                    "step_type": "automated_check",
                    "agent_persona": "ML Ops Engineer",
                    "integrations": ["Weights & Biases", "Snowflake"],
                    "compliance_gates": [],
                    "kpis": ["inference_latency", "model_accuracy"],
                },
            ],
            triggers=["model_approved", "drift_alert"],
            outputs=["deployed_endpoint", "monitoring_dashboard", "retraining_trigger"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-DS-001",
            name="ML Research Engineer",
            role="Machine Learning Engineer",
            domain="Data Science",
            capabilities=["feature_engineering", "model_training", "experiment_design", "statistical_analysis"],
            tools=["MLflow", "Weights & Biases", "DVC", "Snowflake"],
            personality_traits=["scientific", "curious", "rigorous"],
        ),
        AgentPersona(
            persona_id="AP-DS-002",
            name="ML Ops Engineer",
            role="MLOps Engineer",
            domain="Data Science",
            capabilities=["model_deployment", "pipeline_automation", "monitoring_setup", "infrastructure_management"],
            tools=["MLflow", "AWS SageMaker", "Snowflake"],
            personality_traits=["systematic", "reliability-focused", "automation-minded"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="MLflow",
            connector_type="experiment_tracking",
            required=True,
            config_template={"tracking_uri": "", "registry_uri": ""},
            purpose="Experiment tracking, model registry, and deployment.",
        ),
        IntegrationMapping(
            connector_name="Snowflake",
            connector_type="data_warehouse",
            required=True,
            config_template={"account": "", "user": "", "warehouse": ""},
            purpose="Data warehouse for feature stores and analytics.",
        ),
        IntegrationMapping(
            connector_name="DVC",
            connector_type="data_version_control",
            required=False,
            config_template={"remote": ""},
            purpose="Dataset and model artifact versioning.",
        ),
        IntegrationMapping(
            connector_name="Weights & Biases",
            connector_type="experiment_tracking",
            required=False,
            config_template={"api_key": "", "project": ""},
            purpose="Experiment visualization and model performance tracking.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-DS-001",
            standard="Data Privacy (GDPR/CCPA)",
            description="Training datasets containing personal data require privacy impact assessments and data subject consent.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-DS-002",
            standard="Model Governance",
            description="Production models must pass bias/fairness evaluation and have documented performance benchmarks.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-DS-001",
            name="Model Accuracy",
            description="Primary evaluation metric (F1/AUC/RMSE) for production model.",
            unit="score",
            target_value=0.92,
            warning_threshold=0.85,
            critical_threshold=0.78,
            measurement_method="model_eval_metric_on_holdout_set",
        ),
        KPIDefinition(
            kpi_id="KPI-DS-002",
            name="Pipeline Uptime",
            description="Percentage of time data pipelines are running without failures.",
            unit="%",
            target_value=99.5,
            warning_threshold=98.0,
            critical_threshold=95.0,
            measurement_method="successful_runs / scheduled_runs * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-DS-003",
            name="Experiment Velocity",
            description="Number of tracked experiments per week.",
            unit="count",
            target_value=20.0,
            warning_threshold=10.0,
            critical_threshold=5.0,
            measurement_method="count(experiments_per_week)",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-021 — Cybersecurity Firm
# ---------------------------------------------------------------------------

CYBERSECURITY_FIRM = IndustryPreset(
    preset_id="PRESET-021",
    name="Cybersecurity Firm",
    industry="Technology",
    sub_industry="Cybersecurity",
    description="SOC operations, incident response, vulnerability management, and security advisory services.",
    version="1.0.0",
    tags=["cybersecurity", "SOC", "SIEM", "incident-response", "NIST-CSF", "ISO-27001", "MTTD"],
    compatible_with=["PRESET-018", "PRESET-022"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-CYBER-001",
            name="SOC Incident Response",
            description="Detect, triage, contain, and remediate security incidents.",
            steps=[
                {
                    "step_name": "Alert Triage & Classification",
                    "step_type": "automated_check",
                    "agent_persona": "SOC Analyst",
                    "integrations": ["Splunk", "CrowdStrike"],
                    "compliance_gates": ["NIST-CSF-respond", "IR-plan"],
                    "kpis": ["MTTD", "false_positive_rate"],
                },
                {
                    "step_name": "Incident Investigation & Containment",
                    "step_type": "human_review",
                    "agent_persona": "SOC Analyst",
                    "integrations": ["CrowdStrike", "ServiceNow"],
                    "compliance_gates": ["evidence-preservation", "chain-of-custody"],
                    "kpis": ["MTTR"],
                },
                {
                    "step_name": "Root Cause & Post-Incident Report",
                    "step_type": "document_generation",
                    "agent_persona": "Incident Response Lead",
                    "integrations": ["ServiceNow"],
                    "compliance_gates": ["breach-notification-requirements"],
                    "kpis": ["incident_recurrence_rate"],
                },
            ],
            triggers=["SIEM_alert", "client_report", "threat_intel_feed"],
            outputs=["incident_ticket", "containment_actions", "post_incident_report"],
        ),
        WorkflowTemplate(
            template_id="WF-CYBER-002",
            name="Vulnerability Management",
            description="Scan, prioritize, track, and verify remediation of vulnerabilities.",
            steps=[
                {
                    "step_name": "Vulnerability Scanning",
                    "step_type": "automated_check",
                    "agent_persona": "Vulnerability Management Specialist",
                    "integrations": ["CrowdStrike", "Splunk"],
                    "compliance_gates": ["scan-frequency-policy"],
                    "kpis": ["vulnerability_scan_coverage"],
                },
                {
                    "step_name": "Risk Prioritization & Remediation Tracking",
                    "step_type": "processing",
                    "agent_persona": "Vulnerability Management Specialist",
                    "integrations": ["ServiceNow"],
                    "compliance_gates": ["SLA-remediation-timelines"],
                    "kpis": ["vulnerability_remediation_SLA"],
                },
            ],
            triggers=["scheduled_scan", "CVE_published", "pen_test_complete"],
            outputs=["vulnerability_report", "remediation_tickets", "risk_score"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-CYBER-001",
            name="SOC Analyst",
            role="Security Analyst (Tier 2)",
            domain="Cybersecurity",
            capabilities=["alert_triage", "threat_hunting", "log_analysis", "forensic_investigation"],
            tools=["Splunk", "CrowdStrike", "ServiceNow"],
            personality_traits=["analytical", "calm-under-pressure", "curious"],
        ),
        AgentPersona(
            persona_id="AP-CYBER-002",
            name="Incident Response Lead",
            role="IR Lead",
            domain="Cybersecurity",
            capabilities=["incident_coordination", "executive_communication", "legal_liaison", "remediation_oversight"],
            tools=["ServiceNow", "Splunk"],
            personality_traits=["decisive", "communicative", "authoritative"],
        ),
        AgentPersona(
            persona_id="AP-CYBER-003",
            name="Vulnerability Management Specialist",
            role="Vulnerability Analyst",
            domain="Cybersecurity",
            capabilities=["vulnerability_scanning", "risk_prioritization", "patch_tracking", "compliance_reporting"],
            tools=["CrowdStrike", "ServiceNow"],
            personality_traits=["methodical", "persistent", "risk-aware"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Splunk",
            connector_type="SIEM",
            required=True,
            config_template={"host": "", "port": 8089, "token": ""},
            purpose="Security information and event management, log aggregation.",
        ),
        IntegrationMapping(
            connector_name="CrowdStrike",
            connector_type="EDR",
            required=True,
            config_template={"client_id": "", "client_secret": "", "base_url": ""},
            purpose="Endpoint detection and response, threat intelligence.",
        ),
        IntegrationMapping(
            connector_name="ServiceNow",
            connector_type="ITSM",
            required=True,
            config_template={"instance_url": "", "username": "", "password": ""},
            purpose="Incident ticketing, remediation tracking, and change management.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-CYBER-001",
            standard="NIST Cybersecurity Framework",
            description="Security controls must align with NIST CSF Identify, Protect, Detect, Respond, Recover functions.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-CYBER-002",
            standard="SOC 2 Type II",
            description="Managed security services require SOC 2 certification for client trust.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-CYBER-003",
            standard="ISO 27001",
            description="Information Security Management System certification required for enterprise clients.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-CYBER-001",
            name="Mean Time to Detect (MTTD)",
            description="Average hours from threat occurrence to detection.",
            unit="hours",
            target_value=1.0,
            warning_threshold=4.0,
            critical_threshold=24.0,
            measurement_method="avg(detection_time - threat_start_time)",
        ),
        KPIDefinition(
            kpi_id="KPI-CYBER-002",
            name="Mean Time to Respond (MTTR)",
            description="Average hours from incident detection to containment.",
            unit="hours",
            target_value=4.0,
            warning_threshold=12.0,
            critical_threshold=48.0,
            measurement_method="avg(containment_time - detection_time)",
        ),
        KPIDefinition(
            kpi_id="KPI-CYBER-003",
            name="False Positive Rate",
            description="Percentage of security alerts that are false positives.",
            unit="%",
            target_value=10.0,
            warning_threshold=20.0,
            critical_threshold=35.0,
            measurement_method="false_positive_alerts / total_alerts * 100",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-022 — IT Managed Services (MSP)
# ---------------------------------------------------------------------------

IT_MANAGED_SERVICES = IndustryPreset(
    preset_id="PRESET-022",
    name="IT Managed Services Provider",
    industry="Technology",
    sub_industry="Managed Services",
    description="Helpdesk, RMM, patch management, backup monitoring, and client SLA management.",
    version="1.0.0",
    tags=["MSP", "helpdesk", "ITIL", "RMM", "patch-management", "SLA", "SOC2"],
    compatible_with=["PRESET-021", "PRESET-018"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-MSP-001",
            name="IT Support Ticket Lifecycle",
            description="Log, triage, resolve, and close support tickets per SLA.",
            steps=[
                {
                    "step_name": "Ticket Intake & Classification",
                    "step_type": "automated_check",
                    "agent_persona": "MSP Service Desk Agent",
                    "integrations": ["ConnectWise"],
                    "compliance_gates": ["ITIL-incident-management"],
                    "kpis": ["first_response_time"],
                },
                {
                    "step_name": "Tier 1 Resolution or Escalation",
                    "step_type": "processing",
                    "agent_persona": "MSP Service Desk Agent",
                    "integrations": ["ConnectWise", "Autotask"],
                    "compliance_gates": ["SLA-response-targets"],
                    "kpis": ["ticket_resolution_time", "first_call_resolution_rate"],
                },
                {
                    "step_name": "Customer Satisfaction Survey",
                    "step_type": "communication",
                    "agent_persona": "MSP Service Desk Agent",
                    "integrations": ["ConnectWise"],
                    "compliance_gates": [],
                    "kpis": ["customer_NPS", "CSAT_score"],
                },
            ],
            triggers=["ticket_created", "alert_triggered"],
            outputs=["resolved_ticket", "CSAT_response", "SLA_report"],
        ),
        WorkflowTemplate(
            template_id="WF-MSP-002",
            name="Patch Management Cycle",
            description="Assess, test, deploy, and verify patches across managed endpoints.",
            steps=[
                {
                    "step_name": "Patch Assessment & Scheduling",
                    "step_type": "automated_check",
                    "agent_persona": "MSP Infrastructure Engineer",
                    "integrations": ["ConnectWise", "Datto"],
                    "compliance_gates": ["patch-policy"],
                    "kpis": ["patch_compliance_rate"],
                },
                {
                    "step_name": "Patch Deployment & Verification",
                    "step_type": "processing",
                    "agent_persona": "MSP Infrastructure Engineer",
                    "integrations": ["ConnectWise"],
                    "compliance_gates": ["change-management"],
                    "kpis": ["patch_deployment_success_rate"],
                },
            ],
            triggers=["patch_tuesday", "critical_CVE_published"],
            outputs=["patch_report", "compliance_dashboard", "change_record"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-MSP-001",
            name="MSP Service Desk Agent",
            role="L1/L2 Support Technician",
            domain="IT Managed Services",
            capabilities=["ticket_triage", "remote_support", "escalation_management", "KB_authoring"],
            tools=["ConnectWise", "Autotask"],
            personality_traits=["patient", "communicative", "technically-adept"],
        ),
        AgentPersona(
            persona_id="AP-MSP-002",
            name="MSP Infrastructure Engineer",
            role="Systems Engineer",
            domain="IT Managed Services",
            capabilities=["patch_management", "backup_monitoring", "network_troubleshooting", "server_administration"],
            tools=["ConnectWise", "Datto"],
            personality_traits=["methodical", "proactive", "reliability-focused"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="ConnectWise",
            connector_type="PSA",
            required=True,
            config_template={"company_id": "", "public_key": "", "private_key": ""},
            purpose="PSA for ticketing, billing, and project management.",
        ),
        IntegrationMapping(
            connector_name="Autotask",
            connector_type="PSA",
            required=False,
            config_template={"api_key": "", "username": ""},
            purpose="Alternative PSA platform.",
        ),
        IntegrationMapping(
            connector_name="Datto",
            connector_type="backup_RMM",
            required=False,
            config_template={"api_key": ""},
            purpose="Backup, RMM, and business continuity monitoring.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-MSP-001",
            standard="ITIL Framework",
            description="Incident, change, and problem management must follow ITIL best practices.",
            required_approvals=1,
            penalty_severity="medium",
            automated_check=False,
        ),
        ComplianceRule(
            rule_id="CR-MSP-002",
            standard="SOC 2 Type II",
            description="MSP access to client environments requires SOC 2 compliance for security and availability.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=True,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-MSP-001",
            name="SLA Compliance Rate",
            description="Percentage of tickets resolved within contracted SLA response and resolution times.",
            unit="%",
            target_value=98.0,
            warning_threshold=95.0,
            critical_threshold=90.0,
            measurement_method="sla_compliant_tickets / total_tickets * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-MSP-002",
            name="Ticket Resolution Time",
            description="Average hours from ticket open to resolution.",
            unit="hours",
            target_value=4.0,
            warning_threshold=8.0,
            critical_threshold=24.0,
            measurement_method="avg(resolution_time - open_time)",
        ),
        KPIDefinition(
            kpi_id="KPI-MSP-003",
            name="Customer NPS",
            description="Net Promoter Score from post-ticket satisfaction surveys.",
            unit="score",
            target_value=50.0,
            warning_threshold=30.0,
            critical_threshold=10.0,
            measurement_method="promoters_pct - detractors_pct",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-023 — Game Development Studio
# ---------------------------------------------------------------------------

GAME_DEVELOPMENT = IndustryPreset(
    preset_id="PRESET-023",
    name="Game Development Studio",
    industry="Technology",
    sub_industry="Game Development",
    description="Asset pipelines, build systems, QA, and release management for game studios.",
    version="1.0.0",
    tags=["game-dev", "Unity", "Unreal", "QA", "build-systems", "Perforce", "release"],
    compatible_with=["PRESET-019", "PRESET-050"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-GAME-001",
            name="Build & Release Pipeline",
            description="Automated build, QA testing, certification submission, and platform release.",
            steps=[
                {
                    "step_name": "Automated Build & Packaging",
                    "step_type": "automated_check",
                    "agent_persona": "Game Build & Release Engineer",
                    "integrations": ["Unity", "Perforce"],
                    "compliance_gates": ["build-stability-gate"],
                    "kpis": ["build_success_rate"],
                },
                {
                    "step_name": "QA Testing & Bug Triage",
                    "step_type": "human_review",
                    "agent_persona": "QA Lead",
                    "integrations": ["Jira"],
                    "compliance_gates": ["quality-exit-criteria"],
                    "kpis": ["bug_density"],
                },
                {
                    "step_name": "Platform Certification Submission",
                    "step_type": "integration_action",
                    "agent_persona": "Game Build & Release Engineer",
                    "integrations": ["Unity"],
                    "compliance_gates": ["platform-content-ratings", "TCR-TRC-requirements"],
                    "kpis": ["certification_first_pass_rate"],
                },
            ],
            triggers=["milestone_complete", "sprint_end", "hotfix"],
            outputs=["certified_build", "release_notes", "live_game"],
        ),
        WorkflowTemplate(
            template_id="WF-GAME-002",
            name="Asset Production Pipeline",
            description="Art, audio, and design asset creation, review, and integration.",
            steps=[
                {
                    "step_name": "Asset Creation & Check-in",
                    "step_type": "processing",
                    "agent_persona": "Game Art & Asset Coordinator",
                    "integrations": ["Perforce", "Unreal"],
                    "compliance_gates": ["asset-naming-conventions"],
                    "kpis": ["asset_delivery_on_time"],
                },
                {
                    "step_name": "Art Direction Review",
                    "step_type": "human_review",
                    "agent_persona": "Game Art & Asset Coordinator",
                    "integrations": ["Jira"],
                    "compliance_gates": [],
                    "kpis": ["revision_cycles"],
                },
            ],
            triggers=["asset_request_created", "milestone_art_freeze"],
            outputs=["approved_asset", "integrated_asset"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-GAME-001",
            name="Game Build & Release Engineer",
            role="Build Engineer",
            domain="Game Development",
            capabilities=["CI_CD_setup", "platform_submission", "build_optimization", "crash_analysis"],
            tools=["Unity", "Perforce", "Jira"],
            personality_traits=["systematic", "detail-oriented", "automation-focused"],
        ),
        AgentPersona(
            persona_id="AP-GAME-002",
            name="QA Lead",
            role="QA Manager",
            domain="Game Development",
            capabilities=["test_planning", "bug_triage", "regression_testing", "certification_coordination"],
            tools=["Jira"],
            personality_traits=["thorough", "player-empathetic", "deadline-aware"],
        ),
        AgentPersona(
            persona_id="AP-GAME-003",
            name="Game Art & Asset Coordinator",
            role="Art Production Coordinator",
            domain="Game Development",
            capabilities=["asset_tracking", "pipeline_coordination", "art_direction_support", "milestone_tracking"],
            tools=["Perforce", "Unreal", "Jira"],
            personality_traits=["creative", "organized", "collaborative"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="Unity",
            connector_type="game_engine",
            required=False,
            config_template={"organization_id": "", "access_token": ""},
            purpose="Game engine, build pipeline, and Unity Gaming Services.",
        ),
        IntegrationMapping(
            connector_name="Unreal",
            connector_type="game_engine",
            required=False,
            config_template={"project_path": ""},
            purpose="Alternative game engine for AAA productions.",
        ),
        IntegrationMapping(
            connector_name="Jira",
            connector_type="project_management",
            required=True,
            config_template={"domain": "", "api_token": ""},
            purpose="Bug tracking, sprint management, and milestone tracking.",
        ),
        IntegrationMapping(
            connector_name="Perforce",
            connector_type="version_control",
            required=True,
            config_template={"server": "", "user": ""},
            purpose="Version control for large binary game assets.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-GAME-001",
            standard="Platform TCR/TRC (Technical Certification Requirements)",
            description="All submissions to console platforms (PlayStation, Xbox, Nintendo) must pass TCR/TRC certification.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-GAME-002",
            standard="ESRB / PEGI Content Ratings",
            description="Game content must receive appropriate age ratings before commercial release.",
            required_approvals=1,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-GAME-001",
            name="Build Success Rate",
            description="Percentage of automated build jobs that complete successfully.",
            unit="%",
            target_value=95.0,
            warning_threshold=88.0,
            critical_threshold=80.0,
            measurement_method="successful_builds / total_builds * 100",
        ),
        KPIDefinition(
            kpi_id="KPI-GAME-002",
            name="Bug Density",
            description="Number of open critical/major bugs per 1,000 lines of code.",
            unit="bugs/KLOC",
            target_value=0.5,
            warning_threshold=1.5,
            critical_threshold=3.0,
            measurement_method="open_critical_bugs / (codebase_size / 1000)",
        ),
        KPIDefinition(
            kpi_id="KPI-GAME-003",
            name="Time-to-Release",
            description="Days from feature complete milestone to live release.",
            unit="days",
            target_value=30.0,
            warning_threshold=45.0,
            critical_threshold=60.0,
            measurement_method="avg(release_date - feature_complete_date)",
        ),
    ],
)

# ---------------------------------------------------------------------------
# PRESET-024 — AI/ML Startup
# ---------------------------------------------------------------------------

AI_ML_STARTUP = IndustryPreset(
    preset_id="PRESET-024",
    name="AI/ML Startup",
    industry="Technology",
    sub_industry="Artificial Intelligence",
    description="Training pipelines, model serving, data annotation, and AI regulatory compliance.",
    version="1.0.0",
    tags=["AI", "ML", "LLM", "training-pipelines", "inference", "AI-Act", "data-ethics"],
    compatible_with=["PRESET-020", "PRESET-018"],
    workflow_templates=[
        WorkflowTemplate(
            template_id="WF-AI-001",
            name="Foundation Model Fine-tuning Pipeline",
            description="Data curation, annotation, fine-tuning, evaluation, and model serving.",
            steps=[
                {
                    "step_name": "Data Curation & Annotation",
                    "step_type": "processing",
                    "agent_persona": "AI Research Engineer",
                    "integrations": ["Label Studio", "HuggingFace"],
                    "compliance_gates": ["data-ethics-review", "AI-Act-data-requirements"],
                    "kpis": ["annotation_throughput"],
                },
                {
                    "step_name": "Fine-tuning & Training Run",
                    "step_type": "processing",
                    "agent_persona": "AI Research Engineer",
                    "integrations": ["HuggingFace", "AWS SageMaker"],
                    "compliance_gates": [],
                    "kpis": ["training_cost", "model_eval_score"],
                },
                {
                    "step_name": "Evaluation & Model Card",
                    "step_type": "human_review",
                    "agent_persona": "AI Research Engineer",
                    "integrations": ["HuggingFace"],
                    "compliance_gates": ["AI-Act-transparency", "bias-evaluation"],
                    "kpis": ["model_eval_score"],
                },
                {
                    "step_name": "Model Deployment & Inference API",
                    "step_type": "integration_action",
                    "agent_persona": "AI Platform Engineer",
                    "integrations": ["AWS SageMaker", "HuggingFace"],
                    "compliance_gates": ["privacy-impact-assessment"],
                    "kpis": ["inference_latency"],
                },
            ],
            triggers=["training_data_ready", "model_improvement_target_set"],
            outputs=["deployed_model", "model_card", "inference_endpoint"],
        ),
        WorkflowTemplate(
            template_id="WF-AI-002",
            name="Data Annotation Quality Control",
            description="Manage annotators, enforce quality standards, and resolve disagreements.",
            steps=[
                {
                    "step_name": "Annotation Assignment & Instructions",
                    "step_type": "processing",
                    "agent_persona": "Data Operations Lead",
                    "integrations": ["Label Studio"],
                    "compliance_gates": ["annotator-agreement-threshold"],
                    "kpis": ["annotation_throughput"],
                },
                {
                    "step_name": "IAA Review & Adjudication",
                    "step_type": "human_review",
                    "agent_persona": "Data Operations Lead",
                    "integrations": ["Label Studio"],
                    "compliance_gates": ["data-quality-gate"],
                    "kpis": ["inter_annotator_agreement"],
                },
            ],
            triggers=["annotation_batch_ready", "model_retraining_scheduled"],
            outputs=["annotated_dataset", "quality_report"],
        ),
    ],
    agent_personas=[
        AgentPersona(
            persona_id="AP-AI-001",
            name="AI Research Engineer",
            role="Research Engineer",
            domain="AI/ML",
            capabilities=["model_training", "experiment_design", "evaluation_framework", "paper_implementation"],
            tools=["HuggingFace", "AWS SageMaker", "Label Studio"],
            personality_traits=["scientifically-rigorous", "creative", "iterative"],
        ),
        AgentPersona(
            persona_id="AP-AI-002",
            name="AI Platform Engineer",
            role="MLOps / Platform Engineer",
            domain="AI/ML",
            capabilities=["model_serving", "inference_optimization", "infrastructure_scaling", "monitoring"],
            tools=["AWS SageMaker", "HuggingFace"],
            personality_traits=["reliability-focused", "cost-conscious", "automation-minded"],
        ),
        AgentPersona(
            persona_id="AP-AI-003",
            name="Data Operations Lead",
            role="Data Operations",
            domain="AI/ML",
            capabilities=["annotation_management", "data_quality", "vendor_management", "ontology_design"],
            tools=["Label Studio"],
            personality_traits=["quality-driven", "organized", "analytical"],
        ),
    ],
    integration_mappings=[
        IntegrationMapping(
            connector_name="HuggingFace",
            connector_type="model_hub",
            required=True,
            config_template={"token": "", "organization": ""},
            purpose="Model hub, dataset hosting, and inference endpoints.",
        ),
        IntegrationMapping(
            connector_name="AWS SageMaker",
            connector_type="cloud_ML",
            required=True,
            config_template={"region": "", "execution_role": ""},
            purpose="Managed ML training, deployment, and inference infrastructure.",
        ),
        IntegrationMapping(
            connector_name="Label Studio",
            connector_type="annotation",
            required=False,
            config_template={"api_key": "", "base_url": ""},
            purpose="Data annotation platform for training dataset creation.",
        ),
    ],
    compliance_rules=[
        ComplianceRule(
            rule_id="CR-AI-001",
            standard="EU AI Act",
            description="High-risk AI systems require conformity assessment, transparency, and human oversight mechanisms.",
            required_approvals=2,
            penalty_severity="critical",
            automated_check=True,
        ),
        ComplianceRule(
            rule_id="CR-AI-002",
            standard="Data Ethics Policy",
            description="Training data must be sourced ethically with appropriate consent and bias mitigation strategies.",
            required_approvals=2,
            penalty_severity="high",
            automated_check=False,
        ),
    ],
    kpi_definitions=[
        KPIDefinition(
            kpi_id="KPI-AI-001",
            name="Model Training Cost",
            description="Average compute cost per training run.",
            unit="USD",
            target_value=500.0,
            warning_threshold=1500.0,
            critical_threshold=5000.0,
            measurement_method="avg(compute_cost_per_run)",
        ),
        KPIDefinition(
            kpi_id="KPI-AI-002",
            name="Inference Latency (P95)",
            description="95th percentile response time for model inference API.",
            unit="ms",
            target_value=200.0,
            warning_threshold=500.0,
            critical_threshold=1000.0,
            measurement_method="p95(inference_response_time_ms)",
        ),
        KPIDefinition(
            kpi_id="KPI-AI-003",
            name="Annotation Throughput",
            description="Average annotations completed per annotator per hour.",
            unit="annotations/hour",
            target_value=50.0,
            warning_threshold=30.0,
            critical_threshold=15.0,
            measurement_method="total_annotations / total_annotator_hours",
        ),
    ],
)

# ---------------------------------------------------------------------------
# Module export
# ---------------------------------------------------------------------------

ALL_TECHNOLOGY_PRESETS: List[IndustryPreset] = [
    SAAS_COMPANY,
    SOFTWARE_AGENCY,
    DATA_SCIENCE_LAB,
    CYBERSECURITY_FIRM,
    IT_MANAGED_SERVICES,
    GAME_DEVELOPMENT,
    AI_ML_STARTUP,
]
