apiVersion: v1
kind: Service
metadata:
  name: murphy-api
  namespace: murphy-system
  labels:
    app: murphy-system
    component: api
    environment: production
spec:
  type: ClusterIP
  selector:
    app: murphy-system
    component: api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
