import importlib.util
from pathlib import Path


def load_runtime_module():
    runtime_dir = Path(__file__).resolve().parent.parent
    candidates = list(runtime_dir.glob("murphy_system_*_runtime.py"))
    if not candidates:
        raise RuntimeError("Unable to locate Murphy runtime module")
    module_path = candidates[0]
    spec = importlib.util.spec_from_file_location("murphy_system_runtime", module_path)
    module = importlib.util.module_from_spec(spec)
    if spec.loader is None:
        raise RuntimeError("Unable to load Murphy runtime module")
    spec.loader.exec_module(module)
    return module


def test_completion_snapshot_surface_parity():
    runtime = load_runtime_module()
    murphy = runtime.MurphySystem.create_test_instance()

    status = murphy.get_system_status()
    info = murphy.get_system_info()
    doc = runtime.LivingDocument("test_completion_doc", "Completion", "content", "request")
    doc.confidence = 0.9
    murphy._update_document_tree(doc)
    preview = murphy._build_activation_preview(
        doc,
        "Validate completion snapshot parity",
        {"answers": {step["stage"]: "ok" for step in murphy.flow_steps}}
    )

    expected = status["completion_snapshot"]
    assert info["completion_snapshot"] == expected
    assert preview["completion_snapshot"] == expected
    assert info["runtime_execution_profile"] == status["runtime_execution_profile"]
    assert preview["runtime_execution_profile"]["execution_mode"] == status["runtime_execution_profile"]["execution_mode"]
    assert preview["runtime_execution_profile"]["execution_enforcement_level"] == status["runtime_execution_profile"]["execution_enforcement_level"]
    assert preview["runtime_execution_profile"]["control_plane_separation_state"] == status["runtime_execution_profile"]["control_plane_separation_state"]
    assert preview["runtime_execution_profile"]["self_improvement_rd_candidate"] == status["runtime_execution_profile"]["self_improvement_rd_candidate"]
    assert preview["runtime_execution_profile"]["approval_checkpoint_policy"] == status["runtime_execution_profile"]["approval_checkpoint_policy"]
    assert preview["runtime_execution_profile"]["budget_enforcement_mode"] == status["runtime_execution_profile"]["budget_enforcement_mode"]
    assert preview["runtime_execution_profile"]["audit_logging_policy"] == status["runtime_execution_profile"]["audit_logging_policy"]
    assert preview["runtime_execution_profile"]["escalation_routing_policy"] == status["runtime_execution_profile"]["escalation_routing_policy"]
    assert preview["runtime_execution_profile"]["tool_mediation_policy"] == status["runtime_execution_profile"]["tool_mediation_policy"]
    assert preview["runtime_execution_profile"]["deterministic_routing_policy"] == status["runtime_execution_profile"]["deterministic_routing_policy"]
    assert preview["runtime_execution_profile"]["compute_routing_policy"] == status["runtime_execution_profile"]["compute_routing_policy"]
    assert preview["runtime_execution_profile"]["policy_compiler_mode"] == status["runtime_execution_profile"]["policy_compiler_mode"]
    assert preview["runtime_execution_profile"]["permission_validation_policy"] == status["runtime_execution_profile"]["permission_validation_policy"]
    assert preview["runtime_execution_profile"]["delegation_scope_policy"] == status["runtime_execution_profile"]["delegation_scope_policy"]
    assert preview["runtime_execution_profile"]["execution_broker_policy"] == status["runtime_execution_profile"]["execution_broker_policy"]
    assert preview["runtime_execution_profile"]["role_registry_policy"] == status["runtime_execution_profile"]["role_registry_policy"]
    assert preview["runtime_execution_profile"]["authority_boundary_policy"] == status["runtime_execution_profile"]["authority_boundary_policy"]
    assert preview["runtime_execution_profile"]["cross_department_arbitration_policy"] == status["runtime_execution_profile"]["cross_department_arbitration_policy"]
    assert preview["runtime_execution_profile"]["department_memory_isolation_policy"] == status["runtime_execution_profile"]["department_memory_isolation_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_responsibility_policy"] == status["runtime_execution_profile"]["employee_contract_responsibility_policy"]
    assert preview["runtime_execution_profile"]["core_responsibility_scope"] == status["runtime_execution_profile"]["core_responsibility_scope"]
    assert preview["runtime_execution_profile"]["shadow_agent_account_policy"] == status["runtime_execution_profile"]["shadow_agent_account_policy"]
    assert preview["runtime_execution_profile"]["user_base_management_surface_policy"] == status["runtime_execution_profile"]["user_base_management_surface_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_change_authority_policy"] == status["runtime_execution_profile"]["employee_contract_change_authority_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_management_surface_policy"] == status["runtime_execution_profile"]["employee_contract_management_surface_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_accountability_policy"] == status["runtime_execution_profile"]["employee_contract_accountability_policy"]
    assert preview["runtime_execution_profile"]["shadow_agent_org_parity_policy"] == status["runtime_execution_profile"]["shadow_agent_org_parity_policy"]
    assert preview["runtime_execution_profile"]["shadow_agent_contract_binding_policy"] == status["runtime_execution_profile"]["shadow_agent_contract_binding_policy"]
    assert preview["runtime_execution_profile"]["user_base_access_governance_policy"] == status["runtime_execution_profile"]["user_base_access_governance_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_obligation_tracking_policy"] == status["runtime_execution_profile"]["employee_contract_obligation_tracking_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_escalation_binding_policy"] == status["runtime_execution_profile"]["employee_contract_escalation_binding_policy"]
    assert preview["runtime_execution_profile"]["regulatory_context_binding_policy"] == status["runtime_execution_profile"]["regulatory_context_binding_policy"]
    assert preview["runtime_execution_profile"]["autonomy_preference_override_policy"] == status["runtime_execution_profile"]["autonomy_preference_override_policy"]
    assert preview["runtime_execution_profile"]["risk_tolerance_enforcement_policy"] == status["runtime_execution_profile"]["risk_tolerance_enforcement_policy"]
    assert preview["runtime_execution_profile"]["safety_level_assurance_policy"] == status["runtime_execution_profile"]["safety_level_assurance_policy"]
    assert preview["runtime_execution_profile"]["delegation_comfort_governance_policy"] == status["runtime_execution_profile"]["delegation_comfort_governance_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_review_policy"] == status["runtime_execution_profile"]["employee_contract_review_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_versioning_policy"] == status["runtime_execution_profile"]["employee_contract_versioning_policy"]
    assert preview["runtime_execution_profile"]["shadow_agent_account_lifecycle_policy"] == status["runtime_execution_profile"]["shadow_agent_account_lifecycle_policy"]
    assert preview["runtime_execution_profile"]["user_base_ui_audit_policy"] == status["runtime_execution_profile"]["user_base_ui_audit_policy"]
    assert preview["runtime_execution_profile"]["org_chart_assignment_sync_policy"] == status["runtime_execution_profile"]["org_chart_assignment_sync_policy"]
    assert preview["runtime_execution_profile"]["event_queue_durability_policy"] == status["runtime_execution_profile"]["event_queue_durability_policy"]
    assert preview["runtime_execution_profile"]["idempotency_key_enforcement_policy"] == status["runtime_execution_profile"]["idempotency_key_enforcement_policy"]
    assert preview["runtime_execution_profile"]["retry_backoff_policy"] == status["runtime_execution_profile"]["retry_backoff_policy"]
    assert preview["runtime_execution_profile"]["circuit_breaker_policy"] == status["runtime_execution_profile"]["circuit_breaker_policy"]
    assert preview["runtime_execution_profile"]["rollback_recovery_policy"] == status["runtime_execution_profile"]["rollback_recovery_policy"]
    assert preview["runtime_execution_profile"]["planning_plane_decomposition_policy"] == status["runtime_execution_profile"]["planning_plane_decomposition_policy"]
    assert preview["runtime_execution_profile"]["planning_plane_risk_simulation_policy"] == status["runtime_execution_profile"]["planning_plane_risk_simulation_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_permission_gate_policy"] == status["runtime_execution_profile"]["execution_plane_permission_gate_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_budget_guardrail_policy"] == status["runtime_execution_profile"]["execution_plane_budget_guardrail_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_audit_trail_integrity_policy"] == status["runtime_execution_profile"]["execution_plane_audit_trail_integrity_policy"]
    assert preview["runtime_execution_profile"]["swarm_spawn_governance_policy"] == status["runtime_execution_profile"]["swarm_spawn_governance_policy"]
    assert preview["runtime_execution_profile"]["swarm_failure_containment_policy"] == status["runtime_execution_profile"]["swarm_failure_containment_policy"]
    assert preview["runtime_execution_profile"]["swarm_budget_expansion_policy"] == status["runtime_execution_profile"]["swarm_budget_expansion_policy"]
    assert preview["runtime_execution_profile"]["shadow_reinforcement_signal_policy"] == status["runtime_execution_profile"]["shadow_reinforcement_signal_policy"]
    assert preview["runtime_execution_profile"]["behavioral_divergence_tracking_policy"] == status["runtime_execution_profile"]["behavioral_divergence_tracking_policy"]
    assert preview["runtime_execution_profile"]["planning_plane_gate_synthesis_policy"] == status["runtime_execution_profile"]["planning_plane_gate_synthesis_policy"]
    assert preview["runtime_execution_profile"]["planning_plane_org_mapping_policy"] == status["runtime_execution_profile"]["planning_plane_org_mapping_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_tool_permission_enforcement_policy"] == status["runtime_execution_profile"]["execution_plane_tool_permission_enforcement_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_budget_ceiling_override_policy"] == status["runtime_execution_profile"]["execution_plane_budget_ceiling_override_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_escalation_checkpoint_policy"] == status["runtime_execution_profile"]["execution_plane_escalation_checkpoint_policy"]
    assert preview["runtime_execution_profile"]["human_in_the_loop_enforcement_policy"] == status["runtime_execution_profile"]["human_in_the_loop_enforcement_policy"]
    assert preview["runtime_execution_profile"]["regulatory_audit_retention_policy"] == status["runtime_execution_profile"]["regulatory_audit_retention_policy"]
    assert preview["runtime_execution_profile"]["tenant_boundary_enforcement_policy"] == status["runtime_execution_profile"]["tenant_boundary_enforcement_policy"]
    assert preview["runtime_execution_profile"]["policy_exception_handling_policy"] == status["runtime_execution_profile"]["policy_exception_handling_policy"]
    assert preview["runtime_execution_profile"]["runtime_profile_refresh_policy"] == status["runtime_execution_profile"]["runtime_profile_refresh_policy"]
    assert preview["runtime_execution_profile"]["planning_plane_compliance_modeling_policy"] == status["runtime_execution_profile"]["planning_plane_compliance_modeling_policy"]
    assert preview["runtime_execution_profile"]["planning_plane_proposal_generation_policy"] == status["runtime_execution_profile"]["planning_plane_proposal_generation_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_policy_compiler_enforcement_policy"] == status["runtime_execution_profile"]["execution_plane_policy_compiler_enforcement_policy"]
    assert preview["runtime_execution_profile"]["execution_plane_deterministic_override_policy"] == status["runtime_execution_profile"]["execution_plane_deterministic_override_policy"]
    assert preview["runtime_execution_profile"]["hitl_escalation_requirement_policy"] == status["runtime_execution_profile"]["hitl_escalation_requirement_policy"]
    assert preview["runtime_execution_profile"]["shadow_peer_role_enforcement_policy"] == status["runtime_execution_profile"]["shadow_peer_role_enforcement_policy"]
    assert preview["runtime_execution_profile"]["shadow_account_user_binding_policy"] == status["runtime_execution_profile"]["shadow_account_user_binding_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_scope_enforcement_policy"] == status["runtime_execution_profile"]["employee_contract_scope_enforcement_policy"]
    assert preview["runtime_execution_profile"]["employee_contract_exception_review_policy"] == status["runtime_execution_profile"]["employee_contract_exception_review_policy"]
    assert preview["runtime_execution_profile"]["user_base_tenant_boundary_policy"] == status["runtime_execution_profile"]["user_base_tenant_boundary_policy"]
    assert preview["runtime_execution_profile"]["compliance_event_escalation_policy"] == status["runtime_execution_profile"]["compliance_event_escalation_policy"]
    assert preview["runtime_execution_profile"]["regulatory_override_resolution_policy"] == status["runtime_execution_profile"]["regulatory_override_resolution_policy"]
    assert preview["runtime_execution_profile"]["budget_ceiling_revision_policy"] == status["runtime_execution_profile"]["budget_ceiling_revision_policy"]
    assert preview["runtime_execution_profile"]["budget_consumption_alert_policy"] == status["runtime_execution_profile"]["budget_consumption_alert_policy"]
    assert preview["runtime_execution_profile"]["approval_checkpoint_timeout_policy"] == status["runtime_execution_profile"]["approval_checkpoint_timeout_policy"]
    assert preview["runtime_execution_profile"]["compliance_sensor_event_policy"] == status["runtime_execution_profile"]["compliance_sensor_event_policy"]
    assert preview["runtime_execution_profile"]["policy_drift_detection_policy"] == status["runtime_execution_profile"]["policy_drift_detection_policy"]
    assert preview["runtime_execution_profile"]["onboarding_profile_revalidation_policy"] == status["runtime_execution_profile"]["onboarding_profile_revalidation_policy"]
    assert preview["runtime_execution_profile"]["control_plane_mode_transition_policy"] == status["runtime_execution_profile"]["control_plane_mode_transition_policy"]
    assert preview["runtime_execution_profile"]["user_autonomy_preference_ui_policy"] == status["runtime_execution_profile"]["user_autonomy_preference_ui_policy"]
    assert preview["runtime_execution_profile"]["planning_execution_toggle_guard_policy"] == status["runtime_execution_profile"]["planning_execution_toggle_guard_policy"]
    assert preview["runtime_execution_profile"]["governance_exception_escalation_policy"] == status["runtime_execution_profile"]["governance_exception_escalation_policy"]
    assert preview["runtime_execution_profile"]["approval_sla_enforcement_policy"] == status["runtime_execution_profile"]["approval_sla_enforcement_policy"]
    assert preview["runtime_execution_profile"]["tenant_residency_control_policy"] == status["runtime_execution_profile"]["tenant_residency_control_policy"]
    assert preview["runtime_execution_profile"]["swarm_recursion_guard_policy"] == status["runtime_execution_profile"]["swarm_recursion_guard_policy"]
    assert preview["runtime_execution_profile"]["contract_renewal_gate_policy"] == status["runtime_execution_profile"]["contract_renewal_gate_policy"]
    assert preview["runtime_execution_profile"]["shadow_account_suspension_policy"] == status["runtime_execution_profile"]["shadow_account_suspension_policy"]
    assert preview["runtime_execution_profile"]["user_base_offboarding_policy"] == status["runtime_execution_profile"]["user_base_offboarding_policy"]
    assert preview["runtime_execution_profile"]["governance_kernel_heartbeat_policy"] == status["runtime_execution_profile"]["governance_kernel_heartbeat_policy"]
    assert preview["runtime_execution_profile"]["policy_compiler_change_control_policy"] == status["runtime_execution_profile"]["policy_compiler_change_control_policy"]
    assert preview["runtime_execution_profile"]["replay_reconciliation_policy"] == status["runtime_execution_profile"]["replay_reconciliation_policy"]
    assert preview["runtime_execution_profile"]["audit_artifact_retention_policy"] == status["runtime_execution_profile"]["audit_artifact_retention_policy"]
    assert preview["runtime_execution_profile"]["event_backpressure_management_policy"] == status["runtime_execution_profile"]["event_backpressure_management_policy"]
    assert preview["runtime_execution_profile"]["queue_health_slo_policy"] == status["runtime_execution_profile"]["queue_health_slo_policy"]
    assert preview["runtime_execution_profile"]["rollback_compensation_policy"] == status["runtime_execution_profile"]["rollback_compensation_policy"]
    assert preview["runtime_execution_profile"]["durable_queue_replay_policy"] == status["runtime_execution_profile"]["durable_queue_replay_policy"]
    assert preview["runtime_execution_profile"]["swarm_failure_domain_isolation_policy"] == status["runtime_execution_profile"]["swarm_failure_domain_isolation_policy"]
    assert preview["runtime_execution_profile"]["idempotent_recovery_validation_policy"] == status["runtime_execution_profile"]["idempotent_recovery_validation_policy"]
    assert preview["runtime_execution_profile"]["agent_spawn_budget_reconciliation_policy"] == status["runtime_execution_profile"]["agent_spawn_budget_reconciliation_policy"]
    assert preview["runtime_execution_profile"]["audit_chain_export_policy"] == status["runtime_execution_profile"]["audit_chain_export_policy"]
    assert preview["runtime_execution_profile"]["semantics_belief_state_policy"] == status["runtime_execution_profile"]["semantics_belief_state_policy"]
    assert preview["runtime_execution_profile"]["semantics_loss_risk_policy"] == status["runtime_execution_profile"]["semantics_loss_risk_policy"]
    assert preview["runtime_execution_profile"]["semantics_voi_question_policy"] == status["runtime_execution_profile"]["semantics_voi_question_policy"]
    assert preview["runtime_execution_profile"]["semantics_invariance_boundary_policy"] == status["runtime_execution_profile"]["semantics_invariance_boundary_policy"]
    assert preview["runtime_execution_profile"]["semantics_verification_feedback_policy"] == status["runtime_execution_profile"]["semantics_verification_feedback_policy"]
    assert preview["runtime_execution_profile"]["semantics_hypothesis_update_policy"] == status["runtime_execution_profile"]["semantics_hypothesis_update_policy"]
    assert preview["runtime_execution_profile"]["semantics_likelihood_scoring_policy"] == status["runtime_execution_profile"]["semantics_likelihood_scoring_policy"]
    assert preview["runtime_execution_profile"]["semantics_rvoi_decision_policy"] == status["runtime_execution_profile"]["semantics_rvoi_decision_policy"]
    assert preview["runtime_execution_profile"]["semantics_clarifying_question_budget_policy"] == status["runtime_execution_profile"]["semantics_clarifying_question_budget_policy"]
    assert preview["runtime_execution_profile"]["semantics_invariance_retry_policy"] == status["runtime_execution_profile"]["semantics_invariance_retry_policy"]
    assert preview["runtime_execution_profile"]["semantics_hypothesis_distribution_policy"] == status["runtime_execution_profile"]["semantics_hypothesis_distribution_policy"]
    assert preview["runtime_execution_profile"]["semantics_cvar_risk_measure_policy"] == status["runtime_execution_profile"]["semantics_cvar_risk_measure_policy"]
    assert preview["runtime_execution_profile"]["semantics_question_cost_policy"] == status["runtime_execution_profile"]["semantics_question_cost_policy"]
    assert preview["runtime_execution_profile"]["semantics_invariance_transform_set_policy"] == status["runtime_execution_profile"]["semantics_invariance_transform_set_policy"]
    assert preview["runtime_execution_profile"]["semantics_verification_boundary_policy"] == status["runtime_execution_profile"]["semantics_verification_boundary_policy"]
    assert preview["runtime_execution_profile"]["runtime_telemetry_tokens_to_resolution_policy"] == status["runtime_execution_profile"]["runtime_telemetry_tokens_to_resolution_policy"]
    assert preview["runtime_execution_profile"]["runtime_telemetry_question_count_policy"] == status["runtime_execution_profile"]["runtime_telemetry_question_count_policy"]
    assert preview["runtime_execution_profile"]["runtime_telemetry_invariance_score_policy"] == status["runtime_execution_profile"]["runtime_telemetry_invariance_score_policy"]
    assert preview["runtime_execution_profile"]["runtime_telemetry_risk_score_policy"] == status["runtime_execution_profile"]["runtime_telemetry_risk_score_policy"]
    assert preview["runtime_execution_profile"]["runtime_telemetry_verification_feedback_policy"] == status["runtime_execution_profile"]["runtime_telemetry_verification_feedback_policy"]
    assert preview["runtime_execution_profile"]["semantics_question_candidate_generation_policy"] == status["runtime_execution_profile"]["semantics_question_candidate_generation_policy"]
    assert preview["runtime_execution_profile"]["semantics_answer_prediction_policy"] == status["runtime_execution_profile"]["semantics_answer_prediction_policy"]
    assert preview["runtime_execution_profile"]["semantics_belief_normalization_policy"] == status["runtime_execution_profile"]["semantics_belief_normalization_policy"]
    assert preview["runtime_execution_profile"]["semantics_verification_loss_injection_policy"] == status["runtime_execution_profile"]["semantics_verification_loss_injection_policy"]
    assert preview["runtime_execution_profile"]["semantics_action_revision_policy"] == status["runtime_execution_profile"]["semantics_action_revision_policy"]
    assert preview["runtime_execution_profile"]["legacy_orchestrator_discovery_policy"] == status["runtime_execution_profile"]["legacy_orchestrator_discovery_policy"]
    assert preview["runtime_execution_profile"]["rubixcube_orchestrator_adapter_policy"] == status["runtime_execution_profile"]["rubixcube_orchestrator_adapter_policy"]
    assert preview["runtime_execution_profile"]["triage_orchestrator_adapter_policy"] == status["runtime_execution_profile"]["triage_orchestrator_adapter_policy"]
    assert preview["runtime_execution_profile"]["bot_catalog_capability_mapping_policy"] == status["runtime_execution_profile"]["bot_catalog_capability_mapping_policy"]
    assert preview["runtime_execution_profile"]["legacy_orchestrator_wiring_priority_policy"] == status["runtime_execution_profile"]["legacy_orchestrator_wiring_priority_policy"]
    assert preview["runtime_execution_profile"]["modern_arcana_clockwork_bridge_policy"] == status["runtime_execution_profile"]["modern_arcana_clockwork_bridge_policy"]
    assert preview["runtime_execution_profile"]["legacy_orchestrator_compatibility_matrix_policy"] == status["runtime_execution_profile"]["legacy_orchestrator_compatibility_matrix_policy"]
    assert preview["runtime_execution_profile"]["rubixcube_kaia_mix_scoring_policy"] == status["runtime_execution_profile"]["rubixcube_kaia_mix_scoring_policy"]
    assert preview["runtime_execution_profile"]["triage_rollcall_selection_policy"] == status["runtime_execution_profile"]["triage_rollcall_selection_policy"]
    assert preview["runtime_execution_profile"]["legacy_orchestrator_tooling_plan_policy"] == status["runtime_execution_profile"]["legacy_orchestrator_tooling_plan_policy"]
    assert preview["runtime_execution_profile"]["clockwork_orchestrator_bridge_policy"] == status["runtime_execution_profile"]["clockwork_orchestrator_bridge_policy"]
    assert preview["runtime_execution_profile"]["arcana_pipeline_compatibility_policy"] == status["runtime_execution_profile"]["arcana_pipeline_compatibility_policy"]
    assert preview["runtime_execution_profile"]["rubixcube_evidence_engine_policy"] == status["runtime_execution_profile"]["rubixcube_evidence_engine_policy"]
    assert preview["runtime_execution_profile"]["triage_rollcall_confidence_policy"] == status["runtime_execution_profile"]["triage_rollcall_confidence_policy"]
    assert preview["runtime_execution_profile"]["golden_path_reuse_policy"] == status["runtime_execution_profile"]["golden_path_reuse_policy"]
    assert preview["runtime_execution_profile"]["governance_review_cadence_policy"] == status["runtime_execution_profile"]["governance_review_cadence_policy"]
    assert preview["runtime_execution_profile"]["section_status_reconciliation_policy"] == status["runtime_execution_profile"]["section_status_reconciliation_policy"]
    assert preview["runtime_execution_profile"]["orchestrator_wiring_readiness_policy"] == status["runtime_execution_profile"]["orchestrator_wiring_readiness_policy"]
    assert preview["runtime_execution_profile"]["verification_feedback_closure_policy"] == status["runtime_execution_profile"]["verification_feedback_closure_policy"]
    assert preview["runtime_execution_profile"]["self_improvement_backlog_priority_policy"] == status["runtime_execution_profile"]["self_improvement_backlog_priority_policy"]
    assert preview["runtime_execution_profile"]["hitl_escalation_comfort_policy"] == status["runtime_execution_profile"]["hitl_escalation_comfort_policy"]
    assert preview["runtime_execution_profile"]["execution_profile_source"] == "onboarding"
    assert status["runtime_execution_profile"]["execution_profile_source"] == "default"
    assert status["runtime_execution_profile"]["control_plane_separation_state"] == "adaptive"
    assert status["runtime_execution_profile"]["self_improvement_rd_candidate"] == "hybrid_governance_feedback_loop"
    assert status["runtime_execution_profile"]["approval_checkpoint_policy"] == "conditional"
    assert status["runtime_execution_profile"]["budget_enforcement_mode"] == "soft_cap"
    assert status["runtime_execution_profile"]["audit_logging_policy"] == "standard_governance_stream"
    assert status["runtime_execution_profile"]["escalation_routing_policy"] == "policy_scored_chain"
    assert status["runtime_execution_profile"]["tool_mediation_policy"] == "policy_guarded_mediation"
    assert status["runtime_execution_profile"]["deterministic_routing_policy"] == "deterministic_preferred"
    assert status["runtime_execution_profile"]["compute_routing_policy"] == "hybrid_compute_lane"
    assert status["runtime_execution_profile"]["policy_compiler_mode"] == "guarded_policy_compilation"
    assert status["runtime_execution_profile"]["permission_validation_policy"] == "policy_guided_validation"
    assert status["runtime_execution_profile"]["delegation_scope_policy"] == "policy_bounded_delegation"
    assert status["runtime_execution_profile"]["execution_broker_policy"] == "broker_policy_guarded"
    assert status["runtime_execution_profile"]["role_registry_policy"] == "governed_role_registry"
    assert status["runtime_execution_profile"]["authority_boundary_policy"] == "policy_scoped_authority_boundaries"
    assert status["runtime_execution_profile"]["cross_department_arbitration_policy"] == "policy_scored_arbitration"
    assert status["runtime_execution_profile"]["department_memory_isolation_policy"] == "policy_scoped_isolation"
    assert status["runtime_execution_profile"]["employee_contract_responsibility_policy"] == "contract_guided_responsibilities"
    assert status["runtime_execution_profile"]["core_responsibility_scope"] == "org_chart_role_and_contract_policy_boundaries"
    assert status["runtime_execution_profile"]["shadow_agent_account_policy"] == "policy_governed_shadow_accounts"
    assert status["runtime_execution_profile"]["user_base_management_surface_policy"] == "admin_ui_with_policy_api"
    assert status["runtime_execution_profile"]["employee_contract_change_authority_policy"] == "policy_scoped_manager_plus_hr_approval"
    assert status["runtime_execution_profile"]["employee_contract_management_surface_policy"] == "hr_admin_ui_with_policy_api"
    assert status["runtime_execution_profile"]["employee_contract_accountability_policy"] == "contract_obligation_attestation_guided"
    assert status["runtime_execution_profile"]["shadow_agent_org_parity_policy"] == "policy_validated_org_role_shadowing"
    assert status["runtime_execution_profile"]["shadow_agent_contract_binding_policy"] == "contract_binding_policy_guided"
    assert status["runtime_execution_profile"]["user_base_access_governance_policy"] == "rbac_policy_governed_controls"
    assert status["runtime_execution_profile"]["employee_contract_obligation_tracking_policy"] == "obligation_tracking_policy_guided"
    assert status["runtime_execution_profile"]["employee_contract_escalation_binding_policy"] == "contract_escalation_binding_policy_guided"
    assert status["runtime_execution_profile"]["regulatory_context_binding_policy"] == "regulatory_context_policy_guided"
    assert status["runtime_execution_profile"]["autonomy_preference_override_policy"] == "autonomy_override_policy_scoped"
    assert status["runtime_execution_profile"]["risk_tolerance_enforcement_policy"] == "risk_tolerance_policy_scored"
    assert status["runtime_execution_profile"]["safety_level_assurance_policy"] == "safety_level_attestation_guided"
    assert status["runtime_execution_profile"]["delegation_comfort_governance_policy"] == "delegation_comfort_policy_bounds"
    assert status["runtime_execution_profile"]["employee_contract_review_policy"] == "hr_review_policy_guided"
    assert status["runtime_execution_profile"]["employee_contract_versioning_policy"] == "governed_contract_version_history"
    assert status["runtime_execution_profile"]["shadow_agent_account_lifecycle_policy"] == "policy_guided_shadow_lifecycle"
    assert status["runtime_execution_profile"]["user_base_ui_audit_policy"] == "governed_ui_audit_stream"
    assert status["runtime_execution_profile"]["org_chart_assignment_sync_policy"] == "policy_scoped_org_chart_sync"
    assert status["runtime_execution_profile"]["event_queue_durability_policy"] == "durable_queue_policy_guided"
    assert status["runtime_execution_profile"]["idempotency_key_enforcement_policy"] == "idempotency_keys_policy_scoped"
    assert status["runtime_execution_profile"]["retry_backoff_policy"] == "policy_scoped_retry_backoff"
    assert status["runtime_execution_profile"]["circuit_breaker_policy"] == "circuit_breaker_policy_guarded"
    assert status["runtime_execution_profile"]["rollback_recovery_policy"] == "policy_scoped_rollback_recovery"
    assert status["runtime_execution_profile"]["planning_plane_decomposition_policy"] == "policy_guided_decomposition"
    assert status["runtime_execution_profile"]["planning_plane_risk_simulation_policy"] == "risk_simulation_policy_guided"
    assert status["runtime_execution_profile"]["execution_plane_permission_gate_policy"] == "permission_gates_policy_guided"
    assert status["runtime_execution_profile"]["execution_plane_budget_guardrail_policy"] == "policy_scoped_budget_guardrails"
    assert status["runtime_execution_profile"]["execution_plane_audit_trail_integrity_policy"] == "governed_audit_trail_integrity"
    assert status["runtime_execution_profile"]["human_in_the_loop_enforcement_policy"] == "human_in_the_loop_enforcement_policy_guided"
    assert status["runtime_execution_profile"]["regulatory_audit_retention_policy"] == "regulatory_audit_retention_policy_scoped"
    assert status["runtime_execution_profile"]["tenant_boundary_enforcement_policy"] == "tenant_boundary_enforcement_policy_scoped"
    assert status["runtime_execution_profile"]["policy_exception_handling_policy"] == "policy_exception_handling_governed_review"
    assert status["runtime_execution_profile"]["runtime_profile_refresh_policy"] == "runtime_profile_refresh_policy_guided"
    assert status["runtime_execution_profile"]["planning_plane_compliance_modeling_policy"] == "compliance_modeling_policy_guided"
    assert status["runtime_execution_profile"]["planning_plane_proposal_generation_policy"] == "proposal_generation_policy_scoped"
    assert status["runtime_execution_profile"]["execution_plane_policy_compiler_enforcement_policy"] == "execution_policy_compiler_enforcement_scoped"
    assert status["runtime_execution_profile"]["execution_plane_deterministic_override_policy"] == "deterministic_override_policy_scoped"
    assert status["runtime_execution_profile"]["hitl_escalation_requirement_policy"] == "hitl_escalation_requirement_policy_guided"
    assert status["runtime_execution_profile"]["shadow_peer_role_enforcement_policy"] == "shadow_peer_role_enforcement_policy_guided"
    assert status["runtime_execution_profile"]["shadow_account_user_binding_policy"] == "shadow_account_user_binding_policy_guided"
    assert status["runtime_execution_profile"]["employee_contract_scope_enforcement_policy"] == "employee_contract_scope_enforcement_policy_guided"
    assert status["runtime_execution_profile"]["employee_contract_exception_review_policy"] == "employee_contract_exception_review_policy_guided"
    assert status["runtime_execution_profile"]["user_base_tenant_boundary_policy"] == "user_base_tenant_boundary_policy_scoped"
    assert status["runtime_execution_profile"]["planning_execution_toggle_guard_policy"] == "planning_execution_toggle_policy_scoped"
    assert status["runtime_execution_profile"]["governance_exception_escalation_policy"] == "governance_exception_escalation_policy_guided"
    assert status["runtime_execution_profile"]["approval_sla_enforcement_policy"] == "approval_sla_enforcement_policy_scoped"
    assert status["runtime_execution_profile"]["tenant_residency_control_policy"] == "tenant_residency_control_policy_scoped"
    assert status["runtime_execution_profile"]["swarm_recursion_guard_policy"] == "swarm_recursion_guard_policy_scoped"
    assert status["runtime_execution_profile"]["replay_reconciliation_policy"] == "replay_reconciliation_policy_scoped"
    assert status["runtime_execution_profile"]["audit_artifact_retention_policy"] == "audit_artifact_retention_policy_scoped"
    assert status["runtime_execution_profile"]["event_backpressure_management_policy"] == "event_backpressure_management_policy_scoped"
    assert status["runtime_execution_profile"]["queue_health_slo_policy"] == "queue_health_slo_policy_scoped"
    assert status["runtime_execution_profile"]["rollback_compensation_policy"] == "rollback_compensation_policy_scoped"
    assert status["runtime_execution_profile"]["durable_queue_replay_policy"] == "durable_queue_replay_policy_scoped"
    assert status["runtime_execution_profile"]["swarm_failure_domain_isolation_policy"] == "swarm_failure_domain_isolation_policy_scoped"
    assert status["runtime_execution_profile"]["idempotent_recovery_validation_policy"] == "idempotent_recovery_validation_policy_scoped"
    assert status["runtime_execution_profile"]["agent_spawn_budget_reconciliation_policy"] == "agent_spawn_budget_reconciliation_policy_scoped"
    assert status["runtime_execution_profile"]["audit_chain_export_policy"] == "audit_chain_export_policy_scoped"
    assert status["runtime_execution_profile"]["legacy_orchestrator_discovery_policy"] == "legacy_orchestrator_inventory_policy_scoped"
    assert status["runtime_execution_profile"]["rubixcube_orchestrator_adapter_policy"] == "rubixcube_adapter_wiring_policy_scoped"
    assert status["runtime_execution_profile"]["triage_orchestrator_adapter_policy"] == "triage_adapter_wiring_policy_scoped"
    assert status["runtime_execution_profile"]["bot_catalog_capability_mapping_policy"] == "bot_catalog_capability_mapping_policy_scoped"
    assert status["runtime_execution_profile"]["legacy_orchestrator_wiring_priority_policy"] == "legacy_orchestrator_wiring_priority_policy_scoped"
    assert status["runtime_execution_profile"]["clockwork_orchestrator_bridge_policy"] == "clockwork_orchestrator_bridge_policy_scoped"
    assert status["runtime_execution_profile"]["arcana_pipeline_compatibility_policy"] == "arcana_pipeline_compatibility_policy_scoped"
    assert status["runtime_execution_profile"]["rubixcube_evidence_engine_policy"] == "rubixcube_evidence_engine_policy_scoped"
    assert status["runtime_execution_profile"]["triage_rollcall_confidence_policy"] == "triage_rollcall_confidence_policy_scoped"
    assert status["runtime_execution_profile"]["golden_path_reuse_policy"] == "golden_path_reuse_policy_scoped"
    assert status["runtime_execution_profile"]["governance_review_cadence_policy"] == "governance_review_cadence_policy_scoped"
    assert status["runtime_execution_profile"]["section_status_reconciliation_policy"] == "section_status_reconciliation_policy_scoped"
    assert status["runtime_execution_profile"]["orchestrator_wiring_readiness_policy"] == "orchestrator_wiring_readiness_policy_scoped"
    assert status["runtime_execution_profile"]["verification_feedback_closure_policy"] == "verification_feedback_closure_policy_scoped"
    assert status["runtime_execution_profile"]["self_improvement_backlog_priority_policy"] == "self_improvement_backlog_priority_policy_scoped"
    assert status["runtime_execution_profile"]["hitl_escalation_comfort_policy"] == "hitl_escalation_requirement_policy_guided"
    assert expected["summary"]["total_areas"] == len(expected["areas"])
    assert expected["summary"]["remediation_threshold_percent"] == 50
    assert expected["summary"]["low_completion_areas"] >= 1
    assert len(expected["summary"]["low_completion_area_ids"]) == expected["summary"]["low_completion_areas"]
    assert status["runtime_execution_profile"]["execution_enforcement_level"] == "policy_guarded"
    dynamic_chain = next(
        item for item in expected["areas"] if item["area"] == "dynamic_chain_test_coverage"
    )
    assert dynamic_chain["percent"] == 96


def test_runtime_execution_profile_mode_derivation():
    runtime = load_runtime_module()
    murphy = runtime.MurphySystem.create_test_instance()
    strict = murphy._build_runtime_execution_profile(
        "Regulated compliance workflow",
        {"safety_level": "strict", "risk_tolerance": "low"}
    )
    dynamic = murphy._build_runtime_execution_profile(
        "High autonomy production mode",
        {"autonomy_level": "dynamic", "risk_tolerance": "high"}
    )
    assert strict["execution_mode"] == "strict"
    assert strict["execution_profile_source"] == "onboarding"
    assert strict["execution_enforcement_level"] == "full_gate_enforcement"
    assert strict["control_plane_separation_state"] == "enforced"
    assert strict["self_improvement_rd_candidate"] == "governed_policy_tuning_loop"
    assert strict["approval_checkpoint_policy"] == "mandatory"
    assert strict["budget_enforcement_mode"] == "hard_cap"
    assert strict["audit_logging_policy"] == "immutable_full_stream"
    assert strict["escalation_routing_policy"] == "mandatory_human_chain"
    assert strict["tool_mediation_policy"] == "allowlist_mandatory_mediation"
    assert strict["deterministic_routing_policy"] == "deterministic_only"
    assert strict["compute_routing_policy"] == "deterministic_compute_lane"
    assert strict["policy_compiler_mode"] == "locked_policy_compilation"
    assert strict["permission_validation_policy"] == "explicit_role_validation"
    assert strict["delegation_scope_policy"] == "role_bound_delegation_only"
    assert strict["execution_broker_policy"] == "broker_hard_gate"
    assert strict["role_registry_policy"] == "immutable_role_registry"
    assert strict["authority_boundary_policy"] == "hard_authority_boundaries"
    assert strict["cross_department_arbitration_policy"] == "explicit_executive_arbitration"
    assert strict["department_memory_isolation_policy"] == "strict_department_isolation"
    assert strict["employee_contract_responsibility_policy"] == "contract_bound_responsibilities_required"
    assert strict["core_responsibility_scope"] == "org_chart_role_and_contract_hard_boundaries"
    assert strict["shadow_agent_account_policy"] == "identity_bound_shadow_accounts"
    assert strict["user_base_management_surface_policy"] == "admin_ui_only"
    assert strict["employee_contract_change_authority_policy"] == "hr_admin_approval_required"
    assert strict["employee_contract_management_surface_policy"] == "hr_admin_ui_only"
    assert strict["employee_contract_accountability_policy"] == "contract_obligation_attestation_required"
    assert strict["shadow_agent_org_parity_policy"] == "one_to_one_org_role_shadow_required"
    assert strict["shadow_agent_contract_binding_policy"] == "contract_binding_mandatory"
    assert strict["user_base_access_governance_policy"] == "rbac_and_tenant_controls_mandatory"
    assert strict["employee_contract_obligation_tracking_policy"] == "obligation_tracking_required"
    assert strict["employee_contract_escalation_binding_policy"] == "contract_escalation_binding_required"
    assert strict["regulatory_context_binding_policy"] == "regulatory_context_lockdown_required"
    assert strict["autonomy_preference_override_policy"] == "autonomy_override_disabled"
    assert strict["risk_tolerance_enforcement_policy"] == "low_risk_mandatory_enforcement"
    assert strict["safety_level_assurance_policy"] == "safety_level_attestation_required"
    assert strict["delegation_comfort_governance_policy"] == "delegation_comfort_hard_limits"
    assert strict["employee_contract_review_policy"] == "hr_legal_review_mandatory"
    assert strict["employee_contract_versioning_policy"] == "immutable_contract_version_history"
    assert strict["shadow_agent_account_lifecycle_policy"] == "hr_controlled_shadow_lifecycle"
    assert strict["user_base_ui_audit_policy"] == "immutable_ui_audit_stream"
    assert strict["org_chart_assignment_sync_policy"] == "mandatory_org_chart_sync_before_execution"
    assert strict["event_queue_durability_policy"] == "durable_queue_required"
    assert strict["idempotency_key_enforcement_policy"] == "idempotency_keys_mandatory"
    assert strict["retry_backoff_policy"] == "bounded_retry_with_manual_escalation"
    assert strict["circuit_breaker_policy"] == "circuit_breaker_hard_fail_closed"
    assert strict["rollback_recovery_policy"] == "rollback_required_on_policy_breach"
    assert strict["planning_plane_decomposition_policy"] == "hierarchical_decomposition_mandatory"
    assert strict["planning_plane_risk_simulation_policy"] == "risk_simulation_required_before_execution"
    assert strict["execution_plane_permission_gate_policy"] == "permission_gates_required"
    assert strict["execution_plane_budget_guardrail_policy"] == "hard_budget_guardrails"
    assert strict["execution_plane_audit_trail_integrity_policy"] == "immutable_audit_trail_required"
    assert strict["swarm_spawn_governance_policy"] == "spawn_governance_preapproval_required"
    assert strict["swarm_failure_containment_policy"] == "failure_containment_hard_isolation"
    assert strict["swarm_budget_expansion_policy"] == "swarm_budget_expansion_forbidden"
    assert strict["shadow_reinforcement_signal_policy"] == "shadow_reinforcement_signals_strictly_scoped"
    assert strict["behavioral_divergence_tracking_policy"] == "behavioral_divergence_tracking_mandatory"
    assert strict["planning_plane_gate_synthesis_policy"] == "gate_synthesis_required_before_execution"
    assert strict["planning_plane_org_mapping_policy"] == "org_mapping_lock_required"
    assert strict["execution_plane_tool_permission_enforcement_policy"] == "tool_permission_enforcement_mandatory"
    assert strict["execution_plane_budget_ceiling_override_policy"] == "budget_ceiling_override_forbidden"
    assert strict["execution_plane_escalation_checkpoint_policy"] == "escalation_checkpoint_required"
    assert strict["human_in_the_loop_enforcement_policy"] == "human_in_the_loop_enforcement_mandatory"
    assert strict["regulatory_audit_retention_policy"] == "regulatory_audit_retention_mandatory"
    assert strict["tenant_boundary_enforcement_policy"] == "tenant_boundary_enforcement_required"
    assert strict["policy_exception_handling_policy"] == "policy_exception_handling_manual_review_only"
    assert strict["runtime_profile_refresh_policy"] == "runtime_profile_refresh_pre_execution_required"
    assert strict["planning_plane_compliance_modeling_policy"] == "compliance_modeling_required_before_execution"
    assert strict["planning_plane_proposal_generation_policy"] == "proposal_generation_policy_gated"
    assert strict["execution_plane_policy_compiler_enforcement_policy"] == "execution_policy_compiler_enforcement_required"
    assert strict["execution_plane_deterministic_override_policy"] == "deterministic_override_required_for_high_risk"
    assert strict["hitl_escalation_requirement_policy"] == "hitl_escalation_requirement_hard"
    assert strict["shadow_peer_role_enforcement_policy"] == "shadow_peer_role_enforcement_mandatory"
    assert strict["shadow_account_user_binding_policy"] == "shadow_account_user_binding_mandatory"
    assert strict["employee_contract_scope_enforcement_policy"] == "employee_contract_scope_enforcement_required"
    assert strict["employee_contract_exception_review_policy"] == "employee_contract_exception_review_mandatory"
    assert strict["user_base_tenant_boundary_policy"] == "user_base_tenant_boundary_enforcement_required"
    assert strict["compliance_event_escalation_policy"] == "compliance_event_escalation_immediate"
    assert strict["regulatory_override_resolution_policy"] == "regulatory_override_resolution_manual_only"
    assert strict["budget_ceiling_revision_policy"] == "budget_ceiling_revision_manual_approval_only"
    assert strict["budget_consumption_alert_policy"] == "budget_consumption_alert_realtime_required"
    assert strict["approval_checkpoint_timeout_policy"] == "approval_checkpoint_timeout_hard_stop"
    assert strict["compliance_sensor_event_policy"] == "compliance_sensor_events_mandatory"
    assert strict["policy_drift_detection_policy"] == "policy_drift_detection_hard_gate"
    assert strict["onboarding_profile_revalidation_policy"] == "onboarding_profile_revalidation_required_before_execution"
    assert strict["control_plane_mode_transition_policy"] == "control_plane_mode_transition_manual_approval_required"
    assert strict["user_autonomy_preference_ui_policy"] == "user_autonomy_preference_ui_restricted"
    assert strict["planning_execution_toggle_guard_policy"] == "planning_execution_toggle_manual_approval_required"
    assert strict["governance_exception_escalation_policy"] == "governance_exception_escalation_immediate"
    assert strict["approval_sla_enforcement_policy"] == "approval_sla_enforcement_hard_deadline"
    assert strict["tenant_residency_control_policy"] == "tenant_residency_control_hard_enforced"
    assert strict["swarm_recursion_guard_policy"] == "swarm_recursion_guard_hard_limit"
    assert strict["contract_renewal_gate_policy"] == "contract_renewal_gate_required"
    assert strict["shadow_account_suspension_policy"] == "shadow_account_suspension_manual_approval_required"
    assert strict["user_base_offboarding_policy"] == "user_base_offboarding_workflow_required"
    assert strict["governance_kernel_heartbeat_policy"] == "governance_kernel_heartbeat_hard_monitoring"
    assert strict["policy_compiler_change_control_policy"] == "policy_compiler_change_control_manual_review_required"
    assert strict["replay_reconciliation_policy"] == "replay_reconciliation_required"
    assert strict["audit_artifact_retention_policy"] == "audit_artifact_retention_required"
    assert strict["event_backpressure_management_policy"] == "event_backpressure_management_required"
    assert strict["queue_health_slo_policy"] == "queue_health_slo_hard_enforced"
    assert strict["rollback_compensation_policy"] == "rollback_compensation_required"
    assert strict["durable_queue_replay_policy"] == "durable_queue_replay_required"
    assert strict["swarm_failure_domain_isolation_policy"] == "swarm_failure_domain_isolation_required"
    assert strict["idempotent_recovery_validation_policy"] == "idempotent_recovery_validation_required"
    assert strict["agent_spawn_budget_reconciliation_policy"] == "agent_spawn_budget_reconciliation_required"
    assert strict["audit_chain_export_policy"] == "audit_chain_export_required"
    assert strict["semantics_belief_state_policy"] == "structured_spec_hypothesis_belief_required"
    assert strict["semantics_loss_risk_policy"] == "loss_and_cvar_risk_evaluation_required"
    assert strict["semantics_voi_question_policy"] == "voi_questioning_required_before_high_risk_action"
    assert strict["semantics_invariance_boundary_policy"] == "invariance_commutation_gate_required"
    assert strict["semantics_verification_feedback_policy"] == "verification_feedback_loop_required"
    assert strict["semantics_hypothesis_update_policy"] == "belief_hypothesis_posterior_update_required"
    assert strict["semantics_likelihood_scoring_policy"] == "answer_likelihood_scoring_required"
    assert strict["semantics_rvoi_decision_policy"] == "rvoi_question_decision_required"
    assert strict["semantics_clarifying_question_budget_policy"] == "clarifying_question_budget_enforced"
    assert strict["semantics_invariance_retry_policy"] == "invariance_retry_or_ask_required"
    assert strict["semantics_hypothesis_distribution_policy"] == "structured_hypothesis_distribution_required"
    assert strict["semantics_cvar_risk_measure_policy"] == "expected_loss_and_cvar_required"
    assert strict["semantics_question_cost_policy"] == "question_cost_and_voi_threshold_required"
    assert strict["semantics_invariance_transform_set_policy"] == "invariance_transform_set_required"
    assert strict["semantics_verification_boundary_policy"] == "verification_boundary_enforcement_required"
    assert strict["runtime_telemetry_tokens_to_resolution_policy"] == "telemetry_tokens_to_resolution_required"
    assert strict["runtime_telemetry_question_count_policy"] == "telemetry_question_count_required"
    assert strict["runtime_telemetry_invariance_score_policy"] == "telemetry_invariance_score_required"
    assert strict["runtime_telemetry_risk_score_policy"] == "telemetry_risk_score_required"
    assert strict["runtime_telemetry_verification_feedback_policy"] == "telemetry_verification_feedback_required"
    assert strict["semantics_question_candidate_generation_policy"] == "semantics_question_candidate_generation_required"
    assert strict["semantics_answer_prediction_policy"] == "semantics_answer_prediction_required"
    assert strict["semantics_belief_normalization_policy"] == "semantics_belief_normalization_required"
    assert strict["semantics_verification_loss_injection_policy"] == "semantics_verification_loss_injection_required"
    assert strict["semantics_action_revision_policy"] == "semantics_action_revision_required"
    assert strict["legacy_orchestrator_discovery_policy"] == "legacy_orchestrator_inventory_required"
    assert strict["rubixcube_orchestrator_adapter_policy"] == "rubixcube_adapter_wiring_required"
    assert strict["triage_orchestrator_adapter_policy"] == "triage_adapter_wiring_required"
    assert strict["bot_catalog_capability_mapping_policy"] == "bot_catalog_capability_mapping_required"
    assert strict["legacy_orchestrator_wiring_priority_policy"] == "legacy_orchestrator_wiring_priority_required"
    assert strict["modern_arcana_clockwork_bridge_policy"] == "modern_arcana_clockwork_bridge_required"
    assert strict["legacy_orchestrator_compatibility_matrix_policy"] == "legacy_orchestrator_compatibility_matrix_required"
    assert strict["rubixcube_kaia_mix_scoring_policy"] == "rubixcube_kaia_mix_scoring_required"
    assert strict["triage_rollcall_selection_policy"] == "triage_rollcall_selection_required"
    assert strict["legacy_orchestrator_tooling_plan_policy"] == "legacy_orchestrator_tooling_plan_required"
    assert strict["clockwork_orchestrator_bridge_policy"] == "clockwork_orchestrator_bridge_required"
    assert strict["arcana_pipeline_compatibility_policy"] == "arcana_pipeline_compatibility_required"
    assert strict["rubixcube_evidence_engine_policy"] == "rubixcube_evidence_engine_required"
    assert strict["triage_rollcall_confidence_policy"] == "triage_rollcall_confidence_required"
    assert strict["golden_path_reuse_policy"] == "golden_path_reuse_required"
    assert strict["governance_review_cadence_policy"] == "governance_review_cadence_required"
    assert strict["section_status_reconciliation_policy"] == "section_status_reconciliation_required"
    assert strict["orchestrator_wiring_readiness_policy"] == "orchestrator_wiring_readiness_required"
    assert strict["verification_feedback_closure_policy"] == "verification_feedback_closure_required"
    assert strict["self_improvement_backlog_priority_policy"] == "self_improvement_backlog_priority_required"
    assert strict["hitl_escalation_comfort_policy"] == "hitl_escalation_requirement_hard"
    assert strict["escalation_policy"] == "mandatory"
    assert dynamic["execution_mode"] == "dynamic"
    assert dynamic["execution_profile_source"] == "onboarding"
    assert dynamic["execution_enforcement_level"] == "autonomy_accelerated"
    assert dynamic["control_plane_separation_state"] == "relaxed"
    assert dynamic["self_improvement_rd_candidate"] == "autonomous_feedback_acceleration_loop"
    assert dynamic["approval_checkpoint_policy"] == "on_demand"
    assert dynamic["budget_enforcement_mode"] == "user_tunable"
    assert dynamic["audit_logging_policy"] == "sampled_governance_stream"
    assert dynamic["escalation_routing_policy"] == "exception_only_chain"
    assert dynamic["tool_mediation_policy"] == "accelerated_mediation_with_guardrails"
    assert dynamic["deterministic_routing_policy"] == "deterministic_fallback"
    assert dynamic["compute_routing_policy"] == "adaptive_compute_lane"
    assert dynamic["policy_compiler_mode"] == "adaptive_policy_compilation"
    assert dynamic["permission_validation_policy"] == "adaptive_validation_with_bounds"
    assert dynamic["delegation_scope_policy"] == "adaptive_delegation_with_caps"
    assert dynamic["execution_broker_policy"] == "broker_adaptive_guardrailed"
    assert dynamic["role_registry_policy"] == "adaptive_role_registry_with_audit"
    assert dynamic["authority_boundary_policy"] == "adaptive_authority_boundaries_with_audit"
    assert dynamic["cross_department_arbitration_policy"] == "adaptive_arbitration_with_audit"
    assert dynamic["department_memory_isolation_policy"] == "adaptive_isolation_with_audit"
    assert dynamic["employee_contract_responsibility_policy"] == "contract_aware_adaptive_responsibilities"
    assert dynamic["core_responsibility_scope"] == "org_chart_role_and_contract_adaptive_boundaries"
    assert dynamic["shadow_agent_account_policy"] == "adaptive_shadow_accounts_with_audit"
    assert dynamic["user_base_management_surface_policy"] == "admin_ui_plus_delegated_api_with_audit"
    assert dynamic["employee_contract_change_authority_policy"] == "delegated_manager_updates_with_hr_audit"
    assert dynamic["employee_contract_management_surface_policy"] == "hr_admin_ui_plus_delegated_api_with_audit"
    assert dynamic["employee_contract_accountability_policy"] == "contract_obligation_attestation_adaptive"
    assert dynamic["shadow_agent_org_parity_policy"] == "adaptive_org_role_shadowing_with_audit"
    assert dynamic["shadow_agent_contract_binding_policy"] == "contract_binding_adaptive_with_audit"
    assert dynamic["user_base_access_governance_policy"] == "adaptive_rbac_controls_with_audit"
    assert dynamic["employee_contract_obligation_tracking_policy"] == "obligation_tracking_adaptive_with_audit"
    assert dynamic["employee_contract_escalation_binding_policy"] == "contract_escalation_binding_adaptive"
    assert dynamic["regulatory_context_binding_policy"] == "regulatory_context_adaptive_with_audit"
    assert dynamic["autonomy_preference_override_policy"] == "autonomy_override_user_tunable_with_audit"
    assert dynamic["risk_tolerance_enforcement_policy"] == "risk_tolerance_adaptive_with_caps"
    assert dynamic["safety_level_assurance_policy"] == "safety_level_attestation_adaptive"
    assert dynamic["delegation_comfort_governance_policy"] == "delegation_comfort_adaptive_bounds"
    assert dynamic["employee_contract_review_policy"] == "adaptive_hr_review_with_audit"
    assert dynamic["employee_contract_versioning_policy"] == "adaptive_contract_version_history_with_audit"
    assert dynamic["shadow_agent_account_lifecycle_policy"] == "adaptive_shadow_lifecycle_with_audit"
    assert dynamic["user_base_ui_audit_policy"] == "sampled_ui_audit_stream_with_escalation"
    assert dynamic["org_chart_assignment_sync_policy"] == "adaptive_org_chart_sync_with_audit"
    assert dynamic["event_queue_durability_policy"] == "durable_queue_adaptive_with_audit"
    assert dynamic["idempotency_key_enforcement_policy"] == "idempotency_keys_adaptive_with_audit"
    assert dynamic["retry_backoff_policy"] == "adaptive_retry_backoff_with_guardrails"
    assert dynamic["circuit_breaker_policy"] == "circuit_breaker_adaptive_with_audit"
    assert dynamic["rollback_recovery_policy"] == "adaptive_rollback_recovery_with_audit"
    assert dynamic["planning_plane_decomposition_policy"] == "adaptive_decomposition_with_audit"
    assert dynamic["planning_plane_risk_simulation_policy"] == "adaptive_risk_simulation_with_audit"
    assert dynamic["execution_plane_permission_gate_policy"] == "adaptive_permission_gates_with_audit"
    assert dynamic["execution_plane_budget_guardrail_policy"] == "adaptive_budget_guardrails_with_audit"
    assert dynamic["execution_plane_audit_trail_integrity_policy"] == "adaptive_audit_trail_integrity_with_audit"
    assert dynamic["swarm_spawn_governance_policy"] == "spawn_governance_adaptive_with_audit"
    assert dynamic["swarm_failure_containment_policy"] == "failure_containment_adaptive_with_audit"
    assert dynamic["swarm_budget_expansion_policy"] == "swarm_budget_expansion_adaptive_with_caps"
    assert dynamic["shadow_reinforcement_signal_policy"] == "shadow_reinforcement_signals_adaptive_with_audit"
    assert dynamic["behavioral_divergence_tracking_policy"] == "behavioral_divergence_tracking_adaptive_with_audit"
    assert dynamic["planning_plane_gate_synthesis_policy"] == "adaptive_gate_synthesis_with_audit"
    assert dynamic["planning_plane_org_mapping_policy"] == "adaptive_org_mapping_with_audit"
    assert dynamic["execution_plane_tool_permission_enforcement_policy"] == "adaptive_tool_permission_enforcement_with_audit"
    assert dynamic["execution_plane_budget_ceiling_override_policy"] == "budget_ceiling_override_adaptive_with_audit"
    assert dynamic["execution_plane_escalation_checkpoint_policy"] == "escalation_checkpoint_adaptive_with_audit"
    assert dynamic["human_in_the_loop_enforcement_policy"] == "human_in_the_loop_enforcement_adaptive_with_audit"
    assert dynamic["regulatory_audit_retention_policy"] == "regulatory_audit_retention_adaptive_with_audit"
    assert dynamic["tenant_boundary_enforcement_policy"] == "tenant_boundary_enforcement_adaptive_with_audit"
    assert dynamic["policy_exception_handling_policy"] == "policy_exception_handling_adaptive_with_audit"
    assert dynamic["runtime_profile_refresh_policy"] == "runtime_profile_refresh_adaptive_with_audit"
    assert dynamic["planning_plane_compliance_modeling_policy"] == "compliance_modeling_adaptive_with_audit"
    assert dynamic["planning_plane_proposal_generation_policy"] == "proposal_generation_adaptive_with_audit"
    assert dynamic["execution_plane_policy_compiler_enforcement_policy"] == "execution_policy_compiler_enforcement_adaptive_with_audit"
    assert dynamic["execution_plane_deterministic_override_policy"] == "deterministic_override_adaptive_with_audit"
    assert dynamic["hitl_escalation_requirement_policy"] == "hitl_escalation_requirement_adaptive_with_audit"
    assert dynamic["shadow_peer_role_enforcement_policy"] == "shadow_peer_role_enforcement_adaptive_with_audit"
    assert dynamic["shadow_account_user_binding_policy"] == "shadow_account_user_binding_adaptive_with_audit"
    assert dynamic["employee_contract_scope_enforcement_policy"] == "employee_contract_scope_enforcement_adaptive_with_audit"
    assert dynamic["employee_contract_exception_review_policy"] == "employee_contract_exception_review_adaptive_with_audit"
    assert dynamic["user_base_tenant_boundary_policy"] == "user_base_tenant_boundary_adaptive_with_audit"
    assert dynamic["compliance_event_escalation_policy"] == "compliance_event_escalation_adaptive_with_audit"
    assert dynamic["regulatory_override_resolution_policy"] == "regulatory_override_resolution_adaptive_with_audit"
    assert dynamic["budget_ceiling_revision_policy"] == "budget_ceiling_revision_adaptive_with_audit"
    assert dynamic["budget_consumption_alert_policy"] == "budget_consumption_alert_adaptive_with_audit"
    assert dynamic["approval_checkpoint_timeout_policy"] == "approval_checkpoint_timeout_adaptive_with_audit"
    assert dynamic["compliance_sensor_event_policy"] == "compliance_sensor_events_adaptive_with_audit"
    assert dynamic["policy_drift_detection_policy"] == "policy_drift_detection_adaptive_with_audit"
    assert dynamic["onboarding_profile_revalidation_policy"] == "onboarding_profile_revalidation_adaptive_with_audit"
    assert dynamic["control_plane_mode_transition_policy"] == "control_plane_mode_transition_adaptive_with_audit"
    assert dynamic["user_autonomy_preference_ui_policy"] == "user_autonomy_preference_ui_adaptive_with_audit"
    assert dynamic["planning_execution_toggle_guard_policy"] == "planning_execution_toggle_adaptive_with_audit"
    assert dynamic["governance_exception_escalation_policy"] == "governance_exception_escalation_adaptive_with_audit"
    assert dynamic["approval_sla_enforcement_policy"] == "approval_sla_enforcement_adaptive_with_audit"
    assert dynamic["tenant_residency_control_policy"] == "tenant_residency_control_adaptive_with_audit"
    assert dynamic["swarm_recursion_guard_policy"] == "swarm_recursion_guard_adaptive_with_audit"
    assert dynamic["contract_renewal_gate_policy"] == "contract_renewal_gate_adaptive_with_audit"
    assert dynamic["shadow_account_suspension_policy"] == "shadow_account_suspension_adaptive_with_audit"
    assert dynamic["user_base_offboarding_policy"] == "user_base_offboarding_adaptive_with_audit"
    assert dynamic["governance_kernel_heartbeat_policy"] == "governance_kernel_heartbeat_adaptive_with_audit"
    assert dynamic["policy_compiler_change_control_policy"] == "policy_compiler_change_control_adaptive_with_audit"
    assert dynamic["replay_reconciliation_policy"] == "replay_reconciliation_adaptive_with_audit"
    assert dynamic["audit_artifact_retention_policy"] == "audit_artifact_retention_adaptive_with_audit"
    assert dynamic["event_backpressure_management_policy"] == "event_backpressure_management_adaptive_with_audit"
    assert dynamic["queue_health_slo_policy"] == "queue_health_slo_adaptive_with_audit"
    assert dynamic["rollback_compensation_policy"] == "rollback_compensation_adaptive_with_audit"
    assert dynamic["durable_queue_replay_policy"] == "durable_queue_replay_adaptive_with_audit"
    assert dynamic["swarm_failure_domain_isolation_policy"] == "swarm_failure_domain_isolation_adaptive_with_audit"
    assert dynamic["idempotent_recovery_validation_policy"] == "idempotent_recovery_validation_adaptive_with_audit"
    assert dynamic["agent_spawn_budget_reconciliation_policy"] == "agent_spawn_budget_reconciliation_adaptive_with_audit"
    assert dynamic["audit_chain_export_policy"] == "audit_chain_export_adaptive_with_audit"
    assert dynamic["semantics_belief_state_policy"] == "structured_spec_hypothesis_belief_adaptive_with_audit"
    assert dynamic["semantics_loss_risk_policy"] == "loss_and_cvar_risk_evaluation_adaptive_with_audit"
    assert dynamic["semantics_voi_question_policy"] == "voi_questioning_adaptive_with_audit"
    assert dynamic["semantics_invariance_boundary_policy"] == "invariance_commutation_adaptive_with_audit"
    assert dynamic["semantics_verification_feedback_policy"] == "verification_feedback_adaptive_with_audit"
    assert dynamic["semantics_hypothesis_update_policy"] == "belief_hypothesis_posterior_update_adaptive_with_audit"
    assert dynamic["semantics_likelihood_scoring_policy"] == "answer_likelihood_scoring_adaptive_with_audit"
    assert dynamic["semantics_rvoi_decision_policy"] == "rvoi_question_decision_adaptive_with_audit"
    assert dynamic["semantics_clarifying_question_budget_policy"] == "clarifying_question_budget_adaptive_with_audit"
    assert dynamic["semantics_invariance_retry_policy"] == "invariance_retry_or_ask_adaptive_with_audit"
    assert dynamic["semantics_hypothesis_distribution_policy"] == "structured_hypothesis_distribution_adaptive_with_audit"
    assert dynamic["semantics_cvar_risk_measure_policy"] == "expected_loss_and_cvar_adaptive_with_audit"
    assert dynamic["semantics_question_cost_policy"] == "question_cost_and_voi_threshold_adaptive_with_audit"
    assert dynamic["semantics_invariance_transform_set_policy"] == "invariance_transform_set_adaptive_with_audit"
    assert dynamic["semantics_verification_boundary_policy"] == "verification_boundary_enforcement_adaptive_with_audit"
    assert dynamic["runtime_telemetry_tokens_to_resolution_policy"] == "telemetry_tokens_to_resolution_adaptive_with_audit"
    assert dynamic["runtime_telemetry_question_count_policy"] == "telemetry_question_count_adaptive_with_audit"
    assert dynamic["runtime_telemetry_invariance_score_policy"] == "telemetry_invariance_score_adaptive_with_audit"
    assert dynamic["runtime_telemetry_risk_score_policy"] == "telemetry_risk_score_adaptive_with_audit"
    assert dynamic["runtime_telemetry_verification_feedback_policy"] == "telemetry_verification_feedback_adaptive_with_audit"
    assert dynamic["semantics_question_candidate_generation_policy"] == "semantics_question_candidate_generation_adaptive_with_audit"
    assert dynamic["semantics_answer_prediction_policy"] == "semantics_answer_prediction_adaptive_with_audit"
    assert dynamic["semantics_belief_normalization_policy"] == "semantics_belief_normalization_adaptive_with_audit"
    assert dynamic["semantics_verification_loss_injection_policy"] == "semantics_verification_loss_injection_adaptive_with_audit"
    assert dynamic["semantics_action_revision_policy"] == "semantics_action_revision_adaptive_with_audit"
    assert dynamic["legacy_orchestrator_discovery_policy"] == "legacy_orchestrator_inventory_adaptive_with_audit"
    assert dynamic["rubixcube_orchestrator_adapter_policy"] == "rubixcube_adapter_wiring_adaptive_with_audit"
    assert dynamic["triage_orchestrator_adapter_policy"] == "triage_adapter_wiring_adaptive_with_audit"
    assert dynamic["bot_catalog_capability_mapping_policy"] == "bot_catalog_capability_mapping_adaptive_with_audit"
    assert dynamic["legacy_orchestrator_wiring_priority_policy"] == "legacy_orchestrator_wiring_priority_adaptive_with_audit"
    assert dynamic["modern_arcana_clockwork_bridge_policy"] == "modern_arcana_clockwork_bridge_adaptive_with_audit"
    assert dynamic["legacy_orchestrator_compatibility_matrix_policy"] == "legacy_orchestrator_compatibility_matrix_adaptive_with_audit"
    assert dynamic["rubixcube_kaia_mix_scoring_policy"] == "rubixcube_kaia_mix_scoring_adaptive_with_audit"
    assert dynamic["triage_rollcall_selection_policy"] == "triage_rollcall_selection_adaptive_with_audit"
    assert dynamic["legacy_orchestrator_tooling_plan_policy"] == "legacy_orchestrator_tooling_plan_adaptive_with_audit"
    assert dynamic["clockwork_orchestrator_bridge_policy"] == "clockwork_orchestrator_bridge_adaptive_with_audit"
    assert dynamic["arcana_pipeline_compatibility_policy"] == "arcana_pipeline_compatibility_adaptive_with_audit"
    assert dynamic["rubixcube_evidence_engine_policy"] == "rubixcube_evidence_engine_adaptive_with_audit"
    assert dynamic["triage_rollcall_confidence_policy"] == "triage_rollcall_confidence_adaptive_with_audit"
    assert dynamic["golden_path_reuse_policy"] == "golden_path_reuse_adaptive_with_audit"
    assert dynamic["governance_review_cadence_policy"] == "governance_review_cadence_adaptive_with_audit"
    assert dynamic["section_status_reconciliation_policy"] == "section_status_reconciliation_adaptive_with_audit"
    assert dynamic["orchestrator_wiring_readiness_policy"] == "orchestrator_wiring_readiness_adaptive_with_audit"
    assert dynamic["verification_feedback_closure_policy"] == "verification_feedback_closure_adaptive_with_audit"
    assert dynamic["self_improvement_backlog_priority_policy"] == "self_improvement_backlog_priority_adaptive_with_audit"
    assert dynamic["hitl_escalation_comfort_policy"] == "hitl_escalation_requirement_adaptive_with_audit"
    assert dynamic["audit_requirements"] == "minimal"
