"""
Adaptive Campaign Engine — Tier-Filling Campaigns with Traction Monitoring

Design Label: MKT-004 — Adaptive Per-Tier Campaign Management
Owner: VP Marketing / CRO
Dependencies:
  - CampaignOrchestrator (MKT-003, campaign lifecycle & budgets)
  - UnitEconomicsAnalyzer (BIZ-002, tier revenue / cost data)
  - EventBackbone (event publishing for audit / dashboards)
  - HITLApprovalSystem or HumanOversightSystem (founder approval for paid ads)

Purpose:
  Marketing agents need campaigns that are actively trying to fill every
  tier.  When traction is low the system automatically adjusts campaigns
  and demographics.  Larger paid-advertising campaigns can be proposed but
  require human-in-the-loop founder approval combined with a viable market
  strategy generated by the system based on real-time performance data.

Flow:
  1. Bootstrap one campaign per pricing tier (community → enterprise)
  2. Continuously ingest performance metrics (impressions, leads, conversions)
  3. Detect low traction (conversion rate below threshold for N evaluation
     periods)
  4. Auto-adjust: rotate channel mix, shift demographics, update messaging
  5. If organic adjustments fail, generate a PaidAdProposal with budget,
     channels, rationale, and projected ROI
  6. PaidAdProposal requires HITL founder approval before execution
  7. Publish events for every adjustment and proposal for audit trail

Safety invariants:
  - Thread-safe: all shared state guarded by Lock
  - No paid spend without explicit founder approval (HITL gate)
  - Bounded: configurable max proposals and adjustments
  - Audit trail: every pivot and proposal is logged via EventBackbone

Copyright © 2020 Inoni Limited Liability Company
Creator: Corey Post
License: BSL 1.1
"""

from __future__ import annotations

import logging
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

try:
    from thread_safe_operations import capped_append
except ImportError:
    def capped_append(target_list: list, item: Any, max_size: int = 10_000) -> None:
        """Fallback bounded append (CWE-770)."""
        if len(target_list) >= max_size:
            del target_list[: max_size // 10]
        target_list.append(item)
from unit_economics_analyzer import _DEFAULT_TIER_REVENUES

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class TierCampaignStatus(str, Enum):
    """Lifecycle of a per-tier campaign."""
    ACTIVE = "active"
    ADJUSTING = "adjusting"       # Auto-pivoting channels / demographics
    PENDING_APPROVAL = "pending_approval"  # Paid-ad proposal awaiting founder
    PAUSED = "paused"
    COMPLETED = "completed"


class TractionLevel(str, Enum):
    """Traction classification for a tier campaign."""
    HEALTHY = "healthy"
    LOW = "low"
    CRITICAL = "critical"


class ProposalStatus(str, Enum):
    """Approval status for a paid-ad proposal."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class TierPerformanceSnapshot:
    """Point-in-time performance metrics for a tier campaign."""
    period: str                    # ISO date or label, e.g. "2026-W09"
    impressions: int = 0
    leads: int = 0
    conversions: int = 0
    spend_usd: float = 0.0
    recorded_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    @property
    def conversion_rate(self) -> float:
        """Leads → conversions rate.  Returns 0 if no leads."""
        return self.conversions / self.leads if self.leads > 0 else 0.0

    @property
    def lead_rate(self) -> float:
        """Impressions → leads rate.  Returns 0 if no impressions."""
        return self.leads / self.impressions if self.impressions > 0 else 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "period": self.period,
            "impressions": self.impressions,
            "leads": self.leads,
            "conversions": self.conversions,
            "spend_usd": round(self.spend_usd, 2),
            "conversion_rate": round(self.conversion_rate, 4),
            "lead_rate": round(self.lead_rate, 4),
            "recorded_at": self.recorded_at,
        }


@dataclass
class CampaignAdjustment:
    """Record of an automatic campaign adjustment."""
    adjustment_id: str
    tier: str
    reason: str
    old_channels: List[str]
    new_channels: List[str]
    old_demographics: List[str]
    new_demographics: List[str]
    old_messaging: str
    new_messaging: str
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "adjustment_id": self.adjustment_id,
            "tier": self.tier,
            "reason": self.reason,
            "old_channels": self.old_channels,
            "new_channels": self.new_channels,
            "old_demographics": self.old_demographics,
            "new_demographics": self.new_demographics,
            "old_messaging": self.old_messaging,
            "new_messaging": self.new_messaging,
            "created_at": self.created_at,
        }


@dataclass
class PaidAdProposal:
    """Proposal for paid advertising requiring founder HITL approval."""
    proposal_id: str
    tier: str
    proposed_budget_usd: float
    proposed_channels: List[str]
    target_demographics: List[str]
    rationale: str
    projected_roi: float           # e.g. 2.5 = 250% return
    market_strategy: str           # System-generated strategy narrative
    status: ProposalStatus = ProposalStatus.PENDING
    approved_by: Optional[str] = None
    approved_at: Optional[str] = None
    rejection_reason: Optional[str] = None
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "tier": self.tier,
            "proposed_budget_usd": round(self.proposed_budget_usd, 2),
            "proposed_channels": self.proposed_channels,
            "target_demographics": self.target_demographics,
            "rationale": self.rationale,
            "projected_roi": round(self.projected_roi, 2),
            "market_strategy": self.market_strategy,
            "status": self.status.value,
            "approved_by": self.approved_by,
            "approved_at": self.approved_at,
            "rejection_reason": self.rejection_reason,
            "created_at": self.created_at,
        }


@dataclass
class TierCampaign:
    """Campaign state for a single pricing tier."""
    tier: str
    status: TierCampaignStatus = TierCampaignStatus.ACTIVE
    channels: List[str] = field(default_factory=list)
    demographics: List[str] = field(default_factory=list)
    messaging: str = ""
    monthly_revenue_target: float = 0.0
    snapshots: List[TierPerformanceSnapshot] = field(default_factory=list)
    adjustments: List[CampaignAdjustment] = field(default_factory=list)
    proposals: List[PaidAdProposal] = field(default_factory=list)
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    @property
    def total_conversions(self) -> int:
        return sum(s.conversions for s in self.snapshots)

    @property
    def total_leads(self) -> int:
        return sum(s.leads for s in self.snapshots)

    @property
    def total_spend(self) -> float:
        return sum(s.spend_usd for s in self.snapshots)

    def latest_snapshot(self) -> Optional[TierPerformanceSnapshot]:
        return self.snapshots[-1] if self.snapshots else None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tier": self.tier,
            "status": self.status.value,
            "channels": list(self.channels),
            "demographics": list(self.demographics),
            "messaging": self.messaging,
            "monthly_revenue_target": round(self.monthly_revenue_target, 2),
            "total_conversions": self.total_conversions,
            "total_leads": self.total_leads,
            "total_spend": round(self.total_spend, 2),
            "adjustment_count": len(self.adjustments),
            "proposal_count": len(self.proposals),
            "snapshot_count": len(self.snapshots),
        }


# ---------------------------------------------------------------------------
# Default tier campaign configurations
# ---------------------------------------------------------------------------

_DEFAULT_TIER_CAMPAIGNS: Dict[str, Dict[str, Any]] = {
    "community": {
        "channels": ["github_readme", "community_forums", "social_organic", "dev_conferences"],
        "demographics": ["developers", "open_source_contributors", "indie_hackers", "students"],
        "messaging": (
            "Free forever — full automation engine, all modules, "
            "CLI and terminal interfaces. Community-powered."
        ),
    },
    "pro": {
        "channels": ["email_outreach", "linkedin_ads", "google_ads", "webinars"],
        "demographics": ["smb_owners", "startup_founders", "ops_managers", "freelancers"],
        "messaging": (
            "$299/mo — managed cloud hosting, priority support, "
            "advanced analytics, custom connectors."
        ),
    },
    "enterprise": {
        "channels": ["enterprise_sales", "linkedin_enterprise", "industry_events", "partner_referrals"],
        "demographics": ["cto_vp_eng", "enterprise_it", "compliance_officers", "c_suite"],
        "messaging": (
            "Contact us — unlimited deployments, on-premise, "
            "24/7 SRE support, SOC2/HIPAA, dedicated CSM."
        ),
    },
    "creator_starter": {
        "channels": ["social_dm", "tiktok_ads", "influencer_outreach", "referral_program"],
        "demographics": ["content_creators", "onlyfans_operators", "twitch_streamers", "youtubers"],
        "messaging": (
            "$20/mo — automate content scheduling, moderation, "
            "fan engagement across all your platforms."
        ),
    },
    "creator_pro": {
        "channels": ["email_outreach", "social_dm", "youtube_ads", "agency_partnerships"],
        "demographics": ["agency_owners", "top_creators", "multi_platform_creators", "talent_managers"],
        "messaging": (
            "$299/mo — full automation suite, priority AI support, "
            "multi-platform scheduling, advanced analytics."
        ),
    },
}

# Alternate channels/demographics to rotate into when traction is low
_PIVOT_OPTIONS: Dict[str, Dict[str, List[str]]] = {
    "community": {
        "channels": ["reddit_organic", "hackernews", "youtube_tutorials", "discord_community"],
        "demographics": ["devops_engineers", "data_scientists", "hobbyist_makers", "bootcamp_grads"],
    },
    "pro": {
        "channels": ["twitter_ads", "podcast_sponsorship", "content_marketing", "seo_blog"],
        "demographics": ["marketing_managers", "product_managers", "agency_founders", "solopreneurs"],
    },
    "enterprise": {
        "channels": ["gartner_listing", "g2_reviews", "outbound_sdr", "executive_dinners"],
        "demographics": ["ciso", "procurement_leads", "digital_transformation", "board_advisors"],
    },
    "creator_starter": {
        "channels": ["instagram_reels", "twitter_threads", "reddit_creator_subs", "podcast_guesting"],
        "demographics": ["patreon_creators", "kick_streamers", "tiktok_micro_influencers", "newsletter_writers"],
    },
    "creator_pro": {
        "channels": ["linkedin_outreach", "creator_economy_events", "affiliate_network", "pr_features"],
        "demographics": ["mcn_networks", "brand_deal_creators", "course_creators", "podcast_hosts"],
    },
}


# ---------------------------------------------------------------------------
# Adaptive Campaign Engine
# ---------------------------------------------------------------------------

class AdaptiveCampaignEngine:
    """Manages per-tier marketing campaigns with automatic traction adjustment.

    Responsibilities:
      1. Bootstrap one campaign per pricing tier
      2. Ingest performance snapshots each evaluation period
      3. Detect low traction and auto-adjust channels / demographics
      4. Propose paid-advertising campaigns when organic pivots fail
      5. Gate all paid spend behind founder HITL approval
      6. Publish events for every adjustment and proposal
    """

    # Traction thresholds (conversion rate: leads → paying)
    HEALTHY_CONVERSION_RATE = 0.03    # ≥3% = healthy
    LOW_CONVERSION_RATE = 0.01        # 1-3% = low
    # Below 1% = critical

    # How many consecutive low-traction periods before we pivot
    ADJUSTMENT_TRIGGER_PERIODS = 2
    # How many adjustments before proposing paid ads
    MAX_ORGANIC_ADJUSTMENTS = 3

    def __init__(self) -> None:
        self._campaigns: Dict[str, TierCampaign] = {}
        self._lock = threading.Lock()
        self._event_log: List[Dict[str, Any]] = []

    # ------------------------------------------------------------------
    # Bootstrap
    # ------------------------------------------------------------------

    def bootstrap_tier_campaigns(
        self,
        tiers: Optional[List[str]] = None,
    ) -> Dict[str, TierCampaign]:
        """Create one campaign per tier using default configurations."""
        tiers = tiers or list(_DEFAULT_TIER_CAMPAIGNS.keys())
        with self._lock:
            for tier in tiers:
                if tier in self._campaigns:
                    continue
                cfg = _DEFAULT_TIER_CAMPAIGNS.get(tier, {})
                tc = TierCampaign(
                    tier=tier,
                    channels=list(cfg.get("channels", [])),
                    demographics=list(cfg.get("demographics", [])),
                    messaging=cfg.get("messaging", ""),
                )
                self._campaigns[tier] = tc
                self._log_event("campaign_bootstrapped", tier, {
                    "channels": tc.channels,
                    "demographics": tc.demographics,
                })
        return dict(self._campaigns)

    # ------------------------------------------------------------------
    # Performance ingestion
    # ------------------------------------------------------------------

    def record_snapshot(
        self,
        tier: str,
        period: str,
        impressions: int = 0,
        leads: int = 0,
        conversions: int = 0,
        spend_usd: float = 0.0,
    ) -> Optional[TierPerformanceSnapshot]:
        """Record a performance snapshot for a tier campaign."""
        with self._lock:
            tc = self._campaigns.get(tier)
            if tc is None:
                return None
            snap = TierPerformanceSnapshot(
                period=period,
                impressions=impressions,
                leads=leads,
                conversions=conversions,
                spend_usd=spend_usd,
            )
            capped_append(tc.snapshots, snap, max_size=1_000)
            return snap

    # ------------------------------------------------------------------
    # Traction evaluation
    # ------------------------------------------------------------------

    def evaluate_traction(self, tier: str) -> Optional[Dict[str, Any]]:
        """Evaluate traction for a tier and return status + recommended action."""
        with self._lock:
            tc = self._campaigns.get(tier)
            if tc is None:
                return None
            recent = tc.snapshots[-self.ADJUSTMENT_TRIGGER_PERIODS:] if tc.snapshots else []

        if not recent:
            return {
                "tier": tier,
                "traction": TractionLevel.HEALTHY.value,
                "action": "awaiting_data",
                "message": "No performance data yet",
            }

        avg_conv_rate = (
            sum(s.conversion_rate for s in recent) / (len(recent) or 1)
        )

        if avg_conv_rate >= self.HEALTHY_CONVERSION_RATE:
            traction = TractionLevel.HEALTHY
            action = "maintain"
            message = f"Conversion rate {avg_conv_rate:.2%} is healthy"
        elif avg_conv_rate >= self.LOW_CONVERSION_RATE:
            traction = TractionLevel.LOW
            action = "adjust_campaign"
            message = (
                f"Conversion rate {avg_conv_rate:.2%} is low — "
                "recommend channel/demographic adjustment"
            )
        else:
            traction = TractionLevel.CRITICAL
            organic_adjustments = len(tc.adjustments)
            if organic_adjustments >= self.MAX_ORGANIC_ADJUSTMENTS:
                action = "propose_paid_ads"
                message = (
                    f"Conversion rate {avg_conv_rate:.2%} is critical after "
                    f"{organic_adjustments} organic adjustments — "
                    "recommend paid advertising proposal"
                )
            else:
                action = "adjust_campaign"
                message = (
                    f"Conversion rate {avg_conv_rate:.2%} is critical — "
                    "recommend aggressive channel/demographic pivot"
                )

        return {
            "tier": tier,
            "traction": traction.value,
            "avg_conversion_rate": round(avg_conv_rate, 4),
            "action": action,
            "message": message,
            "recent_periods": len(recent),
            "total_adjustments": len(tc.adjustments),
        }

    # ------------------------------------------------------------------
    # Auto-adjust campaigns
    # ------------------------------------------------------------------

    def adjust_campaign(self, tier: str) -> Optional[CampaignAdjustment]:
        """Automatically pivot channels and demographics for a tier.

        Rotates in alternate channels/demographics from the pivot pool
        while preserving any channels that are still performing.
        """
        with self._lock:
            tc = self._campaigns.get(tier)
            if tc is None:
                return None

            pivot = _PIVOT_OPTIONS.get(tier, {})
            old_channels = list(tc.channels)
            old_demographics = list(tc.demographics)
            old_messaging = tc.messaging

            # Rotate: swap in pivot options, keep 1 original channel
            new_channels = pivot.get("channels", old_channels)
            if old_channels:
                # Keep first original channel for continuity
                new_channels = [old_channels[0]] + [
                    c for c in new_channels if c != old_channels[0]
                ][:3]

            new_demographics = pivot.get("demographics", old_demographics)

            # Build adjusted messaging
            default_cfg = _DEFAULT_TIER_CAMPAIGNS.get(tier, {})
            new_messaging = default_cfg.get("messaging", old_messaging)
            if len(tc.adjustments) > 0:
                new_messaging = f"[Adjusted v{len(tc.adjustments) + 1}] {new_messaging}"

            adjustment = CampaignAdjustment(
                adjustment_id=f"adj-{uuid.uuid4().hex[:8]}",
                tier=tier,
                reason="Low traction detected — pivoting channels and demographics",
                old_channels=old_channels,
                new_channels=new_channels,
                old_demographics=old_demographics,
                new_demographics=new_demographics,
                old_messaging=old_messaging,
                new_messaging=new_messaging,
            )

            tc.channels = new_channels
            tc.demographics = new_demographics
            tc.messaging = new_messaging
            tc.status = TierCampaignStatus.ADJUSTING
            capped_append(tc.adjustments, adjustment, max_size=100)

            self._log_event("campaign_adjusted", tier, adjustment.to_dict())
            return adjustment

    # ------------------------------------------------------------------
    # Paid advertising proposals (HITL-gated)
    # ------------------------------------------------------------------

    def propose_paid_campaign(
        self,
        tier: str,
        proposed_budget_usd: float,
    ) -> Optional[PaidAdProposal]:
        """Generate a paid-advertising proposal requiring founder approval.

        The system builds a market strategy rationale based on current
        performance data and projects ROI from the tier's economics.
        """
        with self._lock:
            tc = self._campaigns.get(tier)
            if tc is None:
                return None

            # Build strategy from performance data
            total_imp = sum(s.impressions for s in tc.snapshots)
            total_leads = tc.total_leads
            total_conv = tc.total_conversions
            adjustments_tried = len(tc.adjustments)

            conv_rate = total_conv / total_leads if total_leads > 0 else 0.0

            # Select paid channels based on tier
            paid_channels = self._select_paid_channels(tier)
            target_demos = self._select_paid_demographics(tier)

            # Project ROI: conservative estimate based on improved reach
            projected_new_leads = int(proposed_budget_usd * 0.5)  # ~$2/lead
            projected_conversions = max(1, int(projected_new_leads * max(conv_rate, 0.02)))

            # Revenue lookup per tier (single source of truth)
            revenue_per_conversion = _DEFAULT_TIER_REVENUES.get(tier, 50.0) * 12  # Annual
            projected_revenue = projected_conversions * revenue_per_conversion
            projected_roi = (
                projected_revenue / proposed_budget_usd
                if proposed_budget_usd > 0 else 0.0
            )

            rationale = (
                f"Tier '{tier}' has had {adjustments_tried} organic adjustments "
                f"with {total_imp:,} impressions, {total_leads:,} leads, "
                f"and {total_conv:,} conversions ({conv_rate:.2%} rate). "
                f"Organic channels exhausted — paid advertising recommended "
                f"to accelerate tier fill."
            )

            market_strategy = (
                f"STRATEGY: Allocate ${proposed_budget_usd:,.0f} across "
                f"{', '.join(paid_channels)} targeting {', '.join(target_demos)}. "
                f"Projected {projected_new_leads:,} new leads → "
                f"{projected_conversions:,} conversions → "
                f"${projected_revenue:,.0f} annual revenue "
                f"({projected_roi:.1f}x ROI). "
                f"Based on current funnel data and {adjustments_tried} failed "
                f"organic pivots. Requires founder approval before execution."
            )

            proposal = PaidAdProposal(
                proposal_id=f"paid-{uuid.uuid4().hex[:8]}",
                tier=tier,
                proposed_budget_usd=proposed_budget_usd,
                proposed_channels=paid_channels,
                target_demographics=target_demos,
                rationale=rationale,
                projected_roi=projected_roi,
                market_strategy=market_strategy,
            )

            capped_append(tc.proposals, proposal, max_size=50)
            tc.status = TierCampaignStatus.PENDING_APPROVAL

            self._log_event("paid_ad_proposed", tier, {
                "proposal_id": proposal.proposal_id,
                "budget": proposed_budget_usd,
                "projected_roi": projected_roi,
                "requires": "founder_hitl_approval",
            })

            return proposal

    def approve_proposal(
        self,
        tier: str,
        proposal_id: str,
        approved_by: str,
    ) -> Optional[PaidAdProposal]:
        """Founder approves a paid-ad proposal (HITL gate)."""
        with self._lock:
            tc = self._campaigns.get(tier)
            if tc is None:
                return None
            for p in tc.proposals:
                if p.proposal_id == proposal_id and p.status == ProposalStatus.PENDING:
                    p.status = ProposalStatus.APPROVED
                    p.approved_by = approved_by
                    p.approved_at = datetime.now(timezone.utc).isoformat()
                    tc.status = TierCampaignStatus.ACTIVE
                    self._log_event("paid_ad_approved", tier, {
                        "proposal_id": proposal_id,
                        "approved_by": approved_by,
                    })
                    return p
        return None

    def reject_proposal(
        self,
        tier: str,
        proposal_id: str,
        reason: str = "",
    ) -> Optional[PaidAdProposal]:
        """Founder rejects a paid-ad proposal."""
        with self._lock:
            tc = self._campaigns.get(tier)
            if tc is None:
                return None
            for p in tc.proposals:
                if p.proposal_id == proposal_id and p.status == ProposalStatus.PENDING:
                    p.status = ProposalStatus.REJECTED
                    p.rejection_reason = reason
                    tc.status = TierCampaignStatus.ACTIVE
                    self._log_event("paid_ad_rejected", tier, {
                        "proposal_id": proposal_id,
                        "reason": reason,
                    })
                    return p
        return None

    # ------------------------------------------------------------------
    # Evaluate all tiers and take action
    # ------------------------------------------------------------------

    def evaluate_and_act(self) -> Dict[str, Any]:
        """Evaluate all tier campaigns and take automatic action.

        For each tier:
          - If healthy: maintain
          - If low/critical with adjustments left: auto-adjust
          - If critical after max adjustments: propose paid ads

        Returns a summary of all actions taken.
        """
        results: Dict[str, Any] = {}
        tiers = list(self._campaigns.keys())

        for tier in tiers:
            eval_result = self.evaluate_traction(tier)
            if eval_result is None:
                continue

            action = eval_result.get("action", "maintain")
            entry: Dict[str, Any] = {"evaluation": eval_result}

            if action == "adjust_campaign":
                adj = self.adjust_campaign(tier)
                entry["adjustment"] = adj.to_dict() if adj else None
            elif action == "propose_paid_ads":
                # Propose paid campaign — budget = 10x monthly tier revenue
                tier_rev = {
                    "community": 500, "pro": 2000, "enterprise": 5000,
                    "creator_starter": 1000, "creator_pro": 2000,
                }
                budget = tier_rev.get(tier, 1000)
                proposal = self.propose_paid_campaign(tier, budget)
                entry["proposal"] = proposal.to_dict() if proposal else None

            results[tier] = entry

        return results

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_campaign(self, tier: str) -> Optional[Dict[str, Any]]:
        """Get full campaign state for a tier."""
        with self._lock:
            tc = self._campaigns.get(tier)
            return tc.to_dict() if tc else None

    def get_all_campaigns(self) -> Dict[str, Dict[str, Any]]:
        """Get all tier campaign summaries."""
        with self._lock:
            return {t: tc.to_dict() for t, tc in self._campaigns.items()}

    def get_proposals(
        self,
        status: Optional[ProposalStatus] = None,
    ) -> List[Dict[str, Any]]:
        """Get all paid-ad proposals, optionally filtered by status."""
        proposals: List[Dict[str, Any]] = []
        with self._lock:
            for tc in self._campaigns.values():
                for p in tc.proposals:
                    if status is None or p.status == status:
                        proposals.append(p.to_dict())
        return proposals

    def get_pending_approvals(self) -> List[Dict[str, Any]]:
        """Convenience: get all proposals awaiting founder approval."""
        return self.get_proposals(status=ProposalStatus.PENDING)

    def get_status(self) -> Dict[str, Any]:
        """System status summary."""
        with self._lock:
            total_adjustments = sum(
                len(tc.adjustments) for tc in self._campaigns.values()
            )
            total_proposals = sum(
                len(tc.proposals) for tc in self._campaigns.values()
            )
            pending = sum(
                1 for tc in self._campaigns.values()
                for p in tc.proposals if p.status == ProposalStatus.PENDING
            )
        return {
            "tier_campaign_count": len(self._campaigns),
            "total_adjustments": total_adjustments,
            "total_proposals": total_proposals,
            "pending_approvals": pending,
            "event_log_count": len(self._event_log),
        }

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _select_paid_channels(self, tier: str) -> List[str]:
        """Select appropriate paid channels based on tier."""
        channel_map = {
            "community": ["github_sponsors", "dev_newsletter_ads", "hackathon_sponsorship"],
            "pro": ["google_ads", "linkedin_ads", "facebook_ads"],
            "enterprise": ["linkedin_enterprise_ads", "industry_publication_ads", "trade_show_sponsorship"],
            "creator_starter": ["tiktok_ads", "instagram_ads", "youtube_pre_roll"],
            "creator_pro": ["youtube_ads", "linkedin_ads", "podcast_sponsorship"],
        }
        return channel_map.get(tier, ["google_ads", "linkedin_ads"])

    def _select_paid_demographics(self, tier: str) -> List[str]:
        """Select target demographics for paid campaigns."""
        demo_map = {
            "community": ["developers_25_45", "open_source_maintainers", "tech_students"],
            "pro": ["smb_decision_makers", "startup_cto", "ops_directors"],
            "enterprise": ["fortune_500_it", "vp_engineering", "ciso_compliance"],
            "creator_starter": ["gen_z_creators", "side_hustle_operators", "micro_influencers"],
            "creator_pro": ["top_1pct_creators", "talent_agencies", "mcn_executives"],
        }
        return demo_map.get(tier, ["business_professionals"])

    def _log_event(self, action: str, tier: str, details: Dict[str, Any]) -> None:
        """Append an audit event."""
        event = {
            "action": action,
            "tier": tier,
            "details": details,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        capped_append(self._event_log, event, max_size=10_000)
        logger.info("AdaptiveCampaign: %s for tier=%s", action, tier)
