"""
PATCH-177: Automation Pre-Fight Engine — automation_prefight.py

Pre-fight is the intelligence gate that runs BEFORE any browser automation task.
It answers one question: "Which engine should handle this, and why?"

Decision tree:
  1. Probe target URL → detect captcha type
  2. Check engine availability (GhostController CDP, Playwright)
  3. Apply routing rules based on captcha type + engine capability matrix
  4. Return: AutomationMethod + confidence + rationale

Routing rules (in priority order):
  ├── hCaptcha present               → GHOST (CDP/real JS — hCaptcha token valid)
  ├── Cloudflare Turnstile present   → GHOST (real browser fingerprint needed)
  ├── reCAPTCHA v2/v3 present        → PLAYWRIGHT (audio fallback + stealth JS)
  ├── No captcha detected            → PLAYWRIGHT (faster, more reliable selectors)
  ├── Ghost unavailable              → PLAYWRIGHT (fallback)
  └── Both unavailable               → HITL_ESCALATE (human takes over)

Why this split:
  GhostController (CDP):
    - Drives a real Chromium process via DevTools Protocol
    - hCaptcha token is generated by real in-browser JS → passes validation
    - No Playwright fingerprint markers → harder to detect as bot
    - Slower to launch, heavier resource usage
    - Best for: Stripe, sites with hCaptcha, fingerprint-heavy targets

  Playwright:
    - Clean API, stealth JS patches (navigator.webdriver=false)
    - Better at DOM selector reliability and form filling
    - Audio CAPTCHA fallback for reCAPTCHA
    - Faster cold start
    - Best for: sites with reCAPTCHA or no captcha, form-heavy flows

Murphy's Law applied: Never let the wrong tool try first.
If the probe fails, assume the worst captcha scenario.
"""
from __future__ import annotations

import logging
import time
import urllib.request
import urllib.error
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Optional, Tuple

logger = logging.getLogger(__name__)

# ── Engine availability (checked once at import) ──────────────────────────

def _check_playwright() -> bool:
    try:
        from playwright.async_api import async_playwright  # noqa
        import os
        chromium = "/opt/Murphy-System/.cache/ms-playwright/chromium-1217/chrome-linux64/chrome"
        return os.path.exists(chromium)
    except ImportError:
        return False


def _check_ghost() -> bool:
    """Ghost = GhostBrowser (CDP) or GhostDesktopRunner (native automation)."""
    try:
        from murphy_native_automation import GhostDesktopRunner  # noqa
        return True
    except ImportError:
        pass
    try:
        from ghost_stripe_signup import GhostStripeSignup  # noqa
        return True
    except ImportError:
        pass
    return False


_PLAYWRIGHT_AVAILABLE: bool = _check_playwright()
_GHOST_AVAILABLE: bool = _check_ghost()


# ── Enums ──────────────────────────────────────────────────────────────────

class AutomationMethod(str, Enum):
    """The selected automation engine."""
    GHOST       = "ghost"        # CDP/real Chromium — GhostController
    PLAYWRIGHT  = "playwright"   # Playwright headless — stealth patched
    HITL        = "hitl"         # Escalate to human — no engine can handle


class CaptchaProfile(str, Enum):
    """Captcha presence detected on target page."""
    NONE                = "none"
    HCAPTCHA            = "hcaptcha"
    RECAPTCHA_V2        = "recaptcha_v2"
    RECAPTCHA_V3        = "recaptcha_v3"
    CLOUDFLARE_TURNSTILE = "cloudflare_turnstile"
    GENERIC             = "generic"
    PROBE_FAILED        = "probe_failed"   # Couldn't reach URL — assume worst


# ── Data classes ───────────────────────────────────────────────────────────

@dataclass
class PreFightProbe:
    """Result of probing the target URL."""
    url: str
    reachable: bool
    captcha_profile: CaptchaProfile
    status_code: int = 0
    probe_time_ms: float = 0.0
    raw_signatures: list = field(default_factory=list)
    error: Optional[str] = None


@dataclass
class PreFightDecision:
    """
    The routing decision produced by the pre-fight engine.

    method:         Which engine to use
    captcha:        What was detected on the target
    confidence:     0.0–1.0 — how confident the routing decision is
    rationale:      Human-readable explanation (for HITL / logging)
    ghost_ok:       Is GhostController available?
    playwright_ok:  Is Playwright available?
    probe:          Raw probe data
    """
    method: AutomationMethod
    captcha: CaptchaProfile
    confidence: float
    rationale: str
    ghost_ok: bool
    playwright_ok: bool
    probe: Optional[PreFightProbe] = None


# ── Captcha signatures (ordered by specificity) ──────────────────────────

_CAPTCHA_SIGS: Dict[CaptchaProfile, list] = {
    CaptchaProfile.CLOUDFLARE_TURNSTILE: [
        "challenges.cloudflare.com",
        "cf-turnstile",
        "turnstile/v0/api.js",
        "cf_clearance",
    ],
    CaptchaProfile.HCAPTCHA: [
        "hcaptcha.com/1/api.js",
        "h-captcha",
        "data-hcaptcha-sitekey",
        "hcaptcha.com",
    ],
    CaptchaProfile.RECAPTCHA_V3: [
        "grecaptcha.execute",
        "recaptcha/api.js?render=",
        "g-recaptcha-response",
    ],
    CaptchaProfile.RECAPTCHA_V2: [
        "g-recaptcha",
        "www.google.com/recaptcha",
        "recaptcha/api.js",
        "data-sitekey",
    ],
    CaptchaProfile.GENERIC: [
        "captcha",
        "i am not a robot",
        "bot check",
        "prove you're human",
        "security check",
    ],
}

_PRIORITY_ORDER = [
    CaptchaProfile.CLOUDFLARE_TURNSTILE,
    CaptchaProfile.HCAPTCHA,
    CaptchaProfile.RECAPTCHA_V3,
    CaptchaProfile.RECAPTCHA_V2,
    CaptchaProfile.GENERIC,
]


def _detect_captcha(html: str) -> Tuple[CaptchaProfile, list]:
    """Scan HTML for captcha signatures. Returns (type, matched_signatures)."""
    lower = html.lower()
    for ctype in _PRIORITY_ORDER:
        matched = [sig for sig in _CAPTCHA_SIGS[ctype] if sig.lower() in lower]
        if matched:
            return ctype, matched
    return CaptchaProfile.NONE, []


# ── URL probe ─────────────────────────────────────────────────────────────

def probe_url(url: str, timeout: float = 8.0) -> PreFightProbe:
    """
    Fetch the target URL and detect captcha profile.
    Uses a real browser user-agent to get the actual page JS/HTML,
    not a bot-filtered version.
    """
    t0 = time.monotonic()
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            html = resp.read(65536).decode("utf-8", errors="ignore")
            status = resp.status
    except urllib.error.HTTPError as e:
        # 4xx/5xx still gives us HTML — read it for captcha detection
        try:
            html = e.read(32768).decode("utf-8", errors="ignore")
            status = e.code
        except Exception:
            html = ""
            status = e.code
    except Exception as exc:
        elapsed = (time.monotonic() - t0) * 1000
        return PreFightProbe(
            url=url,
            reachable=False,
            captcha_profile=CaptchaProfile.PROBE_FAILED,
            probe_time_ms=round(elapsed, 1),
            error=str(exc),
        )

    elapsed = (time.monotonic() - t0) * 1000
    captcha, sigs = _detect_captcha(html)

    return PreFightProbe(
        url=url,
        reachable=True,
        captcha_profile=captcha,
        status_code=status,
        probe_time_ms=round(elapsed, 1),
        raw_signatures=sigs,
    )


# ── Routing engine ────────────────────────────────────────────────────────

def select_method(probe: PreFightProbe) -> PreFightDecision:
    """
    PATCH-177: Core routing logic.

    Apply the capability matrix:
      captcha type × engine availability → AutomationMethod + rationale

    GhostController advantages:
      - hCaptcha: real browser JS generates valid token (Playwright fake → blocked)
      - Cloudflare Turnstile: real fingerprint passes auto-challenge
      - No webdriver marker in CDP mode

    Playwright advantages:
      - reCAPTCHA: audio fallback + STT works better
      - No captcha: faster, cleaner selectors, easier error handling
      - Better retry/timeout semantics for form flows
    """
    ghost_ok = _GHOST_AVAILABLE
    pw_ok    = _PLAYWRIGHT_AVAILABLE
    cap      = probe.captcha_profile

    # ── Neither engine available → HITL ──────────────────────────────────
    if not ghost_ok and not pw_ok:
        return PreFightDecision(
            method=AutomationMethod.HITL,
            captcha=cap,
            confidence=1.0,
            rationale=(
                "HITL escalation: neither GhostController nor Playwright is available. "
                "Human must complete this task manually."
            ),
            ghost_ok=ghost_ok,
            playwright_ok=pw_ok,
            probe=probe,
        )

    # ── Probe failed → conservative: use Ghost if available ──────────────
    if cap == CaptchaProfile.PROBE_FAILED:
        if ghost_ok:
            return PreFightDecision(
                method=AutomationMethod.GHOST,
                captcha=cap,
                confidence=0.55,
                rationale=(
                    f"URL probe failed ({probe.error}) — assuming worst-case captcha. "
                    "GhostController selected as conservative choice (real browser fingerprint)."
                ),
                ghost_ok=ghost_ok,
                playwright_ok=pw_ok,
                probe=probe,
            )
        return PreFightDecision(
            method=AutomationMethod.PLAYWRIGHT,
            captcha=cap,
            confidence=0.45,
            rationale=(
                f"URL probe failed ({probe.error}) — GhostController unavailable. "
                "Playwright fallback with stealth JS."
            ),
            ghost_ok=ghost_ok,
            playwright_ok=pw_ok,
            probe=probe,
        )

    # ── hCaptcha → Ghost required ─────────────────────────────────────────
    if cap == CaptchaProfile.HCAPTCHA:
        if ghost_ok:
            return PreFightDecision(
                method=AutomationMethod.GHOST,
                captcha=cap,
                confidence=0.92,
                rationale=(
                    "hCaptcha detected. GhostController selected: real Chromium CDP allows "
                    "hCaptcha JS to generate a genuine h-captcha-response token. "
                    "Playwright's fake browser context would be rejected by hCaptcha's JS fingerprint check."
                ),
                ghost_ok=ghost_ok,
                playwright_ok=pw_ok,
                probe=probe,
            )
        # Ghost unavailable — Playwright will likely fail but it's the only option
        return PreFightDecision(
            method=AutomationMethod.PLAYWRIGHT,
            captcha=cap,
            confidence=0.30,
            rationale=(
                "hCaptcha detected but GhostController is unavailable. "
                "Playwright fallback — WARNING: hCaptcha may block headless browser. "
                "Human override recommended."
            ),
            ghost_ok=ghost_ok,
            playwright_ok=pw_ok,
            probe=probe,
        )

    # ── Cloudflare Turnstile → Ghost preferred ────────────────────────────
    if cap == CaptchaProfile.CLOUDFLARE_TURNSTILE:
        if ghost_ok:
            return PreFightDecision(
                method=AutomationMethod.GHOST,
                captcha=cap,
                confidence=0.85,
                rationale=(
                    "Cloudflare Turnstile detected. GhostController selected: real browser "
                    "fingerprint (TLS, canvas, fonts) passes the auto-challenge. "
                    "Playwright's Chromium may fail the bot fingerprint check."
                ),
                ghost_ok=ghost_ok,
                playwright_ok=pw_ok,
                probe=probe,
            )
        return PreFightDecision(
            method=AutomationMethod.PLAYWRIGHT,
            captcha=cap,
            confidence=0.50,
            rationale=(
                "Cloudflare Turnstile detected. GhostController unavailable — "
                "Playwright with stealth JS will attempt auto-pass (may fail)."
            ),
            ghost_ok=ghost_ok,
            playwright_ok=pw_ok,
            probe=probe,
        )

    # ── reCAPTCHA v2/v3 → Playwright preferred ───────────────────────────
    if cap in (CaptchaProfile.RECAPTCHA_V2, CaptchaProfile.RECAPTCHA_V3):
        if pw_ok:
            return PreFightDecision(
                method=AutomationMethod.PLAYWRIGHT,
                captcha=cap,
                confidence=0.80,
                rationale=(
                    f"{cap.value} detected. Playwright selected: audio CAPTCHA fallback + "
                    "stealth navigator.webdriver patch works well for reCAPTCHA. "
                    "GhostController's OCR-based audio click is less reliable here."
                ),
                ghost_ok=ghost_ok,
                playwright_ok=pw_ok,
                probe=probe,
            )
        return PreFightDecision(
            method=AutomationMethod.GHOST,
            captcha=cap,
            confidence=0.55,
            rationale=(
                f"{cap.value} detected. Playwright unavailable — GhostController fallback. "
                "Audio CAPTCHA via OCR will be attempted."
            ),
            ghost_ok=ghost_ok,
            playwright_ok=pw_ok,
            probe=probe,
        )

    # ── No captcha / generic → Playwright preferred ──────────────────────
    if pw_ok:
        return PreFightDecision(
            method=AutomationMethod.PLAYWRIGHT,
            captcha=cap,
            confidence=0.95,
            rationale=(
                f"No significant captcha detected (profile={cap.value}). "
                "Playwright selected: faster cold start, clean selector API, "
                "reliable form filling with human typing simulation."
            ),
            ghost_ok=ghost_ok,
            playwright_ok=pw_ok,
            probe=probe,
        )
    return PreFightDecision(
        method=AutomationMethod.GHOST,
        captcha=cap,
        confidence=0.85,
        rationale=(
            f"No significant captcha (profile={cap.value}). "
            "GhostController selected (Playwright unavailable)."
        ),
        ghost_ok=ghost_ok,
        playwright_ok=pw_ok,
        probe=probe,
    )


# ── Public API ────────────────────────────────────────────────────────────

def run_prefight(url: str, timeout: float = 8.0) -> PreFightDecision:
    """
    PATCH-177: Entry point for all browser automation tasks.

    1. Probe the target URL
    2. Detect captcha type
    3. Route to the best available engine
    4. Return decision with rationale

    Usage:
        decision = run_prefight("https://dashboard.stripe.com/register")
        if decision.method == AutomationMethod.GHOST:
            # use GhostStripeSignup / GhostController CDP
        elif decision.method == AutomationMethod.PLAYWRIGHT:
            # use PlaywrightSignupRunner
        else:
            # HITL escalate
    """
    logger.info("PATCH-177: pre-fight probe starting for %s", url)
    probe = probe_url(url, timeout=timeout)
    decision = select_method(probe)

    logger.info(
        "PATCH-177: pre-fight result — url=%s captcha=%s method=%s confidence=%.2f | %s",
        url,
        decision.captcha.value,
        decision.method.value,
        decision.confidence,
        decision.rationale[:80],
    )
    return decision


def prefight_status() -> dict:
    """Return engine availability for healthcheck / dashboard display."""
    return {
        "ghost_controller": _GHOST_AVAILABLE,
        "playwright": _PLAYWRIGHT_AVAILABLE,
        "engines_available": sum([_GHOST_AVAILABLE, _PLAYWRIGHT_AVAILABLE]),
        "routing_active": True,
        "patch": "PATCH-177",
    }
