"""Demo Deliverable Generator for Murphy System.

Generates branded, downloadable .txt deliverables for the "Try Murphy Now"
demo. Predefined scenarios use rich templates; custom queries are routed
through the onboard LLM (LocalLLMFallback as the always-available safety net).

License: BSL 1.1 — Inoni LLC / Corey Post
"""
from __future__ import annotations

import hashlib
import re
from datetime import datetime, timezone
from typing import Any, Dict, Optional

# ---------------------------------------------------------------------------
# Branding constants
# ---------------------------------------------------------------------------

_MURPHY_ASCII_LOGO = r"""╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║    ███╗   ███╗██╗   ██╗██████╗ ██████╗ ██╗  ██╗██╗   ██╗           ║
║    ████╗ ████║██║   ██║██╔══██╗██╔══██╗██║  ██║╚██╗ ██╔╝           ║
║    ██╔████╔██║██║   ██║██████╔╝██████╔╝███████║ ╚████╔╝            ║
║    ██║╚██╔╝██║██║   ██║██╔══██╗██╔═══╝ ██╔══██║  ╚██╔╝             ║
║    ██║ ╚═╝ ██║╚██████╔╝██║  ██║██║     ██║  ██║   ██║              ║
║    ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝   ╚═╝              ║
║                                                                      ║
║                       S Y S T E M                                    ║
║                                                                      ║
║              Generated by Murphy System — murphy.systems             ║
║           © 2025 Inoni Limited Liability Company (Corey Post)        ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝"""

_LICENSE_FOOTER = """═══════════════════════════════════════════════════════════════════════

  LICENSE NOTICE — THIS SECTION MAY NOT BE REMOVED

  This deliverable was generated by Murphy System, a product of
  Inoni Limited Liability Company. The OUTPUT of this generation
  is provided under the Apache License, Version 1.0.

  Licensed under the Apache License, Version 1.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-1.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
  either express or implied.

  Murphy System itself is licensed under BSL 1.1.
  See https://github.com/IKNOWINOT/Murphy-System/blob/main/LICENSE

  © 2025 Inoni Limited Liability Company (Corey Post)
  https://murphy.systems

═══════════════════════════════════════════════════════════════════════"""

# ---------------------------------------------------------------------------
# Predefined scenario templates
# ---------------------------------------------------------------------------

_SCENARIO_TEMPLATES: Dict[str, Dict[str, str]] = {
    "onboarding": {
        "title": "Client Onboarding Package",
        "content": """\
■ SECTION 1 — CLIENT INTAKE CHECKLIST
──────────────────────────────────────
  □  Company legal name and DBA (if applicable)
  □  Primary contact: name, title, email, phone
  □  Billing contact (if different)
  □  Signed Non-Disclosure Agreement (NDA) on file
  □  Completed discovery questionnaire returned
  □  Business goals & success metrics documented
  □  Existing tooling inventory (CRM, ERP, billing)
  □  Timeline expectations confirmed
  □  Budget range approved by stakeholder

■ SECTION 2 — MASTER SERVICE AGREEMENT OUTLINE
────────────────────────────────────────────────
  1.  Scope of Services
      - Murphy System workflow automation (defined in SOW)
      - Integration with client-specified third-party APIs
      - Monthly performance reporting

  2.  Term & Renewal
      - Initial term: 12 months from execution date
      - Auto-renews annually unless 30-day written notice

  3.  Fees & Payment
      - Monthly retainer: as per attached SOW
      - Net-30 payment terms; 1.5 % monthly late fee
      - Expenses reimbursed at cost + 10 % admin fee

  4.  Intellectual Property
      - Client owns all data inputs and outputs
      - Murphy System retains ownership of platform IP

  5.  Confidentiality, Data Security & Compliance
      - BSL-1.1 platform; Apache 1.0 deliverable outputs
      - SOC 2 Type II controls in effect

  6.  Limitation of Liability & Indemnification
  7.  Governing Law & Dispute Resolution (AAA Arbitration)
  8.  Signatures block

■ SECTION 3 — INITIAL INVOICE TEMPLATE
────────────────────────────────────────
  Invoice #:    2091
  Client:       [Client Name]
  Date:         [Today]
  Due Date:     [Today + 30 days]

  ┌─────────────────────────────────────────────┬──────────┐
  │ Description                                 │  Amount  │
  ├─────────────────────────────────────────────┼──────────┤
  │ Onboarding & setup fee                      │ $1,500   │
  │ Month 1 retainer (Murphy System automation) │ $3,000   │
  │ API integration (3 services)                │   $500   │
  ├─────────────────────────────────────────────┼──────────┤
  │ TOTAL DUE                                   │ $5,000   │
  └─────────────────────────────────────────────┴──────────┘

  Payment via: ACH / Wire / Stripe link attached
  Notes: First invoice; subsequent invoices billed on the 1st.

■ SECTION 4 — CRM SETUP STEPS
───────────────────────────────
  Step 1: Create contact record in HubSpot / CRM of choice
    - Fields: Full name, company, email, phone, pipeline stage
  Step 2: Assign to pipeline: "Active Clients"
  Step 3: Set follow-up task: 7-day check-in call
  Step 4: Tag: onboarding_2025, murphy_automated
  Step 5: Link invoice #2091 to contact record
  Step 6: Enable deal tracking; set expected close: Month 3

■ SECTION 5 — PROJECT BOARD TASK LIST (14 TASKS)
──────────────────────────────────────────────────
  Sprint 1 — Foundation (Week 1–2)
    [P1] ✦  API credentials collection & vault storage
    [P1] ✦  Murphy workflow installation & environment setup
    [P2] ✦  CRM integration test (read/write contact records)
    [P2] ✦  Billing integration test (create/send invoice)

  Sprint 2 — Automation Build (Week 3–4)
    [P1] ✦  Onboarding workflow: intake → contract → invoice
    [P1] ✦  Notification routing (email + Slack alerts)
    [P2] ✦  Reporting dashboard configuration
    [P3] ✦  Custom workflow rules per client SLA

  Sprint 3 — QA & Handoff (Week 5–6)
    [P1] ✦  End-to-end workflow test with dummy data
    [P1] ✦  Client UAT session scheduled & completed
    [P2] ✦  Documentation delivered (runbook + API guide)
    [P2] ✦  Training session completed (1 hr)
    [P3] ✦  Go-live approval signed
    [P3] ✦  30-day hypercare period begins
""",
    },
    "finance": {
        "title": "Q3 Finance Report",
        "content": """\
■ SECTION 1 — EXECUTIVE SUMMARY
─────────────────────────────────
  Period:   Q3 2024 (July 1 – September 30)
  Prepared: Murphy System Automated Finance Report

  Q3 performance exceeded plan by 7.3 %. Revenue grew 18 % YoY driven
  by SaaS subscription expansion. Operating expenses remained within
  budget. EBITDA margin improved to 34.1 % (+2.8 pp vs Q2 2024).

  Key Highlights:
  • Net Revenue:   $2,847,000   (+18 % YoY, +6 % QoQ)
  • Gross Profit:  $1,938,000   (68 % margin)
  • EBITDA:        $  971,000   (34.1 % margin)
  • Cash on hand:  $4,120,000   (3.4× monthly burn)

■ SECTION 2 — REVENUE BREAKDOWN
─────────────────────────────────
  ┌────────────────────────────┬───────────┬────────┬──────────┐
  │ Revenue Stream             │   Q3 2024 │  Q3 YoY│ % of Rev │
  ├────────────────────────────┼───────────┼────────┼──────────┤
  │ SaaS Subscriptions         │ $1,850,000│  +22 % │  65.0 %  │
  │ Professional Services      │   $640,000│  +12 % │  22.5 %  │
  │ Integration Fees           │   $285,000│   +8 % │  10.0 %  │
  │ Training & Certification   │    $72,000│   +5 % │   2.5 %  │
  ├────────────────────────────┼───────────┼────────┼──────────┤
  │ TOTAL REVENUE              │ $2,847,000│  +18 % │ 100.0 %  │
  └────────────────────────────┴───────────┴────────┴──────────┘

■ SECTION 3 — EXPENSE CATEGORIZATION
──────────────────────────────────────
  ┌────────────────────────────┬───────────┬──────────┐
  │ Expense Category           │   Amount  │ % of Rev │
  ├────────────────────────────┼───────────┼──────────┤
  │ Cost of Revenue (COGS)     │   $909,000│  31.9 %  │
  │ Sales & Marketing          │   $426,000│  15.0 %  │
  │ Research & Development     │   $341,000│  12.0 %  │
  │ General & Administrative   │   $200,000│   7.0 %  │
  ├────────────────────────────┼───────────┼──────────┤
  │ TOTAL OPERATING EXPENSES   │ $1,876,000│  65.9 %  │
  └────────────────────────────┴───────────┴──────────┘

■ SECTION 4 — 6-MONTH REVENUE FORECAST (Q4 2024 – Q1 2025)
─────────────────────────────────────────────────────────────
  Month         │ Revenue Forecast │ Growth Assumption
  ──────────────┼──────────────────┼───────────────────
  October 2024  │   $   965,000    │ +2.0 % MoM
  November 2024 │   $   985,000    │ +2.1 % MoM
  December 2024 │   $ 1,015,000    │ +3.0 % (seasonal)
  January 2025  │   $   940,000    │ -7.4 % (Jan reset)
  February 2025 │   $   970,000    │ +3.2 % MoM
  March 2025    │   $ 1,010,000    │ +4.1 % MoM
  ──────────────┼──────────────────┼───────────────────
  6-Month Total │   $ 5,885,000    │ +22 % vs H2 2023

■ SECTION 5 — RECOMMENDATIONS
───────────────────────────────
  1. Accelerate SaaS expansion:  Upsell 15 % of PS clients to
     annual subscription by Q4; estimated ARR lift: +$240,000.
  2. Optimise COGS:  Renegotiate 3 cloud vendor contracts; target
     5 % reduction → saves ~$45,000/quarter.
  3. Marketing efficiency:  Redirect 20 % of paid-search budget
     to content/SEO; CAC payback period currently 7.2 months —
     target: 5.5 months by Q1 2025.
  4. R&D focus:  Prioritise AI workflow automation features;
     top 3 prospects cited as primary purchase driver.
  5. Cash management:  Maintain ≥3× monthly burn; consider 6-
     month T-bill ladder for idle reserves.
""",
    },
    "hr": {
        "title": "Candidate Screening Report",
        "content": """\
■ SECTION 1 — CANDIDATE SCORING MATRIX
────────────────────────────────────────
  Role: Senior Product Manager
  Hiring Manager: [Name]   |   Req ID: PM-2024-07

  ┌──────────────────┬───────┬───────┬───────┬───────┬───────┐
  │ Criterion        │ Wt %  │Cand A │Cand B │Cand C │Cand D │
  ├──────────────────┼───────┼───────┼───────┼───────┼───────┤
  │ Domain expertise │  25 % │  4/5  │  5/5  │  3/5  │  4/5  │
  │ Leadership exp.  │  20 % │  5/5  │  4/5  │  4/5  │  3/5  │
  │ Data & analytics │  20 % │  4/5  │  4/5  │  5/5  │  3/5  │
  │ Communication    │  15 % │  5/5  │  4/5  │  4/5  │  4/5  │
  │ Culture fit      │  10 % │  4/5  │  5/5  │  3/5  │  5/5  │
  │ Compensation fit │  10 % │  5/5  │  3/5  │  5/5  │  4/5  │
  ├──────────────────┼───────┼───────┼───────┼───────┼───────┤
  │ WEIGHTED SCORE   │ 100 % │ 4.55  │ 4.25  │ 3.90  │ 3.75  │
  │ RANK             │       │  #1   │  #2   │  #3   │  #4   │
  └──────────────────┴───────┴───────┴───────┴───────┴───────┘

■ SECTION 2 — SKILLS ASSESSMENT SUMMARY
─────────────────────────────────────────
  Candidate A — ★★★★★ RECOMMENDED
    Strengths:  8 years PM at SaaS; shipped 3 products >$10M ARR;
                SQL proficient; led cross-functional teams of 12+.
    Gaps:       No formal MBA; limited enterprise sales exposure.
    Verdict:    Strong hire. Offer within band.

  Candidate B — ★★★★☆ STRONG ALTERNATE
    Strengths:  FAANG background; exceptional strategic vision;
                excellent culture alignment scores.
    Gaps:       Compensation expectations 15 % above band.
    Verdict:    Good backup. Negotiate or flag for future req.

  Candidate C — ★★★☆☆ CONDITIONAL
    Strengths:  Deep analytics; strong data science background.
    Gaps:       Limited stakeholder management; no leadership exp.
    Verdict:    Better fit for Sr. Analyst role. Redirect.

  Candidate D — ★★★☆☆ NOT RECOMMENDED
    Strengths:  Great culture fit; enthusiastic.
    Gaps:       2 years experience; significant skill gap for Sr. level.
    Verdict:    Revisit in 12–18 months with growth.

■ SECTION 3 — STRUCTURED INTERVIEW QUESTIONS
──────────────────────────────────────────────
  Round 1 — Screening (30 min, Recruiter)
    Q1. Walk me through your product development process.
    Q2. Describe a product you own end-to-end. What was the outcome?
    Q3. How do you prioritize a backlog with competing stakeholders?

  Round 2 — Technical (60 min, Engineering Lead)
    Q4. Given a drop in a key metric, how do you diagnose root cause?
    Q5. Describe a data-driven decision you made and its impact.
    Q6. How do you write a PRD? Walk us through a recent example.

  Round 3 — Leadership (45 min, VP Product)
    Q7. Tell me about a time you influenced without authority.
    Q8. How have you managed conflict in cross-functional teams?
    Q9. What's your product vision for our space in 3 years?

■ SECTION 4 — RECOMMENDATION SUMMARY
──────────────────────────────────────
  Proceed to offer:  Candidate A
  Backup:            Candidate B (pending compensation discussion)
  Next steps:
    □  Reference checks: 3 professional references (48 hrs)
    □  Background screening: employment + education verification
    □  Offer letter: draft within 2 business days of ref clearance
    □  Target start date: 3 weeks from offer acceptance
""",
    },
    "compliance": {
        "title": "Compliance Audit Report",
        "content": """\
■ SECTION 1 — COMPLIANCE CHECKLIST
─────────────────────────────────────
  Framework:  SOC 2 Type II + GDPR + ISO 27001 (Partial)
  Audit date: [Today]
  Scope:      Data processing systems, access controls, logging

  Access Controls
    [✓] Multi-factor authentication enforced (all users)
    [✓] Role-based access control (RBAC) implemented
    [✓] Privileged access management (PAM) — quarterly review
    [✗] Least-privilege review not completed this quarter  ← FINDING

  Data Protection
    [✓] Data encrypted at rest (AES-256)
    [✓] Data encrypted in transit (TLS 1.3)
    [✓] GDPR Article 30 processing register up to date
    [✗] Data retention schedules not fully documented      ← FINDING

  Incident Response
    [✓] IR plan documented and approved
    [✓] Tabletop exercise completed (Q2)
    [✗] IR plan not tested with full runbook walkthrough   ← FINDING

  Vendor Management
    [✓] Third-party vendor risk assessments on file
    [✓] DPA agreements signed for all data processors
    [✓] Annual vendor re-certification completed

  Logging & Monitoring
    [✓] Centralised SIEM configured (Splunk / ELK)
    [✓] Anomaly detection alerts active
    [✓] Log retention ≥12 months confirmed

■ SECTION 2 — FINDINGS MATRIX
───────────────────────────────
  ┌─────┬────────────────────────────────────┬──────────┬──────────┐
  │ ID  │ Finding                            │ Severity │  Owner   │
  ├─────┼────────────────────────────────────┼──────────┼──────────┤
  │ F-1 │ Least-privilege review overdue     │ MEDIUM   │ IT Ops   │
  │ F-2 │ Data retention policy gaps         │ HIGH     │ Legal    │
  │ F-3 │ IR plan not fully tested           │ MEDIUM   │ SecOps   │
  └─────┴────────────────────────────────────┴──────────┴──────────┘

■ SECTION 3 — RISK ASSESSMENT
───────────────────────────────
  Residual Risk Level:  MEDIUM  (target: LOW by Q1 2025)

  Risk F-2 (Data Retention) — HIGH
    Current state: Retention schedules exist for primary DBs but
    not for backup/archive systems or 3rd-party integrations.
    Potential impact: GDPR Article 5(e) violation; fines up to 4 %
    of global turnover. Reputational damage.
    Likelihood: LOW (no breach indicators)
    Risk score: 6/10

  Risk F-1 (Least Privilege) — MEDIUM
    Current state: RBAC in place; access review last run 5 months ago.
    Potential impact: Insider threat or account compromise could
    escalate privileges beyond required scope.
    Risk score: 4/10

  Risk F-3 (IR Plan Test) — MEDIUM
    Current state: Plan documented; tabletop done in Q2 but no
    full-runbook exercise completed this calendar year.
    Risk score: 3/10

■ SECTION 4 — REMEDIATION TIMELINE
─────────────────────────────────────
  Finding │ Action Required                        │ Due Date   │ Status
  ────────┼────────────────────────────────────────┼────────────┼─────────
  F-1     │ Complete least-privilege access review  │ +2 weeks   │ Assigned
  F-2     │ Document retention for backup/archive   │ +4 weeks   │ In flight
  F-2     │ Obtain DPA confirmation from 3 vendors  │ +3 weeks   │ Pending
  F-3     │ Schedule & complete IR runbook exercise │ +6 weeks   │ Scheduled
""",
    },
    "project": {
        "title": "Project Plan",
        "content": """\
■ SECTION 1 — PROJECT CHARTER
───────────────────────────────
  Project Name:  Murphy System Automation Deployment
  Sponsor:       [Executive Sponsor]
  PM:            [Project Manager]
  Start Date:    [Today]
  Target End:    [Today + 12 weeks]
  Budget:        $48,000
  Priority:      P1 — Strategic

  Objective:
    Deploy Murphy System workflow automation across core business
    functions (onboarding, finance, HR) to reduce manual processing
    time by ≥60 % and achieve ROI within 6 months.

  Success Criteria:
    • 3 automated workflows live and stable in production
    • <2 % error rate on automated tasks
    • Team trained and self-sufficient
    • ROI model validated with actual time-savings data

■ SECTION 2 — MILESTONE TIMELINE
──────────────────────────────────
  Week  1–2  │ ◉ Milestone 1: Environment setup & API credentials
  Week  3–4  │ ◉ Milestone 2: Core workflow development (onboarding)
  Week  5–6  │ ◉ Milestone 3: Finance & HR workflows developed
  Week  7–8  │ ◉ Milestone 4: Internal QA & load testing
  Week  9–10 │ ◉ Milestone 5: UAT with stakeholders
  Week 11    │ ◉ Milestone 6: Production deployment
  Week 12    │ ◉ Milestone 7: Hypercare & KPI review

■ SECTION 3 — RESOURCE ALLOCATION
────────────────────────────────────
  ┌──────────────────────────┬────────────┬──────────┬──────────┐
  │ Resource                 │ Role       │ Allocation│  Weeks   │
  ├──────────────────────────┼────────────┼──────────┼──────────┤
  │ Murphy System Engineer   │ Lead Dev   │  100 %   │  1–10    │
  │ Client IT Lead           │ DevOps     │   50 %   │  1–12    │
  │ Business Analyst         │ Requirements│  75 %   │  1–6     │
  │ QA Engineer              │ Testing    │  100 %   │  7–11    │
  │ Project Manager          │ Governance │   25 %   │  1–12    │
  └──────────────────────────┴────────────┴──────────┴──────────┘

  Budget breakdown:
    Labour (internal):   $30,000 (62 %)
    Murphy System licence: $9,600 (20 %)
    API integrations:    $5,400 (11 %)
    Training & docs:     $3,000 (7 %)

■ SECTION 4 — RISK REGISTER
─────────────────────────────
  ID  │ Risk                        │ Probability │ Impact │ Mitigation
  ────┼─────────────────────────────┼─────────────┼────────┼──────────────────
  R-1 │ API credential delays       │ MEDIUM      │ HIGH   │ Start vendor requests Week 1
  R-2 │ Scope creep                 │ HIGH        │ MEDIUM │ Change control process; weekly PM check-in
  R-3 │ Key-person dependency       │ LOW         │ HIGH   │ Knowledge transfer docs; backup resource identified
  R-4 │ Integration compatibility   │ LOW         │ MEDIUM │ POC in Week 1 before full build begins
  R-5 │ Stakeholder availability    │ MEDIUM      │ MEDIUM │ UAT slots booked in advance; async sign-off options

■ SECTION 5 — RACI MATRIX
───────────────────────────
  Task                      │ PM  │ Dev │ BA  │ QA  │ Sponsor
  ──────────────────────────┼─────┼─────┼─────┼─────┼─────────
  Requirements gathering    │ A   │ C   │ R   │ I   │ I
  Architecture design       │ I   │ R   │ C   │ C   │ A
  Development               │ I   │ R/A │ C   │ C   │ I
  QA & testing              │ I   │ C   │ I   │ R/A │ I
  UAT sign-off              │ C   │ I   │ C   │ I   │ R/A
  Production deployment     │ A   │ R   │ I   │ C   │ I
  Post-launch review        │ R   │ C   │ C   │ C   │ A

  R=Responsible  A=Accountable  C=Consulted  I=Informed
""",
    },
    "invoice": {
        "title": "Invoice Processing Report",
        "content": """\
■ SECTION 1 — PROCESSING SUMMARY
──────────────────────────────────
  Batch ID:      INV-BATCH-2024-Q3-001
  Processed:     [Today]
  Total invoices: 47
  Total value:   $284,750.00

  ┌─────────────────────────────────┬───────┬────────────┐
  │ Status                          │ Count │ Value      │
  ├─────────────────────────────────┼───────┼────────────┤
  │ Approved & queued for payment   │  38   │ $234,200   │
  │ Pending 3-way match             │   5   │  $31,500   │
  │ Exception — requires review     │   3   │  $14,250   │
  │ Duplicate detected & rejected   │   1   │   $4,800   │
  ├─────────────────────────────────┼───────┼────────────┤
  │ TOTAL                           │  47   │ $284,750   │
  └─────────────────────────────────┴───────┴────────────┘

■ SECTION 2 — PAYMENT SCHEDULE
────────────────────────────────
  ┌─────────────────────────┬───────────┬────────────┬─────────────┐
  │ Vendor                  │ Invoice # │ Amount     │ Payment Date│
  ├─────────────────────────┼───────────┼────────────┼─────────────┤
  │ Acme Supplies Co.       │ SI-88421  │  $12,400   │ [+7 days]   │
  │ Cloud Infra Ltd.        │ CI-00391  │  $34,800   │ [+7 days]   │
  │ Marketing Agency X      │ MA-2291   │  $18,000   │ [+14 days]  │
  │ Office Depot            │ OD-77612  │   $1,240   │ [+30 days]  │
  │ [+ 34 more vendors]     │ ...       │ $168,260   │ [Various]   │
  ├─────────────────────────┼───────────┼────────────┼─────────────┤
  │ TOTAL APPROVED          │           │ $234,700   │             │
  └─────────────────────────┴───────────┴────────────┴─────────────┘

  Early-pay discounts captured:  3 invoices × 2 %  = $1,416.00 saved.

■ SECTION 3 — RECONCILIATION REPORT
──────────────────────────────────────
  PO Matching Summary:
    • 3-way match (PO + Receipt + Invoice):  38 of 42 eligible  ✓
    • 2-way match (PO + Invoice only):        4 of 42          △
    • No matching PO found:                   3 invoices       ✗

  GL Coding:
    • Auto-coded by Murphy System:  44 invoices (93.6 %)
    • Requires manual GL code:       3 invoices  (6.4 %)

  Variance Analysis:
    Invoices within ±2 % of PO value: 40 (95 %)
    Invoices >2 % above PO value:      2 (requires approval)

■ SECTION 4 — EXCEPTION LOG
─────────────────────────────
  EX-001 │ INV #SI-88499 │ Vendor: Acme Supplies │ $4,100
    Issue: Invoice amount $200 over PO. Vendor claims
           freight surcharge added post-PO.
    Action: Route to Purchasing for PO amendment or credit memo.
    SLA: Resolve within 5 business days.

  EX-002 │ INV #TK-1122 │ Vendor: Tech Kit Inc. │ $7,350
    Issue: No matching receipt found. Goods may not have arrived.
    Action: Warehouse confirmation requested. Payment on hold.
    SLA: Warehouse response within 48 hrs.

  EX-003 │ INV #MA-2299 │ Vendor: Marketing Agency X │ $2,800
    Issue: Duplicate invoice detected (matches MA-2291 amount
           and date; different invoice number — possible re-submission).
    Action: Vendor contacted; payment withheld pending clarification.
    SLA: Vendor response within 24 hrs.
""",
    },
}

# Scenario keyword → template key mapping
_KEYWORD_MAP = {
    "onboarding": "onboarding",
    "onboard": "onboarding",
    "client": "onboarding",
    "intake": "onboarding",
    "finance": "finance",
    "q3": "finance",
    "quarterly": "finance",
    "revenue": "finance",
    "expense": "finance",
    "forecast": "finance",
    "accounting": "finance",
    "report": "finance",
    "hr": "hr",
    "recruit": "hr",
    "candidate": "hr",
    "hire": "hr",
    "screen": "hr",
    "interview": "hr",
    "resume": "hr",
    "talent": "hr",
    "compliance": "compliance",
    "audit": "compliance",
    "gdpr": "compliance",
    "hipaa": "compliance",
    "soc": "compliance",
    "security": "compliance",
    "risk": "compliance",
    "project": "project",
    "plan": "project",
    "milestone": "project",
    "sprint": "project",
    "timeline": "project",
    "resource": "project",
    "invoice": "invoice",
    "payment": "invoice",
    "billing": "invoice",
    "vendor": "invoice",
    "accounts payable": "invoice",
    "ap ": "invoice",
}


def _detect_scenario(query: str) -> Optional[str]:
    """Return the template key if the query matches a predefined scenario."""
    q = query.lower()
    for keyword, key in _KEYWORD_MAP.items():
        if keyword in q:
            return key
    return None


def _scenario_to_filename(scenario_key: Optional[str], query: str) -> str:
    """Return a safe filename for the deliverable."""
    if scenario_key:
        slugs = {
            "onboarding": "client-onboarding",
            "finance": "q3-finance-report",
            "hr": "candidate-screening",
            "compliance": "compliance-audit",
            "project": "project-plan",
            "invoice": "invoice-processing",
        }
        slug = slugs.get(scenario_key, scenario_key)
    else:
        # Derive slug from first few words of query
        slug = re.sub(r"[^a-z0-9]+", "-", query.lower().strip())[:40].strip("-")
        if not slug:
            slug = "custom-deliverable"
    return f"murphy-{slug}-deliverable.txt"


def build_branded_txt(
    title: str,
    content: str,
    scenario_type: str = "custom",
    quality_score: int = 94,
    generated_at: Optional[str] = None,
) -> str:
    """Wrap content in the full Murphy System branded .txt format."""
    if generated_at is None:
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    meta_block = "\n".join([
        "═" * 71,
        f"  DELIVERABLE: {title}",
        f"  Generated:   {generated_at}",
        f"  Quality:     {quality_score}/100",
        f"  Type:        {scenario_type.replace('_', ' ').title()}",
        "═" * 71,
    ])

    return "\n\n".join([
        _MURPHY_ASCII_LOGO,
        meta_block,
        content.strip(),
        _LICENSE_FOOTER,
    ]) + "\n"


def generate_predefined_deliverable(
    scenario_key: str,
    query: str,
) -> Dict[str, Any]:
    """Return a predefined deliverable for one of the 6 known demo scenarios."""
    template = _SCENARIO_TEMPLATES[scenario_key]
    title = template["title"]
    content = template["content"]
    filename = _scenario_to_filename(scenario_key, query)
    txt = build_branded_txt(title, content, scenario_type=scenario_key)
    return {"title": title, "content": txt, "filename": filename}


def _generate_llm_content(query: str) -> str:
    """Route through the LLM controller cascade; always returns something."""
    # Try async LLM via the synchronous helper first, then fall back to LocalLLMFallback
    try:
        import asyncio
        from src.llm_controller import LLMController, LLMRequest

        controller = LLMController()
        prompt = (
            f"Generate a detailed, professional business deliverable document for the "
            f"following request. Structure it with clear sections, bullet points, and "
            f"actionable content. Request: {query}"
        )
        req = LLMRequest(prompt=prompt, max_tokens=1024)

        # Run async query in a fresh event loop if one is not already running
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import concurrent.futures
                with concurrent.futures.ThreadPoolExecutor(max_workers=1) as exe:
                    future = exe.submit(asyncio.run, controller.query_llm(req))
                    response = future.result(timeout=30)
            else:
                response = loop.run_until_complete(controller.query_llm(req))
        except RuntimeError:
            response = asyncio.run(controller.query_llm(req))

        content = response.content
        if content and len(content) > 50:
            return content
    except Exception:
        pass

    # Always-available fallback: LocalLLMFallback
    try:
        from src.local_llm_fallback import LocalLLMFallback

        fallback = LocalLLMFallback()
        content = fallback.generate(
            f"Generate a detailed professional business deliverable for: {query}",
            max_tokens=1024,
        )
        if content and len(content) > 20:
            return content
    except Exception:
        pass

    # Absolute last resort — structured template
    return _build_minimal_custom_content(query)


def _build_minimal_custom_content(query: str) -> str:
    """Minimal structured content when LLM is unavailable."""
    return f"""\
■ DELIVERABLE OVERVIEW
───────────────────────
  Request:  {query}
  Status:   Generated by Murphy System onboard engine

■ EXECUTIVE SUMMARY
─────────────────────
  This deliverable addresses the request: "{query}"

  Murphy System has analyzed your request and prepared this structured
  document to help you execute the task efficiently. The sections below
  provide a framework, recommended actions, and next steps.

■ RECOMMENDED APPROACH
───────────────────────
  1.  Define clear success criteria before beginning execution.
  2.  Break the task into discrete, measurable sub-tasks.
  3.  Assign ownership and deadlines to each sub-task.
  4.  Schedule a review checkpoint at 50 % completion.
  5.  Document outcomes and lessons learned on completion.

■ ACTION ITEMS
───────────────
  □  Review and customise this deliverable to your specific context.
  □  Share with stakeholders for alignment before execution.
  □  Track progress against the steps above on a weekly basis.
  □  Use Murphy System workflow automation to automate repetitive steps.

■ NEXT STEPS
─────────────
  → Sign up at murphy.systems for AI-powered automation of this workflow.
  → Murphy can generate full SOPs, contracts, and execution plans.
  → Free tier: 10 automated actions/day. Upgrade for unlimited.
"""


def generate_custom_deliverable(query: str) -> Dict[str, Any]:
    """Generate a custom deliverable for an unrecognised query via the LLM."""
    title = f'Custom Deliverable: "{query[:60]}"' if len(query) > 60 else f'Custom Deliverable: "{query}"'
    content = _generate_llm_content(query)
    filename = _scenario_to_filename(None, query)
    txt = build_branded_txt(title, content, scenario_type="custom")
    return {"title": title, "content": txt, "filename": filename}


def generate_deliverable(query: str) -> Dict[str, Any]:
    """Main entry point: detect scenario and dispatch to appropriate generator."""
    scenario_key = _detect_scenario(query)
    if scenario_key and scenario_key in _SCENARIO_TEMPLATES:
        return generate_predefined_deliverable(scenario_key, query)
    return generate_custom_deliverable(query)


def make_fingerprint(request_ip: str, user_agent: str) -> str:
    """Derive an anonymous fingerprint from IP + User-Agent."""
    raw = f"{request_ip}:{user_agent}"
    return hashlib.sha256(raw.encode()).hexdigest()[:32]
