"""
PATCH-R570 (2026-06-04) — surface real inbound to HITL queue

WHAT THIS IS:
  Closes the silent-signal-loss pattern. Rafael at AllQuotas booked a real
  meeting Jun 3 2026 and Murphy never told the founder. The signal sat in
  inbound_replies for 2 days because no module routed external customer
  replies into hitl_queue.

  This module is the bridge. Runs every 5 min via apscheduler.

DESIGN:
  source: inbound_replies WHERE
    received_at > now - 14 days
    AND from_addr does NOT end with @murphy.systems
    AND from_addr does NOT contain noreply / no-reply / dmarcreport / reddit-events
    AND is_test_fixture = 0
    AND intent_class IN ('reply_to_outreach','meeting','inquiry','general_query')
    AND id NOT IN (SELECT inbound_id FROM hitl_dedup)

  for each row:
    - draft apology/thank-you with rules-based templating
    - insert into hitl_queue with stake = high(meeting) / medium(reply) / low(inquiry)
    - record inbound_id in hitl_dedup so it doesn't re-fire

PUBLIC SURFACE:
  surface_pending(limit=20) -> {ok, surfaced, skipped, errors}
"""
import logging
import sqlite3
import json
from datetime import datetime, timezone

logger = logging.getLogger("inbound_to_hitl")
_INBOUND = "/var/lib/murphy-production/inbound_replies.db"
_HITL = "/var/lib/murphy-production/hitl_queue.db"
_DEDUP_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS hitl_dedup (
    inbound_id INTEGER PRIMARY KEY,
    hitl_id TEXT NOT NULL,
    surfaced_at TEXT NOT NULL
)
"""

_STAKE_BY_CLASS = {
    "meeting": "high",
    "reply_to_outreach": "medium",
    "inquiry": "medium",
    "general_query": "low",
}


def _ensure_dedup():
    c = sqlite3.connect(_INBOUND, timeout=5)
    c.execute(_DEDUP_TABLE_SQL)
    c.commit()
    c.close()


# Ship 7 (2026-06-18): identity = Murphy, not Corey. Signed from murphy@murphy.systems.
# Ship 8 (2026-06-18): money-signal triage — see _has_money_signal() below.

_MONEY_KEYWORDS = (
    "price", "pricing", "cost", "costs", "rate", "rates",
    "quote", "quotation", "proposal", "estimate",
    "contract", "agreement", "retainer", "subscribe",
    "fee", "fees", "invoice", "payment", "paid", "billing",
    "how much", "what would it cost", "what does it cost",
    "what do you charge", "your rates", "your pricing",
    "send me a contract", "send a contract",
    "sign up", "signup", "purchase",
)

def _has_money_signal(subject: str, body: str) -> bool:
    """Ship 8: detect when a prospect is ready for the money conversation.
    These get routed to HITL for founder handoff; everything else gets an
    autonomous Murphy reply that qualifies and captures CRM data."""
    blob = (subject + " " + body).lower()
    if "$" in blob:
        return True
    return any(kw in blob for kw in _MONEY_KEYWORDS)


def _extract_name(from_addr: str) -> str:
    """Extract a usable first-name. Handles 'Michael Post <m@x.com>',
    'm.post@x.com', 'asfmike@icloud.com' (returns 'Mike'), etc."""
    if not from_addr:
        return "there"
    # If display name present like "Name <email>", use it
    if "<" in from_addr and ">" in from_addr:
        display = from_addr.split("<")[0].strip().strip('"')
        if display:
            return display.split()[0].title()
        from_addr = from_addr.split("<")[1].split(">")[0]
    if "@" not in from_addr:
        return "there"
    local = from_addr.split("@")[0]
    # Strip leading "asf", "the", common prefixes
    candidate = local.split(".")[0].split("_")[0].split("+")[0]
    # If candidate starts with a prefix like "asfmike" → "Mike"
    if len(candidate) > 5 and candidate.lower().startswith(("asf","the","mr","ms","dr")):
        for prefix in ("asf","the","mr","ms","dr"):
            if candidate.lower().startswith(prefix):
                stripped = candidate[len(prefix):]
                if len(stripped) >= 3:
                    candidate = stripped
                    break
    return candidate.title() if candidate else "there"


def _draft_reply(from_addr: str, subject: str, body: str, intent: str) -> str:
    """Ship 7 (2026-06-18): drafts now signed by Murphy, addressed to the prospect.
    Tone: brief, qualifying, capture-focused. Never quotes price — that's the
    handoff moment to Corey.

    Note: this function only produces the SHORT draft for the HITL card preview.
    The full Murphy-quality reply is generated by inbound_responder.py when the
    auto-reply path is taken; this short draft is just for human review when
    money signal is detected."""
    name = _extract_name(from_addr)
    if intent == "meeting":
        return (
            f"Hi {name} — confirming the meeting on our end. "
            f"Anything you want me to prepare beforehand? — Murphy"
        )
    if intent == "reply_to_outreach":
        return (
            f"Hi {name} — appreciate the reply. To make our next conversation "
            f"useful, can you share: (1) what you're currently using to handle "
            f"this, (2) team size, (3) ballpark timeline? — Murphy"
        )
    if intent == "inquiry":
        return (
            f"Hi {name} — happy to walk through what we do. To tailor the answer, "
            f"could you tell me a bit about your business — what you sell, who "
            f"your customers are, and what's prompting the question now? — Murphy"
        )
    return f"Hi {name} — thanks for the note. — Murphy"


def surface_pending(limit: int = 20) -> dict:
    _ensure_dedup()
    cin = sqlite3.connect(_INBOUND, timeout=5)
    cin.row_factory = sqlite3.Row
    chitl = sqlite3.connect(_HITL, timeout=5)

    rows = cin.execute("""
        SELECT id, received_at, from_addr, subject, body_preview, intent_class
        FROM inbound_replies
        WHERE received_at > datetime('now','-14 days')
          AND from_addr NOT LIKE '%@murphy.systems'
          AND from_addr NOT LIKE '%noreply%'
          AND from_addr NOT LIKE '%no-reply%'
          AND from_addr NOT LIKE '%dmarcreport%'
          AND from_addr NOT LIKE '%reddit-events%'
          AND from_addr NOT LIKE '%cpost%'
          AND from_addr NOT LIKE '%corey.gfc%'
          AND COALESCE(is_test_fixture, 0) = 0
          AND intent_class IN ('reply_to_outreach','meeting','inquiry','general_query')
          AND id NOT IN (SELECT inbound_id FROM hitl_dedup)
        ORDER BY received_at DESC
        LIMIT ?
    """, (limit,)).fetchall()

    # Ship 8 (2026-06-18): money-signal triage.
    # ONLY surface to HITL if the message mentions money/contracts/pricing —
    # that's the founder-handoff moment. Everything else gets routed to the
    # autonomous Murphy auto-responder path (auto_response_status='pending'),
    # where it qualifies, captures CRM data, and replies as Murphy.
    surfaced = 0
    auto_routed = 0
    errors = []
    for r in rows:
        try:
            intent = r["intent_class"]
            from_addr = r["from_addr"]
            subject = r["subject"] or ""
            body = r["body_preview"] or ""

            money = _has_money_signal(subject, body)

            if not money:
                # AUTO-RESPOND PATH: let inbound_responder + autoresponse runner
                # generate a Murphy-signed qualifying reply and capture CRM data.
                # Set status='pending' so inbound_autoresponse_runner picks it up.
                cin.execute(
                    "UPDATE inbound_replies SET auto_response_status='pending' "
                    "WHERE id=? AND (auto_response_status IS NULL OR auto_response_status='staged_hitl')",
                    (r["id"],)
                )
                # Also dedup so we never re-evaluate this row
                cin.execute(
                    "INSERT OR IGNORE INTO hitl_dedup(inbound_id, hitl_id, surfaced_at) "
                    "VALUES (?, ?, datetime('now'))",
                    (r["id"], f"AUTO_{r['id']}_{intent}")
                )
                auto_routed += 1
                continue

            # MONEY SIGNAL — surface to HITL for founder handoff.
            stake = "high"  # money signal = high stake regardless of intent
            hitl_id = f"INB_{r['id']}_money"
            draft = _draft_reply(from_addr, subject, body, intent)
            chitl.execute("""
                INSERT OR IGNORE INTO hitl_queue
                (hitl_id, dag_id, dag_name, blocked_node_id, blocked_node_name,
                 intent, domain, stake, account, created_at, expires_at, status, dag_state_json)
                VALUES (?, 'inbound_money_handoff', ?, 'founder_handoff', ?,
                        ?, 'sales', ?, ?, datetime('now'), datetime('now','+14 days'), 'pending', ?)
            """, (
                hitl_id,
                f"💰 {intent}: {subject[:60]}",
                f"Money signal from {from_addr} — founder handoff",
                intent,
                stake,
                from_addr,
                json.dumps({
                    "inbound_id": r["id"],
                    "from": from_addr,
                    "subject": subject,
                    "body_preview": body[:500],
                    "received": r["received_at"],
                    "draft": draft,
                    "money_signal": True,
                    "handoff_reason": "Mentioned price/contract/payment terms",
                })
            ))
            cin.execute(
                "INSERT OR IGNORE INTO hitl_dedup(inbound_id, hitl_id, surfaced_at) "
                "VALUES (?,?,datetime('now'))",
                (r["id"], hitl_id)
            )
            surfaced += 1
        except Exception as e:
            errors.append({"id": r["id"], "error": str(e)})

    chitl.commit()
    cin.commit()
    chitl.close()
    cin.close()

    return {"ok": True, "surfaced": surfaced, "auto_routed": auto_routed, "errors": errors, "scanned": len(rows)}


if __name__ == "__main__":
    print(surface_pending(limit=10))
