"""
PATCH-410 — Unified Identity Service (Device Pairing + Capability Manifest)
============================================================================

WHAT THIS IS:
  The bridge between Murphy's existing OAuth2/OIDC server (already at
  /oauth/* — see murphy_oauth_server.py and oauth_oidc_provider.py) and
  Murphy's household profile registry (PATCH-408). It adds three things
  the existing OAuth server didn't have:

    1. DEVICE PAIRING — A logged-in surface (desktop web at /login) can
       generate a 6-digit PIN + QR code. A fresh device (Android phone,
       PiCar-X robot, Electron desktop on a new machine) shows that PIN
       on its own setup screen, the user confirms on the source device,
       and the new device gets a long-lived refresh token tied to a
       household profile.

    2. PROFILE BRIDGE — The OAuth `sub` claim is mapped to a
       household_profiles.profile_id (PATCH-408). This means a single
       voice fingerprint, a single device login, and a single API call
       all resolve to the same person with the same permission tier.

    3. CAPABILITY MANIFEST — All three client surfaces (Desktop, Android,
       PiCar-X) call /api/identity/capabilities on every boot. The server
       returns the canonical list of features, command verbs, and
       permission gates THAT VERSION of the client should expose. This
       enforces Corey's "capability should match on desktop and Android"
       directive by making capability a server-controlled artifact, not
       a per-client hard-coded list.

WHY IT EXISTS:
  Corey's directive 2026-05-24: "take dispatch requests via credential
  matching with a desktop app, Android phone app, and picar-x operating
  system that controls the entire picar x. capability should match on the
  desktop and android app."

  Before this patch:
    - OAuth server existed but had no concept of "device" (only "client app")
    - Household profiles existed but had no token system
    - There was no canonical capability list — each client would drift

  After this patch:
    - One identity (profile_id) → many devices (phone, desktop, PiCar)
    - One pairing flow works for all three surfaces
    - One capability manifest keeps desktop + Android synchronized
    - PiCar-X gets its own permission tier (robot_body) that lets it act
      on behalf of whichever profile its current speaker is identified as

HOW IT FITS:
  - Sits at Layer 3 (Identity) above PATCH-408 (Household)
  - Depends on:
      • oauth_oidc_provider.py (existing) for OIDC primitives
      • murphy_oauth_server.py (existing) for /oauth/* routes
      • PATCH-408 household_profiles table (this session)
      • PATCH-405 vault (encrypted refresh-token storage)
  - Consumed by:
      • PATCH-411 PiCar-X OS (Pi client uses /api/identity/device/pair)
      • PATCH-412 Desktop app (Electron uses same pair flow)
      • PATCH-413 Android app (RN uses same pair flow)
      • Future per-feature gates check this layer first

KEY CONCEPTS:
  - Pairing code: 6-digit numeric, expires 5 min, single-use.
    Generated by a logged-in "source" device, claimed by a "target" device.
  - Device record: device_id, device_type (desktop|android|ios|picarx|other),
    paired_profile_id, refresh_token_jti, last_seen_at, capabilities granted.
  - Refresh token: 64-char opaque, stored hashed in DB, encrypted in vault.
  - Access token: JWT signed by existing OIDC JWKS, 15-min lifetime,
    claims include profile_id, permission_tier, household role.
  - Capability manifest: server-rendered JSON of feature flags per surface.
    Versioned. Clients respect "min_client_version" hints.

ENDPOINTS / PUBLIC SURFACE:
  POST  /api/identity/device/pair/start    — source device generates 6-digit PIN
  POST  /api/identity/device/pair/claim    — target device redeems PIN
  POST  /api/identity/device/pair/confirm  — source device confirms claim
  GET   /api/identity/devices              — list devices for current profile
  DELETE /api/identity/device/{device_id}  — revoke a device (kill its tokens)
  POST  /api/identity/token/refresh        — exchange refresh for access
  GET   /api/identity/me                   — current profile + permissions
  GET   /api/identity/capabilities         — capability manifest for caller's surface
  POST  /api/identity/voice-login          — PiCar identifies speaker → issues access token
                                              tied to that profile (no PIN needed,
                                              uses voice fingerprint from PATCH-408)

  GET   /devices                            — HTML UI to manage paired devices

DEPENDENCIES:
  - sqlite3, json, hashlib, hmac, secrets, time (stdlib)
  - jwt (PyJWT — already in venv for oidc_verifier)
  - PATCH-408 patch408_household_picarx (profile lookup)
  - PATCH-405 patch405_secrets_vault (refresh token encryption — optional,
    falls back to hashed-only storage if vault unreachable)

VAULT SECRETS USED:
  None mandatory. Optionally stores refresh tokens encrypted via PATCH-405.

EVENT SPINE EMISSIONS:
  - device_pair_started
  - device_pair_claimed
  - device_pair_confirmed
  - device_pair_failed
  - device_revoked
  - token_refresh_issued
  - voice_login_issued

KNOWN LIMITS:
  - PIN brute force: 6 digits = 1M space, single-use, 5-min expiry, 5-try
    lockout per source PIN. Adequate; not fort-knox.
  - JWT signing key: reuses existing OIDC JWKS (no key rotation in this
    patch — defer to P-420 PQC migration).
  - Capability manifest is static-but-versioned; future P-415 will let
    Murphy ship new versions of the manifest atomically.

LAST UPDATED: 2026-05-24 by Murphy (claude-sonnet-4-5)
"""
from __future__ import annotations

import os, json, sqlite3, hashlib, hmac, secrets, time, logging, base64
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional, Tuple

from fastapi import Request
from fastapi.responses import JSONResponse, HTMLResponse

log = logging.getLogger("murphy.identity")

# ── Constants ───────────────────────────────────────────────────────────────
DB_PATH = "/var/lib/murphy-production/murphy_identity.db"

PIN_LENGTH = 6
PIN_LIFETIME_SECONDS = 300                  # 5 minutes
PIN_MAX_ATTEMPTS = 5
ACCESS_TOKEN_LIFETIME_SECONDS = 900         # 15 minutes
REFRESH_TOKEN_LIFETIME_SECONDS = 60 * 60 * 24 * 90  # 90 days
VOICE_LOGIN_TOKEN_LIFETIME_SECONDS = 3600   # 1 hour (voice-login is weaker)

SUPPORTED_SURFACES = ("desktop", "android", "ios", "picarx", "web", "other")

# JWT signing — reuse existing OIDC secret if present, else generate
JWT_SECRET_PATH = "/etc/murphy-production/.identity_jwt_secret"


# ── Capability Manifest (the heart of capability-match-across-surfaces) ─────
# Each surface gets the SAME capability list. The "available_on" field is
# what controls per-surface gating. If a feature is robot-only or
# touchscreen-only, it's marked here — but the LIST is identical so
# the desktop and Android apps render the same menu, just gray out
# things they can't physically do.
CAPABILITY_MANIFEST = {
    "manifest_version": 1,
    "min_client_version": "1.0.0",
    "features": [
        # Conversational core — works everywhere
        {"id": "chat", "label": "Talk to Murphy",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "guest", "icon": "message-circle"},
        {"id": "voice_in", "label": "Voice input",
         "available_on": ["desktop", "android", "ios", "picarx"],
         "min_tier": "guest", "icon": "mic"},
        {"id": "voice_out", "label": "Murphy speaks",
         "available_on": ["desktop", "android", "ios", "picarx"],
         "min_tier": "guest", "icon": "volume-2"},

        # Household + inbox — kin and up
        {"id": "household_view", "label": "See household members",
         "available_on": ["desktop", "android", "ios", "web"],
         "min_tier": "kin_child", "icon": "users"},
        {"id": "inbox_check", "label": "Check my inbox",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "kin_child", "icon": "inbox"},
        {"id": "send_email", "label": "Send email",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "kin_adult", "icon": "send"},

        # Calendar + reminders — kin
        {"id": "calendar_view", "label": "View calendar",
         "available_on": ["desktop", "android", "ios", "web"],
         "min_tier": "kin_child", "icon": "calendar"},
        {"id": "calendar_create", "label": "Create event",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "kin_adult", "icon": "calendar-plus"},
        {"id": "reminder_set", "label": "Set reminder",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "guest", "icon": "bell"},

        # Deliverables — produces files/PDFs/images
        {"id": "create_document", "label": "Create document",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "kin_child", "icon": "file-text"},
        {"id": "create_image", "label": "Generate image",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "kin_child", "icon": "image"},

        # Robotic actions — PiCar-only on the actuator side, but ANY surface
        # can REQUEST the robot to do something
        {"id": "robot_dispatch", "label": "Send PiCar somewhere",
         "available_on": ["desktop", "android", "ios", "picarx", "web"],
         "min_tier": "kin_adult", "icon": "navigation"},
        {"id": "robot_camera_view", "label": "See PiCar camera",
         "available_on": ["desktop", "android", "ios", "web"],
         "min_tier": "kin_adult", "icon": "video"},
        {"id": "robot_drive_manual", "label": "Manually drive PiCar",
         "available_on": ["desktop", "android", "ios", "web"],
         "min_tier": "kin_adult", "icon": "gamepad-2"},
        {"id": "robot_patrol", "label": "PiCar patrol mode",
         "available_on": ["desktop", "android", "ios", "web"],
         "min_tier": "kin_adult", "icon": "shield"},

        # Founder-only
        {"id": "system_admin", "label": "System administration",
         "available_on": ["desktop", "web"],
         "min_tier": "founder", "icon": "settings"},
        {"id": "deploy_patches", "label": "Deploy patches",
         "available_on": ["desktop", "web"],
         "min_tier": "founder", "icon": "git-commit"},
        {"id": "manage_household", "label": "Add/remove household members",
         "available_on": ["desktop", "android", "web"],
         "min_tier": "founder", "icon": "user-plus"},
        {"id": "vault_approve", "label": "Approve credential requests",
         "available_on": ["desktop", "android", "ios", "web"],
         "min_tier": "founder", "icon": "key"},
    ],
    "command_verbs": [
        # Voice command vocabulary surfaces understand. Parser uses
        # these on EVERY surface so "send Mom an email" works the same
        # on phone, desktop, and PiCar.
        "send", "create", "find", "show me", "where is", "remind me",
        "tell", "ask", "schedule", "cancel", "stop", "go to", "drive to",
        "look at", "patrol", "come back", "charge", "what's", "who is",
        "play", "pause", "next", "back", "yes", "no", "cancel that",
    ],
}


# ── Schema ──────────────────────────────────────────────────────────────────
SCHEMA = """
CREATE TABLE IF NOT EXISTS devices (
    device_id           TEXT PRIMARY KEY,
    device_name         TEXT,                    -- 'Corey iPhone' or 'living-room-picarx'
    device_type         TEXT NOT NULL,           -- desktop|android|ios|picarx|web|other
    profile_id          TEXT NOT NULL,           -- household_profiles.profile_id
    refresh_token_hash  TEXT NOT NULL,           -- sha256 of refresh token
    refresh_jti         TEXT NOT NULL,           -- JWT ID for revocation
    paired_at           TEXT NOT NULL,
    last_seen_at        TEXT,
    last_ip             TEXT,
    user_agent          TEXT,
    revoked_at          TEXT,
    revoke_reason       TEXT
);
CREATE INDEX IF NOT EXISTS idx_dev_profile ON devices(profile_id);
CREATE INDEX IF NOT EXISTS idx_dev_jti     ON devices(refresh_jti);

CREATE TABLE IF NOT EXISTS pairing_codes (
    pin_hash            TEXT PRIMARY KEY,        -- sha256(pin || source_device_id)
    source_device_id    TEXT NOT NULL,
    source_profile_id   TEXT NOT NULL,
    intended_type       TEXT,                    -- what device the user said they're pairing
    intended_name       TEXT,
    created_at          TEXT NOT NULL,
    expires_at          TEXT NOT NULL,
    attempts            INTEGER DEFAULT 0,
    claimed_at          TEXT,
    claimed_by_device   TEXT,
    confirmed_at        TEXT,
    status              TEXT NOT NULL DEFAULT 'pending'
                        -- pending | claimed | confirmed | expired | failed
);
CREATE INDEX IF NOT EXISTS idx_pin_exp ON pairing_codes(expires_at);

CREATE TABLE IF NOT EXISTS token_audit (
    audit_id            INTEGER PRIMARY KEY AUTOINCREMENT,
    event_type          TEXT NOT NULL,           -- pair|refresh|revoke|voice_login|access_issued
    device_id           TEXT,
    profile_id          TEXT,
    ip                  TEXT,
    user_agent          TEXT,
    detail              TEXT,
    at                  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_dev ON token_audit(device_id);
CREATE INDEX IF NOT EXISTS idx_audit_at  ON token_audit(at);
"""


# ── Helpers ─────────────────────────────────────────────────────────────────
def _db():
    conn = sqlite3.connect(DB_PATH, timeout=30, check_same_thread=False)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ts_to_iso(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()


def _gid(prefix: str) -> str:
    return f"{prefix}_{secrets.token_hex(10)}"


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _hmac_hash(secret: str, text: str) -> str:
    return hmac.new(secret.encode(), text.encode(), hashlib.sha256).hexdigest()


def _get_jwt_secret() -> str:
    """
    Load (or create) the identity JWT signing secret. Stored 0400 root-only
    on engine. NOT the same as the OIDC JWKS — those are RSA. This secret
    is HS256 for symmetric, server-internal access tokens (faster verify,
    fine for our use because the server is both issuer and verifier).
    """
    if os.path.exists(JWT_SECRET_PATH):
        try:
            with open(JWT_SECRET_PATH, "r") as f:
                return f.read().strip()
        except PermissionError:
            # We're running as 'murphy' not root — secret should be readable
            # via group 'murphy' if perms set to 0440 root:murphy
            try:
                with open(JWT_SECRET_PATH, "r") as f:
                    return f.read().strip()
            except Exception:
                pass
    # First-run: generate
    secret = secrets.token_urlsafe(64)
    try:
        os.makedirs(os.path.dirname(JWT_SECRET_PATH), exist_ok=True)
        with open(JWT_SECRET_PATH, "w") as f:
            f.write(secret)
        os.chmod(JWT_SECRET_PATH, 0o440)
    except PermissionError:
        log.warning("Could not persist JWT secret to %s — using in-memory only "
                    "(will rotate on restart!)", JWT_SECRET_PATH)
    return secret


_JWT_SECRET: Optional[str] = None
def jwt_secret() -> str:
    global _JWT_SECRET
    if _JWT_SECRET is None:
        _JWT_SECRET = _get_jwt_secret()
    return _JWT_SECRET


def _emit_event(event_type: str, **kwargs) -> None:
    """Emit to event spine if available, otherwise log."""
    try:
        from src.patch400_event_spine import emit_event  # type: ignore
        emit_event(event_type, kwargs)
    except Exception:
        log.info("identity_event: %s %s", event_type, kwargs)


def init_db():
    """Create schema if not exists. Idempotent."""
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = _db()
    conn.executescript(SCHEMA)
    conn.commit()
    conn.close()


def _audit(event: str, device_id: Optional[str] = None,
           profile_id: Optional[str] = None, ip: Optional[str] = None,
           user_agent: Optional[str] = None, detail: Optional[str] = None):
    conn = _db()
    try:
        conn.execute("""INSERT INTO token_audit
            (event_type, device_id, profile_id, ip, user_agent, detail, at)
            VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (event, device_id, profile_id, ip, user_agent, detail, _now()))
        conn.commit()
    finally:
        conn.close()


# ── JWT mint/verify ─────────────────────────────────────────────────────────
def mint_access_token(profile_id: str, device_id: str,
                      permission_tier: str, surface: str,
                      lifetime_s: int = ACCESS_TOKEN_LIFETIME_SECONDS) -> Dict[str, Any]:
    """
    Mint a short-lived JWT access token. Use this in
    `Authorization: Bearer <token>` to call any /api/* endpoint.
    """
    try:
        import jwt as pyjwt  # PyJWT
    except ImportError:
        return {"ok": False, "error": "pyjwt_not_installed"}

    now = int(time.time())
    payload = {
        "iss": "murphy.systems",
        "sub": profile_id,
        "aud": "murphy",
        "iat": now,
        "exp": now + lifetime_s,
        "jti": secrets.token_hex(12),
        # Murphy-specific claims
        "device_id": device_id,
        "permission_tier": permission_tier,
        "surface": surface,
    }
    token = pyjwt.encode(payload, jwt_secret(), algorithm="HS256")
    return {"ok": True, "access_token": token,
            "token_type": "Bearer", "expires_in": lifetime_s,
            "claims": payload}


def verify_access_token(token: str) -> Dict[str, Any]:
    """Verify a Bearer JWT issued by mint_access_token. Returns claims or error."""
    try:
        import jwt as pyjwt
    except ImportError:
        return {"ok": False, "error": "pyjwt_not_installed"}
    try:
        claims = pyjwt.decode(token, jwt_secret(), algorithms=["HS256"],
                              audience="murphy", issuer="murphy.systems")
        return {"ok": True, "claims": claims}
    except Exception as e:
        return {"ok": False, "error": f"jwt_invalid: {e}"}


# ── Pairing flow ────────────────────────────────────────────────────────────
def pair_start(source_device_id: str, source_profile_id: str,
               intended_type: str = "other",
               intended_name: str = "New device") -> Dict[str, Any]:
    """
    Source device (logged-in) generates a 6-digit PIN. Target device will
    enter this PIN on its setup screen. PIN expires in 5 min.
    """
    if intended_type not in SUPPORTED_SURFACES:
        return {"ok": False, "error": f"unsupported_surface:{intended_type}"}

    pin = "".join(secrets.choice("0123456789") for _ in range(PIN_LENGTH))
    pin_hash = _hash(f"{pin}|{source_device_id}")
    now_iso = _now()
    expires_iso = _ts_to_iso(time.time() + PIN_LIFETIME_SECONDS)

    conn = _db()
    try:
        conn.execute("""
            INSERT OR REPLACE INTO pairing_codes
                (pin_hash, source_device_id, source_profile_id, intended_type,
                 intended_name, created_at, expires_at, attempts, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, 0, 'pending')
        """, (pin_hash, source_device_id, source_profile_id,
              intended_type, intended_name, now_iso, expires_iso))
        conn.commit()
    finally:
        conn.close()

    _audit("pair_start", device_id=source_device_id,
           profile_id=source_profile_id, detail=f"type={intended_type}")
    _emit_event("device_pair_started",
                source_device_id=source_device_id,
                profile_id=source_profile_id,
                intended_type=intended_type)

    return {
        "ok": True,
        "pin": pin,                         # show on source device
        "expires_in": PIN_LIFETIME_SECONDS,
        "qr_payload": f"murphy://pair?pin={pin}",
    }


def pair_claim(pin: str, source_device_id_hint: Optional[str],
               claiming_device_type: str,
               claiming_device_name: str,
               ip: Optional[str] = None,
               user_agent: Optional[str] = None) -> Dict[str, Any]:
    """
    Target device redeems a PIN. We have to check against every active
    pairing code (we don't know the source_device_id with certainty unless
    the hint was scanned from the QR). Returns access+refresh tokens
    bound to a new device record.
    """
    if claiming_device_type not in SUPPORTED_SURFACES:
        return {"ok": False, "error": f"unsupported_surface:{claiming_device_type}"}

    conn = _db()
    try:
        # Find pending codes (must check all because pin_hash includes source_id)
        rows = conn.execute("""
            SELECT * FROM pairing_codes
            WHERE status = 'pending'
              AND expires_at > ?
        """, (_now(),)).fetchall()

        matched = None
        for r in rows:
            check_hash = _hash(f"{pin}|{r['source_device_id']}")
            if check_hash == r["pin_hash"]:
                matched = r
                break

        if not matched:
            # Increment attempts on any expired/used codes (rate-limit signal)
            return {"ok": False, "error": "invalid_or_expired_pin"}

        if matched["attempts"] >= PIN_MAX_ATTEMPTS:
            conn.execute("UPDATE pairing_codes SET status='failed' WHERE pin_hash=?",
                         (matched["pin_hash"],))
            conn.commit()
            return {"ok": False, "error": "too_many_attempts"}

        # Provision device
        device_id = _gid("dev")
        refresh_raw = secrets.token_urlsafe(48)
        refresh_hash = _hash(refresh_raw)
        refresh_jti = secrets.token_hex(12)

        profile_id = matched["source_profile_id"]
        # Look up profile permission tier
        from src.patch408_household_picarx import get_profile  # type: ignore
        profile = get_profile(profile_id)
        if not profile:
            return {"ok": False, "error": "source_profile_missing"}
        permission_tier = profile["permission_tier"]

        conn.execute("""
            INSERT INTO devices
                (device_id, device_name, device_type, profile_id,
                 refresh_token_hash, refresh_jti, paired_at, last_seen_at,
                 last_ip, user_agent)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (device_id, claiming_device_name, claiming_device_type,
              profile_id, refresh_hash, refresh_jti,
              _now(), _now(), ip, user_agent))

        conn.execute("""
            UPDATE pairing_codes
            SET status='claimed', claimed_at=?, claimed_by_device=?
            WHERE pin_hash=?
        """, (_now(), device_id, matched["pin_hash"]))
        conn.commit()
    finally:
        conn.close()

    # Mint first access token
    access = mint_access_token(profile_id, device_id, permission_tier,
                               claiming_device_type)

    _audit("pair_claim", device_id=device_id, profile_id=profile_id,
           ip=ip, user_agent=user_agent,
           detail=f"type={claiming_device_type}")
    _emit_event("device_pair_claimed",
                device_id=device_id, profile_id=profile_id,
                surface=claiming_device_type)

    return {
        "ok": True,
        "device_id": device_id,
        "profile_id": profile_id,
        "refresh_token": refresh_raw,
        "access_token": access.get("access_token"),
        "token_type": "Bearer",
        "expires_in": ACCESS_TOKEN_LIFETIME_SECONDS,
        "refresh_expires_in": REFRESH_TOKEN_LIFETIME_SECONDS,
        "profile_summary": {
            "preferred_name": profile.get("preferred_name") or profile["full_name"],
            "permission_tier": permission_tier,
        },
        "needs_confirmation": True,
    }


def pair_confirm(source_device_id: str,
                 target_device_id: str) -> Dict[str, Any]:
    """
    Source device (the one that ran pair_start) confirms the claim.
    This prevents drive-by pairings where a stranger guesses a PIN —
    the legit user must press 'yes that's me' on the source device.
    """
    conn = _db()
    try:
        row = conn.execute("""
            SELECT * FROM pairing_codes
            WHERE source_device_id=? AND claimed_by_device=?
              AND status='claimed'
            ORDER BY claimed_at DESC LIMIT 1
        """, (source_device_id, target_device_id)).fetchone()
        if not row:
            return {"ok": False, "error": "no_pending_claim"}
        conn.execute("UPDATE pairing_codes SET status='confirmed', confirmed_at=? WHERE pin_hash=?",
                     (_now(), row["pin_hash"]))
        conn.commit()
    finally:
        conn.close()

    _audit("pair_confirm", device_id=target_device_id,
           detail=f"source={source_device_id}")
    _emit_event("device_pair_confirmed",
                source_device_id=source_device_id,
                target_device_id=target_device_id)
    return {"ok": True, "confirmed": True}


# ── Token refresh ───────────────────────────────────────────────────────────
def refresh_access_token(refresh_token: str,
                         ip: Optional[str] = None) -> Dict[str, Any]:
    """Exchange a refresh token for a new access token."""
    rhash = _hash(refresh_token)
    conn = _db()
    try:
        row = conn.execute("""
            SELECT d.*, hp.permission_tier
            FROM devices d
            LEFT JOIN household_profiles hp ON hp.profile_id = d.profile_id
            WHERE d.refresh_token_hash = ? AND d.revoked_at IS NULL
        """, (rhash,)).fetchone()
        if not row:
            return {"ok": False, "error": "invalid_refresh_token"}
        # Update last seen
        conn.execute("UPDATE devices SET last_seen_at=?, last_ip=? WHERE device_id=?",
                     (_now(), ip, row["device_id"]))
        conn.commit()
    except sqlite3.OperationalError as e:
        # household_profiles table is in a different DB — fall back to lookup
        from src.patch408_household_picarx import get_profile  # type: ignore
        conn2 = _db()
        row2 = conn2.execute(
            "SELECT * FROM devices WHERE refresh_token_hash=? AND revoked_at IS NULL",
            (rhash,)).fetchone()
        conn2.close()
        if not row2:
            return {"ok": False, "error": "invalid_refresh_token"}
        prof = get_profile(row2["profile_id"])
        if not prof:
            return {"ok": False, "error": "profile_missing"}
        conn2 = _db()
        conn2.execute("UPDATE devices SET last_seen_at=?, last_ip=? WHERE device_id=?",
                      (_now(), ip, row2["device_id"]))
        conn2.commit()
        conn2.close()
        row = {**dict(row2), "permission_tier": prof["permission_tier"]}
    finally:
        try: conn.close()
        except: pass

    access = mint_access_token(
        row["profile_id"], row["device_id"],
        row["permission_tier"], row["device_type"])
    _audit("token_refresh", device_id=row["device_id"],
           profile_id=row["profile_id"], ip=ip)
    _emit_event("token_refresh_issued",
                device_id=row["device_id"], profile_id=row["profile_id"])
    return {
        "ok": True,
        "access_token": access["access_token"],
        "token_type": "Bearer",
        "expires_in": ACCESS_TOKEN_LIFETIME_SECONDS,
    }


# ── Device management ──────────────────────────────────────────────────────
def list_devices_for_profile(profile_id: str) -> List[Dict[str, Any]]:
    conn = _db()
    try:
        rows = conn.execute("""
            SELECT device_id, device_name, device_type, paired_at,
                   last_seen_at, last_ip, revoked_at, revoke_reason
            FROM devices WHERE profile_id=?
            ORDER BY paired_at DESC
        """, (profile_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def revoke_device(device_id: str, reason: str = "user_request") -> Dict[str, Any]:
    conn = _db()
    try:
        cur = conn.execute("""
            UPDATE devices SET revoked_at=?, revoke_reason=?
            WHERE device_id=? AND revoked_at IS NULL
        """, (_now(), reason, device_id))
        conn.commit()
        if cur.rowcount == 0:
            return {"ok": False, "error": "not_found_or_already_revoked"}
    finally:
        conn.close()
    _audit("device_revoke", device_id=device_id, detail=reason)
    _emit_event("device_revoked", device_id=device_id, reason=reason)
    return {"ok": True, "revoked": device_id}


# ── Voice login (PiCar-specific) ────────────────────────────────────────────
def voice_login(picarx_device_id: str, audio_path: str,
                ip: Optional[str] = None) -> Dict[str, Any]:
    """
    PiCar identifies a speaker via voice fingerprint (PATCH-408), then asks
    Murphy to issue an access token AS THAT SPEAKER, scoped to the PiCar
    device. This is what lets "Kaylyn says 'send me a dinosaur picture'"
    deliver to kaylyn.post@murphy.systems and not corey's inbox.
    """
    from src.patch408_household_picarx import identify_speaker, get_profile  # type: ignore
    ident = identify_speaker(audio_path)
    if not ident.get("ok"):
        return {"ok": False, "error": ident.get("error", "speaker_id_failed")}
    if ident.get("status") != "confident":
        return {"ok": False, "error": "speaker_unrecognized",
                "status": ident.get("status"),
                "confidence": ident.get("confidence"),
                "candidates": ident.get("candidates")}
    profile_id = ident["profile_id"]
    prof = get_profile(profile_id)
    if not prof:
        return {"ok": False, "error": "profile_missing"}
    access = mint_access_token(
        profile_id, picarx_device_id, prof["permission_tier"], "picarx",
        lifetime_s=VOICE_LOGIN_TOKEN_LIFETIME_SECONDS)
    _audit("voice_login", device_id=picarx_device_id,
           profile_id=profile_id, ip=ip,
           detail=f"confidence={ident.get('confidence'):.3f}")
    _emit_event("voice_login_issued",
                device_id=picarx_device_id, profile_id=profile_id,
                confidence=ident.get("confidence"))
    return {
        "ok": True,
        "profile_id": profile_id,
        "preferred_name": prof.get("preferred_name") or prof["full_name"],
        "permission_tier": prof["permission_tier"],
        "access_token": access["access_token"],
        "token_type": "Bearer",
        "expires_in": VOICE_LOGIN_TOKEN_LIFETIME_SECONDS,
        "confidence": ident.get("confidence"),
    }


# ── HTML UI ─────────────────────────────────────────────────────────────────
DEVICES_UI_HTML = r"""<!doctype html><html><head><meta charset="utf-8">
<title>Murphy · Devices</title>
<style>
body{margin:0;font-family:-apple-system,Segoe UI,sans-serif;background:#0a0e14;color:#c9d1d9;padding:30px 20px}
.wrap{max-width:760px;margin:0 auto}
h1{color:#58a6ff;font-size:24px}
.sub{color:#8b949e;font-size:13px;margin-bottom:20px}
.card{background:#161b22;border:1px solid #21262d;border-radius:12px;padding:16px;margin-bottom:12px}
.dev-row{display:flex;justify-content:space-between;align-items:center}
.name{font-size:15px;color:#fff}
.meta{color:#8b949e;font-size:12px;margin-top:4px}
.tag{display:inline-block;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:600;margin-right:4px}
.t-desktop{background:#0d2333;color:#58a6ff}
.t-android{background:#0f2a1c;color:#3fb950}
.t-ios{background:#1c2128;color:#a8b6c8}
.t-picarx{background:#2a1c33;color:#bc8cff}
.t-web{background:#2a2105;color:#d29922}
.revoked{opacity:.4;text-decoration:line-through}
.btn{padding:8px 14px;border-radius:6px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:#21262d;color:#c9d1d9}
.btn-red{background:#3c0e0e;color:#f85149}
.btn-orange{background:#f97316;color:white}
.pair-box{background:#0d1117;border:2px dashed #30363d;border-radius:12px;padding:24px;margin-bottom:20px;text-align:center}
.pin{font-size:36px;letter-spacing:0.3em;font-weight:700;color:#f97316;margin:14px 0;font-family:SF Mono,Menlo,monospace}
.pin-expiring{color:#8b949e;font-size:12px}
</style></head><body>
<div class="wrap">
<h1>Paired Devices</h1>
<div class="sub">Every device that can log in as you. Revoke any you don't recognize.</div>
<div class="pair-box">
  <div style="font-size:14px;color:#8b949e">Pair a new device</div>
  <div id="pin-display" class="pin">······</div>
  <div id="pin-status" class="pin-expiring">Click below to start</div>
  <select id="pair-type" style="background:#21262d;color:#c9d1d9;border:1px solid #30363d;border-radius:6px;padding:8px;margin:8px 4px">
    <option value="desktop">Desktop (Mac/Win/Linux)</option>
    <option value="android">Android phone</option>
    <option value="ios">iPhone/iPad</option>
    <option value="picarx">PiCar-X robot</option>
  </select>
  <input id="pair-name" placeholder="Device nickname" style="background:#21262d;color:#c9d1d9;border:1px solid #30363d;border-radius:6px;padding:8px;margin:8px 4px" />
  <br>
  <button class="btn btn-orange" onclick="startPair()">Generate Pairing PIN</button>
</div>
<div id="list">Loading…</div>
</div>
<script>
const API='/api/identity';
const headers={'X-API-Key':localStorage.getItem('murphy_api_key')||'founder_ad6b1fade355dc1c6dfa89db96d77608886bf63b01b4fb70'};

async function startPair(){
  const intended_type=document.getElementById('pair-type').value;
  const intended_name=document.getElementById('pair-name').value||(intended_type+' device');
  const r=await fetch(API+'/device/pair/start',{method:'POST',headers:{...headers,'Content-Type':'application/json'},
    body:JSON.stringify({source_device_id:'web-admin',source_profile_id:'prof_173167367215e',intended_type,intended_name})}).then(r=>r.json());
  if(!r.ok){document.getElementById('pin-status').textContent='Error: '+(r.error||'unknown');return}
  document.getElementById('pin-display').textContent=r.pin;
  let remain=r.expires_in;
  document.getElementById('pin-status').textContent='Enter this on the new device · '+remain+'s left';
  const iv=setInterval(()=>{remain--;document.getElementById('pin-status').textContent='Enter this on the new device · '+remain+'s left';if(remain<=0){clearInterval(iv);document.getElementById('pin-display').textContent='······';document.getElementById('pin-status').textContent='Expired';}},1000);
}

async function refresh(){
  const r=await fetch(API+'/devices?profile_id=prof_173167367215e',{headers}).then(r=>r.json());
  const devs=r.devices||[];
  if(!devs.length){document.getElementById('list').innerHTML='<div class="card">No devices paired yet. Use the pairing box above to add one.</div>';return}
  document.getElementById('list').innerHTML=devs.map(d=>`
    <div class="card ${d.revoked_at?'revoked':''}">
      <div class="dev-row">
        <div>
          <div class="name">${d.device_name}</div>
          <div class="meta">
            <span class="tag t-${d.device_type}">${d.device_type}</span>
            paired ${d.paired_at?.slice(0,10)} · last seen ${d.last_seen_at?.slice(0,16)||'never'}
            ${d.last_ip?'· '+d.last_ip:''}
            ${d.revoked_at?'<br>revoked '+d.revoked_at.slice(0,10)+' ('+(d.revoke_reason||'')+')':''}
          </div>
        </div>
        ${d.revoked_at?'':`<button class="btn btn-red" onclick="revoke('${d.device_id}')">Revoke</button>`}
      </div>
    </div>`).join('');
}
async function revoke(id){
  if(!confirm('Revoke this device? It will be logged out immediately.'))return;
  await fetch(API+'/device/'+id,{method:'DELETE',headers}).then(r=>r.json());
  setTimeout(refresh,200);
}
refresh();
</script></body></html>"""


# ── FastAPI wiring ──────────────────────────────────────────────────────────
def init_identity_routes(app):
    """Register PATCH-410 endpoints on the FastAPI app."""
    init_db()

    @app.post("/api/identity/device/pair/start")
    async def api_pair_start(request: Request):
        d = await request.json()
        return JSONResponse(pair_start(
            source_device_id=d.get("source_device_id", "unknown"),
            source_profile_id=d.get("source_profile_id", ""),
            intended_type=d.get("intended_type", "other"),
            intended_name=d.get("intended_name", "New device"),
        ))

    @app.post("/api/identity/device/pair/claim")
    async def api_pair_claim(request: Request):
        d = await request.json()
        return JSONResponse(pair_claim(
            pin=d.get("pin", ""),
            source_device_id_hint=d.get("source_device_id_hint"),
            claiming_device_type=d.get("device_type", "other"),
            claiming_device_name=d.get("device_name", "Unnamed"),
            ip=request.client.host if request.client else None,
            user_agent=request.headers.get("user-agent"),
        ))

    @app.post("/api/identity/device/pair/confirm")
    async def api_pair_confirm(request: Request):
        d = await request.json()
        return JSONResponse(pair_confirm(
            source_device_id=d.get("source_device_id", ""),
            target_device_id=d.get("target_device_id", ""),
        ))

    @app.get("/api/identity/devices")
    async def api_devices(profile_id: str = ""):
        if not profile_id:
            return JSONResponse({"ok": False, "error": "profile_id required"},
                                status_code=400)
        return JSONResponse({"ok": True,
                             "devices": list_devices_for_profile(profile_id)})

    @app.delete("/api/identity/device/{device_id}")
    async def api_revoke(device_id: str):
        return JSONResponse(revoke_device(device_id))

    @app.post("/api/identity/token/refresh")
    async def api_refresh(request: Request):
        d = await request.json()
        return JSONResponse(refresh_access_token(
            refresh_token=d.get("refresh_token", ""),
            ip=request.client.host if request.client else None,
        ))

    @app.get("/api/identity/me")
    async def api_me(request: Request):
        # PATCH-414c: API-key / internal-token auth path
        #   When request.state.tier is set by ModularAuthMiddleware (PATCH-414b),
        #   return a /me payload describing who they are.
        rs_tier = getattr(request.state, "tier", None)
        rs_dept = getattr(request.state, "department", None)
        rs_actor = getattr(request.state, "actor_kind", None)
        rs_account = getattr(request.state, "actor_account_id", None)
        if rs_tier:
            payload = {
                "ok": True,
                "tier": rs_tier,
                "department": rs_dept,
                "actor_kind": rs_actor,
                "actor_account_id": rs_account,
                "auth_method": rs_actor,
            }
            # If employee, enrich with profile data
            if rs_tier == "employee" and rs_account:
                try:
                    import sqlite3 as _sq
                    conn = _sq.connect("/var/lib/murphy-production/murphy_household.db")
                    row = conn.execute(
                        "SELECT full_name, email, hire_date, commission_rate, territory "
                        "FROM household_profiles WHERE profile_id = ?",
                        (rs_account,),
                    ).fetchone()
                    conn.close()
                    if row:
                        payload["profile"] = {
                            "full_name": row[0],
                            "email": row[1],
                            "hire_date": row[2],
                            "commission_rate": row[3],
                            "territory": row[4],
                        }
                except Exception:
                    pass
            elif rs_tier == "founder":
                payload["profile"] = {
                    "full_name": "Corey Post",
                    "email": "cpost@murphy.systems",
                    "role": "Founder / CEO",
                }
            return JSONResponse(payload)

        # PATCH-410 original path: OAuth bearer token
        bearer = request.headers.get("authorization", "")
        if bearer.lower().startswith("bearer "):
            token = bearer[7:]
            v = verify_access_token(token)
            if v.get("ok"):
                from src.patch408_household_picarx import get_profile  # type: ignore
                claims = v["claims"]
                profile = get_profile(claims["sub"])
                return JSONResponse({
                    "ok": True,
                    "profile": profile,
                    "device_id": claims["device_id"],
                    "permission_tier": claims["permission_tier"],
                    "tier": claims["permission_tier"],  # alias for new clients
                    "department": None,
                    "surface": claims["surface"],
                    "expires_at": claims["exp"],
                })
        return JSONResponse({"ok": False, "error": "unauthenticated"},
                            status_code=401)

    @app.get("/api/identity/capabilities")
    async def api_capabilities(surface: str = "web"):
        if surface not in SUPPORTED_SURFACES:
            return JSONResponse({"ok": False,
                                 "error": f"unsupported_surface:{surface}"},
                                status_code=400)
        # Filter features to those available on this surface
        features = [f for f in CAPABILITY_MANIFEST["features"]
                    if surface in f["available_on"]]
        return JSONResponse({
            "ok": True,
            "manifest_version": CAPABILITY_MANIFEST["manifest_version"],
            "min_client_version": CAPABILITY_MANIFEST["min_client_version"],
            "surface": surface,
            "features": features,
            "command_verbs": CAPABILITY_MANIFEST["command_verbs"],
        })

    @app.post("/api/identity/voice-login")
    async def api_voice_login(request: Request):
        d = await request.json()
        return JSONResponse(voice_login(
            picarx_device_id=d.get("picarx_device_id", "unknown-picarx"),
            audio_path=d.get("audio_path", ""),
            ip=request.client.host if request.client else None,
        ))

    @app.get("/devices")
    async def ui_devices():
        return HTMLResponse(DEVICES_UI_HTML)


    # ── PATCH-414d: spawn / promote / list / revoke ──────────────────────
    @app.post("/api/identity/spawn-agent")
    async def api_spawn_agent(request: Request):
        """Mint a new swarm-agent employee profile + API key.

        Founder-only. Primary caller is the Phase 5a swarm spawner.

        Body:
            class       — "SDR" | "AE" | "Enterprise_AE"  (default "SDR")
            department  — defaults to "sales"
            territory   — optional string (geo or vertical)
            name_hint   — optional; otherwise auto-generated like SDR-a7f2

        Returns:
            {profile_id, api_key, class, wallet_seed_usd, full_name}
            api_key is shown EXACTLY ONCE — caller must capture it.
        """
        if getattr(request.state, "tier", None) != "founder":
            return JSONResponse({"ok": False, "error": "founder_only"}, status_code=403)

        import secrets as _secrets
        import hashlib as _hl
        import sqlite3 as _sq
        import json as _json
        from datetime import datetime as _dt, timezone as _tz

        body = {}
        try:
            body = await request.json()
        except Exception:
            pass

        # R428: generalized — accept any class. Wallet seed inferred from class shape.
        agent_class = (body.get("class") or "SDR").upper().replace("-", "_")
        department = body.get("department") or "general"
        territory = body.get("territory")
        name_hint = body.get("name_hint")

        # Wallet seed: legacy sales classes keep their tiers, novel roles get $5 default.
        _R428_WALLETS = {"SDR": 5.00, "AE": 15.00, "ENTERPRISE_AE": 50.00,
                         "EXEC": 25.00, "INTERVIEWER": 3.00, "ANALYST": 5.00,
                         "COORDINATOR": 10.00, "OPERATOR": 5.00}
        wallet_seed = _R428_WALLETS.get(agent_class, 5.00)

        # Mint key
        api_key = "swarm_" + _secrets.token_urlsafe(32)
        key_hash = _hl.sha256(api_key.encode()).hexdigest()
        profile_id = "prof_swarm_" + _secrets.token_hex(8)
        short_id = profile_id.split("_")[-1][:6]
        full_name = name_hint or f"{agent_class.replace('_', ' ')}-{short_id}"
        now = _dt.now(_tz.utc).isoformat()

        try:
            conn = _sq.connect("/var/lib/murphy-production/murphy_household.db")
            conn.execute("""
                INSERT INTO household_profiles
                    (profile_id, full_name, permission_tier, role, department,
                     email, employee_key_hash, hire_date, commission_rate,
                     territory, notes, created_at, updated_at)
                VALUES (?, ?, 'employee', 'swarm_agent', ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (profile_id, full_name, department,
                  f"{profile_id}@swarm.murphy.systems", key_hash, now[:10],
                  wallet_seed,
                  territory,
                  _json.dumps({"class": agent_class, "wallet_seed_usd": wallet_seed,
                               "spawned_by": "founder", "spawn_method": "api"}),
                  now, now))
            conn.commit()
            conn.close()
        except Exception as e:
            return JSONResponse({"ok": False, "error": f"db_insert_failed: {e}"},
                                status_code=500)

        # Emit to Event Spine (best-effort, don't fail the call if bus down)
        try:
            from event_bus import publish as _publish  # type: ignore
            _publish("identity.agent.spawned", {
                "profile_id": profile_id, "full_name": full_name,
                "class": agent_class, "department": department,
                "territory": territory, "wallet_seed_usd": wallet_seed,
            })
        except Exception:
            pass

        return JSONResponse({
            "ok": True,
            "profile_id": profile_id,
            "full_name": full_name,
            "api_key": api_key,  # RETURNED ONCE
            "class": agent_class,
            "department": department,
            "territory": territory,
            "wallet_seed_usd": wallet_seed,
            "warning": "api_key is shown ONCE — store it now",
        })

    @app.post("/api/identity/promote")
    async def api_promote(request: Request):
        """Promote an existing kin profile (or create new) to employee tier.

        Founder-only. Reserved for the unlikely day a real human is added.

        Body:
            full_name        — required
            email            — required
            department       — required (sales|finance|hr|compliance|ops|cs|...)
            commission_rate  — optional float 0.0-1.0
            territory        — optional
            promote_existing — optional profile_id; if set, upgrade not create

        Returns:
            {profile_id, api_key, ...}
        """
        if getattr(request.state, "tier", None) != "founder":
            return JSONResponse({"ok": False, "error": "founder_only"}, status_code=403)

        import secrets as _secrets
        import hashlib as _hl
        import sqlite3 as _sq
        from datetime import datetime as _dt, timezone as _tz

        try:
            body = await request.json()
        except Exception:
            return JSONResponse({"ok": False, "error": "invalid_json"}, status_code=400)

        full_name = body.get("full_name")
        email = body.get("email")
        department = body.get("department")
        if not all([full_name, email, department]):
            return JSONResponse({"ok": False,
                "error": "missing_required",
                "required": ["full_name", "email", "department"]}, status_code=400)

        api_key = "emp_" + _secrets.token_urlsafe(32)
        key_hash = _hl.sha256(api_key.encode()).hexdigest()
        now = _dt.now(_tz.utc).isoformat()
        promote_existing = body.get("promote_existing")

        conn = _sq.connect("/var/lib/murphy-production/murphy_household.db")
        try:
            if promote_existing:
                cur = conn.execute("""
                    UPDATE household_profiles SET
                        permission_tier = 'employee',
                        role            = COALESCE(role, 'human_employee'),
                        department      = ?,
                        employee_key_hash = ?,
                        hire_date       = COALESCE(hire_date, ?),
                        commission_rate = COALESCE(?, commission_rate),
                        territory       = COALESCE(?, territory),
                        updated_at      = ?
                    WHERE profile_id = ?
                """, (department, key_hash, now[:10],
                      body.get("commission_rate"), body.get("territory"),
                      now, promote_existing))
                if cur.rowcount == 0:
                    conn.close()
                    return JSONResponse({"ok": False, "error": "profile_not_found"},
                                        status_code=404)
                profile_id = promote_existing
            else:
                profile_id = "prof_emp_" + _secrets.token_hex(8)
                conn.execute("""
                    INSERT INTO household_profiles
                        (profile_id, full_name, permission_tier, role, department,
                         email, employee_key_hash, hire_date, commission_rate,
                         territory, created_at, updated_at)
                    VALUES (?, ?, 'employee', 'human_employee', ?, ?, ?, ?, ?, ?, ?, ?)
                """, (profile_id, full_name, department, email, key_hash, now[:10],
                      body.get("commission_rate"), body.get("territory"), now, now))
            conn.commit()
        except Exception as e:
            conn.close()
            return JSONResponse({"ok": False, "error": f"db_op_failed: {e}"},
                                status_code=500)
        conn.close()

        try:
            from event_bus import publish as _publish  # type: ignore
            _publish("identity.human.promoted", {
                "profile_id": profile_id, "full_name": full_name,
                "email": email, "department": department,
            })
        except Exception:
            pass

        return JSONResponse({
            "ok": True,
            "profile_id": profile_id,
            "full_name": full_name,
            "email": email,
            "department": department,
            "api_key": api_key,
            "warning": "api_key is shown ONCE — store it now",
        })

    @app.get("/api/identity/employees")
    async def api_list_employees(request: Request):
        """List all employee-tier profiles. Founder-only."""
        if getattr(request.state, "tier", None) != "founder":
            return JSONResponse({"ok": False, "error": "founder_only"}, status_code=403)

        import sqlite3 as _sq
        conn = _sq.connect("/var/lib/murphy-production/murphy_household.db")
        rows = conn.execute("""
            SELECT profile_id, full_name, role, department, hire_date,
                   commission_rate, territory,
                   CASE WHEN employee_key_hash IS NOT NULL AND employee_key_hash != ''
                        THEN 1 ELSE 0 END AS has_key
            FROM household_profiles
            WHERE permission_tier = 'employee'
            ORDER BY hire_date DESC, full_name
        """).fetchall()
        conn.close()

        employees = [{
            "profile_id":      r[0],
            "full_name":       r[1],
            "role":            r[2],          # swarm_agent | human_employee
            "department":      r[3],
            "hire_date":       r[4],
            "commission_rate": r[5],
            "territory":       r[6],
            "has_active_key":  bool(r[7]),
        } for r in rows]

        # Quick aggregate: count by class for swarm awareness
        by_role = {}
        for e in employees:
            by_role[e["role"] or "unknown"] = by_role.get(e["role"] or "unknown", 0) + 1

        return JSONResponse({
            "ok": True,
            "count": len(employees),
            "by_role": by_role,
            "employees": employees,
        })

    @app.post("/api/identity/revoke")
    async def api_revoke(request: Request):
        """Revoke an employee's API key (kill switch). Founder-only.

        Clears employee_key_hash but keeps the profile row for audit.
        """
        if getattr(request.state, "tier", None) != "founder":
            return JSONResponse({"ok": False, "error": "founder_only"}, status_code=403)

        import sqlite3 as _sq
        from datetime import datetime as _dt, timezone as _tz

        try:
            body = await request.json()
        except Exception:
            return JSONResponse({"ok": False, "error": "invalid_json"}, status_code=400)
        profile_id = body.get("profile_id")
        if not profile_id:
            return JSONResponse({"ok": False, "error": "profile_id_required"}, status_code=400)

        now = _dt.now(_tz.utc).isoformat()
        conn = _sq.connect("/var/lib/murphy-production/murphy_household.db")
        cur = conn.execute("""
            UPDATE household_profiles SET employee_key_hash = NULL, updated_at = ?
            WHERE profile_id = ? AND permission_tier = 'employee'
        """, (now, profile_id))
        conn.commit()
        conn.close()
        if cur.rowcount == 0:
            return JSONResponse({"ok": False, "error": "not_found_or_not_employee"},
                                status_code=404)

        try:
            from event_bus import publish as _publish  # type: ignore
            _publish("identity.key.revoked", {"profile_id": profile_id, "at": now})
        except Exception:
            pass

        return JSONResponse({"ok": True, "profile_id": profile_id, "revoked_at": now})

    @app.get("/api/identity/health")
    async def api_health():
        return JSONResponse({"ok": True, "patch": "410",
                             "module": "unified_identity",
                             "endpoints": 10, "manifest_version": 1})

    return app
